### PR TITLE
renames 'to_string' to 'to_json_string' and makes it ridiculously fast

### PR DESCRIPTION
**Pull request by lemire**
Instead of parsing and reconstructing a string, it just gives you a direct view in the original document. It is obviously much, much faster than parsing and then reserializing. I think that's the kind of approach we want in simdjson.

Fixes: https://github.com/simdjson/simdjson/issues/1584

### CODE REVIEW

**Comment by lemire** [comment]
What I really like about this approach is how incredibly efficient it is. :-)

**Comment by jkeiser** [comment]
This is definitely the right approach :) Prettifying it or minifying takes more work, but a lot of people don't care about that. And even if they do, we can just use the space-removing minifier we built and design a new pretty printer that walks the tokens and keeps track of depth, but doesn't actually parse scalars (which is where the biggest time sink is).

**Comment by lemire** [comment]
@jkeiser This can be improved, I am sure, but if it passes our tests, I will merge into our main branch. You have reviewed and approved the controversial changes.

The rest of the functionality can be modified without much messing around with the core of the front-end.

**Comment by lemire** [comment]
Everything is green, so I am merging this.

**Pull request merged**
