### PR TITLE
Use static variables to enforce initialization order.

### PR DESCRIPTION
**Pull request by chenhao94**
Fixes https://github.com/simdjson/simdjson/issues/1771

### CODE REVIEW

**Comment by lemire** [comment]
In src/implementation.cpp, you added a trailing white space. You should be able to remove it easily.

**Comment by lemire** [comment]
Please review the failing tests.

**Comment by lemire** [comment]
Let us run the tests.

@chenhao94  I will need to review more carefully but, at a glance, what you did feels very good to me. I think you have the right solution.

**Comment by lemire** [comment]
@chenhao94  You may still have trailing spaces.

**Comment by chenhao94** [comment]
> Let us run the tests.
> 
> @chenhao94 I will need to review more carefully but, at a glance, what you did feels very good to me. I think you have the right solution.

I tried those failing Mingw tests. Even the master branch cannot pass those tests.

**Comment by lemire** [comment]
I have reviewed the performance difference manually and it seems that the failing test is spurious.

**Comment by lemire** [comment]
I am running an empty PR at https://github.com/simdjson/simdjson/pull/1775 to verify the build issues with MinGW. It could be that the "tests have gone bad" (i.e., it might be that it is not a problem with this PR). I still would like to fix these issues before merging. I would not want to merge a PR with failing tests in CI.

**Comment by lemire** [comment]
There is indeed an unrelated (new) issue with some of the CI tests. Must be some system change elsewhere. Maybe an update to scoop. I will try to fix it.

**Comment by lemire** [comment]
My expectation is that this PR, on its own is fine, and I plan to merge it.

**Comment by lemire** [comment]
@chenhao94 Could you sync with the main branch? I have decided to remove the scoop-based tests because they have gone bad.

I think that your PR should only fail that performance tests and it must be a spurious failure.

**Comment by lemire** [comment]
Thanks. Let us run the tests.

Then I will need to review manually a bit more.

**Comment by chenhao94** [comment]
> Thanks. Let us run the tests.
> 
> Then I will need to review manually a bit more.

Thanks.

The perf test keeps failing. I am not sure if anything in this PR hurts performance. It does not seem so, but maybe there is something that I missed.

**Comment by jkeiser** [comment]
I've made changes before that regressed performance by 5-10% for no apparent reason. My theory is that some changes kick the compiler / optimizer into a different orbit.

**Comment by lemire** [comment]
@jkeiser @chenhao94 

This test is more of a warning than a failure. It means that someone needs to investigate the effect.

I personally assume that it is a false warning.

It takes a bit of effort to figure it out: I need to run various tests, using various compilers.

The hasty test I did earlier today revealed nothing.

**Comment by lemire** [comment]
I have been running benchmarks and it is a bit weird. It seems like GCC is affected negatively (stage 2) whereas clang benefits (stage 2). This does not make much sense to me.

**Pull request merged**
