### PR TITLE
Add method to get the total number of slots used by an array in the t…

### LINKED ISSUE #1251: [DOM] Expose the total number of elements contained within an array.
`dom::array` should expose the total number of elements contained within it, not just the number of elements at the current scope.

Since the `[` element on the tape encodes the location of its closing `]`, when a user provides typing information for an array we can make a best-guess at how much space we need to store it. It should be clear this API is for advanced usage in the documentation.

https://github.com/TkTech/pysimdjson/pull/59 provides a mechanism for efficiently copying homogeneous arrays around Python without uplifting to complex types. To do this, we have the user explicitly provide the type they want. For example, loading GeoJSON into numpy:

```python
numpy.frombuffer(
    doc.at_pointer('/features/0/geometry/coordinates')
    .as_buffer(of_type='d')
)
```
For 1-dimensional arrays, we just call `m_vec->reserve(src.size())` and all is well. However, for n-dimensional arrays, we have no way of guessing what size of container we really need and need to re-allocate each time we descend into a new scope if `m_vec->capacity() - m_vec->size() < arr.size()`.

By exposing the total number of elements between the start and end, I can do a single allocation which will slightly over-allocate depending on the number of nested `[` and `]` elements, which is fine (and can be fixed after with a single `shrink_to_fit`.

### PR DESCRIPTION
**Pull request by TkTech**
…ape. Closes #1251.

This is used to minimize allocations when turning an n-dimensional array into a homogeneous array in https://github.com/simdjson/simdjson/issues/1251.

### CODE REVIEW

**Comment by TkTech** [comment]
Test failures seem to be circleci issues unrelated to code changes.

**Comment by lemire** [comment]
@TkTech You are correct, we can probably ignore these failures. Let me see if I can restart circleci.

**Comment by TkTech** [comment]
There's a bug here, the amalgamated version is correct but it looks like I didn't commit the updated array-inl.h. Will fix this after work.

**Comment by lemire** [comment]
@TkTech Can you rebase with our main branch? I let this grow old, and now it seems that the PR has a conflict with singleheader files. Note that you do not need to be modifying the singleheader files.

**Comment by TkTech** [comment]
Updated, and the amalgamation files are just the ones from master.

**Comment by lemire** [comment]
Damn it. CI is red all over again.

**Comment by lemire** [comment]
@TkTech  I am happy to merge this despite circle ci bailing out.

We have a white space issue, however.

@pauldreik It seems that the white-space detection does not tell us where the white space is, nor in which files, is that the expected behaviour?

**Comment by lemire** [comment]
I'll overwrite the trailing white space check and merge.

**Comment by pauldreik** [comment]
> @pauldreik It seems that the white-space detection does not tell us where the white space is, nor in which files, is that the expected behaviour?

The error message says to download the artifact which is a diff. There is an "artifacts button" above, which if you click it gives a link to a downloadable file.
One can also run  scripts/remove_trailing_whitespace.sh  locally.

In this case, I think you just needed to merge master into the branch since this branch probably started before I un-whitespaced master.

**Comment by lemire** [comment]
@pauldreik Thanks for the explanation. I will add instructions to the pull request notes.

**Pull request merged**
