### PR TITLE
Adding missing definitions in element.

### PR DESCRIPTION
**Pull request by lemire**
@pauldreik spotted missing definitions in PR https://github.com/simdjson/simdjson/pull/1204

### CODE REVIEW

**Comment by lemire** [comment]
These issues need to be fixed before release 0.6.

**Comment by pauldreik** [comment]
Would it perhaps be a good idea to have an example or a unit test, so the CI fails if these definitions would be missing? They are part of the public API.

**Comment by pauldreik** [comment]
> Would it perhaps be a good idea to have an example or a unit test, so the CI fails if these definitions would be missing? They are part of the public API.

I merged this into the #1204 pull request, which adds fuzzers. That prevents them to go missing again since it would make the fuzzers fail to build.

**Review by pauldreik — APPROVED** [review]
Looks good, merged into #1204

**Comment by lemire** [comment]
Closing.

**Pull request closed without merging**
