### PR TITLE
add multi implementation fuzzer

### LINKED ISSUE #815: Build fewer variants in fuzz/build_fuzzer_variants.sh
Instead of building `noavx` versions of everything, the fuzzers could just run with the environment variable SIMDJSON_FORCE_IMPLEMENTATION=westmere on. Would eliminate the need for half the built variants.

### PR DESCRIPTION
**Pull request by pauldreik**
This adds a fuzzer which parses the same input using all the available implementations (haswell, westmere, fallback on x64).

This should get the otherwise uncovered sourcefiles (mostly fallback) to show up in the fuzz coverage.
For instance, [the fallback directory has only one line covered](https://storage.googleapis.com/oss-fuzz-coverage/simdjson/reports/20200909/linux/src/simdjson/src/fallback/report.html).  
As of the [20200909 report](https://storage.googleapis.com/oss-fuzz-coverage/simdjson/reports/20200909/linux/src/simdjson/report.html), 1866 lines are covered out of 4478.

Also, it will detect if the implementations behave differently:
 - by making sure they all succeed, or all error 
 - turning the parsed data into text again, should produce equal results

While at it, I corrected some minor things:
 - clean up building too many variants, run with forced implementation (closes #815 )
 - always store crashes as artefacts, good in case the fuzzer finds something
 - return value of the fuzzer function should always be 0
 - reduce log spam
 - introduce max size for the seed corpus and the CI fuzzer

### CODE REVIEW

**Comment by lemire** [comment]
That's fantastic.

Related thoughts...

We introduced an "at_pointer" call. 

```C++
dom::parser parser;
dom::element doc = parser.parse(json_document);
auto x = doc.at_pointer("/0/tire_pressure/1");
```

Because at_pointer can, in theory, take arbitrary strings, it would be nice to fuzz that at some point.

**Comment by pauldreik** [comment]
> Because at_pointer can, in theory, take arbitrary strings, it would be nice to fuzz that at some point.

I am actually writing an at_pointer fuzzer right now!

**Comment by pauldreik** [comment]
Ping @jkeiser, do you want to review or should I ask Daniel ?

**Comment by pauldreik** [comment]
> @pauldreik if you pass the environment variable SIMDJSON_FORCE_IMPLEMENTATION=westmere (or any implementation name), it forces simdjson to use that implementation. Would that allow you to just rerun the existing fuzzer once per implementation?

I am not really sure what you mean here, so I guess: you are concerned it is difficult to see which implementation is the offending one, and it would be easier to run the fuzzer once for each non-fallback implementation? 
I get your point, that would make it easier to put a nice label on the github action step. The way the PR in the current state does it has an advantage that it will work regardless of the target (arm or x64) and if an instruction set was disabled. I believe this is preferable when running on oss-fuzz, where I do not really know what hardware they use (probably some not so old x64). 

I have a proposal: I add a good error message which tells which outputs which implementation is the offending one just before abort(). That way you can see which one is the bad one, and I get to keep the generality. Did I comprehend your review correctly, and is my suggested solution OK? If so, I will update the PR. Otherwise, please elaborate!

**Comment by pauldreik** [comment]
I made a prototype of what I suggested in the previous comment, it outputs this when a difference (I introduced a bug on purpose):

> Implementation: haswell	Output: -1.04222
> Implementation: westmere	Output: -1.33333
> Implementation: fallback	Output: -1.33333
> Implementation haswell and westmere do NOT match.
> Implementation haswell and fallback do NOT match.
> Implementation westmere and fallback match.

and then it calls std::abort().

**Comment by jkeiser** [comment]
Yep, that sounds good to me :)

**Pull request merged**
