### PR TITLE
Add parsing competitions to cmake

### PR DESCRIPTION
**Pull request by jkeiser**
This gets all parsing competitions into cmake. I think that's all the executables we build.

This makes two major changes:

1. Build competition benchmarks and tests.
   - Adds dependencies/CMakeLists.txt which initializes submodules for competition
   - Adds `competition-core` and `competition-all` interface-only libraries, when linked these give you -I for the libraries you asked for (and build ujson4c if needed)
   - Builds all competitions in benchmark/
   - Adds issue150 test, building allparserscheckfile
2. Only apply simdjson-specific compile flags to simdjson (i.e. don't sanitize ujson4c).
   - Adds `simdjson-header` interface-only library, when linked this gives you -I for the headers as well as all compiler or linker flags needed.
   - Removes tools/cmake/Options since that's all it did
   - Moves simdjson-specific options into include where simdjson-headers is defined (and the only place they are referenced).

I suspect this has been one of the bigger reasons we've been maintaining both build systems.

### CODE REVIEW

**Comment by jkeiser** [comment]
There was an issue compiling the ujson4c library on clang when I added sanitize; but rather than fix the issue in ujson4c, I opted instead to make sanitize only apply to simdjson and to things that link simdjson. That cleared up the flags for ujson4c quite a bit.

**Comment by lemire** [comment]
I am impressed.

**Comment by lemire** [comment]
This is super neat.

**Comment by jkeiser** [comment]
Yeah, cmake's viral targets are kinda neat!

I just updated it against cmake. Very few changes involved in the rebase

**Comment by jkeiser** [comment]
Yay! That last push fixed it.

The parsing competitions don't presently compile on Windows, because of benchmark.h. I'll file a bug to bring them up to par. We should also get parse.exe up to par (get it to actually report hardware perf counters).

**Comment by jkeiser** [comment]
(Rebased to master.)

**Comment by jkeiser** [comment]
Yeah, I'm still learning about cmake but there are some things to like about it ...

**Pull request merged**
