### PR TITLE
Support JSON pointer in DOM navigation model

### PR DESCRIPTION
**Pull request by jkeiser**
This adds support for JSON pointer in the DOM navigation model. Two things to note:

1. It deliberately doesn't support the # URI fragment syntax. As far as I can tell, that's easier handled by just URI escaping first, and it's also conflating two different syntaxes in a single interface.
2. This patch preserves support for backslash escapes, but as far as I can tell, JSON pointer doesn't support those ...

### CODE REVIEW

**Comment by jkeiser** [comment]
Oh, it also explicitly allows you to index the root element with non-empty keys--e.g. `doc["foo"]` and `doc["/foo"]` are identical. This differs from the JSON pointer spec, which says `doc["foo"]` should be an error because it doesn't specify the `/`. But we ubiquitously allow relative pointers throughout so that you can mix and match JSON pointers with keys. And it was super weird treating `doc["/foo"]` differently from `doc.root()["foo"]`.

**Comment by jkeiser** [comment]
And, I did integer parsing myself because none of the standard libraries let you parse a non-null-terminated string_view without throwing an exception and I really didn't feel like allocating a string.

**Comment by jkeiser** [comment]
While I'm trying not to make changes, we wanted to highlight JSON pointer and it feels like we shouldn't do that unless we can show people how to use it with the blessed API :)

**Comment by jkeiser** [comment]
To be clear, this implementation owes most of its content to @ioioioio's implementation in ParsedJsonIterator! I moved it over, and then refactored it to fit into the piecemeal DOM API.

**Comment by lemire** [comment]
I created an issue for this...
https://github.com/simdjson/simdjson/issues/599

**Comment by jkeiser** [comment]
Thanks! I fixed the tool, and I have a README update coming with usage examples for everything.

**Pull request merged**
