### PR TITLE
Get submodules on demand

### PR DESCRIPTION
**Pull request by jkeiser**
- cmake will retrieve benchmark and ujson4c only, since they need to be
built
- make parse will not retrieve any submodules
- make distinctuseridcompetition will only retrieve competition-core
submodules
- make allparsingcompetition will retrieve all competition submodules

### CODE REVIEW

**Comment by jkeiser** [comment]
I suspect it's hitting concurrency issues with -j4, based on the haphazard results ...

**Comment by jkeiser** [comment]
It was a problem with git locking itself. Problem fixed with a 4s git lock retry timeout.

**Comment by jkeiser** [comment]
Here's where things get pulled now:

```
jkeiser@JKEISER-THINKPAD:~/simdjson/build$ cmake ..
-- Building a dynamic library.
-- Library output directory (does not apply to Visual Studio): /home/jkeiser/simdjson/build
-- /home/jkeiser/simdjson/dependencies//.git does not exist. Initializing ujson4c submodule ...
Submodule 'dependencies/ujson4c' (https://github.com/esnme/ujson4c.git) registered for path 'ujson4c'
Submodule path 'ujson4c': checked out 'e14f3fd5207fe30d1bdea723f260609e69d1abfa'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jkeiser/simdjson/build
jkeiser@JKEISER-THINKPAD:~/simdjson/build$ make distinctuseridcompetition
[ 12%] Generating ../../dependencies/sajson/.git
Submodule 'dependencies/sajson' (https://github.com/chadaustin/sajson.git) registered for path 'sajson'
Submodule path 'sajson': checked out '2dcfd350586375f9910f74821d4f07d67ae455ba'
[ 12%] Built target sajson-submodule
[ 37%] Built target simdjson
[ 50%] Generating ../../dependencies/jsmn/.git
Submodule 'dependencies/jsmn' (https://github.com/zserge/jsmn.git) registered for path 'jsmn'
Submodule path 'jsmn': checked out '18e9fe42cbfe21d65076f5c77ae2be379ad1270f'
[ 50%] Built target jsmn-submodule
[ 62%] Generating ../../dependencies/json/.git
Submodule 'dependencies/json' (https://github.com/nlohmann/json.git) registered for path 'json'
Submodule path 'json': checked out 'a015b78e81c859b88840cb0cd4001ce1fe5e7865'
[ 62%] Built target json-submodule
[ 75%] Generating ../../dependencies/cJSON/.git
Submodule 'dependencies/cJSON' (https://github.com/DaveGamble/cJSON.git) registered for path 'cJSON'
Submodule path 'cJSON': checked out 'c69134d01746dcf551dd7724b4edb12f922eb0d1'
[ 75%] Built target cJSON-submodule
[ 87%] Generating ../../dependencies/rapidjson/.git
Submodule 'scalarvssimd/rapidjson' (https://github.com/Tencent/rapidjson.git) registered for path 'rapidjson'
Submodule path 'rapidjson': checked out 'b32cd9421c5e3cbe183a99b6537ce11441e50656'
[ 87%] Built target rapidjson-submodule
Scanning dependencies of target distinctuseridcompetition
[100%] Building CXX object benchmark/CMakeFiles/distinctuseridcompetition.dir/distinctuseridcompetition.cpp.o
[100%] Linking CXX executable distinctuseridcompetition
[100%] Built target distinctuseridcompetition
jkeiser@JKEISER-THINKPAD:~/simdjson/build$ make allparsingcompetition
[  7%] Generating ../../dependencies/fastjson/.git
Submodule 'dependencies/fastjson' (https://github.com/mikeando/fastjson.git) registered for path 'fastjson'
Submodule path 'fastjson': checked out '485f994a61a64ac73fa6a40d4d639b99b463563b'
[  7%] Built target fastjson-submodule
[ 21%] Built target simdjson
[ 28%] Built target jsmn-submodule
[ 35%] Built target json-submodule
[ 42%] Generating ../../dependencies/gason/.git
Submodule 'dependencies/gason' (https://github.com/vivkin/gason.git) registered for path 'gason'
Submodule path 'gason': checked out '7aee524189da1c1ecd19f67981e3d903dae25470'
[ 42%] Built target gason-submodule
[ 50%] Built target cJSON-submodule
[ 57%] Built target rapidjson-submodule
[ 64%] Generating ../../dependencies/json11/.git
Submodule 'dependencies/json11' (https://github.com/dropbox/json11.git) registered for path 'json11'
Submodule path 'json11': checked out 'ec4e45219af1d7cde3d58b49ed762376fccf1ace'
[ 64%] Built target json11-submodule
[ 71%] Built target sajson-submodule
[ 78%] Built target ujson4c-submodule
[ 78%] Building C object dependencies/CMakeFiles/competition-ujson4c.dir/ujson4c/src/ujdecode.c.o
[ 85%] Linking C static library libcompetition-ujson4c.a
[ 85%] Built target competition-ujson4c
Scanning dependencies of target allparsingcompetition
[ 92%] Building CXX object benchmark/CMakeFiles/allparsingcompetition.dir/parsingcompetition.cpp.o
[100%] Linking CXX executable allparsingcompetition
[100%] Built target allparsingcompetition
jkeiser@JKEISER-THINKPAD:~/simdjson/build$ 
```

**Comment by lemire** [comment]
The makefile had this crazy funny business that people complained about regarding git. But it was designed precisely to avoid concurrency issues with git.

**Comment by jkeiser** [comment]
Well this was neat, but git has no apparent way to actually retry index.lock (I guess core.filesRefLockTimeout isn't for that), and cmake doesn't have good ways to run code such as locking after configure time. I would not mind a different build system.

**Pull request closed without merging**
