### PR TITLE
Providing a size() function to arrays and objects (lazy approach) [MAYBE DO NOT MERGE?]

### PR DESCRIPTION
**Pull request by lemire**
This is an alternative to PR https://github.com/simdjson/simdjson/pull/690

The idea is to compute the size of an array or an object when needed, lazily. Thus if you parse a document and never need to query the size of an array, you are not paying (much) for it. However, if you need it, you incur a price at query time, but only for the arrays or the object where you need the size.

Fixes  https://github.com/simdjson/simdjson/issues/688 and https://github.com/simdjson/simdjson/issues/308

### CODE REVIEW

**Comment by lemire** [comment]
@jkeiser  Here is my current thinking... We can burden the parsing with a lot of needless work "in case someone needs it". Unfortunately, the amount of work that one can tag along is large.

A better long term plan, I think, is to rely on lazy evaluation. You provide the functionality, but you do not force everyone to pay for it.

There is a third option, which is to offer an option to eagerly materialize the the size and other features... but I fear that this third option would add a lot of complexity. Both the lazy and the eager avenues have the advantage of not creating much complexity.

We have a strategic decision to take.

**Comment by jkeiser** [comment]
@lemire I think I'm OK with caching the size here, because I still expect the compiler to destructure this and optimize it away. If eager calculation of the size can be done for arrays without busting perf, I think that's preferable. We can handle objects separately; people are less likely to ask for size() there (they may still do it, but it's *less* likely).

Strategically, I think we need to look into an interface that materializes arrays and objects with the expected big-O characteristics. I have also realized that `max_size()` is not going to solve the problem appropriately: arrays of objects are going to be WAY oversized. I understand that's not the decision we're taking here, it's just part of my personal long-term calculus.

One serious question: if a user is planning to allocate and materialize an array, is it faster to use the vector array-growth approach, or is it faster to iterate through everything twice (once for size, once to copy)?

**Comment by lemire** [comment]
> One serious question: if a user is planning to allocate and materialize an array, is it faster to use the vector array-growth approach, or is it faster to iterate through everything twice (once for size, once to copy)?

It depends very much on the characteristics of the container, doesn't it? I'll write a quick benchmark to test it out.

**Comment by lemire** [comment]
I have just added a benchmark, here are the results on my iMac:

```
-----------------------------------------------------------------------------
Benchmark                                   Time             CPU   Iterations
-----------------------------------------------------------------------------
numbers_scan                            24873 ns        24845 ns        27794
numbers_size_scan                       10154 ns        10143 ns        68426
numbers_load_scan                      167293 ns       167060 ns         4102
numbers_load_size_scan                 165188 ns       164984 ns         4220
```

So querying the size, allocating the std::vector is much faster than just doing a stream of push_back.

**Comment by lemire** [comment]
On the same machine, with the same benchmark, here are the results from the eager approach (https://github.com/simdjson/simdjson/pull/690):

```
-----------------------------------------------------------------------------
Benchmark                                   Time             CPU   Iterations
-----------------------------------------------------------------------------
numbers_scan                            18234 ns        18214 ns        37995
numbers_size_scan                        6813 ns         6805 ns       102218
numbers_load_scan                      173760 ns       173527 ns         4002
numbers_load_size_scan                 160898 ns       160728 ns         4328
```

**Comment by lemire** [comment]
Recopied from the other issue:

1. I would expect the two numbers_scan functions to have the same performance. I do not understand the performance gap.

2. If you are taking into account the time to load the file, whether you have a size() function or not does not make much of a difference, no matter how the size() is computed. The eager approach where you make use of the precomputed size() to preallocate the std::vector wins a bit over the lazy approach (by about 4%). However, if you fail to take advantage of the size() function, then the roles are reversed, the lazy approach is nearly 4% faster.

3. If you just stress the DOM API, and assume that the document has already been parsed, then it is 2x faster (at least) to preallocate, and it does not matter whether you have the eager or lazy size(), it is always faster. 

4. The relative cost of using the API is small compared to the cost of parsing.

5. The lazy approach has poorer performance if you just stress the API.

**Comment by lemire** [comment]
So now moving to a Linux box with GCC and a skylake processor...

lazy...

```
-----------------------------------------------------------------------------
Benchmark                                   Time             CPU   Iterations
-----------------------------------------------------------------------------
numbers_scan                            29007 ns        29008 ns        24205
numbers_size_scan                       25617 ns        25617 ns        27322
numbers_load_scan                      192641 ns       192643 ns         3630
numbers_load_size_scan                 193524 ns       193525 ns         3615
```

Eager...
```
-----------------------------------------------------------------------------
Benchmark                                   Time             CPU   Iterations
-----------------------------------------------------------------------------
numbers_scan                            37099 ns        37099 ns        18866
numbers_size_scan                       20349 ns        20349 ns        34401
numbers_load_scan                      187722 ns       187726 ns         3722
numbers_load_size_scan                 187351 ns       187354 ns         3732
```

So it is a different compiler, and it shows.  In this instance, the lazy approach loses every time, except for the numbers_scan where it is noticeably faster.

**Comment by lemire** [comment]
> One serious question: if a user is planning to allocate and materialize an array, is it faster to use the vector array-growth approach, or is it faster to iterate through everything twice (once for size, once to copy)?

So while all my numbers don't answer all questions, I think I can answer this specific question definitively: yes, it can be faster to iterate through everything twice (once for size, once to copy).

**Comment by lemire** [comment]
All numbers on the linux/skylake box...

 eager...

```
-----------------------------------------------------------------------------
Benchmark                                   Time             CPU   Iterations
-----------------------------------------------------------------------------
numbers_scan                            37534 ns        37535 ns        18937
numbers_size_scan                       20190 ns        20191 ns        34664
numbers_load_scan                      187493 ns       187494 ns         3732
numbers_load_size_scan                 188533 ns       188536 ns         3720
twitter_count                            34.7 ns         34.7 ns     20155885
iterator_twitter_count                    213 ns          213 ns      3278980
twitter_default_profile                 19106 ns        19106 ns        36596
twitter_image_sizes                     0.000 ns        0.000 ns            0
error_code_twitter_count                 34.9 ns         34.9 ns     20059899
error_code_twitter_default_profile      21154 ns        21155 ns        33166
iterator_twitter_default_profile       110803 ns       110805 ns         6310
error_code_twitter_image_sizes           9390 ns         9390 ns        74498
iterator_twitter_image_sizes            54453 ns        54454 ns        12862
print_json                            5825386 ns      5825461 ns          120
```

lazy
```
-----------------------------------------------------------------------------
Benchmark                                   Time             CPU   Iterations
-----------------------------------------------------------------------------
numbers_scan                            28966 ns        28966 ns        24076
numbers_size_scan                       25677 ns        25677 ns        27278
numbers_load_scan                      193187 ns       193189 ns         3620
numbers_load_size_scan                 193615 ns       193617 ns         3616
twitter_count                            42.7 ns         42.7 ns     16401964
iterator_twitter_count                    213 ns          213 ns      3284350
twitter_default_profile                 21271 ns        21272 ns        32821
twitter_image_sizes                     0.000 ns        0.000 ns            0
error_code_twitter_count                 42.8 ns         42.8 ns     16375140
error_code_twitter_default_profile      22838 ns        22838 ns        30526
iterator_twitter_default_profile       111696 ns       111698 ns         6265
error_code_twitter_image_sizes          11178 ns        11179 ns        62784
iterator_twitter_image_sizes            54330 ns        54331 ns        12875
print_json                            5862757 ns      5862834 ns          119
```

So it looks like the lazy approach penalizes other benchmarks, for some odd reason.............?

**Comment by lemire** [comment]
I am going to close this. It is viable, but we have a slight preference for the eager approach.

**Pull request closed without merging**
