### PR TITLE
add utf8 and minifier fuzzers

### PR DESCRIPTION
**Pull request by pauldreik**
This is a placeholder until this branch is ready. Needs some more thinking.

The two fuzzers here showed useful (they detected #1170 and #1169) but they are pretty small and diffferent from the other fuzzers, since they do not really need json documents as input.

Perhaps they should be added to CI fuzzing, but not oss-fuzz in order not to waste resources.

### CODE REVIEW

**Comment by lemire** [comment]
> Needs some more thinking.

Can you elaborate?

Surely, you are not dismissing them solely because they are small?

**Comment by pauldreik** [comment]
Having fuzz targets which are uneven leads to diluted fuzzing effort. Sure, oss fuzz has a lot of cpu power but I do not want to waste it. Also, the CI jobs should be quick to wait for. I think the right thing here is to group the fuzzers in two groups:

Normal fuzzers (the ones already on master), taking json as input. Fuzzed by CI and oss-fuzz.

The small ones (utf8 and minifer), taking something else. Fuzzed by CI but not oss-fuzz.

So what I think remains here is to 
 - modify the oss-fuzz.sh script so it ignores the small ones. 
 - modify the existing github action, so it also runs the small ones. Perhaps for a shorter time.

What do you think?

**Comment by lemire** [comment]
@pauldreik That sounds good. A mild concern is that we try to have CI tests be deterministic as much as possible. It is not great when rerunning the test twice gives different test results.

**Comment by pauldreik** [comment]
> @pauldreik That sounds good. A mild concern is that we try to have CI tests be deterministic as much as possible. It is not great when rerunning the test twice gives different test results.

One could remedy it partially by setting the fuzzing seed to something varying but repeatable, like the git hash or (for short term repeatability) the unix time of the previous midnight. But the fuzzer corpus might have be updated by some other fuzzing run, so the output may differ anyway.
I would say this is a non problem so far. The only false alarm I can remember are the recent flaky afl runs on oss fuzz which were auto closed. No idea why they happened.

**Comment by pauldreik** [comment]
Having slept on this, I think there are two good reasons speaking for putting this on oss-fuzz anyway:
 - it adds coverage, so it is easier to spot what remains to fuzz
 - oss-fuzz is much more complete, using multiple fuzzer engines and build variants (memory sanitizer is difficult to use locally)

Also, it is less work to just add it.

**Comment by pauldreik** [comment]
This waits for #1187 to be fixed.

**Pull request merged**
