### PR TITLE
what happens if we remove this check for CI?

### PR DESCRIPTION
**Pull request by lemire**
This is an experiment in relation with issue 1803.

### CODE REVIEW

**Comment by lemire** [comment]
@Tachi107 What do you think of this PR?

**Comment by Tachi107** [comment]
I tested this patch [here](https://github.com/Tachi107/cloudflare-ddns/commit/428d3b5066992491a06e1454cca3f524fa2c0e51), and it fixed my issue :D

**Comment by lemire** [comment]
Merging.

**Comment by Tachi107** [comment]
Thanks!

**Pull request merged**
