### PR TITLE
Trying to fix issue 1013.

### PR DESCRIPTION
**Pull request by lemire**
Fix for https://github.com/simdjson/simdjson/issues/1013

### CODE REVIEW

**Comment by lemire** [comment]
@yurivict Can you have a look at this?

**Comment by yurivict** [comment]
SONAME is still wrong, because the long form is missing:
```
lib/libsimdjson.so
lib/libsimdjson.so.2
```

**Comment by lemire** [comment]
> SONAME is still wrong, because the long form is missing:

Ok Yuri, tell me what to put.

I don't know what to put. I gave this some thought and arrived at this PR. That is the best that my brain can do. You tell me it is wrong... Fine. I believe you. But can you tell me what would be right?

I am linking against libc.so.6. This matches version 2.something of libc. There is no "full form" of libc. I never needed the long form. What is the purpose of the long form?

Note that I am not arguing against you. I simply don't understand.

**Comment by lemire** [comment]
@jkeiser Can you help?

**Comment by lemire** [comment]
@yurivict (I do appreciate your help. I am just frustrated because I don't know what you are asking me to do.)

**Comment by yurivict** [comment]
```
SET_TARGET_PROPERTIES(
     lbsimdjson
   PROPERTIES
     SOVERSION 1
     VERSION 1.1.0
   )
```

**Comment by lemire** [comment]
@yurivict

Our version is 0.4.5. You want use to declare version 1.1.0? I don't understand. Can you elaborate?


cc  @cdluminate

**Comment by lemire** [comment]
I think that @cdluminate wants me to put ...

```
set_target_properties(<simdjson_shared_library> PROPERTIES
  VERSION 0.4.5
  SOVERSION 2
)
```

**Comment by lemire** [comment]
I don't really care about any of this. Just tell me how this works. We have a new 0.4.x series. It is not (I think) binary compatible with the 0.3.x series. What do I put?

Please don't tell me to put 1.1.0. Or, if you do... explain how you go from 0.4.5 to 1.1.0.

**Comment by yurivict** [comment]
> explain how you go from 0.4.5 to 1.1.0

```1.1.0``` was just an example.
Maybe you want to add this then:
```
set_target_properties(<simdjson_shared_library> PROPERTIES
  VERSION 0.4.5
  SOVERSION 0
)
```

The point is that the first digits should match.

**Comment by jkeiser** [comment]
I started researching a bit, but I haven't had to mess with Linux library versioning before. I started reading some stuff on it and at least one page said SOVERSION should be the first part of VERSION, as @yurivict is saying. But that page also had an API_VERSION that was entirely different, and I'm not sure which is which, and I don't now how canonical that page was besides.

**Comment by cdluminate** [comment]
https://github.com/simdjson/simdjson/issues/1014#issuecomment-652119627 Is a concrete, applicable, and well-defined rule to follow, with which the upstream developer could focus on more important issues.

**Comment by lemire** [comment]
What @cdluminate wrote is "SOVERSION is used to track the ABI change, and it does not have to be consistent with the VERSION, especially ABI consistency is not guaranteed for minor updates.

Setting VERSION to 0.4.5 and SOVERSION to 2 is not wrong."


I think that @cdluminate is right. There are major libraries like libc that have different versions.

To try to satisfy everyone, here is what I propose.

1. We will have an ABI version. It will be 2.0.0. It will next move to 3.0.0 and so forth. This will define the soname.

2. We will have a library version which will remain, say 0.4.5... for now, then move to 0.5.0.


We will keep track of these two things separately.

@yurivict : would that satisfy you?


You have to understand that I am facing contradictory advice and demands.

**Comment by lemire** [comment]
@jkeiser The soversion is used by the dynamic linker and never by the users. That’s my understanding. So I don’t think they need to match. It is just a common practice.

**Comment by lemire** [comment]
Here is an authoritative version...


"Never try to set the interface numbers so that they correspond to the release number of your package.  This is an abuse that only fosters misunderstanding of the purpose of library versions."

https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html

**Comment by yurivict** [comment]
I think you fundamentally misunderstand how SONAME practically works.

When the library installs files:
```
libxx,so
libxx.so.Major
libxx.so.Major.Minor
```

```libxx.so.Major``` is also a ```SONAME```. ```Major``` defines the level of both API and ABI backwards compatibility. Change in ```Major``` triggers update (rebuild) of all depending packages. ```Minor``` is a minory library version. It can also have non-breaking API changes, for example incremental API changes (some functions are added). When only ```Minor``` changes no dependencies need to be rebuilt.

Having ```SONAME``` mismatching a link name ```libxx.so.Major``` is very confusing. I can't find a single example on Linux or FreeBSD when such mismatch happens. All online explanations and examples also follow the above convention.

You need to explain why your project which is just a library like many others is special and should break this natural convention. How does API/ABI compatibility work then for your library?

True, ```SONAME``` is very poorly documented. So we should just follow what others do then and not invent new rules and not seek loopholes.

**Comment by lemire** [comment]
@yurivict 

Here is an example adapted straight from the CMake documentation... Can you explain it to me?

```
set_target_properties(dynamicFramework PROPERTIES
  # "current version" in semantic format
  VERSION 16.4.0
  # "compatibility version" in semantic format 
  SOVERSION 1.0.0
)
```


> I think you fundamentally misunderstand how SONAME practically works.

I am sure. I am also begging anyone to explain it to me. Take the. CMake example above and please explain it to me.

**Comment by yurivict** [comment]
IMO, this is a non-issue. Just set some numbers for both Major and Minor parts and be dome with this.These numbers do not have to match library or package version, they are rather a file version.

**Comment by lemire** [comment]
> IMO, this is a non-issue. Just set some numbers for both Major and Minor parts and be dome with this.These numbers do not have to match library or package version, they are rather a file version.

Yes. I agree with that.

**Comment by yurivict** [comment]
From the library developer perspective, every time you change anything that is non-API breaking in your library you should bump the ```Minor``` part. When you change your interface in a significant way you need to bump the ```Major``` part and possibly reset ```Minor``` to ```0.0```.

**Comment by jkeiser** [comment]
I will say: I sorta wish there was a way we could reset the SOVERSION to 1.0.0 when we release simdjson 1.0.0. It is only the crazy 0.x world that is causing this mismatch. And there can be real confusion when you download simdjson 0.4.2 and notice simdjson.2 gets installed "instead."

I can see a few ways we could go here.  There are probably more.

### Ways To Bump SOVERSION On Each 0.X Release

1. Keep current status quo. Only simdjson.2 is installed. This seems bad because you can't specify you want simdjson 1.4 vs. simdjson 1.3.
2. Make SOVERSION of 0.4.2 2.4.2. It still doesn't match the simdjson version, and can be confusing to someone trying to find the library they want. But it seems some libraries do this.
3. Make the SOVERSION 2.0.4.2? Then do we get simdjson.2, simdjson.2.0, simdjson.2.0.4, simdjson.2.0.4.2? Are 4 version parts even allowed?

### Ways To Make SOVERSION = Simdjson Version

1. Make no guarantees about 0.x compatibility. Revert SOVERSION to 0. Accept breaks until 1.0.
2. Release 1.0.0 earlier than planned. Release 2.0.0 when we hit the actual milestone we were hoping to hit. There are pros and cons to this, and they are all about marketing and stability promises. Both of these are important.

### Compromise?

1. Is there a way to put a negative number, or an identifier like "pre," as part of the major while we are at 0.x? Probably not. But if we could do that, then when 1.0 released, we would be able to use SOVERSION = 1 and have the files sync up at that point. (Let's ignore for now the fact that we already released a library with SOVERSION = 1, and call it water under the bridge.)

**Comment by jkeiser** [comment]
So. Everything I'm reading says shared library version = ABI version, and project version = API version (basically). These can change, and bump, independently. So maybe we just accept that and move on :)

**Comment by jkeiser** [comment]
I'm NOT an expert, and cannot evaluate this, but it seems pretty knowledgeable and well-researched: [this is the best guide I've found to shared library versions so far.](https://dcreager.net/shared-library-versions/)

**Comment by lemire** [comment]
@jkeiser Your reference states the same thing I caught on...

```
Of course, I’ve glossed over an important detail. You might assume from the previous section that the Semantic Version that you’ve chosen for your project (Foo Library 2.1.0) will line up with the version number encoded in your shared library file (libfoo.so.2.1.0). Au contraire, my friend!
```

**Comment by jkeiser** [comment]
> @jkeiser Your reference states the same thing I caught on...
> 
> > Of course, I’ve glossed over an important detail. You might assume from the previous section that the Semantic Version that you’ve chosen for your project (Foo Library 2.1.0) will line up with the version number encoded in your shared library file (libfoo.so.2.1.0). Au contraire, my friend!

Yep. I know for sure the difference between library *file* version and project version has confused me. But it's a fact of life. We still might want to think about one of the alternatives, but there's reasonably strong justification to just unhook the versions from each other.

**Comment by lemire** [comment]
@jkeiser

**Comment by lemire** [comment]
@yurivict I think that this will resolve your concerns. As far as the shared library is concerned, we are on 2.0.0. End of story.

This will part of our 0.4.6 release. 

The file version (soname) and our internal version numbers do not match.

**Pull request merged**
