### PR TITLE
Removed useless submodules

### PR DESCRIPTION
**Pull request by alexey-milovidov**
https://github.com/ClickHouse/ClickHouse/pull/13379

### CODE REVIEW

**Comment by jkeiser** [comment]
Could you elaborate on what you're trying to solve here? We use these submodules during testing and benchmarking, as you can see by the ci failures :)

**Comment by alexey-milovidov** [comment]
Sorry, accidentially opened PR to upstream.

**Comment by lemire** [comment]
@alexey-milovidov Note that there are options in simdjson to ignore these submodules when building the library.

**Comment by alexey-milovidov** [comment]
We are using simdjson in ClickHouse as a submodule but don't want to checkout recursive submodules.
This matters only for the time spent on cloning the repository.

I have made these changes in our fork of simdjson, then created a pull request to our fork... but GitHub suggested to create a pull request to the upstream repository and I missed that.

**Pull request closed without merging**
