### PR TITLE
Make Cmake install non_std/string_view.hpp

### PR DESCRIPTION
**Pull request by furkanusta**

### CODE REVIEW

**Comment by lemire** [comment]
Before we merge this, I want to know why we are not picking the issue in our tests.

This is serious.

**Comment by furkanusta** [comment]
Even without this change, all the unit-tests passes. Problem only manifests itself after you install the library and try to use it and as far as I can see none of the CIs test against that.

For the future, there is a deployment test in Boost.Hana which checks if the library is usable after installation. That might be useful

https://github.com/boostorg/hana/blob/07b42492765f7384e053c4761f4d0eda32b75834/test/CMakeLists.txt#L113

**Comment by furkanusta** [comment]
By the way I had one more issue with the cmake. If it isn't a problem on my end, I can open up a new issue instead of mixing unrelated problems.


```CMake
cmake_minimum_required(VERSION 3.17)
project(fooproject LANGUAGES CXX VERSION 1.0)
# find_package(simdjson-headers PATHS "/usr/local/lib64/cmake/simdjson/")
find_package(simdjson)
add_executable(foo foo.cpp)
target_link_libraries(foo simdjson::simdjson)
```

I had this simple CMakefile and unless I uncomment line 3 (and explicitly state PATHS), I get the following

> -- Could NOT find simdjson-headers (missing: simdjson-headers_DIR)
> CMake Warning at CMakeLists.txt:4 (find_package):
>   Found package configuration file:
> 
>   /usr/local/lib/cmake/simdjson/simdjson-config.cmake
> 
>   but it set simdjson_FOUND to FALSE so package "simdjson" is considered to
>   be NOT FOUND.  Reason given by package:
> 
>   The following imported targets are referenced, but are missing:
>   simdjson-headers

**Comment by jkeiser** [comment]
I am not sure who, if anyone, references the installed headers. Do we distribute them?

If so, we should set *that* as our include directory instead of the source one, perhaps?

**Comment by furkanusta** [comment]
simdjson-headers is linked to simdjson-include-source interface library and  simdjson target

I've managed to fix the problem by installing simdjson-headers target along with simdjson instead of exporting it as a separate one.

Deleted this part in include/CMakeLists.txt:
```CMake
install(TARGETS simdjson-headers
  EXPORT simdjson-headers-config
  INCLUDES DESTINATION include)

install(EXPORT simdjson-headers-config
  FILE simdjson-headers-config.cmake
  DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/simdjson)
```

and instead added to here in src/CMakeLists.txt
```CMake
install(TARGETS simdjson simdjson-headers
  EXPORT simdjson-config
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)
```

I was going to add these changes as well but I am not sure if this is the proper way. It was mostly trial and error for me.

**Comment by lemire** [comment]
> It was mostly trial and error for me.

That's how everything feels to me with CMake.

**Comment by furkanusta** [comment]
I had pushed the changes for the export target but

it seems that before cmake-3.13 install(TARGETS) cannot reference targets defined in sibling directories. That is why clang6 is failing on circleci (it uses 3.10)

Related issue for cmake: https://cmake.org/Bug/view.php?id=14444

Possible solution according to StackOverflow:
1. Move add_library calls to top level (which I don't want to do since it will make top-level CMakeLists too crowded)
2. Wrap add_library calls with a custom wrapper (I don't like custom functions as well since it is quite easy to miss and makes it harder for someone else to figure out)
3. Use separate installation targets (as before).

Right now 3 seems to be the most sensible. I will convert this PR to a draft and try to figure out, how to make one of the 2 installation targets transparent, so that users only have to deal with a single one

**Comment by jkeiser** [comment]
> > It was mostly trial and error for me.

> That's how everything feels to me with CMake.

Weirdly enough ... as the guy who just converted the rest of our tree to CMake? Me too.

I think I'm on record, but I'll repeat: I don't mind if we switch build systems again if someone does the work, I don't think cmake is the bees knees--but it does at least support the OS's we work with :)

> it seems that before cmake-3.13 install(TARGETS) cannot reference targets defined in sibling directories. That is why clang6 is failing on circleci (it uses 3.10)

Grr. Can we require a more recent cmake? Can it even be installed on ubuntu? There are a bunch of really nice features in 3.12 ... but when I do sudo apt install cmake it says I have the most recent version, so I assume our users would have the same trouble.

I really appreciate you figuring out cmake, the install/export stuff was super voodoo to me. This is my first time working with cmake. If you want to restructure things, you will step on no toes :)

**Comment by furkanusta** [comment]
I've looked at this issue and if possible I'd like to work more on CMake, which might also help with some related issues (CI speeds, and MSVC build issues etc.).  I will check the downstream projects to avoid major breakage, and hopefully fix with small steps.
Thus, for now I will be closing this pull request. After proper investigation I will open up new issues to discuss the possible solutions

**Comment by myd7349** [comment]
Any process on this issue?
I encountered the same issue when trying to update `vcpkg`'s `simdjson` to lastest. And to make vcpkg happy, I have to use a bunch of patch files. One of them is: https://github.com/microsoft/vcpkg/pull/10709/files#diff-5849ed25dfd8ff092f8439e8800e7728

Can we install `string_view.hpp` first? In that way, I can remove the patch file mentioned above.

**Comment by lemire** [comment]
@myd7349 This issue was closed, right?

**Comment by jkeiser** [comment]
I actually think we want to merge this. We also wanted to know why we didn't see the issue in our tests, and we need to file a bug on that. (The reason is that none of our tests ever use the installed headers from `build/include/*.h`, they either use amalgamated headers, or headers in the source tree itself.)

**Comment by jkeiser** [comment]
But I can't reopen it for some reason, which means I can't merge it ...

**Comment by jkeiser** [comment]
There is a question of whether we *want* to publish all the include files from include/, however. I think we only want to publish amalgamated headers from singleheader. Either way, as long as we are installing headers we need to install them all.

**Comment by furkanusta** [comment]
Sorry, I didn't get any messages after I closed this. Probably the reason you cannot reopen is that I moved the changes I made in here to an another branch, and cleaned the master branch in my fork.

I had managed to solve the problem mentioned in #830 but I encountered an another problem. I was going to send a more complete patch after I solve this one 

```CMake
include/simdjson/document.h:665:26: error: inlining failed in call to always_inline 
simdjson::dom::parser::parser(size_t) noexcept’: function body not available

```

**Comment by lemire** [comment]
> Sorry, I didn't get any messages after I closed this. Probably the reason you cannot reopen is that I moved the changes I made in here to an another branch, and cleaned the master branch in my fork.

Ok. So I understand that you will issue a new PR, right?

**Pull request closed without merging**
