### PR TITLE
Basic General Madness

### PR DESCRIPTION
**Pull request by the-moisrex**
Added some basic `tag_invoke` CPOs for some STL types (trying to get address this issue: #2230)

I knew soon enough I'll hit the "custom `#include` system" brick of this project; and I just did.

I added a `simdjson/std` directory; the idea is that we don't want the users to include the whole standard library.

But this project's `#include` system is not normal :)

I thought I got away with it with some tricks, but when you run `ninja` some python script yells at us.

### CODE REVIEW

**Comment by lemire** [comment]
> But this project's #include system is not normal :)


It is designed to be deployed as a single header (for users who prefer this).

However, if that's the only problem, this can be solved separately. E.g., *you* don't need to necessarily worry about it.

**Comment by the-moisrex** [comment]
@lemire  Is having a `std` directory like this is a direction you'd like to go?

**Comment by lemire** [comment]
>  Is having a std directory like this is a direction you'd like to go?

It does not look unreasonable to use a separate directory but we don't want people to start including different header files. We want people to always just include `simdjson.h`. The way we would want to handle it is have a macro which enables the functionality optionally.

The fact that you put stuff in a different directory is aesthetic...  

E.g., I don't even want users to stuff like

```
#include "simdjson/generic/ondemand/base.h"
```

Our directory structure should be hidden away from the users. We want them to do ...


```C++
include <iostream>
#include "simdjson.h"
using namespace simdjson;
int main(void) {
    ondemand::parser parser;
    padded_string json = padded_string::load("twitter.json");
    ondemand::document tweets = parser.iterate(json);
    std::cout << uint64_t(tweets["search_metadata"]["count"]) << " results." << std::endl;
}
```


And that's it... With maybe a twist like...

```C++
include <iostream>
#define SIMDJSON_OPTION 12
#include "simdjson.h"
using namespace simdjson;
int main(void) {
    ondemand::parser parser;
    padded_string json = padded_string::load("twitter.json");
    ondemand::document tweets = parser.iterate(json);
    std::cout << uint64_t(tweets["search_metadata"]["count"]) << " results." << std::endl;
}
```

And not something like...


```C++
include <iostream>
#include "simdson/ondemand/array.h"
#include "simdson/ondemand/object.h"
#include "simdson/features/extra/something.h"

...


using namespace simdjson;
int main(void) {
    ondemand::parser parser;
    padded_string json = padded_string::load("twitter.json");
    ondemand::document tweets = parser.iterate(json);
    std::cout << uint64_t(tweets["search_metadata"]["count"]) << " results." << std::endl;
}
```

One reason we don't want users to do this is that we want the code to be portable. Some users just grab `simdjson.h` and `simdjson.cpp` and they dump that in their projects. We want all our examples to work for them too. Unchanged.

**Comment by lemire** [comment]
I'll pull your code and have a look.

**Comment by the-moisrex** [comment]
@lemire 
I usually refrain from having such things:

```C++
#define SIMDJSON_OPTION 12
#include "simdjson.h"
```
because

1. It's order-dependent (options should come before the include), which if we have dumb IDE that re-orders things around, it's less than ideal.
2. It forces our hands if someday we wanted C++20 modules.
3. It relies on MACROS which in not the general direction that C++ is going


Another solution that solve both issues is to (I think) introduce some UBs by forward-declaring the types that we need in `std::` namespace, but we might end up doing some trickery since not all standard library implementations are as straight-forward as we want them to be; for example they declare the type in a sub-namespace and `using` them in the `std::` namespace and all of that.


And of course we could get macroei like this:

```C++
#include "simdjson.h"
SIMDJSON_ENABLE(vector, string, memory)
```

But I still think a manually included file by the user is the cleanest option and lessens the confusion for the users.

**Comment by lemire** [comment]
@the-moisrex We distribute the library as a single header (one `simdson.h` file). It is one of the most popular approach people use to integrate simdjson in their project. E.g., that's how Node.js integrates simdjson but also many other projects.

It is, of course, possible to create a different component that people could use in addition to simdjson.

**Comment by the-moisrex** [comment]
@lemire For single header solution we should be able to pull this off with help of some macro joojoo that the `tag_invoke`s are defined as macros with their incldues, and when the user enables it, we actually put the code right there when it's enabled:

```C++
#include "simdjson.h"
SIMDJSON_ENABLE(vector, string, memory)
```

I just need to know which direction are we going with this before I start implementing things.

**Comment by lemire** [comment]
@the-moisrex 

See https://github.com/simdjson/simdjson/pull/2267 for an application of your latest idea.

**Comment by the-moisrex** [comment]
I'm closing this PR for #2268

**Pull request closed without merging**
