### PR TITLE
Added tests over invalid documents.

### PR DESCRIPTION
**Pull request by lemire**
The On Demand API only validates what you use. This PR adds tests to codify this behavior.

cc @NicolasJiaxin 

Fixes https://github.com/simdjson/simdjson/issues/1623

### CODE REVIEW

**Comment by lemire** [comment]
@NicolasJiaxin Can you have a look?

**Review by NicolasJiaxin — APPROVED** [review]
Looks good!

**Comment by NicolasJiaxin** [comment]
Just a question.. Is `ASSERT_ERROR(expr, simdjson::SUCCESS)` equivalent to just `ASSERT_SUCCESS(expr)` ? If so, is it just a question of style in this case because we are asserting errors?

**Comment by NicolasJiaxin** [comment]
And also, if I understand the test well, this is what we have that On Demand:
*  Will validate the JSON syntax  of all the containers (object/array) in which the accessed value is 
*  Will validate the JSON syntax of all object/array/value only if before to the accessed value

As for escape characters, On Demand will only detect invalid escape sequences if the value is both accessed **and** read. 

So, it is "okay" to have invalid escape sequences in unaccessed keys/strings/values, and it is "okay" to have invalid escape sequence in the accessed key/string/value as long as it is not read (consuming it as a `ondemand::value` and not `std::string_view`).

**Comment by lemire** [comment]
> Just a question.. Is ASSERT_ERROR(expr, simdjson::SUCCESS) equivalent to just ASSERT_SUCCESS(expr) ? If so, is it just a question of style because we are asserting errors in this specific test?

Indeed. I could flip that around to simplify.

**Comment by lemire** [comment]
>  Will validate the JSON syntax of all object/array/value only if before to the accessed value

I think that's correct. Yes.

> As for escape characters, On Demand will only detect invalid escape sequences if the value is both accessed and read.

Within strings, yes, that's correct. Note that we will still detect invalid UTF-8 in the initial call to `iterate` as well as things like unclosed strings (for all but the fallback kernel, I think). However, if you never need the string value, then it may as well be invalid, as far as the On Demand front-end is concerned. Note that this is by design.

> So, it is "okay" to have invalid escape sequences in unaccessed keys/strings/values, and it is "okay" to have invalid escape sequence in the accessed key/string/value as long as it is not read (consuming it as a ondemand::value and not std::string_view). 

As long as you do not consume the value, then we do not have to fully validate it.

**Comment by lemire** [comment]
@NicolasJiaxin I simplified the code as you suggested.

**Pull request merged**
