### PR TITLE
Simpler  general madness

### PR DESCRIPTION
**Pull request by lemire**
This is an alternative to @the-moisrex's PR https://github.com/simdjson/simdjson/pull/2264

Basically, I just copied the content he put into an std directory in a single file 

```
"simdjson/generic/ondemand/std_deserialize.h"
```

The reason why I think it works whereas I was anxious before is that @the-moisrex is quite specific, not using broad concepts. So we extend support to `std::list`, `std::vector`... but not to any generic container-like concept.

If we think that some users might not want these default definitions, we can introduce an optional macro (`SIMDJSON_NEVER_SUPPORT_DESERIALIZATION`) or something, but the idea here is that this would be the right default 99% of the time.

I also removed the concept header I had added: I don't think we need this. Also, instead of checking for `__concepts` all over, we define the macro `SIMDJSON_SUPPORTS_DESERIALIZATION` once. (We don't general check for standard macros all over the code in simdjson, so this usage would be more consistent.) But these are details.

Note that this PR goes to `builder_development_branch` if merged.

(Should this ever get merged, @the-moisrex would get credit since the commits are still present.)

### CODE REVIEW

**Comment by the-moisrex** [comment]
@lemire My argument for these being in separate files is that the user wouldn't have to include pretty much the whole standard library when they include this library.

Because I was thinking of also implementing the STL types I mentioned in #2230 which is pretty much the whole STL.

My argument is not whether or not the users want the default or not, but that the defaults would require us to include pretty much the whole STL in the header file of this library which means the users of this library would be including the whole STL as well which slows down compilation time.

My concern is the compilation time.

**Comment by lemire** [comment]
@the-moisrex 

> My concern is the compilation time.

Compile time is a reasonable concern.

Let us see.

First let us review compile time using Apple LLVM 15 on ARM.

Main branch (C++ 20):


```
 ⚡  for i in {0..3}; do  time c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall ; done
c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.53s user 0.19s system 92% cpu 1.861 total
c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.51s user 0.11s system 98% cpu 1.645 total
c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.49s user 0.11s system 98% cpu 1.629 total
c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.49s user 0.11s system 98% cpu 1.620 total
```

Main branch (C++ 17):

```
⚡  for i in {0..3}; do  time c++ -std=c++17 amalgamate_demo.cpp simdjson.cpp -O3 -Wall ; done
c++ -std=c++17 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.29s user 0.22s system 87% cpu 1.719 total
c++ -std=c++17 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.31s user 0.11s system 97% cpu 1.451 total
c++ -std=c++17 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.30s user 0.11s system 97% cpu 1.445 total
c++ -std=c++17 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.29s user 0.10s system 98% cpu 1.408 total
```


This PR (C++ 20):


```
⚡  for i in {0..3}; do  time c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall ; done
c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.81s user 0.27s system 85% cpu 2.445 total
c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.76s user 0.14s system 98% cpu 1.925 total
c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.76s user 0.14s system 98% cpu 1.928 total
c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.79s user 0.15s system 95% cpu 2.039 total
```

This PR (C++ 17):

```
⚡  for i in {0..3}; do  time c++ -std=c++17 amalgamate_demo.cpp simdjson.cpp -O3 -Wall ; done
c++ -std=c++17 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.53s user 0.24s system 90% cpu 1.941 total
c++ -std=c++17 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.59s user 0.12s system 97% cpu 1.767 total
c++ -std=c++17 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.57s user 0.12s system 98% cpu 1.713 total
c++ -std=c++17 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.58s user 0.13s system 97% cpu 1.746 total
```


builder_development_branch, after running amalgamate.py (C++20):

```
⚡  for i in {0..3}; do  time c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall ; done
c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.86s user 0.40s system 87% cpu 2.595 total
c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.90s user 0.14s system 97% cpu 2.091 total
c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.91s user 0.14s system 98% cpu 2.083 total
c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.90s user 0.15s system 97% cpu 2.086 total

```

builder_development_branch, after running amalgamate.py (C++17):


```
⚡  for i in {0..3}; do  time c++ -std=c++17 amalgamate_demo.cpp simdjson.cpp -O3 -Wall ; done
c++ -std=c++17 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.55s user 0.37s system 80% cpu 2.385 total
c++ -std=c++17 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.55s user 0.12s system 99% cpu 1.675 total
c++ -std=c++17 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.52s user 0.12s system 100% cpu 1.631 total
c++ -std=c++17 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.54s user 0.13s system 95% cpu 1.763 total
```

Let us now switch to GCC 12 (x64):

Main branch (C++ 20):

```
 $ for i in {0..3}; do  time c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall ; done

real	0m8.015s
user	0m7.653s
sys	0m0.326s

real	0m7.661s
user	0m7.313s
sys	0m0.316s

real	0m7.878s
user	0m7.539s
sys	0m0.305s

real	0m8.045s
user	0m7.644s
sys	0m0.363s
```

Main branch (C++ 17):

```
$ for i in {0..3}; do  time c++ -std=c++17 amalgamate_demo.cpp simdjson.cpp -O3 -Wall ; done

real	0m7.270s
user	0m6.935s
sys	0m0.305s

real	0m6.977s
user	0m6.689s
sys	0m0.262s

real	0m7.235s
user	0m6.935s
sys	0m0.272s

real	0m6.970s
user	0m6.696s
sys	0m0.248s
```



This PR (C++ 20):

```
$ for i in {0..3}; do  time c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall ; done

real	0m7.715s
user	0m7.388s
sys	0m0.295s

real	0m7.652s
user	0m7.320s
sys	0m0.300s

real	0m7.361s
user	0m7.046s
sys	0m0.288s

real	0m7.395s
user	0m7.048s
sys	0m0.292s
```

This PR (C++ 17):

```
$ for i in {0..3}; do  time c++ -std=c++17 amalgamate_demo.cpp simdjson.cpp -O3 -Wall ; done

real	0m7.210s
user	0m6.890s
sys	0m0.291s

real	0m7.243s
user	0m6.935s
sys	0m0.279s

real	0m6.949s
user	0m6.662s
sys	0m0.262s

real	0m7.235s
user	0m6.934s
sys	0m0.272s
```



builder_development_branch, after running amalgamate.py (C++ 20):

```
real	0m7.991s
user	0m7.608s
sys	0m0.348s

real	0m7.358s
user	0m7.044s
sys	0m0.286s

real	0m7.640s
user	0m7.286s
sys	0m0.324s

real	0m7.345s
user	0m7.011s
sys	0m0.306s
```

builder_development_branch, after running amalgamate.py (C++ 17):

```
$ for i in {0..3}; do  time c++ -std=c++17 amalgamate_demo.cpp simdjson.cpp -O3 -Wall ; done

real	0m7.641s
user	0m7.287s
sys	0m0.320s

real	0m7.240s
user	0m6.910s
sys	0m0.299s

real	0m7.262s
user	0m6.919s
sys	0m0.314s

real	0m6.998s
user	0m6.705s
sys	0m0.266s
```

## Adding more headers to this PR

It is possible that adding STL headers to simdjson could slow down compile time, but I think we should quantify this effect.

Let add the following headers and recompiler...

```
#include <map>
#include <unordered_map>
#include <set>
#include <unordered_set>
```

I  am using LLVM 15 (arm) again...

This PR (C++ 20):


```
⚡  for i in {0..3}; do  time c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall ; done
c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.88s user 0.37s system 92% cpu 2.422 total
c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.77s user 0.13s system 99% cpu 1.902 total
c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.79s user 0.14s system 99% cpu 1.943 total
c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.77s user 0.13s system 97% cpu 1.951 total
```

This PR with new headers (C++ 20):

```
for i in {0..3}; do  time c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall ; done
c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.78s user 0.34s system 93% cpu 2.271 total
c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.78s user 0.13s system 98% cpu 1.948 total
c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.77s user 0.13s system 99% cpu 1.914 total
c++ -std=c++20 amalgamate_demo.cpp simdjson.cpp -O3 -Wall  1.77s user 0.14s system 98% cpu 1.943 total
```



## Analysis

-  C++20 appears to be costly. It is slower to compile with `-std=c++20` on both our main branch and this PR. The difference appears to be about 20%. It seems unrelated to recent work: this affects our main branch which did not target C++20 feature very much.
- The builder_development_branch compared to the main branch takes longer to build under LLVM (about 20%). It is less clear on my x64/GCC system.
- This PR on its own does not appear to affect compile times...
- Adding more STL headers does not appear, on its own, to affect measurably the compile time.

**Comment by lemire** [comment]
@the-moisrex

> For me, adding this code added ~1sec of compilation time (AI generated code):
> This code added ~2.5 seconds (also AI generated):

Clearly, you add enough dependencies and code to slow down the build. 

Aside from the build times, we also don't want to add thousands of lines of code to the library. This PR here has limited functionality, but does not slow things down nor does it add many lines of code (it is negligible).

I think you are imagining that we are bundle support for just about every possible data type or container in the C++ standard library.

We don't want to do this. There is the build time, but there is also just the volume of code that would get out of hand. We are going to end up with lots of headers, lots of code. Documenting and testing all of this will not be easy and most users will never touch this code anyhow. So the value proposition is not great.

If we want to have a very broad support for all sorts of data structures, then a really nice approach is to use concepts. Does it look like a pushable STL container? Then push the stuff in it.

The problem with this concept approach is that a user might end up with a data structure that 'looks like' a pushable STL container, but they don't want us to handle it, they want to provide their own deserialization code.

The issue with concepts is that they require that there is no ambiguity. Once you have defined how to handle a 'pushable STL container', you can't easily override this (to my knowledge).


So you to use fairly specific concepts if you are going to bundle them into a generic library.

I think that's doable though. Let us see.

**Comment by the-moisrex** [comment]
@lemire I already have concepts like `String`, `StringView`, `StringLike`, `AppendableCollection`, `LinearContainer`, `MapContainer`, and even `Appendable` which can be iterators, pointers, strings, containers or that we can push something into in Web++; but I don't believe this is a good way to go about this.

So I prefer being specific.

Also, I would add deserializations for:

- Raw Pointers
- `volatile` types
- raw array
- `std::array`
- iterators (maybe?)
- ranges (maybe?)
- ...

But as you can see with the way I implemented the `std::vector` and `std::basic_string<...>` and the rest of them, I don't like giving `std::string` or `std::string_view` or other types special treatment which traditionally SIMDJSON have given them special treatments.

For example a `std::pmr::string` is not treated the same way as `std::string` throughout the library.

I see `deserialize` as the opposition of [std::formatter<...>](https://en.cppreference.com/w/cpp/utility/format/formatter#Standard_specializations_for_library_types) which essentially is a serialize; so I would assume anything `std::formatter` supports but with the difference that they can operate on *read-only* types specially containers, but we have to operate on actual containers that contain their own elements and they're not a view of something else; which makes the library being able to get us `std::string_view` a questionable thing since now the user has to ask themselves for **how long can I keep this?**

This is why I'm concerned about the possible compilation time of the STL.
---

### Letting the users disable the defaults

We can simply have another CPO and not concern ourselves with macros at all.

An example implementation:

```C++

template <typename, typename>
struct is_deserialization_enabled : std::true_type {};


template <std::unsigned_integral T, typename ValT>
  requires is_deserialization_enabled<T, ValT>::value
error_code tag_invoke(deserialize_tag, ValT &val, T &out) noexcept {
  // ...
}

```


And users would disable the default for an specific element like:

```C++
template <typename ValT>
struct is_deserialization_enabled<std::vector<double>, ValT> : std::false_type {}
```

And also we could use a CPO like `deserializable_tag` so the users could disable it like this in a `consteval` CPO, **but I do not recommend this way, this is not clean**:

```C++
struct Car {
  consteval bool tag_invoke(is_deserialization_enabled_tag, std::type_identity<Car>) {
     return false;
  }
};
```


---

If we make it possible to disable the defaults easily for the users, I would agree with the use of broader implementations like `Appendable` or `Collection` or `String` or other things because then the users can disable the specific thing that they need to customize, even though, most-like **ADL will give them what they want anyway if their implementation's constraints are more restrict than ours**.

**Comment by lemire** [comment]
> If we make it possible to disable the defaults easily for the users, I would agree with the use of broader implementations like Appendable or Collection or String or other things because then the users can disable the specific thing that they need to customize, even though, most-like ADL will give them what they want anyway if their implementation's constraints are more restrict than ours.

That's a fantastic idea ❤️ ❤️ ❤️ ❤️ ❤️ 

Let us recap to make sure that we all understand the same thing:


1. Provide several concepts covering a broad range of containers and value types. This can be done with relatively little code. So it could build quickly and not require much maintenance.
2. Do not include a wide range of system headers. E.g., there would be no need for `#include <vector>` if the simdjson does not need it.
3. Make it relatively easy for a user of the library to disable our automagical concept-based code when, for their use cases, they need some special handling.

E.g., if I have...

```c++
class Myarray : public std::vector<double> {};
```

Then I understand the user could do...


```C++
template <typename ValT>
struct is_deserialization_enabled<Myarray, ValT> : std::false_type {}
```

... if they want to make sure that they can handcraft their own deserialization code. Correct?

**Comment by the-moisrex** [comment]
@lemire Yes, that is correct.

**Comment by the-moisrex** [comment]
> Then I understand the user could do...
> 
> ```C++
> template <typename ValT>
> struct is_deserialization_enabled<Myarray, ValT> : std::false_type {}
> ```

@lemire though, you wouldn't even need this 👆 if you're planning to customize it like this 👇 because of ADL:

```C++
class Myarray : public std::vector<double> {

  error_code tag_invoke(deserialize_tag, auto& val, Myarray& out) {
      // ...
  }
};
```

**Comment by the-moisrex** [comment]
@lemire Question: Do we really need the `ondemand` namespace? Because in extract, it's `simdjson::ondemand::to` and `simdjson::ondemand::sub`. Is the namespace necessary?

**Comment by lemire** [comment]
> Do we really need the ondemand namespace? Because in extract, it's simdjson::ondemand::to and simdjson::ondemand::sub. Is the namespace necessary?


You have `simdjson::dom` and `simdjson::ondemand`  'namespaces' which are two distinct APIs. 

All of the work that we are discussing only apply to `ondemand`. That's because the DOM API parses everything to an internal tree (which we call a tape) and then you just read off this tree. It would be possible to do C++20 magic there as well, but that's not what we have been doing. There is an array and object class in the DOM API as well, but they are different and subject to different documentation:

https://github.com/simdjson/simdjson/blob/master/doc/dom.md

https://github.com/simdjson/simdjson/blob/master/doc/basics.md

We have users of both APIs, and we are committed to supporting both types of users. The DOM API is easier to use, because it is more conventional. The On-Demand API requires thinking somewhat differently.

One of the magic of the On-Demand API is that you can go straight form the JSON string to your container. That's not possible with our DOM API. You always go first from the JSON string to the parsed tree, and then you can copy into your own data structures.

It is entirely possible for someone to use both the DOM API and the On-Demand API. So `simdjson::array` would not do as we have two of those.

So we qualify based on namespaces.

Of course, as you well know, the user does not need to type `simdjson::ondemand::to`. 


<details><summary>Details</summary>
<p>

## More technical details (engineering)



The `simdjson::ondemand` namespace is not really a namespace per se.

Headers that are under  `include/simdjson/generic` and `src/generic` is not meant to be used directly by anyone from outside the library as it is subject to runtime dispatching. Nobody should ever directly include anything in `include/simdjson/generic` except the library itself. And the library follows strict conventions when doing so.

To better understand the header files under `include/simdjson/generic`, please see...

https://github.com/simdjson/simdjson/blob/master/include/simdjson/generic/base.h

The general idea is that you can (and do!) compile different kernels which can be selected at runtime.

Please see ...

https://github.com/simdjson/simdjson/blob/master/src/implementation.cpp

for the technical details.

Effectively at any given time, you are working within the namespace `simdjson::SIMDJSON_IMPLEMENTATION::ondemand` where `SIMDJSON_IMPLEMENTATION` can take different values.


To help us keep things straight, we use the amalgamation script which validates that basic rules are followed.


</p>
</details>

**Comment by the-moisrex** [comment]
> Of course, as you well know, the user does not need to type simdjson::ondemand::to.

@lemire how come? ADL would not help to find `to` and `sub`'s namespace and even if it did, they're not functions, and ADL does not work on constructors as you can see here:

image

But it does work on functions:
image

Though we can fix that by making `to` and `sub` a different names, and make a function with `to` and `sub`, but even then that wouldn't fix much since arguments in `to("string", random_value_ref)` are not in `simdjson::ondemand`; so `simdjson::ondemand` does not show up on the ADL lookup as the namespaces ADL should look into in order to find `to`.

**Comment by the-moisrex** [comment]
Also, I have put the `deserialize` into the `simdjson` namespace and not `simdjson::whatever::ondemand` namespace:

```C++
namespace simdjson {
inline constexpr struct deserialize_tag {
 /// ...
} deserialize{};
}
```

That means deserialization CPOs need to be in `simdjson` namespace not `simdjson::...::ondemand` namespace.

**Comment by lemire** [comment]
@the-moisrex We are not merging this PR because, I think, we agree not to include a bunch of standard headers and standard types directly in the simdjson library. So I will close it to avoid confusion.

> That means deserialization CPOs need to be in simdjson namespace not simdjson::...::ondemand namespace.

The current PR works in the sense that your test in `ondemand_stl_types_tests.cpp` passes, in CI right now.

Let us focus on what users care about: functionality.

>> Of course, as you well know, the user does not need to type simdjson::ondemand::to.
> @lemire how come?

I recommend focusing on concrete issues. If you have a piece of code, a PR, I'll be happy to discuss it.

**Comment by lemire** [comment]
Closing because @the-moisrex convinced me that this was not the right direction.

**Pull request closed without merging**
