### PR TITLE
Building from the single-header files alone everywhere, including under Visual Studio

### PR DESCRIPTION
**Pull request by lemire**
This is distinct from the single-header tests we already have. It runs everywhere, including under Windows.

### CODE REVIEW

**Comment by lemire** [comment]
Drone is failing for some reason...

**Comment by jkeiser** [comment]
I'd like this to automatically re-amalgamate when you change the headers. I think it can be done. Give me a second.

**Comment by lemire** [comment]
@jkeiser  I think I figured out that the problem I was having was with the parallelism. I guess that the amalgamate.sh script was running just as I was trying to compile the files that it was generating... 

I tried for about 15 mins to tell CMake that my compilation was dependent on the script finishing, but I don't know how to do that and be sure that it works.

However, I can test the single header files that we already have!!!

**Comment by lemire** [comment]
I'll try to add a new test that has this dependency right.

**Comment by lemire** [comment]
Wait! It is not needed. So I think what I did was the right thing in the end. Let us see what the tests say.

**Comment by lemire** [comment]
@jkeiser  I think I am not smart enough for CMake. Here is the 
ci/circleci: sanitize-gcc9 error:

```
/usr/bin/ld.gold: error: CMakeFiles/simdjson.dir/simdjson.cpp.o: file is empty
collect2: error: ld returned 1 exit status
make[3]: *** [src/CMakeFiles/simdjson.dir/build.make:84: libsimdjson.so] Error 1
make[2]: *** [CMakeFiles/Makefile2:182: src/CMakeFiles/simdjson.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1046: tests/CMakeFiles/readme_examples.dir/rule] Error 2
make: *** [Makefile:470: readme_examples] Error 2
```

How does that have anything at all to do with the narrow changes that I made?

**Comment by lemire** [comment]
@jkeiser I think we should merge this.

**Comment by lemire** [comment]
> I'll see if I can get it to automatically re-amalgamate so we're using updated amalgamated sources in CI. Meantime, this is super positive change :)

My current PR, under Visual Studio, will test the single-header files *as they are in the repo*. That's what I want so I can answer people who report failures.

Of course, we could also reamalgate under Windows...  But I think it is complementary.

**Comment by lemire** [comment]
@jkeiser 

>Worth noting we're not running this test, but compiling it gets us 95% of bugs.

We are running it. Here is the result under Windows...

```
922      Start  1: amalgamate_demo_from_repo
923
9241: Test command: C:\projects\simdjson\build\singleheader\Release\amalgamate_demo_from_repo.exe "C:/projects/simdjson/jsonexamples/twitter.json" "C:/projects/simdjson/jsonexamples/amazon_cellphones.ndjson"
9251: Test timeout computed to be: 10000000
9261: parse valid
9271: parse_many valid
928 1/30 Test  #1: amalgamate_demo_from_repo ............................   Passed    0.04 sec
929test 2
```


I admit it is not an extensive test, but we can build the single header demo and run it.

**Comment by lemire** [comment]
I am going to merge this despite the strange error on the sanitizers.

**Pull request merged**
