### PR TITLE
Reenabling the optimized kernels (main branch).

### PR DESCRIPTION
**Pull request by lemire**
It seems that we mistakenly disabled by default the optimized kernels under ARM and PPC.

This is the same patch as https://github.com/simdjson/simdjson/pull/1343

### CODE REVIEW

**Comment by lemire** [comment]
@pauldreik This seems to create problems with the POWER fuzzer...

```
INFO: seed corpus: files: 19634 min: 1b max: 3894b total: 5176967b rss: 40Mb
5163
#19635	INITED cov: 38 ft: 110 corp: 83/17Kb lim: 4 exec/s: 0 rss: 40Mb
5164
Mismatch between implementations of validate_utf8() found:
5165
ppc64 returns true
5166
fallback returns false
5167
==23327== ERROR: libFuzzer: deadly signal
```

**Comment by lemire** [comment]
I am adding this particular broken UTF8 string to our regular tests.

**Comment by jkeiser** [comment]
Looks right. Since the tests passed, does that mean the string you found isn't actually a problem? Or that we don't run that test against all implementations?

**Review by jkeiser — APPROVED** [review]

**Comment by lemire** [comment]
@jkeiser  I have a POWER processor. Let me check.

**Comment by pauldreik** [comment]
Do I understand this correctly, that the power simd was never active?

**Comment by lemire** [comment]
> Do I understand this correctly, that the power simd was never active?

Never is a big word. I have not traced back where it became disabled by default.

At some point, it was enabled for sure. Then we disabled it (by default) accidentally.

**Comment by pauldreik** [comment]
Oh, good that you found this out! Maybe we should add a CI test per architecture that checks that the default (supposedly simd enabled) version are faster than the fallback!

**Comment by pauldreik** [comment]
I tried something like:

time tools/minify ../jsonexamples/github_events.json  >/dev/null

and then

export SIMDJSON_FORCE_IMPLEMENTATION=fallback
time tools/minify ../jsonexamples/github_events.json  >/dev/null

but it seems to be too fast to be relevant.

**Comment by lemire** [comment]
@pauldreik I don't think we want speed to be the deciding factor.

Nothing in our specification requires the fallback to be slower.

**Comment by lemire** [comment]
Verified to work well on POWER:

```
$ ./build/tests/document_stream_tests
Running tests against this implementation: ppc64(PPC64 ALTIVEC)
------------------------------------------------------------
Running document_stream tests.
Running stress_data_race
Running stress_data_race_with_error
Running test_leading_spaces
Running simple_example
got full document at 0
got full document at 9
got full document at 29
Running truncated_window
got full document at 0
got full document at 9
Running truncated_window_unclosed_string
A string is opened, but never closed.
Running issue1307
hex  : 02 00 0C 00 20 00
ascii:  __ __ __ __ __ __
Running issue1308
hex  : 6D C7 6D 5B 41 00
ascii: m__ __m__[__A__ __
Running issue1309
hex  : 09 00 39 38 0A 39 0A 0A 0A 0A 22 22 5F 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 26 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 5F 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 26 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 DB DB DB DB DB DB DB DB DB 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 26 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 26 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 00
ascii:  __ __9__8__ __9__ __ __ __ __"__"_____"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__&__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"_____"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__&__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__&__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__&__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__ __
Running issue1310
hex  : 20 20 5B 20 33 2C 31 5D 20 22 22 22 22 22 22 22 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20
ascii:  __ __[__ __3__,__1__]__ __"__"__"__"__"__"__"__ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __
Running issue1311
hex  : 35 23 30 5B 5B 30 0C FC 00
ascii: 5__#__0__[__[__0__ __ __ __
Running test_naked_iterators
Running test_current_index
Running single_document
Running issue1133
Running single_document_exceptions
Running threaded_disabled
Running small_window
Running large_window
Running json_issue467
Running document_stream_test
..................................................................................................................................................ok
Running document_stream_utf8_test
..................................................................................................................................................ok
document_stream tests are ok.
```

**Comment by lemire** [comment]
Merging.

**Pull request merged**
