### PR TITLE
Adding a new test file.

### PR DESCRIPTION
**Pull request by lemire**

### CODE REVIEW

**Comment by lemire** [comment]
Test file from https://github.com/simdjson/simdjson/issues/921

**Comment by jkeiser** [comment]
I just pinged the originator of the file ... I'd love to find out where these files we're using are from. It's very compelling to people when you can show them your data is from the real world (and to do that it helps to show exactly *where* :)).

**Comment by lemire** [comment]
Agreed.

**Comment by jkeiser** [comment]
@TkTech thinks it's http://s2-public-api-prod.us-west-2.elasticbeanstalk.com/corpus/ . I think that's good enough. We can call it semanticscholar-corpus.json?

**Comment by lemire** [comment]
Sure. I don't want to add this file before 0.4 though.

**Comment by lemire** [comment]
Marking 0.5.

**Pull request merged**
