### PR TITLE
Update simdjson.h to include simdjson_version.h

### PR DESCRIPTION
**Pull request by pps83**
After this change amalgamated simdjson.h has version info at the beginning of the file.

### CODE REVIEW

**Comment by lemire** [comment]
Sure. Let us merge this… I will review.

**Comment by pps83** [comment]
ping ^^^

**Comment by lemire** [comment]
Yes. I will get to it. I want to clean up the vs16 error before merging (not your fault).

**Comment by lemire** [comment]
Reference to https://github.com/simdjson/simdjson/pull/1795

**Pull request merged**
