### PR TITLE
default initialisaiton

### PR DESCRIPTION
**Pull request by ostri**
Yesterday we set a rule that all members need to be initialized (Weffc++ discovered bunch of uninitialized) and that modern style for initialization should be used.

Two more cases that we missed yesterday.

### CODE REVIEW

**Comment by lemire** [comment]
I have asked circleci to start again because I don't understand the failure.

**Comment by ostri** [comment]
> I have asked circleci to start again because I don't understand the failure.

If you are refering to "failed commit", it is my error making git commit/push.

**Comment by lemire** [comment]
@ostri No. Your commit is failing the sanitizers.

**Comment by jkeiser** [comment]
@lemire @ostri make sure this is rebased off latest master. The error you are getting seems to happen when you use -j to run parallel builds with the sanitizer on. I thought it was gone, but maybe it's just happening less often now ...

**Comment by ostri** [comment]
> @lemire @ostri make sure this is rebased off latest master. The error you are getting seems to happen when you use -j to run parallel builds with the sanitizer on. I thought it was gone, but maybe it's just happening less often now ...

Made a fresh fork. It shouldn't be this.

>g++: fatal error: Killed signal terminated program cc1plus
I think compiler crashed.

**Comment by jkeiser** [comment]
@lemire @ostri I guess my attempts to fix that didn't end up in master in all the mayhem. Here's the line that needs to change:

https://github.com/ostri/simdjson/blob/master/.circleci/config.yml#L121

```yaml
  sanitize-gcc9:
    description: Build and run tests on GCC 9 and AVX 2 with a cmake sanitize build
    executor: gcc9
    environment: { CMAKE_FLAGS: -DSIMDJSON_BUILD_STATIC=OFF -DSIMDJSON_SANITIZE=ON, CTEST_FLAGS: **-j4** --output-on-failure -E checkperf }
```

The bolded -j4 needs to be removed. I think I tried fixing it other ways and couldn't find a way.

**Comment by jkeiser** [comment]
@ostri yeah, I've seen that happen in sanitize-gcc9 only, and it seems like it got better when I removed parallel make. One sec.

**Comment by jkeiser** [comment]
@lemire @ostri OK, I think the issue is probably that. I guess my attempts to fix didn't make it to master in all the mayhem.

The code that needs fixing is in .circleci/config.yml:

```yaml
  sanitize-gcc9:
    description: Build and run tests on GCC 9 and AVX 2 with a cmake sanitize build
    executor: gcc9
    environment: { CMAKE_FLAGS: -DSIMDJSON_BUILD_STATIC=OFF -DSIMDJSON_SANITIZE=ON, CTEST_FLAGS: -j4 --output-on-failure -E checkperf }
    steps: [ install_cmake, cmake_test_all ]
```

environment needs `BUILD_FLAGS: ""` added. `, BUILD_FLAGS: }` will likely work too (without the "").

**Comment by ostri** [comment]
> @lemire @ostri OK, I think the issue is probably that. I guess my attempts to fix didn't make it to master in all the mayhem.
> 
> The code that needs fixing is in .circleci/config.yml:
> 
> ```yaml
>   sanitize-gcc9:
>     description: Build and run tests on GCC 9 and AVX 2 with a cmake sanitize build
>     executor: gcc9
>     environment: { CMAKE_FLAGS: -DSIMDJSON_BUILD_STATIC=OFF -DSIMDJSON_SANITIZE=ON, CTEST_FLAGS: -j4 --output-on-failure -E checkperf }
>     steps: [ install_cmake, cmake_test_all ]
> ```
> 
> environment needs `BUILD_FLAGS: ""` added. `, BUILD_FLAGS: }` will likely work too (without the "").

Why are developer and ci builds different?
HP used to day "eat your own s.."

**Comment by jkeiser** [comment]
@lemire @ostri I found it! Turns out I already made the change in [this PR](https://github.com/simdjson/simdjson/pull/728). It's in master.

**Comment by jkeiser** [comment]
> Why are developer and ci builds different?
> HP used to day "eat your own s.."

They aren't, or shouldn't be :) There are a *ton* of different build flavors running in CI. This is one of them. It adds flags to gcc to "sanitize" the code, making it so it will crash super early if there are memory issues, in ways that a normally-compiled version wouldn't. It has helped a ton in catching memory issues we didn't know we had, and I'm grateful it's in CI :)

**Comment by jkeiser** [comment]
So, if you rebase from master you should be good to go. It does seem like this PR is in good shape.

**Comment by ostri** [comment]
> So, if you rebase from master you should be good to go. It does seem like this PR is in good shape.

@jkeiser 
English please. ;-)
I am working all the time from copy of master.

**Comment by lemire** [comment]
> So, if you rebase from master you should be good to go. It does seem like this PR is in good shape.

He means that you need to sync your fork, the same way you did in the past.

Yes, you started from master, but while you were working, John changed master. You need to resync your fork. I know you did it in the past with the other PR... so you know how...

**Comment by lemire** [comment]
You can "rebase" by doing "git pull --rebase" but I don't think John cares whether you actually "rebase". Just pull the official master into your fork.

**Comment by ostri** [comment]
> You can "rebase" by doing "git pull --rebase" but I don't think John cares whether you actually "rebase". Just pull the official master into your fork.

I did that, but I do not understand, how my refreshed disk content will help the build process to go on on the build server. ;-)

**Comment by lemire** [comment]
> I did that, but I do not understand, how my refreshed disk content will help the build process to go on on the build server. ;-) 

You need to push to your repo.

**Comment by ostri** [comment]
> > I did that, but I do not understand, how my refreshed disk content will help the build process to go on on the build server. ;-)
> 
> You need to push to your repo.

$ git push 
Everything up-to-date

**Comment by lemire** [comment]
It says  that you repo is 7 commits behind, see screenshot:

Screen Shot 2020-04-23 at 3 09 05 PM

**Comment by lemire** [comment]
I'll restart the circle ci tests. I don't understand the results.

**Comment by lemire** [comment]
@jkeiser This is not good. We have a randomized continuous integration system in circle ci... Here are the errors currently...

```
 1/14 Test #21: readme_examples_noexceptions11 .......................***Failed    0.05 sec
-- cmake version 3.16.4
-- Building a dynamic library.
-- Library output directory (does not apply to Visual Studio): /home/conan/project
CMake Error at /usr/share/cmake-3.16/Modules/CPack.cmake:750 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:203 (include)


-- Configuring incomplete, errors occurred!
See also "/home/conan/project/CMakeFiles/CMakeOutput.log".
See also "/home/conan/project/CMakeFiles/CMakeError.log".
make: *** [Makefile:1016: cmake_check_build_system] Error 1

      Start 22: readme_examples_will_fail_with_exceptions_off
 2/14 Test #20: readme_examples_noexceptions .........................***Failed    0.05 sec

```

**Comment by jkeiser** [comment]
@lemire on that note, libcpp-clang9 failed for me too, in #786:

```
fatal: unable to access 'https://github.com/simdjson/simdjson/': gnutls_handshake() failed: Error in the pull function.
error: Could not fetch origin
```

Small sample size, but lots of libcpp-clang9 failures here.

**Comment by lemire** [comment]
Ok. The hell. I am merging this. I'll kill circle ci later.

**Pull request merged**
