### PR TITLE
[WIP] Move tape writes and internal state into stage 2 code

### PR DESCRIPTION
**Pull request by jkeiser**
This moves tape writing and related internal parser state into the stage 2 code and out of dom::parser. This should allow for more flexibility in parser implementations (less constraints on what state, what types you have to use, and where you store said state). Broken into lots of little commits to try and review for performance regressions.

WIP because of two performance regressions:

* [String writing](https://github.com/simdjson/simdjson/commit/88d0910c0153e48cff493eb1577f81f9432bf11a) loses 5-10% performance. I do not understand why--it *should* be a simple copy of code that was previously inlined ...
* [Number writing]() is a major loss (on the order of 20%), but was more predictable, since I futzed with it a lot ... still, the performance drop is precisely the same as I normally get when `structural_parser` stops getting enregistered. I suspect that's what's actually happening, but I haven't figured out precisely why yet.

Other commits made no performance difference.

### CODE REVIEW

**Comment by jkeiser** [comment]
@lemire I've tracked the string mystery down to [one small change](https://github.com/simdjson/simdjson/tree/jkeiser/string-state) (g++ 9.3.0):

This is fast:

```c++
really_inline void parser::write_string_length(uint32_t str_length) noexcept {
  memcpy(current_string_buf_loc, &str_length, sizeof(uint32_t));
}
doc_parser.write_string_length(str_length);
```

This is slow:

```c++
memcpy(doc_parser.current_string_buf_loc, &str_length, sizeof(uint32_t));
```

**Comment by lemire** [comment]
@jkeiser  This particular code is going away. Just hold my beer, I am working on the other PR.

**Comment by jkeiser** [comment]
OK, I've discovered that the issue moving number parsing over is *not* the never_inline function. If I remove the parser parameter entirely, it still happens. I think it must be the fact that I'm passing `*this` to the numberparsing function, causing C++ to decide `this` has to actually have an address :/

**Comment by lemire** [comment]
> Just hold my beer, I am working on the other PR.

Drank my beer and cancelled the other PR"

**Comment by lemire** [comment]
The performance drop is not a fluke... it seems quite real and large...

```
 for i in ../jsonexamples/*.json ; do echo $i; ./benchmark/parse $i | grep GB | head -n 1; ./../buildmaster/benchmark/parse $i | grep GB | head -n 1; done
../jsonexamples/apache_builds.json
|    Speed        :  33.2539 ns per block ( 99.35%) -   0.5197 ns per byte -   5.3496 ns per structural -   1.9243 GB/s
|    Speed        :  25.9085 ns per block ( 99.20%) -   0.4049 ns per byte -   4.1679 ns per structural -   2.4698 GB/s
../jsonexamples/canada.json
|    Speed        :  79.7456 ns per block ( 99.73%) -   1.2460 ns per byte -   8.3885 ns per structural -   0.8025 GB/s
|    Speed        :  71.0610 ns per block ( 99.69%) -   1.1103 ns per byte -   7.4750 ns per structural -   0.9006 GB/s
../jsonexamples/citm_catalog.json
|    Speed        :  28.7114 ns per block ( 99.76%) -   0.4486 ns per byte -   5.6979 ns per structural -   2.2290 GB/s
|    Speed        :  22.7589 ns per block ( 99.68%) -   0.3556 ns per byte -   4.5166 ns per structural -   2.8120 GB/s
../jsonexamples/github_events.json
|    Speed        :  29.8143 ns per block ( 98.95%) -   0.4660 ns per byte -   6.5187 ns per structural -   2.1460 GB/s
|    Speed        :  24.2141 ns per block ( 99.05%) -   0.3785 ns per byte -   5.2942 ns per structural -   2.6423 GB/s
../jsonexamples/google_maps_api_compact_response.json
|    Speed        :  96.9568 ns per block ( 98.70%) -   1.5185 ns per byte -   5.7546 ns per structural -   0.6585 GB/s
|    Speed        :  76.6378 ns per block ( 97.41%) -   1.2003 ns per byte -   4.5486 ns per structural -   0.8331 GB/s
../jsonexamples/google_maps_api_response.json
|    Speed        :  51.1985 ns per block ( 98.98%) -   0.8003 ns per byte -   6.7016 ns per structural -   1.2496 GB/s
|    Speed        :  41.6544 ns per block ( 99.01%) -   0.6511 ns per byte -   5.4524 ns per structural -   1.5359 GB/s
../jsonexamples/gsoc-2018.json
|    Speed        :  20.5257 ns per block ( 99.06%) -   0.3207 ns per byte -  14.0728 ns per structural -   3.1180 GB/s
|    Speed        :  19.4240 ns per block ( 99.00%) -   0.3035 ns per byte -  13.3174 ns per structural -   3.2949 GB/s
../jsonexamples/instruments.json
|    Speed        :  37.4124 ns per block ( 99.42%) -   0.5846 ns per byte -   4.7404 ns per structural -   1.7106 GB/s
|    Speed        :  29.0444 ns per block ( 99.24%) -   0.4538 ns per byte -   3.6801 ns per structural -   2.2035 GB/s
../jsonexamples/marine_ik.json
|    Speed        :  83.9815 ns per block ( 99.69%) -   1.3122 ns per byte -   6.0885 ns per structural -   0.7621 GB/s
|    Speed        :  76.0699 ns per block ( 99.13%) -   1.1886 ns per byte -   5.5149 ns per structural -   0.8413 GB/s
../jsonexamples/mesh.json
|    Speed        :  80.4070 ns per block ( 99.63%) -   1.2564 ns per byte -   5.9316 ns per structural -   0.7959 GB/s
|    Speed        :  77.1276 ns per block ( 98.92%) -   1.2052 ns per byte -   5.6897 ns per structural -   0.8297 GB/s
../jsonexamples/mesh.pretty.json
|    Speed        :  48.2305 ns per block ( 99.58%) -   0.7536 ns per byte -   7.7556 ns per structural -   1.3269 GB/s
|    Speed        :  45.7035 ns per block ( 98.88%) -   0.7141 ns per byte -   7.3493 ns per structural -   1.4003 GB/s
../jsonexamples/numbers100.json
|    Speed        :  71.7355 ns per block ( 99.88%) -   1.1209 ns per byte -   8.4119 ns per structural -   0.8922 GB/s
|    Speed        :  69.4770 ns per block ( 99.06%) -   1.0856 ns per byte -   8.1471 ns per structural -   0.9212 GB/s
../jsonexamples/numbers10.json
|    Speed        :  69.6262 ns per block ( 99.48%) -   1.0879 ns per byte -   8.1648 ns per structural -   0.9192 GB/s
|    Speed        :  67.1426 ns per block ( 98.75%) -   1.0491 ns per byte -   7.8735 ns per structural -   0.9532 GB/s
../jsonexamples/numbers.json
|    Speed        :  67.6876 ns per block ( 98.96%) -   1.0578 ns per byte -   7.9386 ns per structural -   0.9454 GB/s
|    Speed        :  64.4561 ns per block ( 96.79%) -   1.0073 ns per byte -   7.5596 ns per structural -   0.9928 GB/s
../jsonexamples/random.json
|    Speed        :  54.9427 ns per block ( 99.37%) -   0.8586 ns per byte -   4.9795 ns per structural -   1.1647 GB/s
|    Speed        :  40.7797 ns per block ( 99.73%) -   0.6372 ns per byte -   3.6959 ns per structural -   1.5692 GB/s
../jsonexamples/repeat.json
|    Speed        :  55.9213 ns per block ( 98.89%) -   0.8765 ns per byte -   9.7876 ns per structural -   1.1408 GB/s
|    Speed        :  49.2247 ns per block ( 98.83%) -   0.7716 ns per byte -   8.6155 ns per structural -   1.2961 GB/s
../jsonexamples/tree-pretty.json
|    Speed        :  46.9407 ns per block ( 98.67%) -   0.7335 ns per byte -   6.4026 ns per structural -   1.3633 GB/s
|    Speed        :  38.4481 ns per block ( 98.77%) -   0.6008 ns per byte -   5.2443 ns per structural -   1.6644 GB/s
../jsonexamples/twitter10.json
|    Speed        :  35.6753 ns per block ( 99.70%) -   0.5574 ns per byte -   6.3699 ns per structural -   1.7939 GB/s
|    Speed        :  29.0243 ns per block ( 99.52%) -   0.4535 ns per byte -   5.1823 ns per structural -   2.2050 GB/s
../jsonexamples/twitter_api_compact_response.json
|    Speed        :  65.1709 ns per block ( 98.28%) -   1.0220 ns per byte -   8.3852 ns per structural -   0.9784 GB/s
|    Speed        :  55.3734 ns per block ( 98.22%) -   0.8684 ns per byte -   7.1246 ns per structural -   1.1516 GB/s
../jsonexamples/twitter_api_response.json
|    Speed        :  52.9414 ns per block ( 97.60%) -   0.8295 ns per byte -   8.7929 ns per structural -   1.2055 GB/s
|    Speed        :  45.2385 ns per block ( 98.77%) -   0.7088 ns per byte -   7.5136 ns per structural -   1.4107 GB/s
../jsonexamples/twitterescaped.json
|    Speed        :  60.5603 ns per block ( 99.67%) -   0.9463 ns per byte -   9.6304 ns per structural -   1.0568 GB/s
|    Speed        :  56.0997 ns per block ( 99.65%) -   0.8766 ns per byte -   8.9211 ns per structural -   1.1408 GB/s
../jsonexamples/twitter.json
|    Speed        :  33.6569 ns per block ( 99.26%) -   0.5259 ns per byte -   6.0099 ns per structural -   1.9014 GB/s
|    Speed        :  26.7444 ns per block ( 99.29%) -   0.4179 ns per byte -   4.7756 ns per structural -   2.3929 GB/s
../jsonexamples/twitter_timeline.json
|    Speed        :  55.8712 ns per block ( 99.09%) -   0.8731 ns per byte -   6.9223 ns per structural -   1.1453 GB/s
|    Speed        :  46.2045 ns per block ( 98.68%) -   0.7221 ns per byte -   5.7246 ns per structural -   1.3849 GB/s
../jsonexamples/update-center.json
|    Speed        :  41.8850 ns per block ( 99.48%) -   0.6545 ns per byte -   5.5022 ns per structural -   1.5280 GB/s
|    Speed        :  33.0281 ns per block ( 99.47%) -   0.5161 ns per byte -   4.3387 ns per structural -   1.9377 GB/s
```

**Comment by jkeiser** [comment]
This PR has been replaced by #876.

**Pull request closed without merging**
