### PR TITLE
We should trim out old benchmarks.

### PR DESCRIPTION
**Pull request by lemire**
Now that @jkeiser has produced really high quality cross-library benchmarks, I think we should retire the old ones. Beyond the obvious fact that if you have something better, you should remove the suboptimal version... my motivation has to do with keeping the library lean. Having more code means more maintenance, longer build times...

This removes 1500 lines of code, which is not nothing.

A mild concern is that we no longer benchmark against as large a range of competitors as we did, but you quickly hit diminishing returns when you have too many.

### CODE REVIEW

**Comment by jkeiser** [comment]
The one caution here is, I haven't implemented the new benchmarks for all the parsers being tested on the old ones. There are 2 left from competition core, at the very least. And allparsingcompetition benchmarks even more of them.

**Comment by jkeiser** [comment]
I did implement what the fastest and most common json parsers, though--just strictly speaking we lose information here, but one could argue it's not super important information.

Still, it's worth looking at what's not implemented in case I missed something. I'm not an expert on which parsers are most commonly used.

**Comment by lemire** [comment]
The parsingcompetition tool that I propose deleting compares rapidjson, boostjson, yyjson, sajson, nlohmann by default. Of the list, we only lose boost but it can be brought back to the new framework by another PR. We also appear to include in the core libraries cjson and jsmn, but I am not sure why we do so: I do not recall anyone doing anything with such comparisons in our context.

I have nothing against the other libraries, but the only one that I think we might miss is boostjson.

> And allparsingcompetition benchmarks even more of them.

I do not think anyone ever used that. I think I wrote it up initially because I needed to get an overview of the field... but my impression is that it never served anyone's purposes.

The fact is that the list of JSON libraries is very long... but it is not cognitively useful to compare 100 things or even 20 different things. The brain can only take so much.

**Review by jkeiser — APPROVED** [review]
I agree boost ought to get its way in there.

**Comment by lemire** [comment]
@jkeiser I have created an issue regarding Boost JSON. Note that we do not currently do anything much with Boost JSON. Only a very naive benchmark... so this PR is not a significant lost.

**Comment by lemire** [comment]
I resolved some conflicts... waiting for the tests to run.

**Comment by lemire** [comment]
Merging.

**Pull request merged**
