### PR TITLE
detect if amalgamation is needed

### PR DESCRIPTION
**Pull request by pauldreik**
The idea is that the CI job checks if the user forgot to run the amalgamation script.

Also, it sets the date to be locale/timezone independent. 

To make it be reproducible, the date is picked from the git commit instead of the current time.

### CODE REVIEW

**Comment by pauldreik** [comment]
I should say that the reason I made this PR, is that the current master has a singleheader out of sync with the rest, which I detected on an unrelated branch where I ran the amalgamate.

**Comment by pauldreik** [comment]
I just reamalgamated master, and now the new CI job reports a small diff, only highlighting the issue of the date being locale sensitive which this PR fixes.

Time for review, @lemire or @jkeiser ?

**Comment by lemire** [comment]
@pauldreik Can you elaborate?

Please relate this PR with the following quote from our documentation...

> The simdjson.h and simdjson.cpp files in the singleheader directory are not always up-to-date with the rest of the code; they are only ever systematically regenerated on releases. To ensure you have the latest code, you can regenerate them by running this at the top level: (...) You need to have a working bash on your system.


See 
https://github.com/simdjson/simdjson/blob/master/HACKING.md#regenerating-single-header-files

> The idea is that the CI job checks if the user forgot to run the amalgamation script.


I am not sure what this implies, but I certainly do not want us to be running the amalgamation script with every commit. We *must* do so during a release but not with every commit. You *may* do so, but we don't want to start doing so systematically.

> I should say that the reason I made this PR, is that the current master has a singleheader out of sync with the rest

Yes. But this is expected. We use the amalgamated files as release artefacts. End users can point at a commit and can grab the two files.

Otherwise, these files are basically unnecessary and should only change occasionally.

Note that, as part of our CI, we do generate the amalgamated files and test them, dynamically.

If you need to up-to-date amalgamated files, you can generate them with a single command.

> Also, it sets the date to be locale/timezone independent.

This sounds like a good idea.

**Comment by pauldreik** [comment]
Thanks for the background. Now I now how I would like this to work:

The singleheader files should *not* be under version control. Instead they should be generated dynamically during CI test (already in place, as you say). On release, they are added to the release files manually.

As a user of the library, I would think it is very weird to say, use simdjson as a subrepo, then out of date files even if I use master.

As a developer of simdjson, I just think it is a hassle to have to wait for it to be generated when building locally (it is slow, especially when using sanitizers as I do for fuzzing).
Also, my IDE picks up the single header version and I have duplicate entries when searching for functions and symbols.

**Comment by lemire** [comment]
@pauldreik We have discussed this before, at some length. There is probably an issue related to it. That's why it is documented.

It can certainly change and I'd be happy for change us to change it for the better. However, it needs to change in a deliberate way, meaning that we need to think it through, we need to document it, we need to think about what it means for our users and so forth. Note that, currently, all of our documentation and releases point the users at the singleheader directory.

Furthermore, as I pointed out as part of another PR, we currently have a release process that is largely automated and reliable. We don't want to move to a largely automated, reliable process to a less automated, less reliable process. Slightly wrong releases cause a lot of grief. All of our recent releases have been smooth.

> As a user of the library, I would think it is very weird to say, use simdjson as a subrepo, then out of date files even if I use master.

This should never happen. If you are a user of the library, you should be using versioned releases in which case everything is in sync. If you are relying on something else, like a random commit... well... don't do that. 

> As a developer of simdjson, I just think it is a hassle to have to wait for it to be generated when building locally (it is slow, especially when using sanitizers as I do for fuzzing).

Short of dropping all of our current layout and doing all of our work inside two files, I don't see how it can be avoided.

That is, the CMake build will amalgamate as part of the tests but we need to do that to ensure that the result is correct. We can't *not test it* because this is what many of our users will ultimately consume.

But it is true that it is amazingly slow... it takes about 4 seconds on my laptop. But it is not the amalgamation itself that is a slow process, intrinsically. We are just copying and pasting files. This should take a fraction of a second. It is slow because we do all of the work in bash using inefficient code. 

So amalgamation performance is a separate issue.

Does anyone know how to profile a bash script? It should not take so long. I'll open an issue.

> Also, my IDE picks up the single header version and I have duplicate entries when searching for functions and symbols.

Right. That is annoying.

**Comment by pauldreik** [comment]
Yes, this would definitely take some effort to pull off. Perhaps we could use even more automation, I found this api to upload files to a release: https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#update-a-release-asset

**Comment by pauldreik** [comment]
> > Also, it sets the date to be locale/timezone independent.
> 
> This sounds like a good idea.

reducing the pull request to this.

**Comment by lemire** [comment]
Right. So github allow us to manually upload files during a release, via the browser. I am sure you understand why I don't think it is a good solution.

I do have another solution that I use for another project. Essentially, you take the source files that you consider to be part of a release and you **move/copy them** to a distinct repository, you check them in and tag them. Imagine having a simdjson_singleheader_release repository... and all you find there are the single header files.

That can be automated and it is safe.

But it would not fix the problem with our *slow* scripts. We need to fix that.

**Comment by pauldreik** [comment]
I meant that the existing release script could post the amalgamated file via the github api.

The script being slow is only a problem if you have to do it every time you build... Having the CI do it or when releasing, is hardly a problem. But for now, I agree it should be faster. Working on it.

**Comment by lemire** [comment]
> The script being slow is only a problem if you have to do it every time you build...

We agree with each other, and I am saying that we have to run the damn thing each time we test a change. I only realized today that it was really slow...

**Comment by pauldreik** [comment]
I found this by accident, which is good to keep the background: https://github.com/simdjson/simdjson/issues/106

**Comment by lemire** [comment]
@pauldreik As you can see, these are not new discussions at all. :-)

That's why it is documented the way it is.

The main annoyance to me is what you indicated. Tools find multiple versions of each function and variable.

**Comment by jkeiser** [comment]
#509 has context as well.

**Pull request merged**
