### PR TITLE
Partial documentation regarding relative JSON pointers.

### PR DESCRIPTION
**Pull request by lemire**
In https://github.com/simdjson/simdjson/pull/1618, @NicolasJiaxin documents the general usage of JSON pointers on top of On Demand. For document instances, we rewind/invalidate between each query at the beginning of each JSON pointer query. To recap, we rewind and reset the string buffer. The expectation is that people consume the result of a JSON pointer by, for example, copying the data into their own data structures.

However, somewhat discreetly, we also allow JSON pointer queries on arrays and object types. They are not formally supported by the standard. In such cases, we do not rewind. Rewinding at the component level would be problematic because the general JSON pointer implementation calls the component's JSON pointer implementation.

Currently, the behavior is as follows:

1. For arrays, we can only use `at_pointer` on a fresh, newly opened array. This means that you can only do `at_pointer` once... following queries should fail or give otherwise invalid results. There is a rather fundamental reason for this: we have no indexing. You may know that you are inside the array, but we don't track the index we are at. We could 'rewind' the arrays but that would allow people to consume the same string values multiple times which we don't want to allow. Furthermore, we don't want people to use `at_pointer` as an index (getting the value 0, 1, ...) as this could lead to performance anti-pattern. So, to sum it up, we allow one `at_pointer`. You can move to one index and maybe within the associated value, and that is all.
2. For objects, you can issue multiple `at_pointer` queries. Each time, you move (forward only) to a new key. Because we can only move forward, it works nicely and there is no other care needed.

The current plan is to remain discreet regarding this functionality. It will appear in our API documentation, but we will not document it further for the time being.

Fixes https://github.com/simdjson/simdjson/issues/1627

### CODE REVIEW

**Review by NicolasJiaxin — COMMENTED** [review]
Looks accurate. Should we keep `at_pointer` for objects and arrays public or make it protected for the time being?

**Comment by NicolasJiaxin** [comment]
If `at_pointer` becomes protected, that would break the benchmark I did in #1619 though.. We could always keep it as it is and make unofficial documentation for now like this PR, as long as it is documented somewhere

**Comment by lemire** [comment]
@NicolasJiaxin I don't think making them private or protected is warranted. These methods ought to work since we rely on them. However, they only work if used in the manner described which requires some care from the user (which is fine at this point).

What I do not want to do is to publish some public function that suggests some functionality we do not offer. I think that as long as we provide ample warnings, it is fine to have "discreet" functionality.

**Comment by NicolasJiaxin** [comment]
Yes I agree!

**Pull request merged**
