### PR TITLE
Test

### PR DESCRIPTION
**Pull request by lemire**

### CODE REVIEW

**Comment by jkeiser** [comment]
Thanks for looking. I'm out with family for a while longer yet.

**Comment by lemire** [comment]
> Thanks for looking. I'm out with family for a while longer yet.

I am curious. It is not me being hard working. Just obsessive.

Enjoy the family.

**Comment by jkeiser** [comment]
Oh! The theory is that this has to do with parallel make?

**Comment by lemire** [comment]
> Oh! The theory is that this has to do with parallel make?

Yes. My impression is that add_custom_command can effectively run twice in parallel if more than one target depends on the output. So you can only have one target depend on the output.

I may have this wrong, the documentation is not explicit. But I think my explanation is credible.

**Pull request closed without merging**
