### PR TITLE
Remove references to iso646.h

### PR DESCRIPTION
**Pull request by pps83**
It's deprecated in c++ and should not be used

### CODE REVIEW

**Comment by lemire** [comment]
This PR removes the alternative tokens which are definitively part of the C++ language and something we should encourage in my opinion.
 https://en.cppreference.com/w/cpp/language/operator_alternative

**Comment by lemire** [comment]
PR https://github.com/simdjson/simdjson/pull/845 suggests that the header is needed.

**Comment by lemire** [comment]
> It's deprecated 

Do you have a reference supporting this statement?

**Comment by jkeiser** [comment]
@lemire sounds like it's deprecated in c++20: https://docs.microsoft.com/en-us/cpp/standard-library/ciso646?view=vs-2019

**Comment by lemire** [comment]
@jkeiser The header has been obsolete for some time. It is a workaround.

Note what it says:

> Because this compatibility header defines names that are keywords in C++

So they are not retiring `and`, `not`, `or`... just the header.

**Comment by jkeiser** [comment]
Oh. Yes. I assumed @pps83 was reverting the keywords because of the fact that it failed in msvc :)

**Comment by pps83** [comment]
I personally find using `or` `and` etc are very confusing in c++, not many people know about these, I've seen people use these as variables even (zlib-ng). Normal operators are natural for c++ programmers, all these alt operators and trigraphs is historical mess to support keyboards that couldn't type these and should not be used in modern code imo

**Comment by lemire** [comment]
> not many people know about these

I agree but simdjson use many things that will be unfamiliar to some.

How much of their low usage is tied to relative poor support by compilers (e.g., Visual Studio used to required special flags)... and historical accidents, rather than merit?

I mean, Python uses `and` and not `&&` and I don't see anyone clamoring for the `&&` operator in Python.



> Normal operators are natural for c++ programmers

Are you saying that if you read...

```C++
if ((x == 1) or (x == 0)) {
}
```

you find it confusing... more confusing than 

```
if ((x == 1) || (x == 0)) {
}
```

Or that ...

```C++
if (not ascii) {
}
```

is better than

```
if (!ascii) {
}
```


> I've seen people use these as variables even (zlib-ng)

I am not familiar with zlib-ng, but these operators are part of the language. Thus the following will definitively not work in standard C++:

```C++

void or() {
    
}
void f() {
    int and = 1;
}
```

It will work under Visual Studio and some old compilers... but such code is definitively not standard compliant.


>  historical mess to support keyboards that couldn't type these

You objectively cannot see any benefit to ...

```C++
int x = z xor y;
```

rather than

```
int x = z ^ y;
```

I don't understand why we would be attached to `!`  or `^` and, to me, they look like historical leftovers from the era were we used one letter variable to save on memory.

**Comment by jkeiser** [comment]
Is the intent here to fix a deprecation error? I can't make one happen with g++-7, g++-10 or clang++-10. Using this command line (all the warnings/errors we enable) I get no warnings or errors:

```
g++-10 -std=c++2a -Werror -Wall -Wextra -Wsign-compare -Wshadow -Wwrite-strings -Wpointer-arith -Winit-self -Wconversion -Wno-sign-conversion -Iinclude -Isrc src/simdjson.cpp examples/quickstart/quickstart.cpp
```

If this is entirely an issue of code style, I'd like to not spend time on it right now, especially since there is no instant consensus on this particular question.

**Comment by pps83** [comment]
> Are you saying that if you read...
> 
> ```c++
> if ((x == 1) or (x == 0)) {
> }
> ```
> Or ...
> 
> ```c++
> if (not ascii) {
> }
> ```

... I'd find these weird. Very weird, that most people would be confused if that's ok in C++. I don't see that any often. To me it's the same when some to try to write perl style in c++:

```
print("something") || die(...);
```
Ignore/close the PR if you find these operators to be OK.

**Comment by lemire** [comment]
I *agree* with you that it is uncommon. It is especially uncommon under Visual Studio.

I also agree that someone might be surprised that it is legal C++ (even though it has been part of C++ since the beginning).

However, I don't think that it is the kind of surprise that will cause people a lot of negative stress.

Regarding your example

```
print("something") || die(...);
```

Wouldn't it be clearer as ...

```C++
print("something") or die(...);
```

**Comment by lemire** [comment]
I am going to close this. I think that there is no issue in the code.

**Pull request closed without merging**
