### PR TITLE
Disallow including headers from implementation files

### PR DESCRIPTION
**Pull request by jkeiser**
Issue #2037 happened because `arm64/implementation.h` was the first file to include `simdjson/implementation.h`. we no longer include some internal files at the top level, but were still including them in some implementation-specific files like `arm64/implementation.h`, which was allowed to be included in an #if SIMDJSON_IMPLEMENTATION_XXX block (which must be behind `SIMDJSON_CONDITIONAL_INCLUDE`). When compiled on a non-arm64 machine, the singleheader implementation will not compile.

I also renamed SIMDJSON_AMALGAMATED to SIMDJSON_CONDITIONAL_INCLUDE, to better mark what it's actually trying to say.

(Come to think, I'm now confused as to how it passed tests ........ but it's definitely wrong, and needs to be fixed, either way.)

This PR:

1. Tightens the rules around who can include what in amalgamate.py checking. Importantly, this detected the root cause of the reported issue (and I fixed it).
   - Disallows *all* implementation-specific files, including arm64.h, arm64/implementation.h and arm64/ondemand.h, from being included outside SIMDJSON_CONDITIONAL_INCLUDE blocks.
   - Disallows top-level headers from being included in any SIMDJSON_CONDITIONAL_INCLUDE file.
   - Disallows `generic` files from being included anywhere except amalgamator files (`arm64.h`, `arm64/implementation.h`, `arm64/ondemand.h`, `generic/amalgamated.h`--top-level files that can be included from outside).
2. Safely allows implementation-specific files (intrinsics.h, etc.) to be included in multiple SIMDJSON_CONDITIONAL_INCLUDE blocks. This will allow us to have more complicated #if statements.
   - Writes out implementation-specific files multiple times if they are included in a multiple SIMDJSON_CONDITIONAL_INCLUDE blocks (but no more than once per block).
   - Fails if an implementation-specific file is included more than once in the same block.
   - Fails if a `generic` file is included more than once per implementation in the same block.
3. Changes all includes to use <> instead of "", because in some cases we were getting relative paths included on accident! Especially with "base.h," which exists at many levels.
4. Renames `SIMDJSON_AMALGAMATED` to `SIMDJSON_CONDITIONAL_INCLUDE` to better explain what it means.
5. Validates that `amalgamate.py` actually includes all the files.
   - Moves `isadetection.h` back to src, since it's no longer needed in `simdjson.h`

### CODE REVIEW

**Review by lemire — APPROVED** [review]
The #include "" -> #include <> could have other consequences... I don't mind it,  but we should be mindful that it could have other impacts. We probably want to add a warning to the release notes.

**Comment by jkeiser** [comment]
@lemire what sort of implications? We can definitely solve it a different way if we want, with relative paths like `#include "./base.h"`. That might in fact be nicer for a lot of things (less repeating of the implementation name in implementation directories).

**Comment by lemire** [comment]
I am not a fan of relative bases and I don’t have any objection to your changes. I just wanted to put a note here in case we get bug reports later. Also the next release is at least a minor version bump.

I don’t know what, if anything, it could harm.

**Comment by jkeiser** [comment]
If it does, I wonder if `#include "/path"` ("absolute" path) might work and be unambiguous.

**Pull request merged**
