### PR TITLE
Safety: assert in debug mode when on demand values are used out of order

### PR DESCRIPTION
**Pull request by jkeiser**
Right now, on demand will exhibit bad behavior when you do this:

```c++
  auto json = R"(
    {
      "x": 1,
      "y": 2
    )"_padded;
  ondemand::parser parser;
  auto doc = parser.iterate(json);
  auto x = doc["x"];
  auto y = doc["y"];
  std::cout << "(" << uint64_t(x) << ", " << uint64_t(y)  << ")" << std::endl;
```

Essentially, you are delaying the parsing of "x" until the cout line, but then you go and grab the "y" field in between, which *skips* "x". Then when you do `uint64_t(x)`, you actually get the value of "y" (2) because that's where the iterator is now.

This PR adds an assert that occurs when this happens. I have verified it has no impact on performance on Skylake. In fact, I have verified that if you enable asserts in release mode, it *still* has no impact on performance. I'd actually like to turn these asserts on for release builds, but release mode in cmake passes -DNDEBUG by default, turning off *all* asserts, and we also have a no-assert policy for embedded-system reasons.

### CODE REVIEW

**Comment by pauldreik** [comment]
Did you mean to use x and y instead of a and b in the json?

**Comment by jkeiser** [comment]
@pauldreik I did! Thanks.

**Comment by lemire** [comment]
@jkeiser Your code sample in the actual PR uses a and b.

**Comment by jkeiser** [comment]
@lemire yep! Modifying now. Everything was a and b before and it successfully failed.

I realized I still have work to do though, to make the new test only run when asserts are on (when NDEBUG is off). I'll also make sure CI has at least one test where that's true.

**Comment by jkeiser** [comment]
OK, I fixed the issue and made the test more robust (it could fail for reasons OTHER than an assert).

I also did something I was planning once this landed: remove "bool at_start" from object_iterator, and check whether the json_iterator->index == object_iterator->_start_index + 1 (since at_start means "just after the `{`". This improved performance significantly on clang, around 3%: I was getting 2.86GB/s on PartialTweets, and now get 3.0GB/s!

Once I've got any further OS issues dealt with, this will be ready for review.

**Comment by jkeiser** [comment]
It appears that last change also helped g++ optimize ... it's now a bit faster than clang, for the first time (3.07GB/s vs. 3.0GB/s).

**Comment by jkeiser** [comment]
OK, it's looking good at the moment. Cirrus CI failed because it couldn't contact the agent (it seems to be generally down right now).

**Comment by jkeiser** [comment]
Interestingly, this could easily be used for an ondemand mode that could go backwards--that *would* let you use values out of order, and look up fields in an unordered fashion.

**Comment by pauldreik** [comment]
> It appears that last change also helped g++ optimize ... it's now a bit faster than clang, for the first time (3.07GB/s vs. 3.0GB/s).

Are you saying this PR is faster than the current master? Wow!

**Comment by jkeiser** [comment]
> Are you saying this PR is faster than the current master? Wow!

Yep :) By almost 10% for g++, and almost 5% for clang. At least on Skylake.

**Review by lemire — APPROVED** [review]
It would be nice to document the fork/wait tests as it seems somewhat non-trivial.

**Comment by jkeiser** [comment]
Will do. It was the simplest way I found I test wheher something died with an asset or not.

**Comment by jkeiser** [comment]
Remaining errors appear to be spurious. I'm going to re-run and then file them as issues if they disappear:

1. [fuzz error](https://github.com/simdjson/simdjson/pull/1342/checks?check_run_id=1559390584): this looks like an earlier issue that happened with utf-8 validation on other PRs:
   ```
   Mismatch between implementations of validate_utf8() found:
   ppc64 returns true
   fallback returns false
   ==26147== ERROR: libFuzzer: deadly signal
       #0 0x10034bdc in __sanitizer_print_stack_trace (/home/runner/work/simdjson/simdjson/build/fuzz/fuzz_utf8+0x10034bdc)
       #1 0x1003f964 in fuzzer::PrintStackTrace() (/home/runner/work/simdjson/simdjson/build/fuzz/fuzz_utf8+0x1003f964)
       #2 0x1004fa70 in fuzzer::Fuzzer::CrashCallback() (/home/runner/work/simdjson/simdjson/build/fuzz/fuzz_utf8+0x1004fa70)
       #3 0x1004f9f8 in fuzzer::Fuzzer::StaticCrashSignalCallback() (/home/runner/work/simdjson/simdjson/build/fuzz/fuzz_utf8+0x1004f9f8)
       #4 0x10073014 in fuzzer::CrashHandler(int, siginfo_t*, void*) (/home/runner/work/simdjson/simdjson/build/fuzz/fuzz_utf8+0x10073014)
LLVMSymbolizer: error reading file: No such file or directory
       #5 0x40007fe28c  ([stack]+0x7fd28c)
   
   NOTE: libFuzzer has rudimentary signal handlers.
         Combine libFuzzer with AddressSanitizer or similar for better crash reports.
   SUMMARY: libFuzzer: deadly signal
   MS: 3 ShuffleBytes-ShuffleBytes-CrossOver-; base unit: e62837e7341ecc1a77bdfd1bd53e04280a3c6e64
   artifact_prefix='./'; Test unit written to ./crash-0852862fb0337490ba79330e807245efd676085b

2. Drone (this failure happened on different tasks in the [PR](https://cloud.drone.io/simdjson/simdjson/7423/17/2) and [push](https://cloud.drone.io/simdjson/simdjson/7422/4/2) CI runs, making me think it's something with that setup):
   ```
   CMake Error at dependencies/import.cmake:32 (file):
   --
   93 | file RENAME failed to rename
   94 |  
   95 | /drone/src/dependencies/
   96 |  
   97 | to
   98 |  
   99 | /drone/src/dependencies/.cache/rapidjson
   100 |  
   101 | because: Invalid argument
   102 |  
   103 | Call Stack (most recent call first):
   104 | dependencies/CMakeLists.txt:81 (import_dependency)
   105 | dependencies/CMakeLists.txt:117 (competition_scope_)
   ```

3. [Cirrus](https://cirrus-ci.com/task/4675127835099136): agent still not responding. Is Cirrus just broke?

**Comment by jkeiser** [comment]
Yeah, the fuzz and Cirrus issues happen on master. Doing a [double-check Travis run](https://cloud.drone.io/simdjson/simdjson/7424) to see if that one recurs.

**Comment by lemire** [comment]
Cirrus does happen at least temporarily broken. I would ignore it for now.

The drone error also appears spurious.

The fuzzer issue is clearly unrelated to your PR. I don't know what it is about.

**Comment by lemire** [comment]
I would ignore the failures. They are not related to this PR. This PR is green.

**Comment by jkeiser** [comment]
Yep, Drone succeeded this time. Merging.

**Comment by jkeiser** [comment]
Next up: out of order execution. Now that we keep the start_index for each object, I'm planning to use the current search-from-current-field approach (so that in-order fields are as fast as before), but if that fails, cycle around and search from the beginning of the object.

**Comment by lemire** [comment]
Sounds quite exciting.

**Pull request merged**
