### PR TITLE
[for discussion] No more null termination

### PR DESCRIPTION
**Pull request by lemire**
We start from https://github.com/simdjson/simdjson/pull/856 and add the optimization that there are no more null endings (which are unsafe anyway). Would also fix https://github.com/simdjson/simdjson/issues/185

In some cases, this goes faster. Twitter goes from 2.42GB/s to 2.47GB/s. It also uses less memory. But, importantly, it is also safer. We cannot guarantee that our strings are free of nulls, so promising a null terminated string, though correct, still leaves us open to the possibility that the original string had a null in it, in which case, the user is being mislead. Small concern, I know.

Another benefit is that we simplify the API.

```
$ for i in ../jsonexamples/*.json ; do echo $i; ./benchmark/parse $i | grep GB | head -n 1; ./../buildmaster/benchmark/parse $i | grep GB | head -n 1; done
../jsonexamples/apache_builds.json
|    Speed        :  25.4460 ns per block ( 99.29%) -   0.3977 ns per byte -   4.0935 ns per structural -   2.5147 GB/s
|    Speed        :  25.6340 ns per block ( 99.23%) -   0.4006 ns per byte -   4.1237 ns per structural -   2.4963 GB/s
../jsonexamples/canada.json
|    Speed        :  72.0404 ns per block ( 99.68%) -   1.1256 ns per byte -   7.5780 ns per structural -   0.8884 GB/s
|    Speed        :  71.0939 ns per block ( 99.64%) -   1.1109 ns per byte -   7.4784 ns per structural -   0.9002 GB/s
../jsonexamples/citm_catalog.json
|    Speed        :  22.7607 ns per block ( 99.68%) -   0.3556 ns per byte -   4.5170 ns per structural -   2.8118 GB/s
|    Speed        :  22.7995 ns per block ( 99.59%) -   0.3562 ns per byte -   4.5247 ns per structural -   2.8070 GB/s
../jsonexamples/github_events.json
|    Speed        :  23.9912 ns per block ( 98.82%) -   0.3750 ns per byte -   5.2455 ns per structural -   2.6668 GB/s
|    Speed        :  24.4489 ns per block ( 98.81%) -   0.3821 ns per byte -   5.3456 ns per structural -   2.6169 GB/s
../jsonexamples/google_maps_api_compact_response.json
|    Speed        :  76.7189 ns per block ( 98.55%) -   1.2016 ns per byte -   4.5534 ns per structural -   0.8322 GB/s
|    Speed        :  76.2270 ns per block ( 98.73%) -   1.1939 ns per byte -   4.5242 ns per structural -   0.8376 GB/s
../jsonexamples/google_maps_api_response.json
|    Speed        :  41.3848 ns per block ( 97.98%) -   0.6469 ns per byte -   5.4171 ns per structural -   1.5459 GB/s
|    Speed        :  41.9363 ns per block ( 98.69%) -   0.6555 ns per byte -   5.4893 ns per structural -   1.5255 GB/s
../jsonexamples/gsoc-2018.json
|    Speed        :  19.2413 ns per block ( 98.86%) -   0.3006 ns per byte -  13.1922 ns per structural -   3.3261 GB/s
|    Speed        :  19.4563 ns per block ( 98.96%) -   0.3040 ns per byte -  13.3396 ns per structural -   3.2894 GB/s
../jsonexamples/instruments.json
|    Speed        :  28.2678 ns per block ( 99.40%) -   0.4417 ns per byte -   3.5817 ns per structural -   2.2640 GB/s
|    Speed        :  28.8327 ns per block ( 99.25%) -   0.4505 ns per byte -   3.6533 ns per structural -   2.2196 GB/s
../jsonexamples/marine_ik.json
|    Speed        :  75.5895 ns per block ( 99.34%) -   1.1811 ns per byte -   5.4801 ns per structural -   0.8467 GB/s
|    Speed        :  75.9863 ns per block ( 98.98%) -   1.1873 ns per byte -   5.5088 ns per structural -   0.8423 GB/s
../jsonexamples/mesh.json
|    Speed        :  76.3198 ns per block ( 99.07%) -   1.1926 ns per byte -   5.6301 ns per structural -   0.8385 GB/s
|    Speed        :  76.9671 ns per block ( 98.77%) -   1.2027 ns per byte -   5.6779 ns per structural -   0.8315 GB/s
../jsonexamples/mesh.pretty.json
|    Speed        :  45.6256 ns per block ( 99.25%) -   0.7129 ns per byte -   7.3367 ns per structural -   1.4027 GB/s
|    Speed        :  45.5598 ns per block ( 98.89%) -   0.7119 ns per byte -   7.3262 ns per structural -   1.4047 GB/s
../jsonexamples/numbers100.json
|    Speed        :  68.2246 ns per block ( 99.72%) -   1.0660 ns per byte -   8.0002 ns per structural -   0.9381 GB/s
|    Speed        :  69.5935 ns per block ( 99.00%) -   1.0874 ns per byte -   8.1607 ns per structural -   0.9196 GB/s
../jsonexamples/numbers10.json
|    Speed        :  65.7411 ns per block ( 99.09%) -   1.0272 ns per byte -   7.7092 ns per structural -   0.9735 GB/s
|    Speed        :  66.8642 ns per block ( 98.47%) -   1.0448 ns per byte -   7.8409 ns per structural -   0.9571 GB/s
../jsonexamples/numbers.json
|    Speed        :  64.4949 ns per block ( 98.92%) -   1.0079 ns per byte -   7.5641 ns per structural -   0.9922 GB/s
|    Speed        :  64.7059 ns per block ( 96.80%) -   1.0112 ns per byte -   7.5889 ns per structural -   0.9890 GB/s
../jsonexamples/random.json
|    Speed        :  40.3545 ns per block ( 99.64%) -   0.6306 ns per byte -   3.6573 ns per structural -   1.5858 GB/s
|    Speed        :  41.1323 ns per block ( 99.69%) -   0.6428 ns per byte -   3.7278 ns per structural -   1.5558 GB/s
../jsonexamples/repeat.json
|    Speed        :  49.2921 ns per block ( 98.44%) -   0.7726 ns per byte -   8.6273 ns per structural -   1.2943 GB/s
|    Speed        :  48.7191 ns per block ( 98.70%) -   0.7636 ns per byte -   8.5270 ns per structural -   1.3095 GB/s
../jsonexamples/tree-pretty.json
|    Speed        :  37.8815 ns per block ( 98.32%) -   0.5920 ns per byte -   5.1670 ns per structural -   1.6893 GB/s
|    Speed        :  38.4759 ns per block ( 98.76%) -   0.6013 ns per byte -   5.2480 ns per structural -   1.6632 GB/s
../jsonexamples/twitter10.json
|    Speed        :  28.3515 ns per block ( 99.44%) -   0.4430 ns per byte -   5.0622 ns per structural -   2.2574 GB/s
|    Speed        :  28.9748 ns per block ( 99.60%) -   0.4527 ns per byte -   5.1735 ns per structural -   2.2088 GB/s
../jsonexamples/twitter_api_compact_response.json
|    Speed        :  54.3861 ns per block ( 98.11%) -   0.8529 ns per byte -   6.9976 ns per structural -   1.1725 GB/s
|    Speed        :  55.5190 ns per block ( 98.69%) -   0.8707 ns per byte -   7.1433 ns per structural -   1.1485 GB/s
../jsonexamples/twitter_api_response.json
|    Speed        :  44.4184 ns per block ( 98.32%) -   0.6960 ns per byte -   7.3773 ns per structural -   1.4368 GB/s
|    Speed        :  45.1255 ns per block ( 98.75%) -   0.7071 ns per byte -   7.4948 ns per structural -   1.4143 GB/s
../jsonexamples/twitterescaped.json
|    Speed        :  55.3273 ns per block ( 99.35%) -   0.8645 ns per byte -   8.7982 ns per structural -   1.1567 GB/s
|    Speed        :  55.3872 ns per block ( 99.62%) -   0.8655 ns per byte -   8.8078 ns per structural -   1.1555 GB/s
../jsonexamples/twitter.json
|    Speed        :  25.8887 ns per block ( 99.40%) -   0.4045 ns per byte -   4.6228 ns per structural -   2.4720 GB/s
|    Speed        :  26.4025 ns per block ( 99.30%) -   0.4126 ns per byte -   4.7145 ns per structural -   2.4239 GB/s
../jsonexamples/twitter_timeline.json
|    Speed        :  45.8424 ns per block ( 99.16%) -   0.7164 ns per byte -   5.6797 ns per structural -   1.3959 GB/s
|    Speed        :  46.0106 ns per block ( 99.02%) -   0.7190 ns per byte -   5.7006 ns per structural -   1.3908 GB/s
../jsonexamples/update-center.json
|    Speed        :  32.8592 ns per block ( 99.36%) -   0.5134 ns per byte -   4.3165 ns per structural -   1.9477 GB/s
|    Speed        :  33.1475 ns per block ( 99.50%) -   0.5179 ns per byte -   4.3544 ns per structural -   1.9307 GB/s
```

### CODE REVIEW

**Comment by lemire** [comment]
Oh ! Come on ! This is not a performance regression.

**Comment by lemire** [comment]
(This PR can be taken "for discussion".)

**Comment by lemire** [comment]
Closing.

**Comment by jkeiser** [comment]
I'm actually on board with eliminating null termination, especially if it speeds things up. Might need to be an option for people though.

**Comment by lemire** [comment]
@jkeiser On Twitter, the benefit is clear enough. Otherwise, the benefit looks to be too small to bother.

**Pull request closed without merging**
