### PR TITLE
do not use deprecated apis in the fuzzers

### PR DESCRIPTION
**Pull request by pauldreik**
simdjson has moved forward! The fuzzers have been refreshed to use the new api.

### CODE REVIEW

**Comment by lemire** [comment]
@pauldreik There is a visual studio compile error...

```
c:\projects\simdjson\include\simdjson/inline/document.h(809): warning C4018: '>': signed/unsigned mismatch [C:\projects\simdjson\build\fuzz\fuzz_dump.vcxproj]
158C:\projects\simdjson\fuzz\fuzz_dump.cpp(24): error C2679: binary '<<': no operator found which takes a right-hand operand of type 'std::string_view' (or there is no acceptable conversion) 
```

**Comment by pauldreik** [comment]
> @pauldreik There is a visual studio compile error...
> 
> ```
> c:\projects\simdjson\include\simdjson/inline/document.h(809): warning C4018: '>': signed/unsigned mismatch [C:\projects\simdjson\build\fuzz\fuzz_dump.vcxproj]
> 158C:\projects\simdjson\fuzz\fuzz_dump.cpp(24): error C2679: binary '<<': no operator found which takes a right-hand operand of type 'std::string_view' (or there is no acceptable conversion) 
> ```

I'm working on it :-)

**Comment by jkeiser** [comment]
Oh thanks! This was the main blocker for adding -Werror everywhere for me :) I didn't know quite enough about the fuzzer to be sure my changes would still actually test what they are supposed to test!

**Comment by jkeiser** [comment]
@pauldreik could you help me with some of these questions? Don't worry about the nits, but I don't understand the fuzzer tests well enough to know what the purpose of the different tests are. I am curious if we would lose anything important if we used << and dropped the dump_raw_tape test ...

**Comment by pauldreik** [comment]
> @pauldreik could you help me with some of these questions? 

Off course! Not sure which questions you mean though? What the fuzzers do perhaps? They just have to somehow trigger interesting behaviour inside the program. It does not really matter which api they use, as long as it results in the code being exercised. 

Most of the fuzzers stress the parser, but they differ in what they do with the parsed result. I want to have separate fuzzers for:
 - dumping back to text ( like the dump_raw_tape fuzzer)
 - dumping as in the readme on the front page intended for end users
 - the json-pointer stuff (looks error prone on the inside!)
 - the minifier
 - ndjson

I look at the coverage output from oss-fuzz to try to see what is missing.

> I am curious if we would lose anything important if we used << and dropped the dump_raw_tape test

Could you elaborate on this, do you mean the dump_raw_tape fuzzer is redundant or that it should be spelt with << instead somehow?

I hope this clarified the situation, perhaps there should be an additional section on the fuzzer readme on the fuzzing strategy!

**Comment by jkeiser** [comment]
> Most of the fuzzers stress the parser, but they differ in what they do with the parsed result. I want
> to have separate fuzzers for:
> 
> * dumping back to text ( like the dump_raw_tape fuzzer)
> * dumping as in the readme on the front page intended for end users

These first two, I'm not sure we need both of: dump_raw_tape is really an internal thing. But I wasn't sure if, like, the fuzzer took the output of dump_raw_tape and used that as feedback to figure out what other test cases to explore. It sounds like the answer there is no :)

* the json-pointer stuff (looks error prone on the inside!)
* the minifier

Are we able to test that these actually work, or is the main point just to test for crashes?

**Comment by pauldreik** [comment]
> Are we able to test that these actually work, or is the main point just to test for crashes?

You bring up an interesting point here! I started out fuzzing simdjson because I had this idea of repeating the crypto differential fuzzing idea for json libraries, (see the comment here: https://github.com/simdjson/simdjson/issues/43#issuecomment-546204105) . There is already some work in this area, see the later comment in the same thread: https://github.com/simdjson/simdjson/issues/43#issuecomment-546510558

So there is 
 - "fuzzing for correctness" where correctness is determined by comparing two implementations which are supposed to give the same answer.
 - fuzzing for memory corruption, leaks etc (found by fuzzing with sanitizers)
 - fuzzing to trigger internal errors (asserts)

We are already covering the last two points. Fuzzing for correctness is non-trivial because of 
 -  tiny floating point differences 
 -  different strategy on utf-8
 - ordering on keys (?)

It strikes me that it would be possible to differential fuzz simdjson against itself, to make sure nothing is changed, which would make it possible to do tweaking/refactoring and be certain that it still works like it used to. A fuzzer job could be comparing master against the branch. It is non-trivial how to keep two versions of the same library at the same time, perhaps by using the amalgamated header and wrapping it in a namespace?

**Comment by lemire** [comment]
@pauldreik @jkeiser 

We have fuzzing for correctness... 

https://github.com/simdjson/fuzzyjson

It is not integrated in simdjson, and not part of CI. The idea is to generate random JSON, and have different libraries parse the same input, and check the differences.

This was used to find several bugs in simdjson, but also in other libraries. That's we found that sajson does not do proper UTF8 validation.

I will open a distinct issue.

**Pull request merged**
