### PR TITLE
Move current_loc to stage 2 code

### PR DESCRIPTION
**Pull request by jkeiser**
Attempt #2. After further testing, I now think I hit a fluke when I saw the performance degradation on skylake. Let's see what CI thinks.

### CODE REVIEW

**Comment by jkeiser** [comment]
The checkperf issues do not replicate on circleci. I'm calling it noise and am producing a PR to reduce the frequency of this nonsense (hopefully without losing the check itself)

**Comment by jkeiser** [comment]
I would appreciate a sanity check on this one, though, if you wouldn't mind running it through the paces ... this is a sensitive change.

**Comment by lemire** [comment]
This is a change to be merged into jkeiser/number-parse-no-write, correct?

**Comment by lemire** [comment]
It is hard for me to balance out PRs that merge into PRs that merge into master... is there any reason not to compare this with master?

**Comment by jkeiser** [comment]
Yeah, since I'm going to get rid of the number parsing PR, I'll redo this one on top of master with just the changes we want to keep.

**Comment by jkeiser** [comment]
Given that this depends on the number parsing one, I'm closing it ... I will redo it at some point though :)

**Pull request closed without merging**
