### PR TITLE
Increase build timeout for circle-ci sanitize job

### PR DESCRIPTION
**Pull request by jkeiser**
This is an attempt to get rid of the spurious errors we keep getting for gcc sanitize in circle ci.

### CODE REVIEW

**Comment by lemire** [comment]
60 mins seems like a long time... :-)

**Comment by jkeiser** [comment]
Instead of killing the build, this at least gave us some useful output to track down:

```
Scanning dependencies of target ondemand_twitter_tests
/home/travis/build/simdjson/simdjson/include/simdjson/dom/serialization-inl.h:74: error: relocation overflow
try relinking with a smaller --stub-group-size
```

**Comment by jkeiser** [comment]
@lemire mostly because I didn't want to futz with it anymore. But maybe this output will let us track down why it's slow, instead.

**Comment by jkeiser** [comment]
I'm going to rerun this job, but this failure is odd: https://cloud.drone.io/simdjson/simdjson/8296/15/2

```
1508	Running truncated_window_unclosed_string
864s
1509	A string is opened, but never closed.
864s
1510	Running issue1307
864s
1511	hex  : 02 00 0C 00 20 00 
864s
1512	ascii:  __ __ __ __ __ __
864s
1513	Running issue1308
864s
1514	hex  : 6D C7 6D 5B 41 00 
864s
1515	ascii: m__ __m__[__A__ __
864s
1516	Running issue1309
864s
1517	hex  : 09 00 39 38 0A 39 0A 0A 0A 0A 22 22 5F 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 26 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 5F 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 26 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 F3 DB DB DB DB DB DB DB DB DB 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 26 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 26 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 22 00 
864s
1518	ascii:  __ __9__8__ __9__ __ __ __ __"__"_____"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__&__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"_____"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__&__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__&__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__&__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__"__ __
864s
1519	Running issue1310
864s
1520	hex  : 20 20 5B 20 33 2C 31 5D 20 22 22 22 22 22 22 22 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 
864s
1521	ascii:  __ __[__ __3__,__1__]__ __"__"__"__"__"__"__"__ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __
864s
1522	Running issue1311
864s
1523	hex  : 35 23 30 5B 5B 30 0C FC 00 
864s
1524	ascii: 5__#__0__[__[__0__ __ __ __
864s
1525	Running test_naked_iterators
864s
1526	Running test_current_index
864s
1527	Running single_document
864s
1528	Running issue1133
864s
1529	Running single_document_exceptions
864s
1530	Running window_too_small_issue1370
864s
1531	.Expected a capacity error but got: No error
864s
1532	The input was: []�1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
864s
1533	We parsed the document: []
```

I seem to recall other occasional capacity errors in the past.

**Comment by jkeiser** [comment]
The Drone sanitize test failed with:

```
[ 97%] Linking CXX executable ondemand_object_tests
CMakeFiles/ondemand_object_tests.dir/ondemand_object_tests.cpp.o: In function `auto object_tests::value_object_find_field_unordered()::$_23::operator()<simdjson::simdjson_result<simdjson::fallback::ondemand::document> >(simdjson::simdjson_result<simdjson::fallback::ondemand::document>) const':
/home/travis/build/simdjson/simdjson/include/simdjson/generic/ondemand/token_iterator-inl.h:11:(.text+0x1fffde4): relocation truncated to fit: R_PPC64_REL24 (stub) against symbol `__asan_report_store8' defined in .text section in /usr/lib/llvm-10/lib/clang/10.0.0/lib/linux/libclang_rt.asan-powerpc64le.a(asan_rtl.cpp.o)
/home/travis/build/simdjson/simdjson/include/simdjson/generic/ondemand/token_iterator-inl.h:11:(.text+0x1fffe74): relocation truncated to fit: R_PPC64_REL24 (stub) against symbol `__ubsan_handle_type_mismatch_v1_abort' defined in .text section in /usr/lib/llvm-10/lib/clang/10.0.0/lib/linux/libclang_rt.asan-powerpc64le.a(ubsan_handlers.cpp.o)
/home/travis/build/simdjson/simdjson/include/simdjson/generic/ondemand/token_iterator-inl.h:11:(.text+0x1ffff0c): relocation truncated to fit: R_PPC64_REL24 (stub) against symbol `__asan_report_load4' defined in .text section in /usr/lib/llvm-10/lib/clang/10.0.0/lib/linux/libclang_rt.asan-powerpc64le.a(asan_rtl.cpp.o)
/home/travis/build/simdjson/simdjson/include/simdjson/generic/ondemand/token_iterator-inl.h:11:(.text+0x1fffff4): relocation truncated to fit: R_PPC64_REL24 (stub) against symbol `__ubsan_handle_pointer_overflow_abort' defined in .text section in /usr/lib/llvm-10/lib/clang/10.0.0/lib/linux/libclang_rt.asan-powerpc64le.a(ubsan_handlers.cpp.o)
CMakeFiles/ondemand_object_tests.dir/ondemand_object_tests.cpp.o: In function `auto object_tests::value_object_find_field_unordered()::$_23::operator()<simdjson::simdjson_result<simdjson::fallback::ondemand::document> >(simdjson::simdjson_result<simdjson::fallback::ondemand::document>) const':
/home/travis/build/simdjson/simdjson/include/simdjson/generic/ondemand/value_iterator-inl.h:31:(.text+0x2000064): relocation truncated to fit: R_PPC64_REL24 (stub) against symbol `__asan_report_load8' defined in .text section in /usr/lib/llvm-10/lib/clang/10.0.0/lib/linux/libclang_rt.asan-powerpc64le.a(asan_rtl.cpp.o)
/home/travis/build/simdjson/simdjson/include/simdjson/generic/ondemand/value_iterator-inl.h:31:(.text+0x20000e0): relocation truncated to fit: R_PPC64_REL24 (stub) against symbol `__ubsan_handle_type_mismatch_v1_abort' defined in .text section in /usr/lib/llvm-10/lib/clang/10.0.0/lib/linux/libclang_rt.asan-powerpc64le.a(ubsan_handlers.cpp.o)
/home/travis/build/simdjson/simdjson/include/simdjson/generic/ondemand/value_iterator-inl.h:(.text+0x200016c): relocation truncated to fit: R_PPC64_REL24 (stub) against symbol `__ubsan_handle_type_mismatch_v1_abort' defined in .text section in /usr/lib/llvm-10/lib/clang/10.0.0/lib/linux/libclang_rt.asan-powerpc64le.a(ubsan_handlers.cpp.o)
/home/travis/build/simdjson/simdjson/include/simdjson/generic/ondemand/value_iterator-inl.h:470:(.text+0x200020c): relocation truncated to fit: R_PPC64_REL24 (stub) against symbol `__asan_report_load4' defined in .text section in /usr/lib/llvm-10/lib/clang/10.0.0/lib/linux/libclang_rt.asan-powerpc64le.a(asan_rtl.cpp.o)
/home/travis/build/simdjson/simdjson/include/simdjson/generic/ondemand/value_iterator-inl.h:31:(.text+0x2000278): relocation truncated to fit: R_PPC64_REL24 (stub) against symbol `__ubsan_handle_sub_overflow_abort' defined in .text section in /usr/lib/llvm-10/lib/clang/10.0.0/lib/linux/libclang_rt.asan-powerpc64le.a(ubsan_handlers.cpp.o)
/home/travis/build/simdjson/simdjson/include/simdjson/generic/ondemand/value_iterator-inl.h:(.text+0x2000314): relocation truncated to fit: R_PPC64_REL24 (stub) against symbol `__ubsan_handle_type_mismatch_v1_abort' defined in .text section in /usr/lib/llvm-10/lib/clang/10.0.0/lib/linux/libclang_rt.asan-powerpc64le.a(ubsan_handlers.cpp.o)
CMakeFiles/ondemand_object_tests.dir/ondemand_object_tests.cpp.o: In function `auto object_tests::value_object_find_field_unordered()::$_23::operator()<simdjson::simdjson_result<simdjson::fallback::ondemand::document> >(simdjson::simdjson_result<simdjson::fallback::ondemand::document>) const':
/home/travis/build/simdjson/simdjson/include/simdjson/generic/ondemand/json_iterator-inl.h:162:(.text+0x200042c): additional relocation overflows omitted from the output
```

**Comment by lemire** [comment]
@jkeiser The error is interesting...

```
The input was: []�1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
```

**Comment by lemire** [comment]
Here is the original code.

```C++
bool window_too_small_issue1370() {
    std::cout << "Running " << __func__ << std::endl;
    char input[2049];
    input[0] = '[';
    for(size_t i = 1; i < 1024; i++) {
      input[2*i+1]= '1';
      input[2*i+2]= i < 1023 ? ',' : ']';
    }
    auto json = simdjson::padded_string(input,2049);
    // We are going to repeat this test 1000 times so
    // that if there is an issue, we are more likely to
    // trigger it systematically.
    for(size_t trial = 0; trial < 1000; trial++) {
      std::cout << ".";
      std::cout.flush();
      simdjson::dom::parser parser;
      size_t count = 0;
      size_t window_size = 1024; // deliberately too small
      simdjson::dom::document_stream stream;
      ASSERT_SUCCESS( parser.parse_many(json, window_size).get(stream) );
      for (auto doc : stream) {
        if (!doc.error()) {
          std::cerr << "Expected a capacity error but got: " << doc.error() << std::endl;
          std::cerr << "The input was: " << json << std::endl;
          simdjson::dom::element this_document;
          ASSERT_SUCCESS(doc.get(this_document));
          std::cerr << "We parsed the document: " << this_document << std::endl;
          return false;
        }
        count++;
      }
      if(count == 2) {
        std::cerr << "Expected a single document " << std::endl;
        return false;
      }
    }
    std::cout << std::endl;
    return true;
  }
```

I think we have stack corruption error. I'll issue a PR.

**Comment by lemire** [comment]
@jkeiser I did spend quite a bit of time reviewing the related code. I never could find anything that looked like a bug. I can never prove that there is no bug, of course, but the printout suggests that there is a stack corruption issue.  I think we should just reduce stack usage, which is what PR https://github.com/simdjson/simdjson/pull/1515 does.

**Comment by lemire** [comment]
I merged this PR with our main branch to sync things up.

**Comment by lemire** [comment]
@jkeiser I think that the changes I made (avoid using a lot of stack) made the sanitizers happier.

**Comment by lemire** [comment]
We might want to drop this PR. I think that there was a real issue having to do with using sanitizers + debug + large on-stack arrays during the tests. This is fixed.

**Comment by lemire** [comment]
I am going to close this PR. I think that this was fixed in a better way by tracking down the offending code.

**Pull request closed without merging**
