### PR TITLE
new number parsing

### PR DESCRIPTION
**Pull request by lemire**
This PR is an overhaul of the number parsing routine.

1. This trims out a lot of "complicated" code in the number parsing routine. The main idea is to do less work to avoid doing other work, and rather to do all of the work eagerly. Putting it differently, this is a more "branchless" approach. We also reorganize the lookup tables and slightly reduce their size.  The results appear to be somewhat positive, mostly neutral. 
2. We make more aggressive use of the fast path. For example, we handle the production subnormal and round-to-even numbers all from our fast path.
3. We also document the code better, with more comments throughout.
4. We also have the general problem that not all platforms provide a *sane* (or at least, an accurate) strtod, and since we want a locale-independent approach, we have to rely on strtod_l which is non-standard (although well supported). Still, some strtod_l appear not to be precise (just like strtod). Out there, you will find Gay's C code from the early 2000s, but it has not aged well. There are libraries like abseil, but they do not support all the platforms we want to support.  This here follows a proposal by Nigel Tao. It relies on slow but relatively understandable code credited to Ken Thompson. What we care about, in simdjson, is not speed, since this code will almost never be called, but rather that it is correct and easy to debug. So I have adapted and tested Nigel's code to a C++ style that is more "simdjson-like", trimming what was unneeded. The fallback code is non throwing and non allocating. Fixes https://github.com/simdjson/simdjson/issues/1190
5. We also add quite a bit of new testing to make sure that the number parsing is exact.

The performance is roughly unaffected.

Here are some specific performance comparisons (this PR vs the main branch).

## AMD Rome + GNU GCC 9

|filename | ref. speed (GB/s) |candidate speed | difference |
|:--------| ----------:| --------------:| ----------:|
|mesh.json|0.780|0.796|2.1%|
|marine_ik.json|0.809|0.817|1.0%|
|gsoc-2018.json|3.404|3.428|0.7%|
|semanticscholar-corpus.json|2.098|2.101|0.1%|
|numbers.json|0.893|0.894|0.1%|
|github_events.json|2.705|2.706|0.0%|
|update-center.json|1.905|1.903|-0.1%|
|google_maps_api_response.json|2.078|2.074|-0.1%|
|citm_catalog.json|2.583|2.576|-0.3%|
|google_maps_api_compact_response.json|1.080|1.077|-0.3%|
|apache_builds.json|2.451|2.441|-0.4%|
|twitter_timeline.json|1.625|1.615|-0.6%|
|random.json|1.550|1.539|-0.7%|
|instruments.json|2.039|2.024|-0.7%|
|mesh.pretty.json|1.302|1.293|-0.7%|
|twitter_api_response.json|2.455|2.432|-1.0%|
|twitter_api_compact_response.json|1.980|1.960|-1.0%|
|tree-pretty.json|2.154|2.129|-1.2%|
|twitter.json|2.405|2.374|-1.3%|
|twitterescaped.json|1.222|1.206|-1.3%|
|repeat.json|2.417|2.376|-1.7%|
|canada.json|0.785|0.762|-3.0%|

Variation: -3.0% -- 2.1%

|filename | ref. instructions/byte |candidate instructions/byte | difference |
|:--------| ----------:| --------------:| ----------:|
|mesh.pretty.json|9.113|9.262|1.6%|
|numbers.json|12.658|12.858|1.6%|
|canada.json|15.140|15.316|1.2%|
|twitterescaped.json|7.797|7.856|0.8%|
|twitter_timeline.json|6.187|6.207|0.3%|
|marine_ik.json|14.283|14.328|0.3%|
|gsoc-2018.json|2.679|2.684|0.2%|
|mesh.json|15.671|15.693|0.1%|
|citm_catalog.json|4.668|4.672|0.1%|
|semanticscholar-corpus.json|4.499|4.502|0.1%|
|github_events.json|4.199|4.202|0.1%|
|twitter.json|4.578|4.580|0.1%|
|update-center.json|5.316|5.318|0.0%|
|twitter_api_response.json|4.708|4.708|0.0%|
|apache_builds.json|4.809|4.810|0.0%|
|google_maps_api_compact_response.json|10.753|10.753|0.0%|
|google_maps_api_response.json|5.702|5.702|0.0%|
|instruments.json|5.962|5.962|0.0%|
|random.json|7.689|7.689|0.0%|
|repeat.json|5.410|5.410|0.0%|
|tree-pretty.json|5.513|5.512|-0.0%|
|twitter_api_compact_response.json|5.783|5.783|-0.0%|

Variation: -0.0% -- 1.6%

## AMD Rome + LLVM CLANG 9

|filename | ref. speed (GB/s) |candidate speed | difference |
|:--------| ----------:| --------------:| ----------:|
|canada.json|0.643|0.748|16.4%|
|mesh.pretty.json|1.128|1.209|7.2%|
|google_maps_api_compact_response.json|0.978|1.018|4.1%|
|google_maps_api_response.json|1.955|2.029|3.8%|
|apache_builds.json|2.302|2.365|2.8%|
|numbers.json|0.811|0.828|2.1%|
|gsoc-2018.json|3.415|3.460|1.3%|
|update-center.json|1.808|1.831|1.3%|
|twitterescaped.json|1.160|1.171|0.9%|
|github_events.json|2.491|2.513|0.9%|
|repeat.json|2.376|2.397|0.9%|
|semanticscholar-corpus.json|2.057|2.065|0.4%|
|twitter_api_response.json|2.262|2.269|0.3%|
|mesh.json|0.703|0.702|-0.1%|
|random.json|1.456|1.453|-0.2%|
|twitter.json|2.258|2.252|-0.3%|
|marine_ik.json|0.734|0.732|-0.3%|
|citm_catalog.json|2.522|2.497|-1.0%|
|twitter_timeline.json|1.439|1.417|-1.5%|
|twitter_api_compact_response.json|1.815|1.768|-2.6%|
|instruments.json|1.871|1.817|-2.9%|
|tree-pretty.json|1.990|1.912|-3.9%|

Variation: -3.9% -- 16.4%

|filename | ref. instructions/byte |candidate instructions/byte | difference |
|:--------| ----------:| --------------:| ----------:|
|canada.json|15.512|16.146|4.1%|
|mesh.pretty.json|9.657|9.970|3.2%|
|numbers.json|13.442|13.842|3.0%|
|mesh.json|17.100|17.413|1.8%|
|marine_ik.json|15.578|15.758|1.2%|
|twitterescaped.json|7.750|7.720|-0.4%|
|citm_catalog.json|4.650|4.594|-1.2%|
|instruments.json|6.153|6.066|-1.4%|
|repeat.json|5.519|5.436|-1.5%|
|gsoc-2018.json|2.605|2.563|-1.6%|
|tree-pretty.json|5.594|5.473|-2.2%|
|google_maps_api_response.json|5.786|5.631|-2.7%|
|twitter_timeline.json|6.240|6.071|-2.7%|
|twitter.json|4.585|4.458|-2.8%|
|random.json|7.874|7.650|-2.9%|
|twitter_api_response.json|4.720|4.584|-2.9%|
|github_events.json|4.181|4.057|-3.0%|
|twitter_api_compact_response.json|5.862|5.686|-3.0%|
|semanticscholar-corpus.json|4.518|4.382|-3.0%|
|google_maps_api_compact_response.json|11.148|10.804|-3.1%|
|apache_builds.json|4.830|4.669|-3.3%|
|update-center.json|5.349|5.145|-3.8%|

Variation: -3.8% -- 4.1%

## Remark 

This pull request is a new one based on a previous pull requesdt. Indeed, I cannot fix the merge in https://github.com/simdjson/simdjson/pull/1149 as it seems too much for github. (New commits in the branch do not appear in the pull request.) (Something in the GitHub backend failed.)

### CODE REVIEW

**Comment by lemire** [comment]
@jkeiser I think github is entirely busted. Tests do not fire.

**Comment by jkeiser** [comment]
Same with Drone: https://cloud.drone.io/simdjson/simdjson

**Comment by lemire** [comment]
Ah. It woke up. The tests are now running.

**Comment by lemire** [comment]
The perf. check error is very likely a false positive. There are performance variations, depending on the data input, but there is no overall drop in performance.

**Comment by lemire** [comment]
Ok. I just need to go over the performance again. See whether some minor tuning is in order to recoup a 1% loss over some files in some cases.

**Comment by lemire** [comment]
Ok. I am mergin this. It is worth doing for the new tests alone.

The performance effect is quite neutral (this is the best we can hope given that our number parsing routine is already super fast).

**Pull request merged**
