### PR TITLE
Make Markdown problems go away in VS Code markdownlint

### PR DESCRIPTION
**Pull request by jkeiser**
I opened README.md in VS Code and noticed a bunch of lint errors. This fixes them and adds a few to ignore.

I don't really care what the rules are, just that my Problems tab is empty :)

### CODE REVIEW

**Comment by lemire** [comment]
I browsed it and it looks reasonable. Merge at will.

I am concerned however about the fact that you introduce style changes to satisfy a style checker that you alone might be running. A better solution, or a more sustainable one would be to have a CI test on markdown... maybe something like this...

https://github.com/markdownlint/markdownlint

I'd hate to start getting pull requests having to do with styles left and right. If it is a one-off, it is fine, but, naturally, as others will edit the files, they may break your style checker and down we go.

It is almost better to have a draconian style check at pull-request time.

**Comment by lemire** [comment]
@jkeiser I did not mean to block this!!!

**Comment by jkeiser** [comment]
Oh hell, I forgot this. If someone is irritated and wants to update to latest master, go ahead! I will get back when I've got time, which has been increasingly scarce ...

**Comment by jkeiser** [comment]
(This is very low pri.)

**Comment by jkeiser** [comment]
I'mma close for now. It's really not a big deal either way but when I spend more time on simdjson it won't be on this :)

**Pull request closed without merging**
