### PR TITLE
QA infrastructure & missing inlines

### PR DESCRIPTION
**Pull request by ostri**
Self control is good, supervision is even better. (J.V. Stalin ;-) ) 

There should be QA mechanism which enforces that developers follow the good programming practice rules. 
There should be QA run after the compilation process that verify everything is kosher.

At this point of time the following rules are enforced:
-  all performance rules
- all bugprone rules
- all portability rules but simd intristics (we want them)

non private members are allowed for now, since they require major code reshuffle.

**How to do it ?**
`sudo dnf install clang-tools-extra # just the very first time`

Remaining part is already in cmake and it works out of the box at each build.

In order to prove that the mechanism works, I already fixed the missing inlines, as they were reported by the tool.

### CODE REVIEW

**Comment by ostri** [comment]
@lemire @jkeiser 
Since we are in a mode of dropping conversations. 
Are we going to forward with this, or should I drop it? 
All you have to do is to install clang-tidy on the server.

**Comment by jkeiser** [comment]
@ostri I expect we were both asleep the entire time this was open :) I can't reopen it for some reason.

But I think @lemire would agree it's good to validate whatever style things we think are important in CI. We've added a metric TON of validation in CI to this point, and even have a style check (which we are not sure is doing anything anymore, but that's another matter). I think it's fine to reopen as long as we can customize the tool to validate what we all agree is important :)

**Comment by ostri** [comment]
@jkeiser 
Tool is clang-tidy, you have literally 1001 different well documented test condition to check.
You can cherry pick what do you want or need.
For limited part it can even fix certain errors for you.
check <https://clang.llvm.org/extra/clang-tidy/checks/list.html> 
I am also using it within VS in order to lint me in realtime.

I read that you want to have C++11 compatibility. This works currently. I tested it. As you can see in my previous post.  Problematic is only [x,y] = parser ... syntax.

Amalgamate is problematic for normal users, since it pollutes their working space and unnecessary prolongs the compile/development time with user of the library. This was my primary reason for my engagement. @lemire does not want to hear it, but that's the fact of life. 
I understand his position, never the less I left academia 25 year ago. Goals in academia and business are different. Luckily I am in the industry now and I think I know what we need from libraries like simdjson.

I am 95% sure that my closed question which relate with constexpr is valid and that current situation represents logical error.

Next time I visit my kid at the great lakes I invite you for a glass of vine. :-)

Stay healthy. Bye.

**Comment by jkeiser** [comment]
We'll take a look at tidy. I hope you get to go to the great lakes again soon :)

**Comment by lemire** [comment]
It might indeed be nice to integrate clang-tidy.

> I am 95% sure that my closed question which relate with constexpr is valid and that current situation represents logical error.

Computed GOTOs need the addresses at compile-time. Please refer to the documentation in the Performance file. I do not think that there is a logical error but if there is one, you ought to be able to illustrate it with a bug. I invite you to do so. Note that computed GOTOs are not supported under Visual Studio, so we disable them there, at a performance cost.

> Amalgamate is problematic for normal users, since it pollutes their working space and unnecessary prolongs the compile/development time with user of the library. This was my primary reason for my engagement. @lemire does not want to hear it, but that's the fact of life.
I understand his position, never the less I left academia 25 year ago. Goals in academia and business are different. Luckily I am in the industry now and I think I know what we need from libraries like simdjson.

There can be different opinions on the matter... Here is what @pps83 work in another thread... "Those amalgamated versions are perfect imo. Better than any cmake/vs instructions. People who do c++ should be able to add files to their projects :)"

There has been complains, some of them warranted, about how difficult it is to use simdjson. Mostly this had to do with various limitations, and by a so-so API. Thanks in large part to @jkeiser, we have gone a long way toward solving usability issues. There remains a few issues, but they are fewer and fewer.

Amalgamated files have not been an issue for our users. For one thing, they are optional. If you prefer you can use CMake.

Maybe you are concerned about compile time due to the headers?

First, let us say you do not like simdjson because there are too many headers. What is the next choice? The next logical choice is RapidJSON. It is a great library, very fast, very mature, very robust... essentially bug free... ready for production.

How is RapidJSON written? 100% headers. Just headers all the way.

All the other open source JSON libraries are either slower or much less mature, much less robust... And I'd say, most of them are riddled wit bugs... or they are just *much* slower. Yet, many many of them are distributed as sets of headers... only headers... 

Why should that be surprising? The whole C++ standard library is dominated by headers (certainly STL is).

Ok. So how slow is slow. It takes about 1.8 s to compile the demo from scratch, naively. If, instead, you precompile simdjson.cpp into an object file and just compile against simdjson.h, the compilation takes a bit over half a second...

So, adding simdjson to your project adds 0.5 s to the compile time.

Screen Shot 2020-04-24 at 4 59 48 PM


Now you present amalgamation as some academic crazy idea. So you know where I learned about this idea? From sqlite... probably the most widely use database engine in the world. It is distributed in almost exactly the same manner as simdjson (no accident!!!).

And yeah... it takes 18 seconds to build a little executable...

Screen Shot 2020-04-24 at 5 17 53 PM

Grab it there: https://www.sqlite.org/2020/sqlite-amalgamation-3310100.zip

If you read about why they publish it like so, you will learn that it is has to do with performance.  Compiling small units that you glue together is fast, but one big blob of code gives the compiler more choice.

Now, simdjson is distributed just like sqlite (this is in our documentation).

We are not sqlite, and never will be, but we are trying to learn from them. I think we are.

In another thread, I asked how we should work on better releases for simdjson. I am all ears. But please propose practical, actionable solutions. 

And no, we are not going to shy away from using lots of headers because our primary asset is runtime speed. However, if you are want to try and fork simdjson, and do away with the headers. Please do so. And see how well you fare performance wise with old-school compile-link-compile-link...

**Comment by ostri** [comment]
Public open source projects (POSP) are fun, because they gather people:
1. (interaction) who can work together and 
2. (problem) who are attracted by the same challenging problem.
K = problem * interaction. 
POSP with high K attracts more skilled people and are traditionally more successful.

>It might indeed be nice to integrate clang-tidy.

IMHO you should. There are two or three nasty bugs there. They won't be discovered just with pure human code inspection.

> Computed GOTOs need the addresses at compile-time. Please refer to the documentation in the Performance file. I do not think that there is a logical error but if there is one, you ought to be able to illustrate it with a bug. 

I was asking about **constexpr**.  Constexpr has nothing to do there. Please check: <https://stackoverflow.com/questions/45380073/can-you-make-a-computed-goto-in-c>
You do not need constexpr in order to perform computed gotos.

> Now you present amalgamation as some academic crazy idea. So you know where I learned about this idea? From sqlite... probably the most widely use database engine in the world. It is distributed in almost exactly the same manner as simdjson (no accident!!!).

**You are talking about something I never said. I said:**

> Goals in academia and business are different. 

With academia the goal is to get a research grant, to publish the idea, to be invited for lectures and maybe to be famous. Being there, done that.
In industry you tend to do something useful that is paid by the customers. You need to be effective.
Being effective in training, development, installation and maintenance (upgrades and bugs). Nonstandard solutions are generally not perceived as effective.

I've never talked about "crazy ideas". 
Since you mentioned sqlite. 
How do you distribute sqlite in fedora, centos, redhat even though it has amalgamated possibility? 

`sudo dnf install sqlite`

and you get some headers and some binaries. 

In C++ public library header represents public library interface. I **think** that with the pimpl idiom one can move majority of functionality of of the current public simdjson header to implementation part that is hidden from the user without performance problems. Implementation part == hpp + cpp.
This "hidden" implementation part is not recompiled every time I press ctrl S during my application development, which (by accident) includes simdjson header file. This hidden part is also not affected by the application compiler switches.
If public interface is simple, there will be more glue libraries for other languages (e.g. python, java, ...). Check for example zmq.

public interface that is performance critical is simple (just two functions):
```
handler parse(env, <json filename>);
handler parse (env, <json string>);
you can add some additional methods   (not performance critical)
env init_env(<maybe number of threads or workers>);
destroy(env);
auto get_{object, array, string, int, real, bool} (handler, path);
bool is_error(handler)
```

Amalgamation, like I said, has its benefits initially and in niche markets (e.g. embedded systems) and if technology requires (e.g. templates without pimpl idiom).

> In another thread, I asked how we should work on better releases for simdjson. I am all ears. But please propose practical, actionable solutions.

I tried, but you closed the discussion.

In POSP you get expert knowledge for free (i.e. without being paid), but you partially pay that with a bit longer discussion and argumentation. There is no doubt that project owner can always reject suggestions. Only some project owners know how to do it without alienating the source of the suggestion.

**Comment by jkeiser** [comment]
> IMHO you should. There are two or three nasty bugs there. They won't be discovered just with pure human code inspection.

I know I'm asking you to do work and you're feeling a bit alienated, but I'd really appreciate if you could drop some knowledge here :) I don't need you to rerun clang-tidy or anything, but what was the nature of the nasty bugs you noticed? If nothing else it will definitely bump the priority of this for me!

> In industry you tend to do something useful that is paid by the customers. You need to be effective. Being effective in training, development, installation and maintenance (upgrades and bugs).

You weren't responding to me, but note I've been an industry programmer for decades, so the perspective is at least not completely missing here :) @lemire is from academia, but built this with the intent of crossing over and making these ideas industrially useful. It is now seeing some of the growing pains involved with actually doing that, I think :) An awesome problem even if there are bumps on the road.

I'm going to disengage with the amalgamation question for the moment. Sorry about that. I really do understand and share your general intuition regarding interface/implementation separation, and compile times; but working deeply with simdjson has shaken up some of those intuitions a bit and it's not all fully integrated in my head yet :) I don't want to waste your time or mine going in circles in the meantime. Over the next couple of releases (before 1.0) we'll gather more datapoints and will revisit. We already support being compiled as a shared or static library, so switching is entirely possible.

**Comment by lemire** [comment]
> I was asking about constexpr. You do not need constexpr in order to perform computed gotos.

You can do almost everything in C++ without constexpr. I agree.

What constexpr says is "this is a constant available at compile time". In our case, it is a list of addresses which must be available at compile-time.

> Constexpr has nothing to do there. 

Why not?

**Comment by ostri** [comment]
> > IMHO you should. There are two or three nasty bugs there. They won't be discovered just with pure human code inspection.
> 
> I know I'm asking you to do work and you're feeling a bit alienated, but I'd really appreciate if you could drop some knowledge here :) I don't need you to rerun clang-tidy or anything, but what was the nature of the nasty bugs you noticed? If nothing else it will definitely bump the priority of this for me!

integer -> character assignment : compiler and architecture dependant; 
deallocation of unallocated memory block

check again with tidy. Second one has long reproduction chain.

**Comment by ostri** [comment]
> > Constexpr has nothing to do there.
> 
> Why not?

1. computed goto's were used  long before the invention of the constexpr.; so they should work without.
2. constexpr you use if you want to calculate something at compile time. This address assignment is definitely task for either linker or loader.

**Comment by jkeiser** [comment]
> constexpr you use if you want to calculate something at compile time. This address assignment is definitely task for either linker or loader.

Interesting. This is a nuance I don't fully understand: I had assumed that a constexpr *address* is basically a symbolic name, resolved during linking or loading. (Edit: I *think* [this](https://stackoverflow.com/questions/14872240/unique-address-for-constexpr-variable) is saying that you're right.)

How in the world is this even compiling, if that's the case? Can you even resolve a goto address before linking and loading? I think we'd want to switch to static if the above is true, but I can't quite wrap my head around what the compiler actually *does* in this case.

**Comment by lemire** [comment]
See https://stackoverflow.com/questions/13499658/constexpr-initializing-with-pointers

**Comment by lemire** [comment]
As long you point at something that has static storage duration, you are fine.

**Comment by lemire** [comment]
> `sudo dnf install sqlite` and you get some headers and some binaries.

Fedora has packaged the sqlite dependency for your convenience. Have you asked Fedora to package simdjson? You can get simdjson as a source package under Ubuntu and debian. I bet that the same is feasible for Fedora.

**Pull request closed without merging**
