### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by void-mian**
Some typos in comments.

### CODE REVIEW

**Comment by void-mian** [comment]
BTW, Can't I rely on these api? I see it's marked as private.

**Comment by lemire** [comment]
Merging.

**Comment by lemire** [comment]
> Can't I rely on these api? I see it's marked as private.

What is your use case? These functions are meant for internal use. I am not sure how a user of the library would ever need them...

**Comment by void-mian** [comment]
I've created a helper function that returns simdjson_result<int> as the result.  But I ended up using optional<int> instead, because I noticed the error code was unreliable.

**Comment by lemire** [comment]
The error code should not be unreliable. Can you give me an example with code?

**Comment by void-mian** [comment]
Sorry for the misunderstanding. I mean it's unstable, the [doc](https://github.com/simdjson/simdjson/blob/master/doc/basics.md#error-handling) says the error code may be changed. And here a example:
``` cpp
simdjson::simdjson_result<int> count_key_recursively(simdjson::ondemand::value& value, const std::string_view& key) {
    simdjson::error_code ec;
    simdjson::ondemand::object temp;
    if (value.get_object().get(temp)) {
        return ec;
    }
    // iterate the json recursively...
}
```
Since I don't need the error code here, I replace it with std::optional to indicate whether a parser error has occurred.

**Comment by lemire** [comment]
In that code, ec is never initialized, right?

Do you mean to write…


    if(error_code ec = value.get_object().get(temp); ec) {
      return ec;
    }

**Comment by void-mian** [comment]
Yes, forgot to assign the error code.

**Pull request merged**
