### PR TITLE
Initial Apple M1 optimisations

### PR DESCRIPTION
**Pull request by dougallj**
This is roughly a 14% performance improvement on the minify twitter.json benchmark.

These changes are described in more detail at https://github.com/simdjson/simdjson/discussions/1658

### CODE REVIEW

**Comment by lemire** [comment]
That is very clean.

**Comment by lemire** [comment]
@dougallj Please sync our with main branch and run the following...

```
./build/benchmark/bench_parse_call --benchmark_filter=fast_minify
```

I am getting...

```C++
------------------------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------------------
fast_minify_twitter/repeats:10_mean        96573 ns        96563 ns           10 Gigabytes=6.54013G/s docs=10.3563k/s
fast_minify_twitter/repeats:10_median      96236 ns        96236 ns           10 Gigabytes=6.56218G/s docs=10.3912k/s
fast_minify_twitter/repeats:10_stddev        538 ns          522 ns           10 Gigabytes=35.2474M/s docs=55.814/s
fast_minify_twitter/repeats:10_max         97419 ns        97329 ns           10 Gigabytes=6.57419G/s docs=10.4102k/s
fast_minify_gsoc/repeats:10_mean          520787 ns       520773 ns           10 Gigabytes=6.39039G/s docs=1.92029k/s
fast_minify_gsoc/repeats:10_median        521033 ns       521025 ns           10 Gigabytes=6.38709G/s docs=1.91929k/s
fast_minify_gsoc/repeats:10_stddev          3176 ns         3164 ns           10 Gigabytes=38.8814M/s docs=11.6837/s
fast_minify_gsoc/repeats:10_max           525216 ns       525217 ns           10 Gigabytes=6.44858G/s docs=1.93777k/s
```

and with your PR...

```
------------------------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------------------
fast_minify_twitter/repeats:10_mean        86799 ns        86798 ns           10 Gigabytes=7.27575G/s docs=11.5211k/s
fast_minify_twitter/repeats:10_median      86735 ns        86735 ns           10 Gigabytes=7.28095G/s docs=11.5293k/s
fast_minify_twitter/repeats:10_stddev        243 ns          244 ns           10 Gigabytes=20.4158M/s docs=32.3284/s
fast_minify_twitter/repeats:10_max         87198 ns        87197 ns           10 Gigabytes=7.31293G/s docs=11.58k/s
fast_minify_gsoc/repeats:10_mean          496170 ns       496155 ns           10 Gigabytes=6.70763G/s docs=2.01562k/s
fast_minify_gsoc/repeats:10_median        496710 ns       496701 ns           10 Gigabytes=6.69986G/s docs=2.01328k/s
fast_minify_gsoc/repeats:10_stddev          4031 ns         4002 ns           10 Gigabytes=53.7471M/s docs=16.1508/s
fast_minify_gsoc/repeats:10_max           505189 ns       505081 ns           10 Gigabytes=6.76932G/s docs=2.03415k/s
```

**Comment by lemire** [comment]
It seems to cost us a penalty when parsing however...

Current master...

```
❯ ./build/benchmark/bench_parse_call --benchmark_filter=parse_gsoc
Unable to determine clock rate from sysctl: hw.cpufrequency: No such file or directory
2021-07-16 12:00:08
Running ./build/benchmark/bench_parse_call
Run on (8 X 24.121 MHz CPU s)
CPU Caches:
  L1 Data 64 KiB (x8)
  L1 Instruction 128 KiB (x8)
  L2 Unified 4096 KiB (x8)
Load Average: 1.48, 1.71, 1.85
---------------------------------------------------------------------------------------
Benchmark                             Time             CPU   Iterations UserCounters...
---------------------------------------------------------------------------------------
parse_gsoc/repeats:10_mean       829218 ns       828689 ns           10 Gigabytes=4.01596G/s docs=1.20678k/s
parse_gsoc/repeats:10_median     829762 ns       829102 ns           10 Gigabytes=4.0138G/s docs=1.20613k/s
parse_gsoc/repeats:10_stddev       6304 ns         5882 ns           10 Gigabytes=28.5008M/s docs=8.56439/s
parse_gsoc/repeats:10_max        839547 ns       837677 ns           10 Gigabytes=4.05294G/s docs=1.21789k/s
```

With this PR...

```
❯ ./build/benchmark/bench_parse_call --benchmark_filter=parse_gsoc
Unable to determine clock rate from sysctl: hw.cpufrequency: No such file or directory
2021-07-16 12:00:17
Running ./build/benchmark/bench_parse_call
Run on (8 X 24.121 MHz CPU s)
CPU Caches:
  L1 Data 64 KiB (x8)
  L1 Instruction 128 KiB (x8)
  L2 Unified 4096 KiB (x8)
Load Average: 1.63, 1.73, 1.86
---------------------------------------------------------------------------------------
Benchmark                             Time             CPU   Iterations UserCounters...
---------------------------------------------------------------------------------------
parse_gsoc/repeats:10_mean       891586 ns       891543 ns           10 Gigabytes=3.73279G/s docs=1.12169k/s
parse_gsoc/repeats:10_median     891746 ns       891729 ns           10 Gigabytes=3.7319G/s docs=1.12142k/s
parse_gsoc/repeats:10_stddev       5594 ns         5540 ns           10 Gigabytes=23.195M/s docs=6.97/s
parse_gsoc/repeats:10_max        900747 ns       900499 ns           10 Gigabytes=3.76504G/s docs=1.13138k/s
```

**Comment by lemire** [comment]
On Demand performance seems unaffected (`./build/benchmark/bench_ondemand --benchmark_filter=ondemand`) or the effect is small.

**Comment by lemire** [comment]
Right so the regression in parsing performance seems to be due to the introduction of the additional branch.

**Comment by lemire** [comment]
If I only keep "Avoid some expensive popcounts on ARM", which leaves the parsing performance unchanged (since it only touches the minifier), then I no longer find any benefit to this PR...

Current master...

```
------------------------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------------------
fast_minify_twitter/repeats:10_mean        96573 ns        96563 ns           10 Gigabytes=6.54013G/s docs=10.3563k/s
fast_minify_twitter/repeats:10_median      96236 ns        96236 ns           10 Gigabytes=6.56218G/s docs=10.3912k/s
fast_minify_twitter/repeats:10_stddev        538 ns          522 ns           10 Gigabytes=35.2474M/s docs=55.814/s
fast_minify_twitter/repeats:10_max         97419 ns        97329 ns           10 Gigabytes=6.57419G/s docs=10.4102k/s
fast_minify_gsoc/repeats:10_mean          520787 ns       520773 ns           10 Gigabytes=6.39039G/s docs=1.92029k/s
fast_minify_gsoc/repeats:10_median        521033 ns       521025 ns           10 Gigabytes=6.38709G/s docs=1.91929k/s
fast_minify_gsoc/repeats:10_stddev          3176 ns         3164 ns           10 Gigabytes=38.8814M/s docs=11.6837/s
fast_minify_gsoc/repeats:10_max           525216 ns       525217 ns           10 Gigabytes=6.44858G/s docs=1.93777k/s
```

This PR...

```
------------------------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------------------
fast_minify_twitter/repeats:10_mean        96486 ns        96475 ns           10 Gigabytes=6.54606G/s docs=10.3656k/s
fast_minify_twitter/repeats:10_median      96387 ns        96365 ns           10 Gigabytes=6.5534G/s docs=10.3773k/s
fast_minify_twitter/repeats:10_stddev        478 ns          469 ns           10 Gigabytes=31.7527M/s docs=50.2802/s
fast_minify_twitter/repeats:10_max         97166 ns        97144 ns           10 Gigabytes=6.57985G/s docs=10.4192k/s
fast_minify_gsoc/repeats:10_mean          520446 ns       520112 ns           10 Gigabytes=6.39868G/s docs=1.92278k/s
fast_minify_gsoc/repeats:10_median        521538 ns       521383 ns           10 Gigabytes=6.38269G/s docs=1.91797k/s
fast_minify_gsoc/repeats:10_stddev          4491 ns         4242 ns           10 Gigabytes=52.4204M/s docs=15.7521/s
fast_minify_gsoc/repeats:10_max           525791 ns       524863 ns           10 Gigabytes=6.50058G/s docs=1.9534k/s
```

**Comment by dougallj** [comment]
Ah, thanks! Yeah, I see the same thing - I'll use these benchmarks in the future. Unfortunately it looks like it's back to the drawing board for this one.

(I guess we could have the branch in the minifier and no branch in the parser, but I'd prefer to properly understand what's going on before considering anything like that.)

**Comment by lemire** [comment]
@dougallj Can you run my tests and see whether you get the same results?


When comparing this PR with our main branch using GCC 10, the result is more mixed (a gain on twitter and a slim regression over gsoc)....

Main branch (GCC 10):

```
$ ./buildgcc/benchmark/bench_parse_call --benchmark_filter=fast_minify
2021-07-16 16:28:30
Running ./buildgcc/benchmark/bench_parse_call
Run on (4 X 48 MHz CPU s)
Load Average: 0.25, 0.15, 0.06
------------------------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------------------
fast_minify_twitter/repeats:10_mean        97196 ns        97170 ns           10 Gigabytes=6.4993G/s docs=10.2916k/s
fast_minify_twitter/repeats:10_median      97363 ns        97269 ns           10 Gigabytes=6.49248G/s docs=10.2808k/s
fast_minify_twitter/repeats:10_stddev        612 ns          605 ns           10 Gigabytes=40.5411M/s docs=64.1965/s
fast_minify_twitter/repeats:10_max         98088 ns        98088 ns           10 Gigabytes=6.56717G/s docs=10.3991k/s
fast_minify_gsoc/repeats:10_mean          520058 ns       520031 ns           10 Gigabytes=6.39952G/s docs=1.92303k/s
fast_minify_gsoc/repeats:10_median        520295 ns       520258 ns           10 Gigabytes=6.3965G/s docs=1.92212k/s
fast_minify_gsoc/repeats:10_stddev          3283 ns         3282 ns           10 Gigabytes=40.4293M/s docs=12.1488/s
fast_minify_gsoc/repeats:10_max           524633 ns       524635 ns           10 Gigabytes=6.46494G/s docs=1.94269k/s
```

This PR (GCC10):

```
$ ./buildgcc/benchmark/bench_parse_call --benchmark_filter=fast_minify
2021-07-16 16:40:34
Running ./buildgcc/benchmark/bench_parse_call
Run on (4 X 48 MHz CPU s)
Load Average: 0.02, 0.17, 0.11
------------------------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------------------
fast_minify_twitter/repeats:10_mean        89628 ns        89604 ns           10 Gigabytes=7.04808G/s docs=11.1606k/s
fast_minify_twitter/repeats:10_median      89499 ns        89446 ns           10 Gigabytes=7.06031G/s docs=11.18k/s
fast_minify_twitter/repeats:10_stddev        514 ns          524 ns           10 Gigabytes=41.1306M/s docs=65.13/s
fast_minify_twitter/repeats:10_max         90360 ns        90350 ns           10 Gigabytes=7.10762G/s docs=11.2549k/s
fast_minify_gsoc/repeats:10_mean          524215 ns       524204 ns           10 Gigabytes=6.34865G/s docs=1.90774k/s
fast_minify_gsoc/repeats:10_median        524734 ns       524721 ns           10 Gigabytes=6.34211G/s docs=1.90578k/s
fast_minify_gsoc/repeats:10_stddev          3772 ns         3763 ns           10 Gigabytes=45.6221M/s docs=13.7093/s
fast_minify_gsoc/repeats:10_max           529781 ns       529725 ns           10 Gigabytes=6.41321G/s docs=1.92714k/s
```


If I remove the extra branch and keep only the population count change, then I get a net regression...

```
$ ./buildgcc/benchmark/bench_parse_call --benchmark_filter=fast_minify
2021-07-16 16:43:46
Running ./buildgcc/benchmark/bench_parse_call
Run on (4 X 48 MHz CPU s)
Load Average: 0.17, 0.14, 0.10
------------------------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------------------
fast_minify_twitter/repeats:10_mean        99033 ns        99032 ns           10 Gigabytes=6.37725G/s docs=10.0983k/s
fast_minify_twitter/repeats:10_median      99023 ns        99022 ns           10 Gigabytes=6.37753G/s docs=10.0988k/s
fast_minify_twitter/repeats:10_stddev        763 ns          763 ns           10 Gigabytes=49.126M/s docs=77.7907/s
fast_minify_twitter/repeats:10_max        100106 ns       100102 ns           10 Gigabytes=6.45693G/s docs=10.2245k/s
fast_minify_gsoc/repeats:10_mean          538648 ns       538630 ns           10 Gigabytes=6.17861G/s docs=1.85665k/s
fast_minify_gsoc/repeats:10_median        538970 ns       538958 ns           10 Gigabytes=6.17457G/s docs=1.85543k/s
fast_minify_gsoc/repeats:10_stddev          3856 ns         3849 ns           10 Gigabytes=44.1158M/s docs=13.2566/s
fast_minify_gsoc/repeats:10_max           544002 ns       543977 ns           10 Gigabytes=6.23228G/s docs=1.87278k/s
```

**Comment by lemire** [comment]
@dougallj One useful thing is to switch compiler and compare. If you install docker on your M1 machine (use the aarch64 version of docker), then you have easy access to GCC 10... see https://github.com/lemire/docker_programming_station

**Comment by dougallj** [comment]
Main branch (clang):

```
---------------------------------------------------------------------------------------
Benchmark                             Time             CPU   Iterations UserCounters...
---------------------------------------------------------------------------------------
parse_gsoc/repeats:10_mean       814927 ns       814927 ns           10 Gigabytes=4.08359G/s docs=1.2271k/s
parse_gsoc/repeats:10_median     814942 ns       814942 ns           10 Gigabytes=4.08352G/s docs=1.22708k/s
parse_gsoc/repeats:10_stddev        345 ns          345 ns           10 Gigabytes=1.72783M/s docs=0.519206/s
parse_gsoc/repeats:10_max        815450 ns       815450 ns           10 Gigabytes=4.08631G/s docs=1.22792k/s
------------------------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------------------
fast_minify_twitter/repeats:10_mean        95852 ns        95852 ns           10 Gigabytes=6.58842G/s docs=10.4327k/s
fast_minify_twitter/repeats:10_median      95863 ns        95863 ns           10 Gigabytes=6.58766G/s docs=10.4315k/s
fast_minify_twitter/repeats:10_stddev       53.0 ns         53.1 ns           10 Gigabytes=3.64693M/s docs=5.7749/s
fast_minify_twitter/repeats:10_max         95926 ns        95927 ns           10 Gigabytes=6.59366G/s docs=10.441k/s
fast_minify_gsoc/repeats:10_mean          514582 ns       514582 ns           10 Gigabytes=6.46705G/s docs=1.94332k/s
fast_minify_gsoc/repeats:10_median        514612 ns       514612 ns           10 Gigabytes=6.46669G/s docs=1.94321k/s
fast_minify_gsoc/repeats:10_stddev          90.5 ns         90.5 ns           10 Gigabytes=1.13804M/s docs=0.341975/s
fast_minify_gsoc/repeats:10_max           514693 ns       514693 ns           10 Gigabytes=6.46884G/s docs=1.94386k/s
```

This PR (clang):

```
---------------------------------------------------------------------------------------
Benchmark                             Time             CPU   Iterations UserCounters...
---------------------------------------------------------------------------------------
parse_gsoc/repeats:10_mean       885063 ns       885063 ns           10 Gigabytes=3.76G/s docs=1.12986k/s
parse_gsoc/repeats:10_median     885081 ns       885082 ns           10 Gigabytes=3.75991G/s docs=1.12984k/s
parse_gsoc/repeats:10_stddev        693 ns          693 ns           10 Gigabytes=2.94363M/s docs=0.884548/s
parse_gsoc/repeats:10_max        886335 ns       886335 ns           10 Gigabytes=3.76413G/s docs=1.13111k/s
------------------------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------------------
fast_minify_twitter/repeats:10_mean        84833 ns        84833 ns           10 Gigabytes=7.44423G/s docs=11.7879k/s
fast_minify_twitter/repeats:10_median      84827 ns        84827 ns           10 Gigabytes=7.44473G/s docs=11.7887k/s
fast_minify_twitter/repeats:10_stddev       40.3 ns         40.3 ns           10 Gigabytes=3.53931M/s docs=5.60448/s
fast_minify_twitter/repeats:10_max         84910 ns        84910 ns           10 Gigabytes=7.44806G/s docs=11.794k/s
fast_minify_gsoc/repeats:10_mean          504146 ns       504146 ns           10 Gigabytes=6.60097G/s docs=1.98357k/s
fast_minify_gsoc/repeats:10_median        503434 ns       503433 ns           10 Gigabytes=6.61027G/s docs=1.98636k/s
fast_minify_gsoc/repeats:10_stddev          1336 ns         1336 ns           10 Gigabytes=17.4779M/s docs=5.25204/s
fast_minify_gsoc/repeats:10_max           505830 ns       505829 ns           10 Gigabytes=6.62081G/s docs=1.98953k/s
```

I'll set up docker sometime in the next few days - that sounds really useful, thanks!

**Comment by lemire** [comment]
>I'll set up docker sometime in the next few days

It should be as easy as just download the installation package. Using my 'docker_programming_station' could take a few minutes of your time (to figure things out), but all and in all, it is much less complicated than one might expect.

Of course, you probably can also install gcc via brew... but I find that it is always more error-prone. Docker tends to work more consistently.

**Pull request closed without merging**
