### PR TITLE
Remove our dependency on strtod_l

### PR DESCRIPTION
**Pull request by lemire**
We have the general problem that not all platforms provide a *sane* (or at least, an accurate) strtod, and since we want a locale-independent approach, we have to rely on strtod_l which is non-standard (although well supported). Still, some strtod_l appear not to be precise (just like strtod). Out there, you will find Gay's C code from the early 2000s, but it has not aged well. There are libraries like abseil, but they do not support all the platforms we want to support. 

This here follows a proposal by Nigel Tao. It relies on slow but relatively understandable code credited to Ken Thompson. What we care about, in simdjson, is not speed, since this code will almost never be called, but rather that it is correct and easy to debug. So I have adapted and tested Nigel's code to a C++ style that is more "simdjson-like", trimming what was unneeded.

The fallback code is non throwing and non allocating.

Fixes https://github.com/simdjson/simdjson/issues/1190

(Accidentally, this PR got bundled with commit 1ed3ce0, but that's fine.)

### CODE REVIEW

**Comment by lemire** [comment]
I am working on fixing the failures (which appear to expose a real issue).

**Comment by lemire** [comment]
Remaining problems are platform issues. More later.

**Comment by lemire** [comment]
For people reading this, including @jkeiser, the challenge here is that many systems have broken strtod parsers. We used to fallback on the system's strtod, so we were just as broken as they were in the worst case. But we now have an accurate fallback parser. So how do we test it out? We used to test it by comparing our results with strtod... (yes, somewhat circular, but you have to have some ground truth)... but now we can't because on systems where strtod is broken, we get different answers in some cases, and it *appears* like we are failing. But I don't think we are.


What is somewhat frustrating is that there are systems out there that come with a broken strtod. By broken I mean that it does not round to the nearest floating-point number, breaking to nearest even.

**Comment by lemire** [comment]
Ok. I think that this is ready for review!!! 

cc @jkeiser

**Comment by lemire** [comment]
@pauldreik  It seems that the fuzzer fails for some reason?

**Comment by lemire** [comment]
Last commit adds another round of randomized testing.

**Comment by lemire** [comment]
Converting to draft. Latest round of tests seems to reveal an unexpected issue.

**Comment by pauldreik** [comment]
> @pauldreik It seems that the fuzzer fails for some reason?

Wow, something is really going on here. Lot's of slow runs!  What takes 14 minutes on master takes 30 minutes (and counting) Is there a possibility of triggering an infinite loop with some problematic input?

**Comment by lemire** [comment]
@pauldreik There was indeed the possibility of an infinite loop. I closed that off.

It makes sense that it would harm the fuzzer. Thanks for your feedback. I think it clears that up.

**Comment by lemire** [comment]
I am having a hard time making sense of these errors. Working on it.

**Comment by lemire** [comment]
I cannot reproduce any of these errors. There is something I do not understand.

**Comment by lemire** [comment]
Something is really strange. I modified the code so that it would print out what it is doing, it did catch my commit, but nothing gets printed (it does on my machines).

**Comment by lemire** [comment]
Oh. I figured it out. Another PR has been merged into master and the two PR mess each other up.

**Comment by lemire** [comment]
Ok. So my previous PR that allowed us to parse up to 19 digits had a bug in the specific case where no decimal separator is found. So my additional tests were revealing a problem, but this problem was not apparent with the PR alone... you had to sync with master. So it was a little bit of a puzzler.

Good thing is, I found out about a bug in our main branch before it ever made it to a release.

**Comment by lemire** [comment]
@jkeiser  Ok. *Now* it is ready for review. Note that this PR adds a fair amount of new testing which is needed.

**Comment by lemire** [comment]
I'd want to merge this before going back to PR https://github.com/simdjson/simdjson/pull/1149 and simplifying our fast path. Partly this is because the current PR adds useful tests...

**Comment by lemire** [comment]
I think that the fuzzers (which are really good) triggered an interesting issue whereas parsing really crazy floats could take a really long time. Thankfully, it is easy to guard against such attacks. Fixed.

**Comment by lemire** [comment]
@jkeiser  This PR increases testing + it makes more likely that our code will work everywhere by removing a dependency on a non-standard C function + it fixes problems on messed up platforms like cygwin.

**Comment by lemire** [comment]
Under GNU GCC 9, this leads to maybe slightly better performance (AMD Rome processor):


|filename | ref. speed (GB/s) |candidate speed | difference |
|:--------| ----------:| --------------:| ----------:|
|gsoc-2018.json|3.277|3.399|3.7%|
|twitterescaped.json|1.186|1.216|2.6%|
|twitter.json|2.401|2.450|2.0%|
|tree-pretty.json|2.168|2.201|1.5%|
|github_events.json|2.736|2.772|1.3%|
|semanticscholar-corpus.json|2.077|2.104|1.3%|
|marine_ik.json|0.801|0.811|1.3%|
|instruments.json|2.082|2.107|1.2%|
|twitter_api_compact_response.json|1.995|2.019|1.2%|
|canada.json|0.781|0.789|1.1%|
|google_maps_api_compact_response.json|1.088|1.100|1.1%|
|google_maps_api_response.json|2.105|2.123|0.9%|
|twitter_api_response.json|2.483|2.501|0.7%|
|repeat.json|2.356|2.371|0.6%|
|random.json|1.533|1.541|0.5%|
|citm_catalog.json|2.635|2.649|0.5%|
|update-center.json|1.919|1.927|0.4%|
|twitter_timeline.json|1.647|1.653|0.4%|
|mesh.json|0.793|0.795|0.4%|
|apache_builds.json|2.479|2.487|0.4%|
|numbers.json|0.895|0.891|-0.4%|
|mesh.pretty.json|1.315|1.310|-0.5%|

The numbers are somewhat more negative for clang.

In theory, this PR should not change the performance since we are basically replacing code that never gets called (statistically speaking).

**Comment by lemire** [comment]
Moving the slow path its own file to avoid unnecessary inlining.

GCC9


|filename | ref. speed (GB/s) |candidate speed | difference |
|:--------| ----------:| --------------:| ----------:|
|numbers.json|0.890|0.920|3.4%|
|gsoc-2018.json|3.274|3.373|3.0%|
|github_events.json|2.720|2.785|2.4%|
|marine_ik.json|0.808|0.826|2.2%|
|twitter.json|2.388|2.440|2.2%|
|instruments.json|2.081|2.118|1.7%|
|google_maps_api_compact_response.json|1.084|1.102|1.7%|
|tree-pretty.json|2.169|2.204|1.6%|
|canada.json|0.780|0.792|1.5%|
|twitter_timeline.json|1.638|1.660|1.3%|
|apache_builds.json|2.483|2.514|1.3%|
|repeat.json|2.352|2.381|1.3%|
|mesh.json|0.794|0.804|1.2%|
|twitter_api_response.json|2.483|2.512|1.2%|
|citm_catalog.json|2.636|2.666|1.1%|
|twitterescaped.json|1.206|1.217|0.9%|
|update-center.json|1.912|1.929|0.9%|
|twitter_api_compact_response.json|1.995|2.011|0.8%|
|random.json|1.532|1.543|0.7%|
|semanticscholar-corpus.json|2.082|2.094|0.6%|
|mesh.pretty.json|1.318|1.323|0.4%|
|google_maps_api_response.json|2.113|2.117|0.2%|

Variation: 0.2% -- 3.4%

clang


|filename | ref. speed (GB/s) |candidate speed | difference |
|:--------| ----------:| --------------:| ----------:|
|canada.json|0.643|0.664|3.3%|
|google_maps_api_compact_response.json|0.977|1.008|3.2%|
|google_maps_api_response.json|1.955|2.010|2.8%|
|mesh.pretty.json|1.128|1.159|2.7%|
|instruments.json|1.840|1.887|2.6%|
|github_events.json|2.476|2.523|1.9%|
|random.json|1.457|1.469|0.8%|
|marine_ik.json|0.732|0.736|0.5%|
|update-center.json|1.819|1.828|0.5%|
|twitter.json|2.247|2.258|0.5%|
|citm_catalog.json|2.513|2.523|0.4%|
|numbers.json|0.812|0.815|0.3%|
|mesh.json|0.703|0.704|0.1%|
|repeat.json|2.372|2.372|0.0%|
|gsoc-2018.json|3.435|3.434|-0.0%|
|tree-pretty.json|1.983|1.980|-0.2%|
|twitterescaped.json|1.168|1.165|-0.3%|
|semanticscholar-corpus.json|2.063|2.057|-0.3%|
|apache_builds.json|2.307|2.299|-0.4%|
|twitter_api_compact_response.json|1.845|1.832|-0.7%|
|twitter_api_response.json|2.279|2.255|-1.0%|
|twitter_timeline.json|1.461|1.422|-2.7%|

Variation: -2.7% -- 3.3%

This is what I expected. No performance impact (and even some mysterious gains).

**Comment by lemire** [comment]
I rebased against our main branch.

**Comment by lemire** [comment]
Closing this PR in favour of https://github.com/simdjson/simdjson/pull/1149

**Pull request closed without merging**
