### PR TITLE
Let us link to the API on simdjson.org

### PR DESCRIPTION
**Pull request by lemire**

### CODE REVIEW

**Comment by lemire** [comment]
This might be considered as a fix for https://github.com/simdjson/simdjson/issues/588

**Comment by jkeiser** [comment]
> This might be considered as a fix for #588

Agreed :)

**Comment by data-man** [comment]
Rust port now is [simd-lite/simd-json](https://github.com/simd-lite/simd-json).

**Comment by lemire** [comment]
@data-man  Ok. I took into account the change of location.

@Licenser : if your old repo is dead, you probably want to put a sign there.

**Comment by lemire** [comment]
Merged.

**Pull request merged**
