### PR TITLE
Adding a new benchmark for ondemand: distinct user id

### PR DESCRIPTION
**Pull request by lemire**
This benchmark extracts all user ids for a file. The On Demand approach is roughly twice as fast. So we get 4.6GB/s  (On Demand) vs 2.3GB/s for the DOM approach. So definitively worth it if you can have it.

@pauldreik : this is partially to answer your proposal that the release notes include some numbers.

Some extra documentation is needed. To be discussed.

```
cmake -DCMAKE_CXX_FLAGS="-march=haswell" -B newbuild
cmake --build  newbuild --target bench_ondemand
./newbuild/benchmark/bench_ondemand     

-----------------------------------------------------------------------------------
Benchmark                         Time             CPU   Iterations UserCounters...
-----------------------------------------------------------------------------------
DistinctUserID<Dom>          292407 ns       291718 ns         2405 best_bytes_per_sec=2.28583G best_docs_per_sec=3.6196k best_items_per_sec=416.253k bytes=631.515k bytes_per_second=2.01614G/s docs_per_sec=3.42797k/s items=115 items_per_second=394.217k/s [best: throughput=  2.29 GB/s doc_throughput=  3619 docs/s items=       115 avg_time=    292196 ns]
On Demand implementation: haswell
DistinctUserID<OnDemand>     144774 ns       144476 ns         4812 best_bytes_per_sec=4.60677G best_docs_per_sec=7.2948k best_items_per_sec=838.902k bytes=631.515k bytes_per_second=4.07088G/s docs_per_sec=6.92156k/s items=115 items_per_second=795.979k/s [best: throughput=  4.61 GB/s doc_throughput=  7294 docs/s items=       115 avg_time=    144617 ns]
```

### CODE REVIEW

**Comment by lemire** [comment]
@jkeiser 


The documentation had 
```C++
std::string_view screen_name = tweet["user"]["screen_name"];
```

but this won't compile. 

The slight extension...
```C++
std::string_view screen_name = tweet["user"].get_object()["screen_name"];
```
is unsafe.

So we may want to do something like...

```C++
      std::string_view screen_name;
      {
        ondemand::object user        = tweet["user"];
        screen_name                  = user["screen_name"];
      }
```

to make sure it compiles and to ensure safety.

**Comment by jkeiser** [comment]
Doh! Yes, I didn't realize we needed this restriction until after the documentation had already been written, and didn't realize I had used this construct in it!

I think fixing this restriction is an absolute retirement for 0.7, but for now, the code you wrote seems like the right way to do it, even if it is ugly as hell (which is the fault of my api, not you :).

**Comment by lemire** [comment]
I'll do some more work on this (fixing tests and so forth), but we'll go with this code sample for now, as it is approved by @jkeiser.

For people reading this, my expectation is that our documentation will evolve regarding the On Demand API quite a bit in future releases.

**Comment by lemire** [comment]
I'll leave this here in case @jkeiser wants to do some final tweak.

This is read to be merged.

**Comment by lemire** [comment]
Merging.

**Pull request merged**
