### PR TITLE
Can we test with GCC 9

### PR DESCRIPTION
**Pull request by lemire**
Aims to verify https://github.com/simdjson/simdjson/issues/622

See failing tests gcc8-avx  and gcc9-avx

### CODE REVIEW

**Comment by jkeiser** [comment]
@lemire I am beginning to think we can get rid of `simdjson_move_result` entirely if we:

1. Make `operator T()` into `operator T&()`
2. Make `padded_string::padded_string(T&)` and `document::document(T&)` work the same way as the `(T&&)` version

But, I don't understand why we do this:

```c++
  inline padded_string(padded_string &&o) noexcept;
  padded_string(const padded_string &o) noexcept = delete;
```

But don't support this:

```c++
  inline padded_string(padded_string &o) noexcept;
```

Oversight or on purpose?

**Comment by jkeiser** [comment]
Oh, never mind: [this helped me understand it better](https://www.fluentcpp.com/2018/02/06/understanding-lvalues-rvalues-and-their-references/). I do wonder if there's a way to carry the `&&` through though. I'll play with that.

**Comment by jkeiser** [comment]
@lemire I found a fix that lets you remove `std::move()` and actually remove `simdjson_move_result` altogether at #628 .

Note that the strict -Werror tests are failing because we use [[deprecated]] classes in some of our tests. We should do whatever voodoo is necessary to make those specific tests not be warnings, so that we can tell if we're using deprecated stuff anywhere we weren't expecting to.

**Comment by jkeiser** [comment]
@lemire your fix is alongside the same lines; I'd be happy to build on top of your patch with the removal of simdjson_move_result. I just added a few extra &&'s on the get and take side.

**Comment by lemire** [comment]
Ok. I am killing this PR.

**Pull request closed without merging**
