### PR TITLE
Updating the performance numbers.

### PR DESCRIPTION
**Pull request by lemire**
New performance numbers (in preparation for the next release)

gbps

### CODE REVIEW

**Comment by lemire** [comment]
growing

**Comment by lemire** [comment]
@jkeiser This is ready for review.

**Comment by lemire** [comment]
In my mind, this would fix https://github.com/simdjson/simdjson/issues/591

**Comment by jkeiser** [comment]
Holy crap that steady line is goddamn gorgeous.

**Comment by jkeiser** [comment]
So we've gotten 15% faster since 0.2 on Skylake, sounds like.

**Comment by lemire** [comment]
@jkeiser  If you follow the links, you will find the raw data as well as the scripts, via Docker containers, to reproduce the results. Of course, the results vary depending on the hardware but, hopefully, docker takes care of most of the software variability.

We did get much faster and combined with accurate number parsing... well...

**Pull request merged**
