### PR TITLE
This should fix an issue we have with unclosed strings with document_stream

### PR DESCRIPTION
**Pull request by lemire**
We have an issue that, in some rare cases, with adversarial inputs, our code will misbehave.

credit: @pauldreik  for identifying the issue and helping me reproduce it.

### CODE REVIEW

**Comment by lemire** [comment]
Harder to get right than it seems.

**Comment by pauldreik** [comment]
> Harder to get right than it seems.

Sounds like json parsing in general :-)

**Comment by pauldreik** [comment]
With the changes in this commit, the ndjson fuzzer has now survived more than five minutes without crashing. Looks good!

**Comment by lemire** [comment]
Merging.

**Pull request merged**
