### PR TITLE
Trying to diagnose a potential on-demand bug

### PR DESCRIPTION
**Pull request by lemire**
If you just created an array, you would think that `iter.is_at_container_start` would return true no matter what.

### CODE REVIEW

**Comment by lemire** [comment]
@jkeiser It fails some of the time with 

```
32/72 Test #35: ondemand_array_tests .................................***Failed    0.02 sec
builtin_implementation -- fallback
------------------------------------------------------------

Running tests.
> Running iterate_sub_array_count ...
> Running iterate_complex_array_count ...
FAIL: firstmyarray.count_elements().get(count) returned error: Objects and arrays can only be iterated when they are first encountered. (25)
FAILED.
```

The relevant code is this...
```C++

  bool iterate_complex_array_count() {
    TEST_START();
    ondemand::parser parser;
    auto cars_json = R"( { "zero":[], "test":[ { "val1":1, "val2":2 }, { "val1":1, "val2":2 } ] }   )"_padded;
    ondemand::document doc;
    ASSERT_SUCCESS(parser.iterate(cars_json).get(doc));
    ondemand::array firstmyarray;
    ASSERT_SUCCESS(doc.find_field("zero").get_array().get(firstmyarray));
    size_t count{0};
    ASSERT_SUCCESS(firstmyarray.count_elements().get(count));
```

Critically, the array is empty.

It fails within `count_elements()` at...

```C++
simdjson_really_inline simdjson_result<size_t> array::count_elements() & noexcept {
#ifdef SIMDJSON_DEVELOPMENT_CHECKS
  // array::begin() makes the same check.
  if(!iter.is_at_container_start()) { return OUT_OF_ORDER_ITERATION; }
#endif
```

I find this odd because `array::begin()` does...

```C++
simdjson_really_inline simdjson_result<array_iterator> array::begin() noexcept {
#ifdef SIMDJSON_DEVELOPMENT_CHECKS
  if (!iter.is_at_iterator_start()) { return OUT_OF_ORDER_ITERATION; }
#endif
  return array_iterator(iter);
}
```

So if `iter.is_at_iterator_start()` is false given an empty array, then that would imply that we can't iterate over an empty array?

**Comment by lemire** [comment]
Note that it only fails in some test because this test is only triggered in debug mode. Most of our CI is in release mode.

**Comment by lemire** [comment]
We have that...

```C++
simdjson_really_inline bool value_iterator::is_at_iterator_start() const noexcept {
  // We can legitimately be either at the first value ([1]), or after the array if it's empty ([]).
  auto delta = _json_iter->token.index - _start_position;
  return delta == 1 || delta == 2;
}
```

**Comment by jkeiser** [comment]
Some design info: is_open() will return false immediately on empty array/hash, because we check for that case immediately (since that's the only time `}` / `]` can legally appear instead of a key or value--it can't happen between ).

**Comment by jkeiser** [comment]
From the looks of that, is_at_iterator_start() is *trying* to accomodate the fact that after json_iterator.start_array(), the iterator could either be:

1. Open, and at the first value (delta=1):
   ```
   [ 123 ]
     ^
   0 1   2
   ```
2. Closed, and after the empty array/hash:
   ```
   [ ] ...
       ^
   0 1 2
   ```

**Comment by lemire** [comment]
@jkeiser 

> From the looks of that, is_at_iterator_start() is trying to accomodate the fact that after json_iterator.start_array(), the iterator could either be:

Yes. So it should return true always when I have create a new array, whether it is empty or not.

**Comment by lemire** [comment]
I do not understand.

**Comment by jkeiser** [comment]
So, here is what I think the count_elements method should look like (i.e. there's no reason I know of that it *shouldn't* work):

```c++
simdjson_really_inline simdjson_result<size_t> array::count_elements() & noexcept {
  size_t count{0};
  // Important: we do not consume any of the values.
  for(simdjson_unused auto v : *this) { count++; }
  // The above loop will always succeed, but we want to report errors.
  if(iter.error()) { return iter.error(); }
  // We need to move back at the start because we expect users to iterate through
  // the array after counting the number of elements.
  // enter_at_container_start is safe here because we know that we do not have an empty array.
  iter.enter_at_container_start(); // sets the depth to indicate that we are inside the container and accesses the first element
  return count;
}
```

I'm getting something *very* weird when I see this, however (with `-DSIMDJSON_VERBOSE_LOGGING=ON`, which I recommend turning on anytime you're having an issue):

```
| Event                | Buffer                         | Next       | Depth | Detail |
|----------------------|--------------------------------|------------|-------|--------|
  ...
|     +array           | [], "test":[ { "val1":1, "val2 | ], "test": |     2 |  |
|     empty array      | [], "test":[ { "val1":1, "val2 | ], "test": |     2 |  |
|       -skip          | ], "test":[ { "val1":1, "val2" | , "test":[ |     3 |  |
|       skip           | "test":[ { "val1":1, "val2":2  | :[ { "val1 |     3 |  |
|     ERROR: Missing comma between array elements | :[ { "val1":1, "val2":2 }, { " | [ { "val1" |     2 |  |
FAIL: new_count returned 3 (expected 0)
FAILED.
```

From the `-skip` line, it looks to me like the empty array logic--for whatever reason--is putting us at the `]` and setting depth to 3 (which is what a *non-*empty array should do). That, or we have some other code running in between when we start the array and when we call count_elements?

I don't think even #1636 is simpler than this. I suspect the reason you (and I) are having difficulty understanding it is that we have a bug somewhere--we're breaking our invariants. The complexity is because we're trying to work around it. Even if we fix count_elements, someone should be able to run the for loop you see there against the array, and have it work!

**Comment by jkeiser** [comment]
Oh! This is because I didn't short circuit. `enter_at_container_start()` requires that.

**Comment by jkeiser** [comment]
@lemire the test passes when I fix that:

```c++
  size_t count{0};
  // Important: we do not consume any of the values.
  for(simdjson_unused auto v : *this) { count++; }
  // The above loop will always succeed, but we want to report errors.
  if(iter.error()) { return iter.error(); }
  // We need to move back at the start because we expect users to iterate through
  // the array after counting the number of elements.
  if (count > 0) {
    // enter_at_container_start is safe here because we know that we do not have an empty array.
    iter.enter_at_container_start(); // sets the depth to indicate that we are inside the container and accesses the first element
  }
```

**Comment by jkeiser** [comment]
Going to push that fix here to see what happens.

**Comment by jkeiser** [comment]
Reflecting a tiny bit, The complexity here may just be that our method of resetting the iterator requires you to know the current iteration state before you can call it. Replacing `enter_at_container_start()` with a `reset()` (protected so it's only used by us) which can be called on any valid array might reduce confusion a bit. It could do so like this, I think:

```c++
iter.set_position(start_position);
iter.started_array();
```

**Comment by jkeiser** [comment]
If we did that, the `count_elements()` method would look like this:

```c++
  size_t count{0};
  // Important: we do not consume any of the values.
  for(simdjson_unused auto v : *this) { count++; }
  // The above loop will always succeed, but we want to report errors.
  if(iter.error()) { return iter.error(); }
  // We need to move back at the start because we expect users to iterate through
  // the array after counting the number of elements.
  reset();
  return count;
}
```

**Comment by jkeiser** [comment]
Even more idiomatically:

```c++
simdjson_really_inline simdjson_result<size_t> array::count_elements() & noexcept {
  size_t count{0};
  for(auto v : *this) { SIMDJSON_TRY(v.error()); count++; }
  reset();
  return count;
}
```

**Comment by lemire** [comment]
@jkeiser Having safe `reset()` methods for both arrays and objects would greatly improve usability (for us).

> (with -DSIMDJSON_VERBOSE_LOGGING=ON, which I recommend turning on anytime you're having an issue):

I honestly do not understand the logging. It looks really neat and you put a lot of work into it, and I am sure it helps you a great deal... but I can't figure it out.

That's why I created the `to_string()` methods so that I can study the behaviour of the code. 

What I do is that I insert lines where I do something like `std::cout << iter.to_string() ...` at strategic locations, and I end up figuring this out that way.

This here is a good example...

```
|     +array           | [], "test":[ { "val1":1, "val2 | ], "test": |     2 |  |
|     empty array      | [], "test":[ { "val1":1, "val2 | ], "test": |     2 |  |
|       -skip          | ], "test":[ { "val1":1, "val2" | , "test":[ |     3 |  |
|       skip           | "test":[ { "val1":1, "val2":2  | :[ { "val1 |     3 |  |
```

I don't understand this log. It seems that `-skip` moved us from `]` to `"test` in one go. What is `-skip` vs `skip`?

I have no mental map as to how each line maps to the code, or to the state of the json_iterator or of the state of the value_iterator.

The way my brain works, I'd like to see what happens with each new structural element. What is the current depth and so forth. If an array or an object is created, what are its properties at construction time, and where does it get destroyed.


(Note: I am not complaining or criticizing, I am just explaining how I work with this code.)

**Comment by lemire** [comment]
@jkeiser 

Ok, but back at the core of the issue... If I just created an array, then `is_at_container_start()` might be true or false depending on whether the array is empty or not, correct?

**Comment by lemire** [comment]
@jkeiser  If we agree `is_at_container_start()` will be false when I just created an empty array, then what is the logic in that code doing...

```
simdjson_really_inline bool value_iterator::is_at_iterator_start() const noexcept {
  // We can legitimately be either at the first value ([1]), or after the array if it's empty ([]).
  auto delta = _json_iter->token.index - _start_position;
  return delta == 1 || delta == 2;
}
```

That is... what is the state we are supposed to be in when we just created an array?

**Comment by jkeiser** [comment]
The main thing the logging does is tell you the depth and position of the iterator at each and every user-visible step (since those two things are the only things that actually affect iteration). +array says "this is where we were when we discovered the start array," -array says "this is where we were when we ended the array, "skip" says "this is a structural or value I'm skipping," and "+/-skip" says "this is a start/end array or object we're skipping."

**Comment by lemire** [comment]
@jkeiser  Ok. I was confusing is_at_container_start and is_at_iterator_start.

Ah. This is one mystery.

**Comment by lemire** [comment]
> The main thing the logging does is tell you the depth and position of the iterator at each and every user-visible step (since those two things are the only things that actually affect iteration). +array says "this is where we were when we discovered the start array," -array says "this is where we were when we ended the array, "skip" says "this is a structural or value I'm skipping," and "+/-skip" says "this is a start/end array or object we're skipping."

That's helpful.

**Comment by jkeiser** [comment]
Correct. It looks like `is_at_container_start()` will only be true if you are right after the `[` or `{`. I imagine it's used internally for `started_array`/`started_object`, which is where we check for the empty array/object. It shouldn't be useful anywhere else: the user should *never* be in this state for an empty array/object.

(started_array/object are called by start_array/object and mainly exist because sometimes you already *know* it's an array/object and have advanced past the opening `[`/`{`.)

The is_at_ and assert_at_ methods are poorly documented and likely have consistency and naming issues. I added them as I went and focused solely on maintaining internal invariants for the internal code rather than making them a beautiful interface.

**Comment by jkeiser** [comment]
I'd really like some feedback on how to make the logging make sense; it *ought* to convey everything you need to know, and is trying to do so visually (instead of writing out the position it shows you where you are in the buffer, for example). I'd like it to be useful to people who aren't me, because I think it is in fact useful :)

**Comment by jkeiser** [comment]
I really really need to write up the internals here. I think after the padding removal is complete, that'll be a good next thing. Though I'm sorry you had to slog through this, I'm also sort of glad, because it can give us an idea of what stuff is hard to understand and needs either cleanup or explanation (leaning heavily towards "cleanup" :).

**Comment by lemire** [comment]
@jkeiser So we are absolutely clear, I am not criticizing you.

**Comment by jkeiser** [comment]
I don't feel you are :) I also can't feel super bad; since it seems to be a new kind of algorithm, I constructed it by "feeling out" the design space and frequently refactoring. While I try to keep things cohesive when I do that, it can definitely get lost.

But I still empathize when people have trouble wading through it!

**Comment by lemire** [comment]
>  I also can't feel super bad

Well. Also, it seems that the whole confusion is my fault. I made a few careless mistakes.

**Comment by lemire** [comment]
I am trying to improve the documentation at https://github.com/simdjson/simdjson/pull/1638

**Comment by lemire** [comment]
@jkeiser Ok. I think we can actually merge this PR with your changes. I like it better.


I don't think I ever spent that much effort on so few lines of code for so little functionality.

At least, the `find_unordered_field` provides mission-critical functionality.

**Comment by lemire** [comment]
@jkeiser So `reset` would be like enter_at_container_start() but it would then check whether we have `}`or `]`and if so, move again. Maybe something like this...

```
/**
 * Restart an array iteration.
 * @returns Whether the array has any elements (returns false for empty).
  */
  simdjson_warn_unused simdjson_really_inline bool 
reset_array() {
  move_at_start(); // iter.set_position(start_position); may not be sufficient here due to the need to adjust the depth
  return iter.started_array();
}
```

**Comment by lemire** [comment]
Presumably, we could code a `reset_object()` method like so...

```C++
/**
 * Restart an object iteration.
 * @returns Whether the object has any fields (returns false for empty).
 */
simdjson_warn_unused simdjson_really_inline bool reset_object() {
  move_at_start(); // iter.set_position(start_position); may not be sufficient here due to the need to adjust the depth
  return iter.started_object();
}
```

**Comment by lemire** [comment]
I'll try to do resets in a distinct PR. See if it works.

**Comment by jkeiser** [comment]
move_to_container_start() probably fits the motif, but yeah :) container_start is different from start_position, and maybe we should call start_position something else (value_position?) so that we don't have the word start meaning so many different things. I think that's likely what caused your confusion.

Maybe container_start / start_container could be inside_container or something, to reduce the number of "start"s as well.

And yes, reset_object() makes sense there. We could probably use that in find_field.

**Comment by jkeiser** [comment]
Note that *I* didn't notice the difference between container_start and iterator_start either, even though I was staring at it! :)

**Comment by jkeiser** [comment]
Maybe instead of having a move_to_first_container_position or move_to_container_start, we should just not have that concept anywhere. Literally inline those methods to their callers. Then there's nothing to confuse anymore :)

**Comment by jkeiser** [comment]
That could also apply to iterator_start, actually (though maybe that's used in more places?). The best way not to get confused between a bunch of concepts is not to write them out as concepts in the first place (and thus not take up concept space in your head).

**Comment by lemire** [comment]
@jkeiser It is a good process when working on something new to gradually reduce the surface area. I have just created a couple of PRs that go in this direction.

**Comment by lemire** [comment]
Closing.

**Pull request closed without merging**
