### PR TITLE
Do not inline file IO functions

### PR DESCRIPTION
**Pull request by pps83**

### CODE REVIEW

**Comment by lemire** [comment]
Can you provide a rationale for the proposed change? I am discouraging changes that do not bring identifiable benefits.

Shouldn't `simdjson_impl.cpp` be `simdjson_io.cpp`?

**Comment by jkeiser** [comment]
Note that inline [doesn't mean what it sounds like](https://stackoverflow.com/questions/22102919/static-vs-inline-for-functions-implemented-in-header-files). In particular, it means "hey compiler, even if other people include simdjson.h, I want you to use *this definition* of the function and not worry about whether someone else might redefine it." It just happens that if you say this, the compiler is *allowed* to inline the code.

The crucial thing here is that the compiler doesn't have to inline it (and for larger functions it *won't*):

> The compiler will then either inline calls to the function, or merge together the function definitions from different TU's (so that the resulting function exists once in the executable).

Here's the rubrick I've been using for "inline" vs. non-inline:

* simdjson.h: User facing code. This is where all client code goes. Code that may be called by the client, and has only one implementation, belongs here.
* simdjson.cpp: Implementations. Runtime-selected implementation code (and any code that will only be called by runtime-selected code) belongs here.

I'm not married to my interpretation.

**Comment by lemire** [comment]
@jkeiser


> Here's the rubrick I've been using for "inline" vs. non-inline:

This is explicite in https://github.com/simdjson/simdjson/blob/master/HACKING.md

**Comment by pps83** [comment]
> Note that inline [doesn't mean what it sounds like](https://stackoverflow.com/questions/22102919/static-vs-inline-for-functions-implemented-in-header-files). In particular, it means "hey compiler, even if other people include simdjson.h, I want you to use _this definition_ of the function and not worry about whether someone else might redefine it." It just happens that if you say this, the compiler is _allowed_ to inline the code.

It's unlikely to be inlined and why would anybody want that, function call will be absolutely negligible compared to any sort of file io anyways (even if it's temporary file from fs cache). 
My main reason to move it to cpp is to add eventually `_CRT_SECURE_NO_WARNINGS` to that cpp file to prevent warnings/errors from fopen. Currently, you'd need to write messy code or define `_CRT_SECURE_NO_WARNINGS` in simdjson.h, which will affect users of you simdjson: if users remove "simdjson.h" include from some of their files they may be "surprised" with those warnings/errors. The other reason: I wouldn't want to add definition of that function to each .cpp file that includes simdjson.h: if it's not a header-only lib, all such functions should be moved to cpp imo.

> someone else might redefine it

Sounds like this would violate ODR. If somebody redefines inline version you may get that other version. Compiler is free to choose any of these, off course. What you describe sounds line you are confusing inline vs static (not class-static, but regular static function). Try to add some ifdefs in any function in a header, and then include it from different src files that use the header (and define different defines effectively altering functions body in different translation units): one will be taken by the linker and you don't know which version gets "lucky".

I don't view `inline` keyword that it's related to any type of inlining. It's more like a linker flag to resolve duplicates: without `inline` keyword you will get linker errors because of duplicates, with `inline` keyword linker assumes that all these duplicates are the same and chooses one of them at will.

**Comment by pps83** [comment]
> Shouldn't `simdjson_impl.cpp` be `simdjson_io.cpp`?

Initially, I simply added definition directly in simdjson.cpp. implementation.cpp also clearly is used for something else, didn't want to add it there as well.
 If you guys think that this change is ok, I'll rename to any suitable name. I named it `simdjson_impl.cpp` so other functions that shouldn't be in .h could be moved to simdjson_impl.cpp eventually.

**Comment by jkeiser** [comment]
> My main reason to move it to cpp is to add eventually _CRT_SECURE_NO_WARNINGS to that cpp file to prevent warnings/errors from fopen.

Is there a reason we can't do it just for the part of the file where it matters? We do that in a few other places. Plus, fopen_s might actually solve the problem, I am hopeful anyway :)

I had typed up a whole analysis here: there are some reasons we might want to non-inline some functions, but there's a tangled web of concerns there affecting performance and our own developer time, and I'd rather we not change the current, fairly clear rule until we have a big reason :)

**Comment by pps83** [comment]
> > My main reason to move it to cpp is to add eventually _CRT_SECURE_NO_WARNINGS to that cpp file to prevent warnings/errors from fopen.
> 
> Is there a reason we can't do it just for the part of the file where it matters? We do that in a few other places. Plus, fopen_s might actually solve the problem, I am hopeful anyway :)

You cannot add it to your project and/or header. It's not going to work, I hope it's clear for you why it won't work. (I left a comment in other thread about it as well)

> I had typed up a whole analysis here: there are some reasons we might want to non-inline some functions, but there's a tangled web of concerns there affecting performance and our own developer time, and I'd rather we not change the current, fairly clear rule until we have a big reason :)

well, regarding developer time: I proposed a fix, made an effort to integrate it upstream, you decided to start working on this and other problems that I raised in this and other PRs. End result: I wasted my time, and now you are also wasting your time.

If the library isn't header-only, all things that aren't perf critical should be in .cpp. Reading files, is clearly such example function that should not be inlined function in headers. Many large companies/projects completely ban use of boost for that reason: too much code in headers, huge compile times, huge object files, huge linking times.

**Comment by jkeiser** [comment]
Could've sworn I had a reply here earlier, sorry about that.

> If the library isn't header-only, all things that aren't perf critical should be in .cpp. 

simdjson *aspires* to be header-only, but cannot achieve that at the moment because the runtime architecture selection (at least at present) requires actual function pointers. I guess I'd call it a header-mostly library at the moment. You can absolutely consume it as a library as well, it's just designed around dropping the files into your project at the moment.

More importantly, "perf critical" is in the eye of the beholder. What you're hearing from me is not "man I just want all these functions in the header," not at all: what you are hearing is "I am super worried I'm going to spend a TON of time agonizing over what things are perf critical and what aren't because I've done that in the past, and I want to spend that time making the library itself performant!" I'm aware it's an emotional concern, but it's a concern of a developer on the project :) Hence the desire for a clear rubric.

I could probably live with "things with system calls should go into .cpp" as a rubric.

> Reading files, is clearly such example function that should not be inlined function in headers. Many large companies/projects completely ban use of boost for that reason: too much code in headers, huge compile times, huge object files, huge linking times.

Yeah, a compile time measurement would not be amiss here. It's an important metric to optimize. I really don't want to dismiss that, I'm arguing to try to find the point of convergence/difference, not just to argue :)

**Comment by lemire** [comment]
>  I proposed a fix, made an effort to integrate it upstream, you decided to start working on this and other problems that I raised in this and other PRs. End result: I wasted my time, and now you are also wasting your time.

That's a mischaracterization of what happened.

Quite aside from the details of this one case, we frequently try various things, and only merge a few. Please see the collection of dropped PRs. You will find lots of PRs by @lemire  and @jkeiser  that have never been merged. We consider many things, we compare, and we discuss.

**Comment by lemire** [comment]
@pps83 

And, as far as I am concerned, I have not even seen a suggestion that this PR be dropped.

**Comment by jkeiser** [comment]
We've got the CRT_SECURE warning beaten down; I don't think we have a new rubric yet for what to inline and what not (even if these seem very likely to fall in the "not" side of that line). I suggest we close as "doesn't happen to fit the current rubric," discuss how we organize our headers and inlining separately, and then globally move everything that falls outside the "inline" category at that time.

**Comment by jkeiser** [comment]
Doing that, given no objection here. Please respond or reopen if the previous comment just missed you.

**Pull request closed without merging**
