### PR TITLE
Fix clang warning -Wused-but-marked-unused.

### PR DESCRIPTION
**Pull request by vitlibar**
When compiling with "-Weverything" Clang is showing a lot of warnings like this

```
warning: 'parse' was marked unused but was used
      [-Wused-but-marked-unused]
```

For example, I get such warnings in this simple program:

```
#include <string>
#include <iostream>
#include <simdjson.h>

#pragma clang diagnostic warning "-Weverything"
#pragma clang diagnostic ignored "-Wc++98-compat"

int main()
{
    std::string_view json = "23.5";
    simdjson::dom::parser parser;
    auto doc = parser.parse(json.data(), json.size());
    std::cout << "json parsed" << (doc.error() ? " with error" : "") << std::endl;
    return 0;
}
```

It's because of these definition:

```
#define really_inline inline __attribute__((always_inline, unused))
#define never_inline inline __attribute__((noinline, unused))
```

Clang treats the `unused` attribute as though the function should never be used and warns us if it's actually used.
It seems we can fix that by just dropping the attribute.

### CODE REVIEW

**Comment by lemire** [comment]
@vitlibar Your PR fails some of our tests.

The "unused" warning means that the function may be, in some compilation units, unused. In C++17, it becomes available as the standard attribute [[maybe_unused]]. See https://en.cppreference.com/w/cpp/language/attributes/maybe_unused We use this attribute to *silence* warnings.

**Comment by vitlibar** [comment]
> The "unused" warning means that the function may be, in some compilation units, unused.
In Clang it doesn't seem to work that way.

**Comment by vitlibar** [comment]
> @vitlibar Your PR fails some of our tests.

It looks like the tests failed only where `really_inline` was used with `static`.
I can try to replace `really_inline static` with either `static` or `really_inline`, if you don't mind.

**Comment by vitlibar** [comment]
> The "unused" warning means that the function may be, in some compilation units, unused. In C++17, it becomes available as the standard attribute [[maybe_unused]]. See https://en.cppreference.com/w/cpp/language/attributes/maybe_unused We use this attribute to _silence_ warnings.

In Clang `[[maybe_unused]]` works perfectly (exactly as the documentation says), but `__attribute((unused))` shows that warning if the function is actually used. I don't know why it works that way.

**Comment by jkeiser** [comment]
> > @vitlibar Your PR fails some of our tests.
> 
> It looks like the tests failed only where `really_inline` was used with `static`.
> I can try to replace `really_inline static` with either `static` or `really_inline`, if you don't mind.

static and inline are separate things though--wouldn't the removal of one or the other change the meaning?

**Comment by lemire** [comment]
Here is the LLVM relevant documentation:

> When passing the -Wunused flag to Clang, entities that are unused by the program may be diagnosed. The `[[maybe_unused]]` (or `__attribute__((unused)))` attribute can be used to silence such diagnostics when the entity cannot be removed. For instance, a local variable may exist solely for use in an assert() statement, which makes the local variable unused when NDEBUG is defined.

https://clang.llvm.org/docs/AttributeReference.html

**Comment by lemire** [comment]
> static and inline are separate things though--wouldn't the removal of one or the other change the meaning?


I think that `static` allows the compiler to know that the function is unused. 

Evidently, the linker does not participate in this static analysis game, otherwise you'd have lots of fun, with the linker complaining left and right that functions are unused.

Removing these few static qualifiers is probably not going to change anything to the library, so it is fine.

**Comment by vitlibar** [comment]
> Removing these few static qualifiers is probably not going to change anything to the library, so it is fine.

Done. I removed such static qualifiers (there were only two of them) and it fixed the build.

**Comment by lemire** [comment]
These changes look fine. I am merging.

**Pull request merged**
