### PR TITLE
Fixing UTF-8 validation under PPC64

### PR DESCRIPTION
**Pull request by lemire**
So this is the second UTF-8 test that the unicode fuzzer says is failing us on POWER hardware.

### CODE REVIEW

**Comment by lemire** [comment]
@pauldreik @jkeiser I think that the UTF-8 fuzzer under POWER is busted. I cannot reproduce the errors that it is giving me.

That is, I keep taking the failing tests and plugging them back into our tests and they work fine.

Note that I have direct access to a POWER9 system and I can run the tests there... and everything appears fine.

**Comment by jkeiser** [comment]
Both tests have a lot of NULLs (\00) ... is it possible that it's recognizing them as null terminators on POWER?

**Comment by jkeiser** [comment]
Hmm, no, I don't think it's that. The previous failing test would still have 0x80 at the end, which is invalid. One thing both have in common is that the bad UTF-8 is `\x80\x00\x00\x00`.

**Comment by lemire** [comment]
@jkeiser The thing is, the test succeeds which means that the POWER processor correctly flags the string as invalid.

That is, our problem only occurs under the fuzzer.

**Comment by lemire** [comment]
Ok. So the buzzer found a new one...

Am I just going to add it again to our test... Something is deeply wrong here.

```
ppc64 returns true
6617
fallback returns false
6618
Offending input: "\x20\x0b\x00\x00\x00\x64\x3a\x64\x3a\x64\x3a\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x5b\x30\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
```

**Comment by lemire** [comment]
It is not like Paul's fuzzer code is rocket science. Maybe it is somehow wrong, but I don't see it.

**Comment by lemire** [comment]
I was making a mistake of my own. Last commit should fix it and hopefully reveal the issue.

**Comment by lemire** [comment]
Ah. Ah.

Looks like the fuzzer is not busted after all. There is an issue but it does not seem POWER related?

**Comment by lemire** [comment]
Ah. The problem has to do with the presence of null characters which throws off the tests we do. Let me fix that.

**Comment by lemire** [comment]
So I have replaced the nulls with 1s.

**Comment by lemire** [comment]
OK. I finally have a reproducible test case that fails under POWER.

**Comment by lemire** [comment]
OK. I figured it out. There is a bug specific to POWER.

**Comment by lemire** [comment]
For people reading this... The bug was that the POWER code would do a saturated subtraction with  0x80 and check if the result is zero, if so, it would consider the result to be ASCII. But, of course, 0x80 is not ASCII yet it would then consider 0x80  to be ASCII.

This suggest that we never fuzzed the POWER uff-8 validator.

**Comment by lemire** [comment]
Ah. Good news. @pauldreik's fuzzer has turned green.

The off-by-one error strikes again.

**Comment by pauldreik** [comment]
Late to the party! Good that you identified the problem and fixed this.

**Comment by lemire** [comment]
> Late to the party! Good that you identified the problem and fixed this.


It turns out that your fuzzer was just fine, and that we just made a bunch of little mistakes that made it sound like things were insane.

It was a simple off-by-one bug in the end.

Once again, fuzzing saves the day.

**Pull request merged**
