### PR TITLE
Eliminate use of padding in scalars

### PR DESCRIPTION
**Pull request by jkeiser**
After this, we should be able to eliminate the need for padding altogether.

### CODE REVIEW

**Comment by lemire** [comment]
Compilation appears to fail with ...

```
Scanning dependencies of target padded_string_view_char_star_no_capacity_should_compile
[100%] Building CXX object tests/ondemand/compilation_failure_tests/CMakeFiles/padded_string_view_char_star_no_capacity_should_compile.dir/padded_string_view_char_star_no_capacity.cpp.o
/home/conan/project/tests/ondemand/compilation_failure_tests/padded_string_view_char_star_no_capacity.cpp:8:38: error: token ";" is not valid in preprocessor expressions
    8 | #if COMPILATION_TEST_USE_FAILING_CODE;
      |                                      ^
/home/conan/project/tests/ondemand/compilation_failure_tests/padded_string_view_char_star_no_capacity.cpp: In function ‘int main()’:
/home/conan/project/tests/ondemand/compilation_failure_tests/padded_string_view_char_star_no_capacity.cpp:18:10: error: conflicting declaration ‘auto json’
   18 |     auto json = "1"_padded;
      |          ^~~~
/home/conan/project/tests/ondemand/compilation_failure_tests/padded_string_view_char_star_no_capacity.cpp:7:10: note: previous declaration as ‘const char* json’
    7 |     auto json = "1                                                                                          ";
      |          ^~~~
make[3]: *** [tests/ondemand/compilation_failure_tests/CMakeFiles/padded_string_view_char_star_no_capacity_should_compile.dir/build.make:82: tests/ondemand/compilation_failure_tests/CMakeFiles/padded_string_view_char_star_no_capacity_should_compile.dir/padded_string_view_char_star_no_capacity.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:3035: tests/ondemand/compilation_failure_tests/CMakeFiles/padded_string_view_char_star_no_capacity_should_compile.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3042: tests/ondemand/compilation_failure_tests/CMakeFiles/padded_string_view_char_star_no_capacity_should_compile.dir/rule] Error 2
make: *** [Makefile:1230: padded_string_view_char_star_no_capacity_should_compile] Error 2
```

I'll push a commit to try to fix it.

**Comment by lemire** [comment]
@jkeiser I pushed some minor changes to the compilation test which should help.

**Comment by jkeiser** [comment]
Note: I realized I inverted the performance characteristics for bool and null: we pass the length of the token (plus trailing whitespace) to parse_bool, but parse_bool assumes it was given the remaining length of the document, treating Len=4/5 as the unlikely cases when they are in fact the most likely ones. I'll uninvert asap. Shouldn't impact kostya or most of the performance tests, though. (I think partial tweets is there only one that reads a bool.)

**Comment by jkeiser** [comment]
@lemire thanks!

**Comment by lemire** [comment]
@jkeiser I cannot verify locally the remaining failures.

**Comment by lemire** [comment]
> After this, we should be able to eliminate the need for padding altogether.

I reviewed the code and it looks good... but we still rely on  `stringparsing::parse_string` as well as `backslash_and_quote::copy_and_find`. It is thankfully easy to add a guarded version of stringparsing::parse_string` where you pass the end of the string and add a check.

**Comment by jkeiser** [comment]
Note that I haven't checked performance yet, either: I went with a single parse_number function where we pass a nullptr if we're not at the root (i.e. don't need to do length checks). I am assuming that the if (end != nullptr) checks will be optimized away since it's all inline.

**Comment by jkeiser** [comment]
(In other words, if the optimizer does what I hope, the instruction count for kostya should be identical to the parent or.)

**Comment by jkeiser** [comment]
I wonder if there's a good way to trigger a performance run on ampere and skylake when a pr happens, and have it uploaded.

**Comment by jkeiser** [comment]
At the least, it would be possible to make a bot that would listen to prs for a comment like @perfbot run, then run and upload results when ready.

**Comment by lemire** [comment]
@jkeiser 

> At the least, it would be possible to make a bot that would listen to prs for a comment like @perfbot run, then run and upload results when ready.

This seems entirely feasible but your PR is so important that we will no doubt want to do careful hand-tuned analysis.

**Comment by lemire** [comment]
@jkeiser Let me try something on your PR.

**Comment by lemire** [comment]
My PR at https://github.com/simdjson/simdjson/pull/1614 could help with some of the sanitize failures we are seeing. Let us see.

**Comment by lemire** [comment]
@jkeiser I have merged my PR into your PR. I think it should now go green and build faster.

**Comment by lemire** [comment]
There it goes. It is now all green, as promised!

**Comment by jkeiser** [comment]
@lemire thanks tons for the green :)

I just checked in a change to remove the `unlikely` in bool/null parsing. I also restructured it a bit, using if statements instead of && and ||, but since those are short-circuiting, I'm expecting the same number of branches.

**Comment by jkeiser** [comment]
And the latest checkin should remove the *actual* last padding need in ondemand: SIMD string parsing no longer needs it. I implemented this one by having it load the remainder bytes into a temporary buffer when it reaches the end (which is a simdjson_unlkely path because it will only happen in the last 32 bytes of the buffer).

It's possible we could gain something by storing the last_full_buf or end pointer somewhere it can be enregistered or at least not recalculated; for now I'm recalculating it once per string. I also haven't checked the impact of using simdjson_unlikely here.

**Comment by jkeiser** [comment]
Oh right, that would be because only the DOM typically runs the new code at all :)

**Comment by jkeiser** [comment]
Oy, now it looks like the string parsing changes caused sanitize errors. Exactly what one would expect if it's written a little wrong :) I'll debug this week.

**Comment by jkeiser** [comment]
(Unless it's the fact that I literally didn't initialize the memory :). It's actually not necessary to do so but it's an unlikely branch anyway.

**Comment by lemire** [comment]
Sanitizers actually transform the C++ programming experience (mostly for the better).

**Comment by jkeiser** [comment]
Yes they do :) it looks like it wasn't the change I thought it was; the sanitizers are still failing. I'll take a look when I get time, but being in Colorado this week with the family might cramp my style a bit :)

**Comment by jkeiser** [comment]
Found at least one of them :) Accessing dom_parser_implementation of the wrong type. Let's see if this fixes it.

**Comment by lemire** [comment]
@jkeiser It is looking good.

**Comment by jkeiser** [comment]
Once that passes--if it does--i have another commit pushed to a different branch that removes padding from the on demand API and tests. I think Dom can remove it without much work, too, but wasn't focused on it.

**Comment by lemire** [comment]
It seems that there are minor issues around the ARM kernel. I expect that they are minor.

**Comment by jkeiser** [comment]
Yeah, looks like compiler errors.

**Comment by lemire** [comment]
@jkeiser I should be able to fix it later today (at least fix the compiler errors).

**Comment by jkeiser** [comment]
The commit I just pushed ought to fix ARM.

**Comment by lemire** [comment]
@jkeiser Sorry for the delay: I was going to get to it! :-)

While we are at it, I will check that it builds under POWER (manually).

**Comment by lemire** [comment]
@jkeiser I verified manually that the branch builds under POWER and ARM.

**Comment by jkeiser** [comment]
@lemire no problem, I appreciate you thinking about it either way :) I'm just getting to stuff as I have moments.

**Comment by lemire** [comment]
I will try to resync this stale PR as much as possible in the coming days.

**Comment by lemire** [comment]
Merged into https://github.com/simdjson/simdjson/pull/1665

**Comment by lemire** [comment]
This PR has been fully integrated in a more recent PR at https://github.com/simdjson/simdjson/pull/1665

**Comment by lemire** [comment]
Closing this since the work is going well in the parallel PR. I recommend moving future contributions there.

**Pull request closed without merging**
