### PR TITLE
This adds a new SAX benchmark

### PR DESCRIPTION
**Pull request by lemire**
If we are going to have internal SAX, I think we ought to have a couple of benchmarks. This was written quickly but might prove useful.

This is mostly for discussion though it could be merged (into jkeiser/sax-bench). My main purpose was to learn about the new code.

I invite you to checkout the performance results for yourself. Assuming that I did not get anything wrong, they are impressive.

### CODE REVIEW

**Comment by lemire** [comment]
@jkeiser Obviously, there is an issue to be resolved with parse_double.

**Comment by jkeiser** [comment]
Nice! I'm seeing roughly the same nearly 2x throughput improvement on your benchmark as I saw on mine.

**Comment by lemire** [comment]
@jkeiser Feel free to merge it. If you do, it will merge into your own PR.

**Comment by jkeiser** [comment]
It's fascinating that your benchmark gives the same level of improvement, because my benchmark is designed only to parse like 10% of the file and yours does everything. Mine clearly has further inefficiencies to work out :)

**Comment by jkeiser** [comment]
@lemire note parse_double was commented out because I made some "innovations" I hadn't tested the performance of, and parse_large_unsigned is commented out because while it seems right, I haven't tested it. It's an interesting function though, eh? I was planning to use it for twitter's large IDs. I like how the unrolling worked out--no need to bother with overflow detection unless you have a lot of digits!

(Which makes me wonder if parse_large_unsigned could serve another purpose in the main parse_number function: you could stuff all integer overflow detection in that path and fast-path 1-7-digit integers, which probably make up 99% of integers and even 99% of float prefixes.)

We're also going to need rigorous tests for these functions before we release them to the wild, even though my methodology for creating them was to take parse_number and remove the float bits, I could've done that wrong. I'll add bigass comments precheckin.

**Comment by lemire** [comment]
Right. I am not assuming that any of these new functions are correct. We definitively should verify even if we don't open it up publicly.

**Comment by jkeiser** [comment]
You're right; I'll do that :)

**Pull request merged**
