### PR TITLE
This might enable folks to just build the library.

### PR DESCRIPTION
**Pull request by lemire**
Related to PR https://github.com/simdjson/simdjson/pull/956

Also, I think it fixes https://github.com/simdjson/simdjson/issues/955

### CODE REVIEW

**Comment by lemire** [comment]
@dgrr Can you have a look? This would *just* build the library, nothing else.

**Comment by lemire** [comment]
I am wondering whether it is necessary.

**Comment by jkeiser** [comment]
Is there some way to make it so people who include your project from their own cmake get a different set of defaults targeted at library users instead of developers of the library?

**Comment by lemire** [comment]
> Is there some way to make it so people who include your project from their own cmake get a different set of defaults targeted at library users instead of developers of the library?

Right. So if you are dumping simdjson in your own project, you probably just want the library to build, nothing more.

The solution I found online is that people do the reverse. By default, only the library gets build, and you have to select the features one by one.

**Comment by dgrr** [comment]
Hello,

Personally, I think the best approach on the current state of the library would be to build it by default, and optionally allow developers to enable benchmarks. But maybe, that would break backwards compatibility.

And @lemire I just tried your branch and works perfectly. Thanks

**Comment by lemire** [comment]
We need to think this over.

I am marking this for 0.5.

**Comment by lemire** [comment]
I'll merge this for now, and open a distinct issue.

**Pull request merged**
