### PR TITLE
Compile with conversion warnings enabled

### PR DESCRIPTION
**Pull request by jkeiser**
This:
- Adds -Wconversion on Linux
- Reenables conversion warnings on Windows

I made fewer underlying type changes when I fixed it this time, and it didn't get slower in my tests.

The bitmanipulation.h changes cause the functions to return the same type as the underlying intrinsics. I've found performance suffers when you don't do that (likely due to unnecessary conversions). I tried returning decltype(_popcnt64) and such, but that doesn't compile.

NOTE: I would be happy to use the `double(X)` idiom instead of `static_cast<double>(X)` if it's more idiomatic; I saw somewhere you should always use x_cast<>, but I can't find it now. I see recommendations to use C-style casts for numeric types, and I'm on board there. Thoughts? Care?

### CODE REVIEW

**Comment by jkeiser** [comment]
Fixes #756 .

**Comment by lemire** [comment]
> NOTE: I would be happy to use the double(X) idiom instead of static_cast<double>(X) if it's more idiomatic; I saw somewhere you should always use x_cast<>, but I can't find it now. I see recommendations to use C-style casts for numeric types, and I'm on board there. Thoughts? Care?

From a "oh it is pretty" point of view, I prefer the T(x) cast idiom when T is a primitive/numeric type. I am unclear why static_cast<T>(x) would ever be better. When classes are involved, then it is something else... but I can't imagine how static_cast<int>(1) would differ from int(1).

**Comment by lemire** [comment]
(But I do not care ultimately.)

**Comment by jkeiser** [comment]
I'll do me a global search and replace, I like the look of double() as well.

**Comment by jkeiser** [comment]
Did static_cast<T>() -> T() for all single-word numeric primitives.

Turns out VS2017 gets angry when you convert uint64_t -> size_t, presumably because on 32-bit systems that will cause dataloss, so I fixed that too.

**Comment by jkeiser** [comment]
On skylake and skylake-x, I see a very small, but likely real, increase in instruction count (a little less than one instruction per 64-byte block on twitter.json, about 0.5%). If there is performance degradation, it's noise.

I'm still puzzled that there's a change. I would have expected this to be pro forma for the most part. Does adding casts force C++ to do the cast at that time, but if you omit them it finds a better place or way to do the cast?

**Comment by jkeiser** [comment]
Aha! @lemire interestingly, **this commit** accounts for the entire change in instructions per cycle. Before this, we were looping over a 64-bit index (the native result type of _popcnt(), which is int64_t). After, we cast to int and use that as the loop index, and we are back to the normal number of instructions. I am wondering if Intel is better at writing 32 bits to memory with a 32 bit index; I remember something like that when studying address modes a while back.

**Comment by jkeiser** [comment]
@lemire OK, this one is baked, with the T() change and Windows size_t() conversions added.

**Comment by jkeiser** [comment]
This removes the last warning removal from Windows, but #767 fixes the last actual warning.

**Comment by jkeiser** [comment]
Ugh. With all that, there may be an actual perf degradataion on clang6 (but not on gcc).

**Comment by jkeiser** [comment]
More specifically, clang on WESTMERE?

**Comment by jkeiser** [comment]
Well, on skylake at least, we see 1 extra instruction per 128 bytes for westmere. Wonder what that's about. I doubt _popcnt64 has a different signature on westmere ...

**Comment by jkeiser** [comment]
On skylake-x, there's one *less* instruction per 128 bytes for westmere. Presumably a branch prediction thing.

**Comment by jkeiser** [comment]
I'm sorta inclined to call that a wash.

**Comment by jkeiser** [comment]
And the perf tests passed this time. Calling it good. All yours @lemire, in your copious free time ;)

**Comment by lemire** [comment]
Syncing with master.

**Comment by jkeiser** [comment]
> We are now mixing static_cast(...) with T(...). I do not care: do not change anything. I just had to flag it. I repeat my preference for T(...) based on aesthetics.

Yeah, I left two-word primitive casts as static_cast<> because (T)EXPR just breaks my brain and I couldn't bring myself to do it (i.e. (unsigned long)x).

**Comment by jkeiser** [comment]
Ye Gods, I think we're approaching the end of the Warning Nightmare.

**Pull request merged**
