### PR TITLE
Add `SIMDJSON_` prefix to enum names LOG_INFO and LOG_ERROR, because they are commonly used as macro names in other projects, such as ClickHouse.

### PR DESCRIPTION
**Pull request by byronhe**

### CODE REVIEW

**Comment by lemire** [comment]
Running tests.

**Comment by jkeiser** [comment]
I guess this makes some sense to avoid conflicts when people use `using simdjson::*` ... it still feels weird, doesn't C++ let users disambiguate using a specific statement?

Assuming this isn't part of the public interface (and I think it isn't) I'd love to just use `enum class` and stop dumping this stuff into the top level namespace. Rename the enum values as `info` and `error`, etc. Then we'd use log_level::info and log_level::error (etc.).

It's supposedly a c++11 feature, so we *should* be safe.

**Comment by lemire** [comment]
@byronhe  Can you answer @jkeiser ?

I think it makes sense to avoid LOG_INFO or LOG_ERROR as it can credibly be used as a macro. However, if you use a macro for log and error, then you are probably guilty.

**Comment by lemire** [comment]
Ok. I think merging PR https://github.com/simdjson/simdjson/pull/2004 was mistake.

**Comment by lemire** [comment]
This PR is no longer needed. 

However, I invite us (and @yongxiangng) to be mindful of the usage of LOG_ERROR and LOG_INFO as it could be used as macros in other projects.

**Pull request closed without merging**
