### PR TITLE
fuzz on power

### PR DESCRIPTION
**Pull request by pauldreik**

### CODE REVIEW

**Comment by pauldreik** [comment]
I need to debug this interactively (handling linker problems, since libfuzzer is not available with -fsanitize=fuzzer in the ppc64 build).

I tried to get a ppc64le docker up locally on my amd64 machine, but failed. Help appreciated with a pointer on how to do that. Or perhaps if someone has real powerpc hardware I could temporarily ssh into? That would be great since the fuzzing performance likely is higher than running emulated.

I think I will not be able to fix this fast enough for the 0.7 timeframe.

Ping @danlark1 @lemire

**Comment by lemire** [comment]
@pauldreik I do have real POWER9 hardware. Email me and I will give you access.

**Comment by pauldreik** [comment]
Wow, this was a lot easier when having access to a real machine, thanks @lemire !

I got it running and fuzzed over night with all cores, with sanitizers, no problems found. So far so good.

Trying to get it to run in this github action was trickier. First, leak sanitizer had to be disabled. Then, Ubuntu 20.04 failed with some weird error I have never seen before. I switched to Debian Buster. Now I get  
```
 ==13058==ERROR: AddressSanitizer failed to allocate 0xfffffe0e00000000 (-2138893713408) bytes at address 120200000000 (errno: 12)
==13058==ReserveShadowMemoryRange failed while trying to map 0xfffffe0e00000000 bytes. Perhaps you're using ulimit -v
qemu: uncaught target signal 6 (Aborted) - core dumped
Aborted (core dumped)
Error: The process '/home/runner/work/_actions/uraimo/run-on-arch-action/v2.0.5/src/run-on-arch.sh' failed with exit code 134
```

Fuzzing without address sanitizer feels a bit handicapped but better than nothing. So this job will not be as useful as I hoped, but better than not fuzzing power at all.

**Comment by pauldreik** [comment]
This is ready for merging.

**Comment by lemire** [comment]
Restarted the failed job.

**Pull request merged**
