### PR TITLE
Jupyter notebook to generate plot from bench_ondemand files

### PR DESCRIPTION
**Pull request by jkeiser**
There's some hard coding going on in here, particularly /home/jkeiser/simdjson ... but it's probably better to have all this checked in somewhere. It's a Jupyter notebook, and can be used to read any number of JSON benchmark outputs from bench_ondemand.

The graph:

image

### CODE REVIEW

**Comment by lemire** [comment]
@jkeiser Do we want this in the main simdjson repo. or do we want it as part of separate repo. within the simdjson organization? (Honest question.)

**Comment by jkeiser** [comment]
Ultimately I want a separate json benchmark repository. I'll happily build one and put this there. No time right now to move the actual benchmarks though.

One could also argue that results should be stored elsewhere, outside of a repository. I just don't know where :)

**Comment by lemire** [comment]
> One could also argue that results should be stored elsewhere, outside of a repository. I just don't know where :)

I could see it as a `simdjson_perf_notebook` repository. 

> Ultimately I want a separate json benchmark repository. I'll happily build one and put this there. No time right now to move the actual benchmarks though.

Yes. But this comes with some downsides if you are doing active work and need to track performance. The separate repo. needs to point at "something". You might think "ok, it is going to point at the tip of our main branch"... but what if you are testing out a branch?

So it is really nice to have a set of core benchmarks bundled with the main code.

However, competitive benchmarks could be more easily moved elsewhere.

**Comment by jkeiser** [comment]
Moved to the json_benchmark_results repository.

**Pull request closed without merging**
