### PR TITLE
Using just ASCII.

### PR DESCRIPTION
**Pull request by lemire**
Should be self-explanatory. Related https://github.com/simdjson/simdjson/pull/896

### CODE REVIEW

**Comment by lemire** [comment]
@jkeiser This destroys a bit an explanation you had written in a comment... But we can still reverse-engineer it.

**Comment by jkeiser** [comment]
@lemire yeah, the comment feels *more* confusing replaced in that way. Better to move the whole thing to a markdown file, it's mostly design explanation anyway.

**Comment by lemire** [comment]
I will move the explanation.

**Comment by lemire** [comment]
@jkeiser 

> the comment feels more confusing replaced in that way. Better to move the whole thing to a markdown file, it's mostly design explanation anyway.

So I moved it in its own section of the HACKING.md file. The version I moved is the original one you wrote.

**Comment by lemire** [comment]
@jkeiser  Believe me or not, this creates a failing performance test in CI.

**Comment by lemire** [comment]
@jkeiser Have a look. This should now be good.

**Comment by myd7349** [comment]
Confirm fixed.

**Comment by lemire** [comment]
Ok. We can tweak the details later. Let us merge this.

**Pull request merged**
