### PR TITLE
Fix C++ 20 compilation

### LINKED ISSUE #1083: This commit breaks compilation with GCC
Hi, just reporting that commit 796588900cde2df3e7d974d4250f057ff204a80f breaks GCC compilation in ArchLinux.

**Error:**
static assertion failed3194 | static_assert(std::ranges::sized_range<simdjson::dom::array>);

**Compiler version:**
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.1.0 (GCC)

### PR DESCRIPTION
**Pull request by jkeiser**
Fixes #1083.

C++20 fails to compile simdjson on master.

I fixed the underlying problem (there were static_asserts that depended on simdjson/element.h, which had not yet been loaded).

I did not add a quickstart20 test to surface this issue earlier, because we have lurking C++20 warnings in the codebase (there is an issue filed somewhere). If this PR succeeds, however, we know this specific problem is fixed: reamalgamating triggers the issue and I reamalgamated.

### CODE REVIEW

**Comment by lemire** [comment]
Ah. Ah. The plot thickens.

**Comment by jkeiser** [comment]
Haven't got back to this, and probably won't today, but it's on the list.

**Comment by jkeiser** [comment]
Updated from master.

**Comment by jkeiser** [comment]
Fixed the underlying issue.

**Pull request merged**
