### PR TITLE
Minor tweak on number parsing

### PR DESCRIPTION
**Pull request by lemire**
This is merely a code simplification. To be merged into https://github.com/simdjson/simdjson/tree/jkeiser/simplify-integer-parse

### CODE REVIEW

**Comment by jkeiser** [comment]
Oh, nice, so we *can* reliably write out int max if we use one weird trick :)

**Comment by jkeiser** [comment]
Let me tell you how I was thinking about the code here. My desire was to make the success path *never* invoke one of these branches. That's why there was a negative if and a !negative if ... my mental model was that there is one main path that almost every number (negative or not) goes down every time, and a few side branches for unusual cases that hopefully never get taken. The if else model means that large negative numbers go down a different path from large positive ones, making the branch predictor have to predict when it will see a negative number.

The else is a little cleaner, though, and since we're already arguably edge case (> 17 digits) and I have no actual evidence to back up my model, it is probably ok :)

What do you think?

**Comment by lemire** [comment]
> My desire was to make the success path never invoke one of these branches. That's why there was a negative if and a !negative if ... my mental model was that there is one main path that almost every number (negative or not) goes down every time, and a few side branches for unusual cases that hopefully never get taken. The if else model means that large negative numbers go down a different path from large positive ones, making the branch predictor have to predict when it will see a negative number.

Maybe the coffee is not strong enough, but I don't understand. It is too abstract.

Let us take this example...
```C++
int z2(int x);
int z1(int x);
int f(bool b, int x) {
    if(b && x > 100) return z1(1);
    if(!b && x > 10000) return z2(2);
    return 3;
}
```

Look at how GCC compiles it...

```
f:
        cmp     esi, 100
        jle     .L2
        test    dil, dil
        jne     .L11
.L2:
        cmp     dil, 1
        je      .L3
        cmp     esi, 10000
        jg      .L12
.L3:
        mov     eax, 3
        ret
.L12:
        mov     edi, 2
        jmp     z2
.L11:
        mov     edi, 1
        jmp     z1
```

So it is branching on 100, then branching on the boolean, then possibly branching on the 10000.

Let us now look at Visual Studio...

```
f       PROC                                      ; COMDAT
        test    cl, cl
        je      SHORT $LN5@f
        cmp     edx, 100                      ; 00000064H
        jle     SHORT $LN3@f
        mov     ecx, 1
        jmp     z1
$LN5@f:
        cmp     edx, 10000                                ; 00002710H
        jle     SHORT $LN3@f
        mov     ecx, 2
        jmp     z2
$LN3@f:
        mov     eax, 3
        ret     0
f       ENDP
```

It is actually doing it as if we had an  if/then else... right? It checks b, branches and then checks the 100, 10000... 


What did you expect as a result, in assembly?

**Comment by jkeiser** [comment]
I expected a single branch per if statement, which I'm clearly not getting because && and || are implemented as branch pairs :) Head canon updated.

I wonder if | and & would ever be worthwhile, allowing a single, far more predictable branch on two conditions at once. But that is super theoretical and something to evaluate separately.

**Comment by jkeiser** [comment]
I'll go godbolt it.

**Comment by jkeiser** [comment]
With -O3, the compiler disregards the `&`, treating it the same as `&&`.

What I was thinking in my head is closer to:

```
f(bool, int):
        ; x < 100
        xor     eax, eax
        cmp     esi, 100
        setg    al

        ; !b & (x < 100)
        andn   eax, dil
        jne .L2

        ; x < 10000
        cmp     esi, 10000
        setg    al

        ; b & (x < 10000)
        and    eax, dil
        jne .L3

        ; return 3;
        mov     eax, 3
        ret

.L2:
        ; if (!b && (x < 100)) { z1(1) }
        mov     edi, 1
        jmp     z1(int)

.L3:
        ; if (!b && (x < 100)) { z2(2) }
        mov     edi, 2
        jmp     z2(int)
```

One 99.9% predictable success path (remember, the if statements are supposed to be error conditions):
- 11 instructions and 2 predictable branches.

vs. Visual Studio success paths (which seems like the better assembly if you're going to use multiple branches anyway), which are harder to predict because the *combination* is the error, not the individual conditions. Let's treat b as unpredictable (it's more like "negative") and x < y as predictable (18 digits):
- !b, x >= 100: 6 instructions, 1 unpredictable branch, 1 predictable branch
- b, x >= 10000: 6 instructions, 1 unpredictable branch, 1 predictable branch

Because of the extra work required to do all the comparisons at once (and the difficulty of putting x < 100 into a register), my suggestion is almost twice as many instructions, and no unpredictable branches. I'd guess Visual Studio is going to come out on top.

**Comment by lemire** [comment]
Merging for code simplification on the assumption that performance effects are nil. If we think that this can be better optimized, we can come back to it.

**Pull request merged**
