### PR TITLE
Alert user when they use object indexing incorrectly

### PR DESCRIPTION
**Pull request by jkeiser**
> NOTE: This is a Draft only because I need to recheck performance against master and possibly add a SIMDJSON_PRODUCTION flag. I believe the feature itself is complete.

This PR returns an error when the user uses the On Demand object indexing API. Currently it moves the cursor incorrectly and fails in invisible, impossible-to-debug ways, in some cases reading past the end of the buffer.

We check API usage errors at runtime sometimes, because we don't have a way (that I know of) to enforce some things at compiler-time. Specifically, we check that people don't save values and then access them out of order, because there is only one cursor and it is forward-only. Iterating or indexing into arrays and objects requires the cursor to move into the array or object, which invalidates open array/object iterators if you are in a parent or child. We are currently checking object indexing when you are in a *child* object or array because that's an inexpensive check.

We still aren't checking for out-of-order usage is object indexing another object from a sibling or parent. There are very real use cases where this will happen: I did it accidentally myself when implementing the "top tweet" test.

This is the last safety issue around incorrect API usage that I'm aware of. After this, simdjson will always tell you early in the development process when you use the API wrong--either at compile time, or the first time you run the offending code.

## Examples

Both of these error cases have at least one common application that makes it likely users will try: finding the "top" object that matches a certain criteria, like maximum retweet count. To do this, you need to scan all the objects, keeping the current match around, and replace that match when you find one with higher retweet count.

An obvious way to do this will be to stash the `value` or `object` and use it later. This can trigger both antipatterns:
* First, the user will (very reasonably) want to only parse the final matching object. It would be jarring to have to parse the text and screen name of every *possible* match, only to overwrite that later. The obvious way to do this is to stash the object and read these fields at the end. `best_match["text"]` at the end will likely return NO_SUCH_FIELD, because the cursor is in the parent object, and that's where it will look. It's not clear how one would debug this, as all the tweets do in fact have a "text" field!
* Second, the user, noticing that they have the object stashed *anyway*, may not even want to store the match criteria. While this is a performance antipattern, it's such an obvious thing to try that it absolutely *will* be tried. This use of previous objects while in a sibling will fail in extremely non-obvious ways: in particular, `if (best_match["retweet_count"] < candidate["retweet_count"]) { best_match = candidate; }` will always read both fields from the *current* object, meaning the first tweet will always be considered the top tweet and we'll never replace the candidate. This is so subtle and invisible that I imagine people tearing their hair out for days.

Here's a simple example that finds the "leftmost point"--the one with the lowest x value. It illustrates both antipatterns:

```c++
auto json = R"( [
  { "x': 3, "y": 4 },
  { "x': 1, "y": 2 },
  { "x': 5, "y": 6 },
] )"_padded;
auto doc = parser.iterate(json);
simdjson_result<ondemand::value> leftmost_point;
bool first_value = true;
for (auto point : doc) {
  if (first_value) {
    leftmost_point = point;
    first_value = false;
    continue;
  }
  // The user is trying to compare the "x" from the previous point to the "x" in the current one. The code is reasonable, if inefficient.
  // ERROR: this will silently do the wrong thing: even though leftmost_point is a previous point, it will search inside the current object, yielding the same "x" both times.
  if (uint64_t(leftmost_point["x"]) < point["x"]) {
    leftmost_point = point;
  }
}
// ERROR: the cursor is at EOF, so this will run past the end of the buffer and emit undefined results.
std::cout << "x: " << uint64_t(leftmost_point["x"]) << ", y: " << uint64_t(leftmost_point["y"]) << std::endl;
```

I think we want to support this use case, but until we *do*, it's something people are likely to try and it will fail in surprising, largely invisible ways. I also think support for this use case will (in some cases) require a separate API, so we'll still need the above fix for the standard API.

## Errata

Oh, and also, in [that last PR](https://github.com/simdjson/simdjson/pull/1416), I forgot to rename the error code to `ONDEMAND_OUT_OF_ORDER_ITERATION` per the suggestion. (Though now that I think, if we're converging on a world where ondemand is the primary API, we might not want to prefix things like that way--if ondemand is synonymous with simdjson, the word is redundant ...)

@lemire what's your thought on the above?

## Possible Solutions

This is a trickier problem than opening an array and object iterator, because those operations always start at a fixed, known position, object["x"] expects to happen anywhere in the object. There are two ways to handle this.

First, we could force you to open an "object indexer" anytime you index. This means that object indexing doesn't need to do checks, but it makes the API much less satisfying. value["x"]["y"] is so much nicer than `value.indexed()["x"].indexed()["y"]`.

Second, we can add a check, which is going to be expensive. The simplest check I can think of that works universally is to keep a stack of the start indexes of each open iterator. Then, when you do object["x"], it first verifies that the start index at the current level is the same as the object's start index. If we've moved on to another object since then, we return OUT_OF_ORDER_ITERATION.

I went with the second because a satisfying API is really important.

## Solution Performance

Keeping the indexes on a stack and comparing them is going to require:
* An extra write every time the user gets a new value (which we *might* be able to lock down to just objects and arrays). Not incurred on skipping.
* An extra read and compare on every object index (unless the compiler is smart enough to realize start_indexes[depth()] hasn't changed between the time we got the object and used obj["index"]).

These are both frequent operations. Indeed, this PR was showing an extra 5% performance hit when I last ran it (though I think that may have included the 2-3% hit from #1416).

### Performance and SIMDJSON_PRODUCTION

I think this is important enough to be on by default: when you first use simdjson, you are generally writing an application. Most users would rather take a 5% performance hit than spend days of frustrating debugging, if you gave them the choice. And even when people are checking performance, 95% of current performance is still far and away better than anything else out there.

However, I think we can make 100% performance easily recoverable with a SIMDJSON_PRODUCTION flag, which turns off any API safety checks and local debugging aids, allowing full speed with safety in production. We already have SIMDJSON_ONDEMAND_SAFETY_RAILS=OFF, but I think a SIMDJSON_PRODUCTION=ON captures the flavor much better and is easier to explain and recommend to users.

Either way, I'll ensure that if the safety rails are off, this PR doesn't lose us any performance. We might even be able to get back the roughly 2-3% from #1416 .

### CODE REVIEW

**Comment by jkeiser** [comment]
Disconcertingly, I get the same performance with `-DSIMDJSON_PRODUCTION=ON` as OFF (5.6GB/s). I added `SIMDJSON_PRODUCTION` and verified that `start_indexes` is excluded from compilation. Requires investigation.

**Comment by jkeiser** [comment]
... and this is because *master* has 5.6GB/s, as well. This commit doesn't even seem to reduce throughput relative to master, which I find hard to believe.

Will investigate later tonight.

**Comment by jkeiser** [comment]
Hmm. false alarm I think. Rerunning master gives 6.0 now. I'll recheck this.

**Comment by lemire** [comment]
That's about ~7% of difference.

**Comment by jkeiser** [comment]
@lemire yeah, and none of that difference seems to be related to the actual new checks, since they happen even with SIMDJSON_API_USAGE_CHECKS off.

All of the loss happens with the first commit, so next idea is to make it possible to disable the check there and see if *that* works: https://github.com/simdjson/simdjson/pull/1432/commits/9934f659873ecb4dc0e5489d2463c285c2f834ce

Then start isolating the other changes (such as the fact that we start at depth 0 and descend_to(1) now instead of starting at depth 1).

**Comment by jkeiser** [comment]
@lemire one thing to note: the loss I was seeing yesterday seems to have disappeared (or skylake got magically faster): master is currently zipping along at 6.0GB/s.

**Comment by jkeiser** [comment]
@lemire I have reverted every single change here, and still get 5.7GB/s nearly every single time. I'm starting to think there is (as expected) no actual difference when SIMDJSON_PRODUCTION is on, but I'm going to just ... keep rerunning it until I get 5.9 or 6.0 to confirm it can actually do that. Same behavior is happening on master.

**Comment by jkeiser** [comment]
Exactly one revert did seem to make an actual difference, however--starting from depth 1 instead of starting from depth 0 and descending to 1 bumped it back from 5.6 to 5.7. I am still getting 5.7 after a full revert though, so ...

I've included that revert in the branch.

**Comment by jkeiser** [comment]
Aha! The latest commit fixes baseline performance. In fact, it bumps it to 6.1GB/s, the fastest I've ever seen.

Turns out having _capacity / _max_depth available in a local variable makes a rather large difference.

**Comment by jkeiser** [comment]
@lemire after some tuning, here's where the most recent version falls out:

## Skylake

| Branch | Variant | Throughput | Iterations | Branch Misses | Cache Refs | Cache Misses |
|------|---|---|---|---|
| master | production | 5.98 GB/s | 1377592 | 806 | 30528 | 0 |
| PR | production | 6.03 GB/s | 1377568 | 723 | 32395 | 14 |
| PR | development | 5.72 GB/s| 1377293 | 696 | 32698 | 0 |

"production" variant is `-DSIMDJSON_PRODUCTION=ON`. It's interesting that development is so similar in instruction count, yet so much slower (obviously, they must be slower instructions). I'm surprised at the lack of extra memory accesses, though.

The DOM version highlights one difference that might be important: while it has twice as many instructions (2832505), it has four times the branch misses (3144).

So we're losing pretty much 5% in development mode. Since people first working with simdjson are likely to just run cmake without arguments to explore, it feels right to keep it in development mode by default, to prevent frustration (and keep people *using* simdjson).

But I can understand the argument the other way :) What's your feeling?

**Comment by lemire** [comment]
What is the impact of this flag on people who use conan or other package managers?

**Comment by jkeiser** [comment]
If you bring in simdjson as a .h, you can use -DSIMDJSON_API_USAGE_CHECKS to turn it on, but it'd be better if it were on by default. I'll just use SIMDJSON_PRODUCTION everywhere so the default is the same!

**Comment by jkeiser** [comment]
OK, I rejiggered it so that the API usage checks are on by default no matter where you use it. For non-cmake uses, you pass -DSIMDJSON_PRODUCTION when you compile.

**Comment by jkeiser** [comment]
Still worth talking about whether to flip the default, though. I know there's a good argument that the default experience should be the fastest possible, since that's the defining feature of simdjson, but for my part, I think having a frustrating three-day debug session is going to turn more people off than a 5% loss, and I hate to put people through that :)

**Comment by lemire** [comment]
@jkeiser I did not "demand" that the error be prefixed, this just a minor proposal. What you have is fine. Had I been really concerned, I would have spoken up. Let us not get into bike shedding.

**Comment by lemire** [comment]
@jkeiser I think that usability over performance is usually a good trade-off.

I think that the SIMDJSON_PRODUCTION is a neat. We will want to document it carefully, however. Specifically, we need to provide guidance as to:

1. What is SIMDJSON_PRODUCTION for?
2. When you should set SIMDJSON_PRODUCTION.
3. Why you should set SIMDJSON_PRODUCTION.
4. How you should set SIMDJSON_PRODUCTION.
5. Whether it is safe to turn on SIMDJSON_PRODUCTION.

Regarding 1... this is not trivial and I expect most users will not understand it without some explicit explanation. It is not about runtime safety per se. It is to help you make sure that your use of the API is proper. Now... your approach here is a bit unusual and will require explanations... because the way this is supposed to work is that your first build and compiler in debug and then once it works, you build it in release. Now you are suggesting that even in release mode, SIMDJSON_PRODUCTION be on by default.

Regarding 2... I think that should come early in the process. As soon as you have run your code once or twice over real JSON, you can move on.

Regarding 3... If we want to have the feature at all, we should carefully explain the benefits of bothering with SIMDJSON_PRODUCTION.

Regarding 4... You suggest passing it to the compiler but I think some users will want to set it as part of their C++  code. I always find it easier to hack my code than to hack the build system. So you have `#include ...simdjson.h...` and then just before that, you set SIMDJSON_PRODUCTION... after you have debugged your code... does that work?

Regarding 5...  I think we go back a bit to the notion of asserts where people will tell you that you removing asserts in production code is like removing your safety belt once you take your car to the highway. People *want* safety in production... so if you take them that SIMDJSON_PRODUCTION removes safety, they will not want to turn it on.


 I suppose we should update the Kostya benchmark, so that it sets the SIMDJSON_PRODUCTION macro?

**Comment by jkeiser** [comment]
> @jkeiser I did not "demand" that the error be prefixed, this was just a minor proposal. What you have is fine. Had I been really concerned, I would have spoken up. Let us not get into bike shedding.

I didn't think you demanded it :) Neither of us really demand anything, we just explain what we think, make sure we understand each other, and try really hard to accomodate. I like the dynamic, it makes much better software than either of us could alone.

**Comment by jkeiser** [comment]
> @jkeiser I think that usability over performance is usually a good trade-off.
> 
> I think that the SIMDJSON_PRODUCTION is a neat. We will want to document it carefully, however. Specifically, we need to provide guidance as to:
> 
> 1. What is SIMDJSON_PRODUCTION for?
> 2. When you should set SIMDJSON_PRODUCTION.
> 3. Why you should set SIMDJSON_PRODUCTION.
> 4. How you should set SIMDJSON_PRODUCTION.
> 5. Whether it is safe to turn on SIMDJSON_PRODUCTION.
> 
> Regarding 1... this is not trivial and I expect most users will not understand it without some explicit explanation. It is not about runtime safety per se. It is to help you make sure that your use of the API is proper. Now... your approach here is a bit unusual and will require explanations... because the way this is supposed to work is that your first build and compiler in debug and then once it works, you build it in release. Now you are suggesting that even in release mode, SIMDJSON_PRODUCTION be on by default.

Per release versus debug, do you think it would be reasonable to enable it in release mode always? I could imagine people always developing in debug. It didn't occur to me because I almost never debug simdjson that way (since it's disproportionately slow in debug mode).

I'm totally on board with this. It makes sense. And it's a lot easier to explain.

> Regarding 2... I think that should come early in the process. As soon as you have run your code once or twice over real JSON, you can move on.

Yep. The idea is these checks will fail the first time you run them. The only case where that might not happen is if you do *very* inadequate testing before you release--for example, only testing top_tweets cases where the last tweet is the top one.

> Regarding 3... If we want to have the feature at all, we should carefully explain the benefits of bothering with SIMDJSON_PRODUCTION.
> 
> Regarding 4... You suggest passing it to the compiler but I think some users will want to set it as part of their C++ code. I always find it easier to hack my code than to hack the build system. So you have `#include ...simdjson.h...` and then just before that, you set SIMDJSON_PRODUCTION... after you have debugged your code... does that work?

Yep!

> Regarding 5... I think we go back a bit to the notion of asserts where people will tell you that you removing asserts in production code is like removing your safety belt once you take your car to the highway. People _want_ safety in production... so if you take them that SIMDJSON_PRODUCTION removes safety, they will not want to turn it on.

I thought about how the name could make things clearer, actually, and `-DSIMDJSON_DEVELOPMENT_CHECKS=1` probably strikes the right balance of not being alarming and communicating fairly clearly when you should and should not use it.

> I suppose we should update the Kostya benchmark, so that it sets the SIMDJSON_PRODUCTION macro?

Probably. Unless we decide to enable it automatically in release mode (when NDEBUG=1, I think is the right check?).

This reminds me, I need to go and actually analyze the performance gap for all the scenarios, not just find_tweet (which is where I got the 5% number). Kostya could well be worse, though it *might* even be better.

**Comment by lemire** [comment]
@jkeiser 

It does feel to me something like how, with STL, you can do all sorts of unsafe things without warning (e.g., without bound checking), in 'debug mode' whereas in 'release mode', it is assumed that you debugged your code.

So maybe it makes sense to take the training wheels off in release mode... and then explain, carefully, in the documentation, that we expect people to build and test their code in debug mode.

**Comment by jkeiser** [comment]
@lemire I made the change, so that now release mode turns off development checks by default, and -DSIMDJSON_DEVELOPMENT_CHECKS turns them on. Debug turns them on by default as well.  SIMDJSON_PRODUCTION is no more. Performance is at normal levels in release mode. I think this is ready, assuming CI checks out.

**Review by lemire — APPROVED** [review]
Beautiful as usual. Merge!!!

**Pull request merged**
