### PR TITLE
Under ARM, it is slightly better to reverse the word once and then extract the bits.

### PR DESCRIPTION
**Pull request by lemire**
This gives a nice speedup (about 3%) under ARM to stage 1 over many files.

|   |  before |  after |
|---|---|---|
|  twitter | 5.6936 GB/s  |   5.8474 GB/s |
| canada  | 5.2355 GB/s   |  5.4106 GB/s  |
| apache_builds  |    6.1337 GB/s |  6.3507 GB/s  |
| github_events  |  6.5684 GB/s |   6.7383 GB/s |

These numbers are with clang 12 under an Apple M1 laptop. To get solid results, I use  commands like `benchmark/parse -n 5000 jsonexamples/github_events.json`.

Unfortunately, the required instruction (rbit) is difficult to access from C++. I had to use inline assembly so it does not work under Visual Studio. Visual Studio has such an intrinsic, but it seems limited to 32-bit (at least up to recently).

This is not a large gain but given that we rely heavily on stage 1 for everything, 3% is quite nice.

Fixes https://github.com/simdjson/simdjson/issues/322

### CODE REVIEW

**Comment by lemire** [comment]
Somehow I had closed https://github.com/simdjson/simdjson/issues/322 due to lack of interest and motivation, but I think I was wrong to do so. It is a worthwhile issue.

**Comment by aqrit** [comment]
possible alternative
https://lemire.me/blog/2019/05/15/bitset-decoding-on-apples-a12/#comment-406914

**Comment by lemire** [comment]
@aqrit 

Yeah. Ok. So you can do it without bit reversal, but it is not clear to me that it saves you much. Maybe you can help me see more clearly. Here are the functions I have in mind, I simplified them so we could see what is happening.

```C++
#include <cstdint>
// Current code
void flatten_bits(uint32_t *base_ptr, uint32_t *base, uint32_t idx, uint64_t bits) {
  if (bits != 0u) {
    uint32_t cnt = __builtin_popcountll(bits);
    uint32_t next_base = *base + cnt;
    uint32_t b = *base;
    for(uint32_t i = 0; i < 16; i++) {
      base_ptr[b + i] = static_cast<uint32_t>(idx) + __builtin_ctzll(bits);
      bits = bits & (bits - 1);
    }
    *base = next_base;
  }
}

// New PR
void flatten_bits_pr(uint32_t *base_ptr, uint32_t *base, uint32_t idx, uint64_t bits) {
  if (bits != 0u) {
     uint64_t rev_bits;
     __asm("rbit %0, %1" : "=r"(rev_bits) : "r"(bits));
    uint32_t cnt = __builtin_popcountll(bits);
    uint32_t next_base = *base + cnt;
    uint32_t b = *base;    
    for(uint32_t i = 0; i < 16; i++) {
       int lz = __builtin_clzll(rev_bits);
       base_ptr[b + i] = static_cast<uint32_t>(idx) + lz;
       rev_bits = rev_bits ^ (uint64_t(0x8000000000000000) >> lz);
    } 
    *base = next_base;
  }
}

// What some people are proposing???
void flatten_bits_alternative(uint32_t *base_ptr, uint32_t *base, uint32_t idx, uint64_t bits) {
  if (bits != 0u) {
    uint32_t cnt = __builtin_popcountll(bits);
    idx += 63;
    uint32_t next_base = *base + cnt;
    uint32_t b = *base;
    for(uint32_t i = 0; i < 16; i++) {
        uint64_t lowest = (-bits) & (bits );
      base_ptr[b + i] =
       idx - 
       __builtin_clzll(lowest);
      bits -= lowest;
    } 
    *base = next_base;
  }
}



```

Now, here is what godbolt is given me.

https://godbolt.org/z/8E81cdbWj

The current tight loop is:

```asm
.L3:
  rbit x5, x3
  sub x6, x3, #1
  clz x5, x5
  and x3, x3, x6
  add w5, w2, w5
  str w5, [x0, w4, uxtw 2]
  add w4, w4, 1
  cmp w7, w4
  bne .L3
```

Notice how it keep reversing the bits and then calling the leading zero? That's the weird way of computing the trailing zeros. Uh!

I am going to omit the cmp, the bne (jump), the store and the counter increment (add w4, w4, 1).  The store I cannot avoid, the pointer increment can go away under unrolling.

So I have rbit, sub, clz, and, add... so 5 instructions.

Let us compare with x64:

```asm
.L3:
  xor edx, edx
  add rax, 4
  tzcnt rdx, rcx
  blsr rcx, rcx
  add edx, esi
  mov DWORD PTR [rax-4], edx
  cmp rax, rdi
  jne .L3
```

I think `xor edx, edx`  is a noop.  If I ignore the increment, the store and the comparaison, I have tzcnt, blsr, add so only three instructions!  Quite a bit better than ARM.


Ok. Can ARM catch up?... let me look at code matching my PR...

```asm
.L11:
  clz x0, x3
  add w5, w2, w0
  str w5, [x6, w4, uxtw 2]
  add w4, w4, 1
  lsr x0, x8, x0
  eor x3, x3, x0
  cmp w7, w4
  bne .L11
```

So we are introducing a shift which is not so nice, but omitting the cmp and the branch and the load/store, I have 4instructions, which is down from 5 before. So I saved one instruction in the tight loop. Victory!

To be clear, I am paying for the this by the bit reversal that I do once at the beginning of the function... but that's only one instruction. I actually have a relatively fat function header with 10 instructions or so... hence it is not going to make a bit difference. I also have a fast path when the input word is zero.

The essential instructions are...

```
  clz x0, x3 // compute __builtin_clzll(rev_bits);
  add w5, w2, w0 // compute the sum static_cast<uint32_t>(idx) + lz;
 lsr x0, x8, x0 // compute (uint64_t(0x8000000000000000) >> lz)
  eor x3, x3, x0 // compute the xor in rev_bits ^ (uint64_t(0x8000000000000000) >> lz)
```

Can we go lower?


What about what I think you are proposing?

```asm
.L19:
  neg x2, x3
  and x2, x2, x3
  clz x5, x2
  sub x3, x3, x2
  sub w2, w6, w5
  str w2, [x0, w4, uxtw 2]
  add w4, w4, 1
  cmp w7, w4
  bne .L19
```

I go back to 5 instructions.

That's instruction count. What about data parallelism?


The x64 updates the word with one instruction (  blsr rcx, rcx ), so it can pipeline a ton of instructions per cycle. In the main branch, ARM has two critical instructions per cycle...

```
  sub x6, x3, #1
  and x3, x3, x6
```

This is what keeps x3 updated. So unless there is fusion, it needs two cycles at least per loop.

The new code in this PR is much worse... it has a sequence of three instructions that are data dependent... that's not good.

```
  clz x0, x3
  lsr x0, x8, x0
  eor x3, x3, x0
```

So it is not obvious that the PR would do better... but it does empirically.

But what I think you are proposing is just as bad...
```
  neg x2, x3
  and x2, x2, x3
  sub x3, x3, x2
```

**Comment by lemire** [comment]
This is pretty:

```C++
void flatten_bits_alternative(uint32_t *base_ptr, uint32_t *base, uint32_t idx, uint64_t bits) {
  if (bits != 0u) {
    uint32_t cnt = __builtin_popcountll(bits);
    idx += 63;
    uint32_t next_base = *base + cnt;
    uint32_t b = *base;
    uint64_t lowest = 0;
    for(uint64_t i = 0; i < 16; i++) {
        lowest = (bits - lowest)
         & (lowest - bits);
      base_ptr[b + i] =
       idx - __builtin_clzll(lowest);
    } 
    *base = next_base;
  }
}
```

But it is still generate 5 non-trivial instruction with a sequence of 3 data dependent instruction. So it is not obviously better than the PR with is 4 non-trivial instructions.

**Comment by lemire** [comment]
@aqrit Any thought?

**Comment by aqrit** [comment]
CLZ and variable shift are fast on ARM.
So figure the reversed version has a 3 cycle latency chain
```
for(...){
    lz = CLZ(bits); // cycle 1
    hi_bit = 0x8000000000000000 >> lz; // cycle 2
    bits ^= hi_bit; // cycle 3

    index_buf[i] = offset + lz; // off chain
}
```

the alternative version is one more instruction in the inner loop, but only has 2 cycles on the critical path (maybe?)
```
static inline
void flatten_bits_alternative(uint64_t bits, uint32_t offset, uint32_t* index_buf)
{
	uint64_t next_bit, temp;
	uint32_t popcnt; 

	popcnt = __builtin_popcountll(bits);
	next_bit = bits & (-bits);
	index_buf[0] = offset - CLZ(next_bit);

	for(int i = 1; i < 8; i++) {
		temp = next_bit - bits; // cycle 1
		bits = bits ^ next_bit; // cycle 1
		next_bit = temp & bits; // cycle 2

		index_buf[i] = offset - CLZ(next_bit); // off chain?
	}

	if (popcnt > 8) {
		for(int i = 0; i < 8; i++) {
			; //...
		}
	}
	//... 
}
```

**Comment by aqrit** [comment]
With the reversed version, I wonder if it would be better to just shift off the highest set bit directly:
```
for(...){
    lz = CLZ(bits);
    bits <<= lz;
    offset += lz;
    index_buf[i] = offset; 
}
```

**Comment by lemire** [comment]
This PR can probably be merged.

**Comment by lemire** [comment]
Merging.

**Pull request merged**
