### PR TITLE
Adding unlikely

### PR DESCRIPTION
**Pull request by lemire**
Adding one word to @jkeiser's PR boosts the GCC performance significantly in one test. The file twitter.json benefits a lot.

Performance effect on AMD Rome, GCC 9:

```
$ for i in ../jsonexamples/*.json; do echo $i; ./benchmark/parse -n 50 $i |grep GB|head -n 1; ../build_no_goto/benchmark/parse -n 50 $i |grep GB|head -n 1; done
../jsonexamples/apache_builds.json
|    Speed        :  29.3157 ns per block ( 98.65%) -   0.4581 ns per byte -   4.7164 ns per structural -   2.1828 GB/s
|    Speed        :  29.5123 ns per block ( 98.77%) -   0.4612 ns per byte -   4.7480 ns per structural -   2.1682 GB/s
../jsonexamples/canada.json
|    Speed        :  89.2029 ns per block ( 99.63%) -   1.3938 ns per byte -   9.3834 ns per structural -   0.7175 GB/s
|    Speed        :  88.8588 ns per block ( 99.63%) -   1.3884 ns per byte -   9.3472 ns per structural -   0.7202 GB/s
../jsonexamples/citm_catalog.json
|    Speed        :  26.4472 ns per block ( 99.37%) -   0.4132 ns per byte -   5.2486 ns per structural -   2.4199 GB/s
|    Speed        :  26.5883 ns per block ( 99.48%) -   0.4154 ns per byte -   5.2766 ns per structural -   2.4070 GB/s
../jsonexamples/github_events.json
|    Speed        :  27.9499 ns per block ( 98.25%) -   0.4369 ns per byte -   6.1124 ns per structural -   2.2891 GB/s
|    Speed        :  28.2750 ns per block ( 98.48%) -   0.4419 ns per byte -   6.1835 ns per structural -   2.2628 GB/s
../jsonexamples/google_maps_api_compact_response.json
|    Speed        :  66.8324 ns per block ( 97.01%) -   1.0467 ns per byte -   3.9679 ns per structural -   0.9554 GB/s
|    Speed        :  67.3730 ns per block ( 98.11%) -   1.0552 ns per byte -   4.0000 ns per structural -   0.9477 GB/s
../jsonexamples/google_maps_api_response.json
|    Speed        :  34.2059 ns per block ( 98.88%) -   0.5347 ns per byte -   4.4788 ns per structural -   1.8703 GB/s
|    Speed        :  34.4755 ns per block ( 96.91%) -   0.5389 ns per byte -   4.5141 ns per structural -   1.8557 GB/s
../jsonexamples/gsoc-2018.json
|    Speed        :  21.2044 ns per block ( 99.36%) -   0.3313 ns per byte -  14.5383 ns per structural -   3.0182 GB/s
|    Speed        :  21.0894 ns per block ( 99.49%) -   0.3295 ns per byte -  14.4595 ns per structural -   3.0347 GB/s
../jsonexamples/instruments.json
|    Speed        :  33.3677 ns per block ( 98.81%) -   0.5214 ns per byte -   4.2281 ns per structural -   1.9180 GB/s
|    Speed        :  34.4621 ns per block ( 98.97%) -   0.5385 ns per byte -   4.3667 ns per structural -   1.8571 GB/s
../jsonexamples/marine_ik.json
|    Speed        :  82.4708 ns per block ( 99.09%) -   1.2886 ns per byte -   5.9790 ns per structural -   0.7760 GB/s
|    Speed        :  83.6998 ns per block ( 99.65%) -   1.3078 ns per byte -   6.0681 ns per structural -   0.7646 GB/s
../jsonexamples/mesh.json
|    Speed        :  85.3834 ns per block ( 99.16%) -   1.3342 ns per byte -   6.2988 ns per structural -   0.7495 GB/s
|    Speed        :  86.5636 ns per block ( 98.71%) -   1.3527 ns per byte -   6.3858 ns per structural -   0.7393 GB/s
../jsonexamples/mesh.pretty.json
|    Speed        :  51.5500 ns per block ( 98.72%) -   0.8055 ns per byte -   8.2895 ns per structural -   1.2415 GB/s
|    Speed        :  51.7865 ns per block ( 99.07%) -   0.8092 ns per byte -   8.3275 ns per structural -   1.2358 GB/s
../jsonexamples/numbers.json
|    Speed        :  74.1633 ns per block ( 98.75%) -   1.1590 ns per byte -   8.6985 ns per structural -   0.8628 GB/s
|    Speed        :  73.7741 ns per block ( 99.19%) -   1.1529 ns per byte -   8.6528 ns per structural -   0.8674 GB/s
../jsonexamples/random.json
|    Speed        :  45.3791 ns per block ( 99.31%) -   0.7091 ns per byte -   4.1128 ns per structural -   1.4102 GB/s
|    Speed        :  48.3607 ns per block ( 99.14%) -   0.7557 ns per byte -   4.3830 ns per structural -   1.3233 GB/s
../jsonexamples/repeat.json
|    Speed        :  30.2191 ns per block ( 98.61%) -   0.4737 ns per byte -   5.2943 ns per structural -   2.1112 GB/s
|    Speed        :  30.5618 ns per block ( 98.35%) -   0.4790 ns per byte -   5.3543 ns per structural -   2.0875 GB/s
../jsonexamples/tree-pretty.json
|    Speed        :  33.8037 ns per block ( 96.52%) -   0.5282 ns per byte -   4.6119 ns per structural -   1.8931 GB/s
|    Speed        :  35.6037 ns per block ( 98.66%) -   0.5564 ns per byte -   4.8575 ns per structural -   1.7974 GB/s
../jsonexamples/twitter_api_compact_response.json
|    Speed        :  39.0633 ns per block ( 97.61%) -   0.6126 ns per byte -   5.0302 ns per structural -   1.6324 GB/s
|    Speed        :  40.5759 ns per block ( 98.58%) -   0.6363 ns per byte -   5.2249 ns per structural -   1.5715 GB/s
../jsonexamples/twitter_api_response.json
|    Speed        :  30.8912 ns per block ( 98.18%) -   0.4840 ns per byte -   5.1342 ns per structural -   2.0660 GB/s
|    Speed        :  32.2385 ns per block ( 95.83%) -   0.5051 ns per byte -   5.3581 ns per structural -   1.9796 GB/s
../jsonexamples/twitterescaped.json
|    Speed        :  58.9406 ns per block ( 99.07%) -   0.9210 ns per byte -   9.3730 ns per structural -   1.0858 GB/s
|    Speed        :  60.2780 ns per block ( 99.35%) -   0.9419 ns per byte -   9.5857 ns per structural -   1.0617 GB/s
../jsonexamples/twitter.json
|    Speed        :  30.3944 ns per block ( 97.36%) -   0.4749 ns per byte -   5.4275 ns per structural -   2.1055 GB/s
|    Speed        :  31.3792 ns per block ( 98.72%) -   0.4903 ns per byte -   5.6033 ns per structural -   2.0394 GB/s
../jsonexamples/twitter_timeline.json
|    Speed        :  46.7561 ns per block ( 97.86%) -   0.7307 ns per byte -   5.7940 ns per structural -   1.3686 GB/s
|    Speed        :  47.3303 ns per block ( 98.33%) -   0.7397 ns per byte -   5.8652 ns per structural -   1.3520 GB/s
../jsonexamples/update-center.json
|    Speed        :  37.7276 ns per block ( 99.05%) -   0.5895 ns per byte -   4.9561 ns per structural -   1.6963 GB/s
|    Speed        :  37.6495 ns per block ( 98.63%) -   0.5883 ns per byte -   4.9459 ns per structural -   1.6999 GB/s
```

### CODE REVIEW

**Comment by jkeiser** [comment]
Indeed! This one unlikely gives a massive benefit across the board vs. the original PR, pretty much sweeping away any performance degradation it had caused. skylake-x (vs. original PR, not master):

| File                             | Blocks | master Cycles | PR Cycles | +Throughput | master Instr. | PR Instr. | -Instr. | master Branch Misses | PR Branch Misses | -Branch Misses | master Cache Misses | PR Cache Misses | -Cache Misses | master Cache Refs | PR Cache Refs | -Cache Refs |
| ---                              |    --: |   --: |   --: |   --: |   --: |   --: |   --: |    --: |    --: |   --: |    --: |    --: |   --: |    --: |    --: |   --: |
| canada                           |  35172 | 322.5 | 297.1 |    7% | 994.6 | 994.6 |    0% |  18522 |  18827 |   -1% |  20919 |  22265 |   -6% | 154706 | 154686 |    0% |
| gsoc-2018                        |  51997 |  74.8 |  72.6 |    2% | 171.2 | 171.5 |    0% |  31750 |  29440 |    7% |  53528 |  50858 |    4% | 168466 | 168378 |    0% |
| github_events                    |   1017 |  80.6 |  78.4 |    2% | 268.8 | 269.9 |    0% |    137 |    101 |   26% |      0 |      0 |    0% |      0 |      0 |    0% |
| random                           |   7976 | 144.2 | 140.6 |    2% | 495.9 | 497.3 |    0% |   2003 |   2042 |   -1% |    250 |      4 |   98% |  37828 |  37328 |    1% |
| instruments                      |   3442 | 104.4 | 102.0 |    2% | 376.1 | 375.6 |    0% |    516 |    492 |    4% |      4 |      1 |   75% |   2812 |    468 |   83% |
| twitter                          |   9867 |  94.7 |  92.8 |    2% | 298.6 | 299.6 |    0% |   3779 |   3453 |    8% |      0 |     21 |    0% |  31946 |  32157 |    0% |
| update-center                    |   8330 | 115.4 | 113.5 |    1% | 343.7 | 345.1 |    0% |   5575 |   5678 |   -1% |      9 |     22 | -144% |  33522 |  33809 |    0% |
| twitterescaped                   |   8787 | 193.1 | 190.6 |    1% | 513.6 | 511.1 |    0% |   5118 |   4915 |    3% |     58 |     14 |   75% |  30119 |  29130 |    3% |
| apache_builds                    |   1988 |  86.2 |  85.8 |    0% | 309.0 | 310.4 |    0% |    106 |    108 |   -1% |      0 |      0 |    0% |      0 |      7 |    0% |
| mesh.pretty                      |  24646 | 180.9 | 180.9 |    0% | 586.8 | 586.8 |    0% |  13481 |  13661 |   -1% |   1323 |   1276 |    3% |  88220 |  88150 |    0% |
| marine_ik                        |  46616 | 291.8 | 292.1 |    0% | 923.2 | 922.9 |    0% |  54351 |  53443 |    1% | 109139 | 108135 |    0% | 255953 | 255862 |    0% |
| numbers                          |   2345 | 257.4 | 258.7 |    0% | 802.3 | 802.3 |    0% |   2199 |   2176 |    1% |      0 |      4 |    0% |    126 |     27 |   78% |
| citm_catalog                     |  26987 |  84.5 |  87.3 |   -3% | 313.9 | 317.3 |   -1% |   1748 |   1783 |   -2% |    934 |    681 |   27% |  89500 |  89497 |    0% |
| mesh                             |  11306 | 294.7 | 305.9 |   -3% | 991.9 | 991.9 |    0% |  10030 |  10418 |   -3% |     14 |     55 | -292% |  60153 |  61000 |   -1% |

**Comment by jkeiser** [comment]
We get a more consistent, but less impressive, benefit if we apply it to the check to make sure the key is a string:

| File                             | Blocks | master Cycles | PR Cycles | +Throughput | master Instr. | PR Instr. | -Instr. | master Branch Misses | PR Branch Misses | -Branch Misses | master Cache Misses | PR Cache Misses | -Cache Misses | master Cache Refs | PR Cache Refs | -Cache Refs |
| ---                              |    --: |   --: |   --: |   --: |   --: |   --: |   --: |    --: |    --: |   --: |    --: |    --: |   --: |    --: |    --: |   --: |
| canada                           |  35172 | 322.5 | 306.7 |    4% | 994.6 | 991.5 |    0% |  18522 |  18880 |   -1% |  20919 |  22630 |   -8% | 154706 | 154736 |    0% |
| instruments                      |   3442 | 104.4 | 100.1 |    4% | 376.1 | 374.1 |    0% |    516 |    539 |   -4% |      4 |      2 |   50% |   2812 |    428 |   84% |
| gsoc-2018                        |  51997 |  74.8 |  71.8 |    4% | 171.2 | 171.2 |    0% |  31750 |  30446 |    4% |  53528 |  53026 |    0% | 168466 | 168456 |    0% |
| numbers                          |   2345 | 257.4 | 248.0 |    3% | 802.3 | 798.1 |    0% |   2199 |   2161 |    1% |      0 |      0 |    0% |    126 |     52 |   58% |
| github_events                    |   1017 |  80.6 |  77.9 |    3% | 268.8 | 269.0 |    0% |    137 |    122 |   10% |      0 |      0 |    0% |      0 |      0 |    0% |
| twitter                          |   9867 |  94.7 |  91.7 |    3% | 298.6 | 298.5 |    0% |   3779 |   3414 |    9% |      0 |      5 |    0% |  31946 |  33472 |   -4% |
| random                           |   7976 | 144.2 | 139.7 |    3% | 495.9 | 495.3 |    0% |   2003 |   2021 |    0% |    250 |      0 |    0% |  37828 |  36708 |    2% |
| twitterescaped                   |   8787 | 193.1 | 188.8 |    2% | 513.6 | 509.8 |    0% |   5118 |   4977 |    2% |     58 |      7 |   87% |  30119 |  29786 |    1% |
| update-center                    |   8330 | 115.4 | 113.0 |    2% | 343.7 | 343.6 |    0% |   5575 |   5787 |   -3% |      9 |      0 |    0% |  33522 |  33493 |    0% |
| mesh.pretty                      |  24646 | 180.9 | 177.5 |    1% | 586.8 | 585.5 |    0% |  13481 |  13170 |    2% |   1323 |    992 |   25% |  88220 |  88172 |    0% |
| marine_ik                        |  46616 | 291.8 | 288.4 |    1% | 923.2 | 920.0 |    0% |  54351 |  53981 |    0% | 109139 | 111907 |   -2% | 255953 | 255866 |    0% |
| apache_builds                    |   1988 |  86.2 |  85.7 |    0% | 309.0 | 309.5 |    0% |    106 |    113 |   -6% |      0 |      0 |    0% |      0 |     62 |    0% |
| mesh                             |  11306 | 294.7 | 297.0 |    0% | 991.9 | 989.0 |    0% |  10030 |  10108 |    0% |     14 |      5 |   64% |  60153 |  60919 |   -1% |
| citm_catalog                     |  26987 |  84.5 |  86.2 |   -2% | 313.9 | 316.7 |    0% |   1748 |   1732 |    0% |    934 |   1222 |  -30% |  89500 |  89393 |    0% |

**Comment by jkeiser** [comment]
And by replacing `if ( parser.start_object(false) ) { goto error; } else { goto object_begin; }` and friends with `if ( parser.start_object(false) ) { goto error; }; goto object_begin;` it gets even better:

+ ssh skylake-x cat /home/jkeiser/simdjson-remote/build/output.txt
| File                             | Blocks | master Cycles | PR Cycles | +Throughput | master Instr. | PR Instr. | -Instr. | master Branch Misses | PR Branch Misses | -Branch Misses | master Cache Misses | PR Cache Misses | -Cache Misses | master Cache Refs | PR Cache Refs | -Cache Refs |
| ---                              |    --: |   --: |   --: |   --: |   --: |   --: |   --: |    --: |    --: |   --: |    --: |    --: |   --: |    --: |    --: |   --: |
| canada                           |  35172 | 322.5 | 293.3 |    9% | 994.6 | 994.6 |    0% |  18522 |  18514 |    0% |  20919 |  21676 |   -3% | 154706 | 154764 |    0% |
| gsoc-2018                        |  51997 |  74.8 |  72.2 |    3% | 171.2 | 170.9 |    0% |  31750 |  30191 |    4% |  53528 |  50749 |    5% | 168466 | 168366 |    0% |
| instruments                      |   3442 | 104.4 | 100.9 |    3% | 376.1 | 374.6 |    0% |    516 |    484 |    6% |      4 |      3 |   25% |   2812 |   3169 |  -12% |
| marine_ik                        |  46616 | 291.8 | 283.0 |    3% | 923.2 | 922.4 |    0% |  54351 |  53948 |    0% | 109139 | 114611 |   -5% | 255953 | 255840 |    0% |
| github_events                    |   1017 |  80.6 |  78.3 |    2% | 268.8 | 267.8 |    0% |    137 |    116 |   15% |      0 |      0 |    0% |      0 |      0 |    0% |
| twitter                          |   9867 |  94.7 |  92.2 |    2% | 298.6 | 297.4 |    0% |   3779 |   3477 |    7% |      0 |    442 |    0% |  31946 |  32478 |   -1% |
| numbers                          |   2345 | 257.4 | 251.1 |    2% | 802.3 | 802.3 |    0% |   2199 |   2158 |    1% |      0 |      0 |    0% |    126 |      1 |   99% |
| random                           |   7976 | 144.2 | 141.2 |    2% | 495.9 | 493.9 |    0% |   2003 |   2007 |    0% |    250 |      7 |   97% |  37828 |  36818 |    2% |
| mesh.pretty                      |  24646 | 180.9 | 177.2 |    2% | 586.8 | 586.8 |    0% |  13481 |  13561 |    0% |   1323 |   1450 |   -9% |  88220 |  88110 |    0% |
| twitterescaped                   |   8787 | 193.1 | 190.3 |    1% | 513.6 | 512.3 |    0% |   5118 |   5054 |    1% |     58 |    120 | -106% |  30119 |  30651 |   -1% |
| apache_builds                    |   1988 |  86.2 |  85.1 |    1% | 309.0 | 308.1 |    0% |    106 |    107 |    0% |      0 |      0 |    0% |      0 |      0 |    0% |
| update-center                    |   8330 | 115.4 | 114.2 |    1% | 343.7 | 342.2 |    0% |   5575 |   5692 |   -2% |      9 |      1 |   88% |  33522 |  33601 |    0% |
| mesh                             |  11306 | 294.7 | 293.7 |    0% | 991.9 | 991.9 |    0% |  10030 |  10240 |   -2% |     14 |    498 | -3457% |  60153 |  59905 |    0% |
| citm_catalog                     |  26987 |  84.5 |  85.8 |   -1% | 313.9 | 313.4 |    0% |   1748 |   1743 |    0% |    934 |   1112 |  -19% |  89500 |  89402 |    0% |

Replacing all error conditions with unlikely makes things worse, FYI. I'll see what happens if we tag all places we first *encounter* errors with unlikely, but not tag `if (f()) { goto error; }` "rethrows."

**Comment by lemire** [comment]
> Replacing all error conditions with unlikely makes things worse

My rule of thumb is that "unlikely" should be used sparingly.

In this instance, I had the idea of trying it after reading through the assembly of your PR and seeing that the assembly did not match my expectation. Adding "unlikely" made the assembly nicer.

**Pull request closed without merging**
