### PR TITLE
fix function was exited without releasing

### PR DESCRIPTION
**Pull request by ihsinme**
the function has the ability to exit without first clearing the allocated memory.

I propose to fix this error.

### CODE REVIEW

**Comment by lemire** [comment]
I submit to you that a better fix is to embed « bool *is_file_as_expected = new bool[c]; » in a unique_ptr for automatic memory management.

**Comment by ihsinme** [comment]
> I submit to you that a better fix is to embed « bool *is_file_as_expected = new bool[c]; » in a unique_ptr for automatic memory management.

really good option.
but in this case it is easier for me to use "delete".
there is only one uncontrolled exit and the logic is built for a normal pointer.
if you are using "unique_ptr" in this case, you will need to add the use of get, remove the call to "delete".
so I suggest you think about it.
if you solve unique_ptr I will try to fix the PR.

**Comment by lemire** [comment]
@ihsinme If you are concerned with memory leaks when the program exits with an error, then I submit to you that there is at least one more leak (fullpath).

**Comment by ihsinme** [comment]
shit that I missed it.
now I will add its release.

**Comment by lemire** [comment]
@ihsinme We reject code with trailing white spaces as a matter of policy... make sure to remove all trailing white space characters at the end of your lines of code.

**Comment by ihsinme** [comment]
judging by the artifact, it was not my fixes that caused the error

**Comment by lemire** [comment]
Let me check our main branch.

**Comment by lemire** [comment]
Ok. Merging you PR.

**Pull request merged**
