### PR TITLE
Deprecate more, show less private things in doxygen

### PR DESCRIPTION
**Pull request by jkeiser**
Added [[deprecated]] on a few more methods and using declarations that doxygen had marked deprecated/private. Also deprecated allocate_capacity, since we never, ever set the max_depth anyway set_capacity works fine.

Basically trying to thin down the API docs to only include things we want people to call.

Updates the order of some methods in parser as well.

### CODE REVIEW

**Comment by jkeiser** [comment]
Just added a couple of private-markings from the linked issues.

**Comment by lemire** [comment]
We are getting segmentation faults in the performance differential tests. This is intriguing.

**Comment by jkeiser** [comment]
Ah! This is because the benchmarker calls stage1 and stage2 directly, and now that I changed it to use set_capacity(), it no longer allocates max_depth buffers (since that gets caught in parse). I think I don't like this. I'd rather all the allocation happened up front before you ever called parse. That way if you arrange it so it's fixed capacity, memory allocation never happens after startup.

Maybe allocate_capacity() is best after all, and I should remove set_capacity / set_max_depth.

**Comment by jkeiser** [comment]
Fixed. I did create a new method, `allocate()`, to replace `allocate_capacity()`, simply because allocate_capacity returns a bool, and it seems more consistent with many other interfaces to have it return an error_code = MEMALLOC.

**Pull request merged**
