### PR TITLE
This moves us to On Demand as the default front-end.

### PR DESCRIPTION
**Pull request by lemire**
This is the last step as far as I am concerned prior to version 0.9: making On Demand our primary front-end and moving DOM to a secondary status.

- [X] create dom.md file
- [X] update doc/basics_doxygen.md so that it is a mere pointer to GitHub ressources (ease maintenance)
- [X] make basics.md and README.md present On Demand as the default
- [X] deleted the (private) get_root_value() method from the ondemand::document type.
- [X] added a tree iteration example (@jkeiser  should review it carefully, line by line, to ensure I did not screw up).

It is a bit of a daring move, to switch to On Demand... but I feel quite certain that if we are going to do it for 1.0, we should do it for 0.9 and not wait at the last minute.

### CODE REVIEW

**Comment by lemire** [comment]
I have converted this to a draft PR given offline discussions with @jkeiser indicating that the change I made might be *unsafe*.

**Comment by lemire** [comment]
@jkeiser This PR should not be safe. I use a "move template" which I think is the most elegant approach.

**Review by jkeiser — APPROVED** [review]
This is really really well done :) Thanks!

**Comment by jkeiser** [comment]
If I wasn't clear before, I think we can probably release 0.9. There's
nothing I know of that truly blocks it. You have just completed the last
major thing.

We probably want to make more noise about this one, though, and craft the
announcement / make sure it goes where it needs to.

**Comment by lemire** [comment]
@jkeiser I am doing more minor cleaning and then I will propose something. I need to update the web site and retire more DOM stuff.

**Pull request merged**
