### PR TITLE
Get headers compiling in editor

### PR DESCRIPTION
**Pull request by jkeiser**
Right now, opening our header files in VS Code generally yields a lot of errors. This is because the headers aren't self-contained.

This PR has a number of effects:

**All files now compile cleanly in the editor.**
  - All generic and implementation-specific files include their dependencies in a `#ifndef SIMDJSON_AMALGAMATED`.
  - Generic files hide their include guards behind `#ifndef SIMDJSON_AMALGAMATED` (this just makes it so files can include each other in-editor without worrying about dups).
  - If you are editing a generic file, it will compile it against the most advanced available implementation, so that things like simd will be loaded in and be testable. (This is particularly useful when editing src/ files; most of stage1 doesn't compile under the fallback implementation.)
  - clangd is now the recommended VS Code extension.

**Amalgamation is safer and more targeted.**
  * Amalgamation will fail if you attempt to include a common file (simdjson/*.h or simdjson/internal/*.h) from an implementation-specific file (arm64, ). This prevents errors where common files are hidden behind #ifdefs.
  * `simdjson.cpp` is now fully independent of `simdjson.h` (don't have to include both anymore)
  * `#include "simdjson.h"` will not process any implementations except the builtin one (where before it would process all of them, even though it only needed the builtin one for ondemand). This doesn't make simdjson.h appreciably smaller, but it should be faster to compile.
* `simdjson.cpp` no longer includes the full simdjson.h, only getting what it uses. This particularly means it won't include DOM or ondemand. It only uses what it needs to produce the stage 1 / stage 2 implementations. This should make it both smaller and faster to compile.

## How It Works

The primary problem preventing our generic and implementation-specific headers from compiling in VS Code is that they cannot compile independently (i.e. call clang with `clang++ ... include/simdjson/generic/numberparsing.h`). This is because they do not include their own dependencies (which is good practice in general, because it gives you a way to know when your dependencies are no longer used and what your actual dependency tree is).

This PR introduces a new define, `SIMDJSON_AMALGAMATED`, which is enabled in key places in the source where implementation-specific files will be amalgamated. `src/simdjson.cpp`, `src/simdjson/builtin.h` and `src/simdjson/builtin/ondemand.h` are key places here.

Thus, SIMDJSON_AMALGAMATED will always be defined when generic and implemenation-specific files are loaded from simdjson.cpp and simdjson.h, but when editing those files directly, it will not be defined. This means generic and implementation-specific files can include.

Generic files also hide their include guards behind this, since they can only be included once per implementation, and SIMDJSON_AMALGAMATED is always defined when multiple implementations may be compiled. Generic files now look like this:

```c++
#ifndef SIMDJSON_GENERIC_NUMBERPARSING_H

#ifndef SIMDJSON_AMALGAMATED
#define SIMDJSON_GENERIC_NUMBERPARSING_H // <-- include guard only defined in editor
#include "simdjson/generic/base.h"
#include "simdjson/generic/jsoncharutils.h" // <-- other generic files are only included directly in editor
#include "simdjson/internal/numberparsing_tables.h" // <-- common headers are only included directly in editor
#endif // SIMDJSON_AMALGAMATED

#include <limits>
#include <ostream>

namespace simdjson {
namespace SIMDJSON_IMPLEMENTATION {

...

} // namespace SIMDJSON_IMPLEMENTATION
} // namespace simdjson

#endif // SIMDJSON_GENERIC_NUMBERPARSING_H
```

To facilitate amalgamation, generic/dependencies.h must have the same #includes. It is then the responsibility of the higher-level amalgamating file (i.e. simdjson.cpp / builtin.h) to `#include "generic/dependencies.h"` *before* including implementation-specific files. simdjson.cpp, for example, now looks like this:

```c++
#include "simdjson/generic/dependencies.h" // <- include generic dependencies before we amalgamate
#include "generic/dependencies.h"

#define SIMDJSON_AMALGAMATED // <-- now it's ok to include implementation files, and not ok to include common headers

#if SIMDJSON_IMPLEMENTATION_ARM64
#include "arm64.cpp"
#endif
#if SIMDJSON_IMPLEMENTATION_FALLBACK
#include "fallback.cpp"
#endif
#if SIMDJSON_IMPLEMENTATION_HASWELL
#include "haswell.cpp"
#endif
#if SIMDJSON_IMPLEMENTATION_ICELAKE
#include "icelake.cpp"
#endif
#if SIMDJSON_IMPLEMENTATION_PPC64
#include "ppc64.cpp"
#endif
#if SIMDJSON_IMPLEMENTATION_WESTMERE
#include "westmere.cpp"
#endif

#undef SIMDJSON_AMALGAMATED // <-- no longer ok to include implementation files, common headers are OK
```

### CODE REVIEW

**Comment by lemire** [comment]
@jkeiser Great idea...

**Comment by jkeiser** [comment]
@lemire could you do me a favor when you get some time, and run this on your machine? It's succeeding and passing tests on my machine, but for reasons I haven't fathomed, CI is trying to compile icelake on every platform.

The line that's including icelake/implementation.cpp is definitely behind `#if SIMDJSON_IMPLEMENTATION_ICELAKE`, and I can't see how in the world that could possibly flip to 1 ...

**Comment by lemire** [comment]
@jkeiser I will but if you email me an ecdsa, I will give you access to an Ice Lake server that you can use. :-)

**Comment by lemire** [comment]
https://security.stackexchange.com/questions/23383/ssh-key-type-rsa-dsa-ecdsa-are-there-easy-answers-for-which-to-choose-when

**Comment by lemire** [comment]
@jkeiser In implementation_detection.h, you have the following...

```C++
#ifndef SIMDJSON_IMPLEMENTATION_ICELAKE
#define SIMDJSON_IMPLEMENTATION_ICELAKE ((SIMDJSON_IS_X86_64) && (SIMDJSON_AVX512_ALLOWED) && (SIMDJSON_COMPILER_SUPPORTS_VBMI2))
#endif
```

In common_defs.h, we have

```C++
// By default, we allow AVX512.
#ifndef SIMDJSON_AVX512_ALLOWED
#define SIMDJSON_AVX512_ALLOWED 1
#endif
```

and

```C++
#ifdef __has_include
// How do we detect that a compiler supports vbmi2?
// For sure if the following header is found, we are ok?
#if __has_include(<avx512vbmi2intrin.h>)
#define SIMDJSON_COMPILER_SUPPORTS_VBMI2 1
#endif
#endif
```

In portability.h, you have

```C++
#if defined(__x86_64__) || defined(_M_AMD64)
#define SIMDJSON_IS_X86_64 1
...
```

So in most instances, if you have a recent compiler and you are under x64, you will have `SIMDJSON_IMPLEMENTATION_ICELAKE` set to true (1).

**Comment by lemire** [comment]
@jkeiser Can you elaborate on your expectation?

**Comment by jkeiser** [comment]
@lemire oh! You're saying they're mostly legitimately icelake? That's possible.

I got suspicious when I noticed the `macos` job was failing to compile, with icelake as its target.

I just realized that I'm actually compiling on a single-architecture machine, since it's ARM :/ Happily, I can flip the fallback implementation on to actually test the header including thing. My guess is, it's not working.

**Comment by lemire** [comment]
@jkeiser 

The current status (as I expected it to be) is that for 64-bit ARM, we build a single kernel (ARM NEON), but for x64 machine, we build a whole range of kernels *including* icelake. Typically, I work on macBooks but I use visual studio code + their ssh extension to develop on an x64 server.

**Comment by jkeiser** [comment]
Yeah! I was just thinking I had 2 kernels and I didn't, so the whole artifice I built to try to include C++ files only once came crumbling down!

**Comment by jkeiser** [comment]
All right, I got it working, somewhat less ambitiously: I just couldn't get the include guards to work with one generic file + multiple implementations. However, I was able to make it so that every single file compiles in VS Code: if you are editing a generic file, it includes the builtin implementation for you so it will be able to compile correctly. If you are editing an implementation-specific file (arm64/*.h), it will include that implementation. If you edit an amalgamation file, it will include the necessary dependencies. For everything else, it takes no special action. (simdjson.cpp and simdjson.h, for example, compile exactly as they do outside VS Code.)

I also drastically thinned the number of things we include: simdjson.h will no longer waste time compiling all possible implementations, since ondemand is only ever compiled with the builtin implementation. simdjson.cpp still compiles all implementations. There are a few files I think might be possible to move to src/, but I haven't done that; this was more than enough change at one time :)

None of these have any effect unless you are in VS Code (the SIMDJSON_IS_EDITOR macro is not defined outside of VS Code).

**Comment by lemire** [comment]
@jkeiser The single header build may need to be adjusted.

**Comment by jkeiser** [comment]
Looks like two small platform specific issues (some missing includes) and it'll pass.

**Comment by jkeiser** [comment]
Figured out a way to do this that doesn't involve special #defines when you're in the editor, by introducing a single new variable, `SIMDJSON_AMALGAMATED`, which indicates you are defining an implementation which is likely behind `#ifdef SIMDJSON_IMPLEMENTATION_XXX`.

* Implementation-specific files (generic, arm64, fallback, etc.):
  - Must `#include` their dependencies behind `#ifndef SIMDJSON_AMALGAMATED`. This makes it so they work in the editor.
    ```c++
    #ifndef SIMDJSON_AMALGAMATED
    <include any common files here>
    #endif // SIMDJSON_AMALGAMATED
    ```
* Generic files follow the same rules as implementation-specific files, plus:
  - Use this pattern to ensure they are only included once when you're editing a generic file:
    ```c++
    #ifndef SIMDJSON_GENERIC_MYFILE_H
    #ifndef SIMDJSON_AMALGAMATED
    #define SIMDJSON_GENERIC_MYFILE_H
    <include any common files or other generic files here>
    #endif // SIMDJSON_AMALGAMATED
    ...
    #endif // SIMDJSON_GENERIC_MYFILE_H
    ```
    This way, we have single-include protection when editing generic or implementation-specific files (when SIMDJSON_AMALGAMATED is on), but simdjson.cpp and simdjson.h can still define multiple implementations without triggering the include guard. 
  - This makes it so that all headers explicitly describe their dependencies, which can help us see what parts of our code depend on each other.
  - The same dependencies must be placed in `simdjson/generic/dependencies.h` or `simdjson/generic/ondemand/dependencies.h`. These files will be included outside the SIMDJSON_AMALGAMATED region, so they can be shared across implementations.
* Common headers (simdjson/*.h and simdjson/internal/*.h):
  - May not be included when SIMDJSON_AMALGAMATED is on: they must be included before it's turned on.

simdjson.cpp, builtin.h and builtin/ondemand.h all declare SIMDJSON_AMALGAMATED, because they put implementations behind `#ifdef SIMDJSON_IMPLEMENTATION_XXX`.

**Comment by jkeiser** [comment]
Other related changes:
* `simdjson.h` and `simdjson.cpp` are now independent files. simdjson.cpp does not include (or require you to include) simdjson.h. If you include both, things will work fine.
* `simdjson.h` now only defines the implementation for the builtin implementation (whatever it happens to be). It doesn't actually define any other implementations, which are loaded at runtime via the .cpp file. It also includes dom, and ondemand for the builtin implementation.
* `simdjson.cpp` defines all implementations, but does not include ondemand or dom because it doesn't use them.
* Each implementation has a single header that defines it, locked behind well-defined include guards (i.e. `SIMDJSON_ARM_H` and `SIMDJSON_FALLBACK_H`). That way, if you include simdjson.h and simdjson.cpp both, they won't try to redefine the same implementation.

For example. Let's say you compile with flags that make `westmere` your builtin implementation, but westmere, haswell and icelake are all compiled implementations.

simdjson.h will include these namespaces:
```
simdjson
simdjson::dom
simdjson::ondemand
simdjson::builtin
simdjson::builtin::ondemand
simdjson::westmere
simdjson::westmere::ondemand
```

simdjson.cpp includes these namespaces:
```
simdjson
simdjson::haswell
simdjson::icelake
simdjson::westmere
```

**Comment by lemire** [comment]
@jkeiser Please see https://github.com/simdjson/simdjson/pull/2034

**Comment by jkeiser** [comment]
It looks like Ubuntu s390x is having a similar issue--maybe it will be fixed by this!

I think we must have been including <intrin.h> or <arm64_neon.h> even when the appropriate kernel isn't being loaded.

**Comment by jkeiser** [comment]
I also made it so it will normalize paths when writing out the file, so that windows and linux don't have a difference.

**Comment by lemire** [comment]
@jkeiser I am fine with the PR but I do have a concern: We have two outstanding and reasonable PRs.

https://github.com/simdjson/simdjson/pull/2026 by @Cuda-Chen

and

https://github.com/simdjson/simdjson/pull/2030 by @yongxiangng

We probably want to keep an eye out for massive conflicts. Typically, we try to merge the small PRs first, before we make a large change.

It is fine to merge this big one first and then adapt the small PRs later, but we should be mindful of the conflicts.

**Comment by jkeiser** [comment]
I'm OK with helping update those PRs if they aren't ready!

**Comment by jkeiser** [comment]
@lemire I've updated the explanation in the initial description of this PR.

**Comment by lemire** [comment]
@jkeiser I have re-reviewed both of them and they look ready to merge. So we have to decide. Either we merge them first, and then you go, or we do it in reverse. I don't care which way we go.

**Review by lemire — APPROVED** [review]

**Comment by jkeiser** [comment]
@lemire may as well merge the others first! I can merge them into mine.

**Comment by jkeiser** [comment]
Looks like it's a clean merge!

**Comment by jkeiser** [comment]
I've done a local run against this with the merged stuff, and there are no conflicts and it passes.

**Comment by lemire** [comment]
Woohoo!!!

**Pull request merged**
