### PR TITLE
Better documentation of default_batch_size

### PR DESCRIPTION
**Pull request by lemire**
cc @casperisfine 

@jkeiser I have also changed the case of the constant. Did you put it all uppercase on purpose?

### CODE REVIEW

**Comment by jkeiser** [comment]
I set it uppercase because my impression is that's the accepted coding style for compile-time constants. I'm not attached, but I also don't know what role would make it lowercase here ...

**Comment by lemire** [comment]
@jkeiser 

I have only used all uppercase for macros, but I see that you have used it for everything that is constexpr. Ok. I will revert.

**Comment by lemire** [comment]
@jkeiser This PR no longer changes the case.

**Comment by lemire** [comment]
Merging since this is now a documentation-only change with nothing to anger @jkeiser.

**Pull request merged**
