### PR TITLE
update string_view lite to version 1.6.0

### PR DESCRIPTION
**Pull request by striezel**
This is the string_view lite header as seen in the current master branch, commit [d27d7b5081406a35b41cb16b321be8833b4cd811](https://github.com/martinmoene/string-view-lite/commit/d27d7b5081406a35b41cb16b321be8833b4cd811), on <https://github.com/martinmoene/string-view-lite>.

### CODE REVIEW

**Comment by striezel** [comment]
Hmm. One of the checks using Visual Studio 16 (`Visual Studio 16 2019, Win32, ON`) fails. Here's an extract of the output leading up to the failure:

```
-- Importing simdjson-data (simdjson/simdjson-data@a5b13babe65c1bba7186b41b43d4cbdc20a5c470)
-- Importing cxxopts (jarro2783/cxxopts@794c975)
CMake Error at dependencies/import.cmake:32 (file):
  file RENAME failed to rename

    D:/a/simdjson/simdjson/dependencies/

  to

    D:/a/simdjson/simdjson/dependencies/.cache/cxxopts

  because: Access is denied.


  

Call Stack (most recent call first):
  dependencies/CMakeLists.txt:145 (import_dependency)


CMake Error at dependencies/import.cmake:40 (message):
-- Configuring incomplete, errors occurred!
See also "D:/a/simdjson/simdjson/build/CMakeFiles/CMakeOutput.log".
  Missing cxxopts_SOURCE_DIR variable
See also "D:/a/simdjson/simdjson/build/CMakeFiles/CMakeError.log".
Call Stack (most recent call first):
  dependencies/CMakeLists.txt:146 (add_dependency)


Error: Process completed with exit code 1.
```

However, the other Visual Studio 16 checks (`Visual Studio 16 2019, Win32, OFF`, `Visual Studio 16 2019, x64, ON`, and `Visual Studio 16 2019, x64, OFF`) are passing. To me this looks like it could be an intermittent problem with the build job or GitHub Actions and re-triggering the job might solve the issue. But I am no expert here, so getting someone to look at this is probably better.

**Comment by lemire** [comment]
Restarted CI job.

**Comment by lemire** [comment]
This PR should not break our CI tests this way. I do not understand.

**Comment by striezel** [comment]
> This PR should not break our CI tests this way. I do not understand.

I do not quite understand this either. What has puzzled me already on the day I submitted this pull request was that some of the jobs seemed to take a very long time to start. Even when you restarted the CI job, which was more than two hours after the submission, several jobs had not even started. Even when I checked again ca. eight hours after the submission, a lot of jobs were still "queued" or "pending". I do not know what the usual duration for a complete CI run including all those jobs here is, but that seems a bit too much to me.  And now when I look at some of the failed runs like [this one](https://github.com/simdjson/simdjson/actions/runs/1078024314), it just says

```
macos-build
This request was automatically failed because there were no enabled runners online to process the request for more than 1 days.
```
or on [another failed job](https://github.com/simdjson/simdjson/actions/runs/1078024330):
```
ubuntu-build
This request was automatically failed because there were no enabled runners online to process the request for more than 1 days.
```

This looks like there has been some kind of problem with GitHub Actions in general. Checking at GitHub Status confirms that there has been an issue with GitHub Actions yesterday: https://www.githubstatus.com/incidents/8qy34dmg4kdm It also says that the incident has been resolved, so maybe we should give it another go.

**Comment by striezel** [comment]
@lemire:
My initial idea was to just to let you trigger the complete CI again. However, to rule out the possibility that this is some issue with restarted CI jobs I just submitted another pull request with the same changes: #1677
Let's see whether this one fares better.

Feel free to close this PR in case the other one succeeds.

**Comment by striezel** [comment]
Closing in favor of https://github.com/simdjson/simdjson/pull/1677, CI tests over there have passed.

**Pull request closed without merging**
