### PR TITLE
Make it possible to check that an implementation is supported at runtime

### PR DESCRIPTION
**Pull request by lemire**
The idea for this new method came via a discussion with @pauldreik

At compile-time, we generate several kernels. At runtime, they are all available. If you select the wrong one, you could crash your system. This function would tell you whether it is safe to call the kernel. This determination must be done at runtime.

This is highly specialized and not likely to be generally useful.

We should only merge this if it is actually useful to someone.

(This is the second and proper PR.)

### CODE REVIEW

**Comment by pauldreik** [comment]
This will be just what I need to hopefully fix the flaky tests with afl-asan! Will try it out and have a look within a few days, just started a new assignment so need to attend to that.

**Comment by lemire** [comment]
@pauldreik I went through and guarded all of our accesses to the implementations, including in the fuzzers, so they should be safer.

**Comment by lemire** [comment]
I like this PR a lot. It makes small things more robust. Our tools instantly benefit from the checks.

Fewer crashes!

cc @jkeiser

**Comment by lemire** [comment]
Ok. I am going to merge this because I think it is likely to just make things better.

**Pull request merged**
