### PR TITLE
[WIP] Faster architecture-specific minifier

### PR DESCRIPTION
**Pull request by jkeiser**
This is a minifier using the actual stage 1 code, taking advantage of the new structural scanner. It's faster than json_minify, by about 2x. Interestingly, it's slower than parsing the file into a DOM. I'm pretty sure there are optimizations that can be done here, however; it's somewhat naive, grabbing the mask of non-whitespace (taking strings into account) and using memcpy() on each non-whitespace region. I haven't tried any variant optimizations at all.

```
make parsingcompetition && ./parsingcompetition jsonexamples/twitter.json

despacing with RapidJSON                        :  9.156 cycles per input byte (best)  10.995 cycles per input byte (avg) 
despacing with RapidJSON Insitu                 :  8.696 cycles per input byte (best)  9.148 cycles per input byte (avg) 
json_minify                                     :    2.182 cycles per input byte (best)    2.326 cycles per input byte (avg)    0.910 GB/s (error margin: 0.058 GB/s)
simdjson->minify                                :    1.152 cycles per input byte (best)    1.224 cycles per input byte (avg)    1.719 GB/s (error margin: 0.104 GB/s)
minisize = 466906, original size = 631515  (minified down to 73.93 percent of original) 
RapidJSON Insitu orig                           :    3.498 cycles per input byte (best)    3.867 cycles per input byte (avg)    0.568 GB/s (error margin: 0.055 GB/s)
RapidJSON Insitu despaced                       :    3.011 cycles per input byte (best)    3.300 cycles per input byte (avg)    0.660 GB/s (error margin: 0.058 GB/s)
sajson orig                                     :    1.770 cycles per input byte (best)    1.910 cycles per input byte (avg)    1.121 GB/s (error margin: 0.083 GB/s)
sajson despaced                                 :    1.427 cycles per input byte (best)    1.617 cycles per input byte (avg)    1.389 GB/s (error margin: 0.165 GB/s)
simdjson orig                                   :    0.712 cycles per input byte (best)    0.856 cycles per input byte (avg)    2.772 GB/s (error margin: 0.468 GB/s)
simdjson despaced                               :    0.665 cycles per input byte (best)    1.169 cycles per input byte (avg)    2.965 GB/s (error margin: 1.279 GB/s)
```

I'm only despacing, is that right? You could make JSON smaller by canonicalizing it--i.e. by parsing \uXXXX, and by replacing 0.000 with 0.0 or even 0--but I don't believe we're doing that, and I'm not sure anyone else does ...

### CODE REVIEW

**Comment by lemire** [comment]
Minifying can be surprisingly difficult and expensive. The proper way is to vectorize it...

The proper way on x64 is to rely on the following magic:

```C++
// Write up to 16 bytes, only the bytes corresponding to a 1-bit are written
// out. credit: Anime Tosho
static __m128i skinnycleanm128(__m128i x, int mask) {
  int mask1 = mask & 0xFF;
  int mask2 = (mask >> 8) & 0xFF;
  __m128i shufmask = _mm_castps_si128(
      _mm_loadh_pi(_mm_castsi128_ps(_mm_loadl_epi64(
                       (const __m128i *)(thintable_epi8 + mask1))),
                   (const __m64 *)(thintable_epi8 + mask2)));
  shufmask =
      _mm_add_epi8(shufmask, _mm_set_epi32(0x08080808, 0x08080808, 0, 0));
  __m128i pruned = _mm_shuffle_epi8(x, shufmask);
  intptr_t popx2 = BitsSetTable256mul2[mask1];
  __m128i compactmask =
      _mm_loadu_si128((const __m128i *)(pshufb_combine_table + popx2 * 8));
  return _mm_shuffle_epi8(pruned, compactmask);
}
```

(The thintable_epi8 is in our code base.)

It looks ugly and so forth, but it is really just two calls to _mm_shuffle_epi8.

You first pack (remove spaces) in two 8-byte subwords. Then you slide them together. This is complicated, a bit, but the end result is that you can do all of the work with a small lookup table.

I think I can port it on top of your PR if you stand still long enough.

**Comment by jkeiser** [comment]
Wow, if that's fast I could use it for a ton of stuff.

**Comment by jkeiser** [comment]
Without the branches writing the output, I bet we could pull 5GB/s (around the time spent in current state 1).

**Comment by lemire** [comment]
I'll work something out.

**Comment by lemire** [comment]
I should be able to have a prototype ready today if people leave me alone for an hour or so.

**Comment by jkeiser** [comment]
Thankfully, having people leave you alone is a bit easier these days :)

**Comment by lemire** [comment]
I try to look feverish.

**Comment by lemire** [comment]
I am hoping that this is made obsolete by https://github.com/lemire/simdjson/pull/568

**Comment by jkeiser** [comment]
Closing in favor of #568. Thanks!

**Pull request closed without merging**
