### PR TITLE
Document stream: truncate final unfinished document and give access to the number of truncated bytes.

### PR DESCRIPTION
**Pull request by lemire**
Currently, when using parse_many, if there is an unclosed final string, then a whole block (e.g., 1 MB) of stage 1 processing is wasted since stage 1 ends in error. Thus we must instruct users not to provide ndjson inputs with unclosed final string...

This PR would tolerate a final unclosed string. What it does is to exclude the unclosed string (it is virtually removed) as well as other "trailing garbage".

The downside of this approach is that a final unclosed string gets ignored, so it is possible to have garbage as part of your stream and be unaware if the garbage is part of an unclosed string. Users are expected to call the `truncated_bytes()` to see whether truncation occurs. If so, they have to handle these leftover bytes somehow.

It is mostly a quality-of-life issue.

### CODE REVIEW

**Comment by lemire** [comment]
@jkeiser This goes deeper than I thought it would. What it tries to do is to handle nicely and safely dirty end of streams.

**Comment by rychale** [comment]
I understand it depends on length of each JSON doc, but since I mostly parse not very long documents I would prefer solution when parser returns all but last document in case it is truncated (so doc.error() !=0 for last document). I don't want to receive partially parsed document missing truncated string, etc with no error code. So I don't care if I can receive some fields of partially parsed document or not.

In case of long very long JSON documents maybe it is worth to return fields successfully parsed along with some error code like PARTIAL. In this case the user can decide to amend the buffer and rerun parsing once again as he knows current document's offset.

Apologise if your's implementation is going to return some error code in case of partial document already.

Alexey

**Comment by lemire** [comment]
>  I don't want to receive partially parsed document missing truncated string, etc with no error code. 

I am not sure I understand your comment but let me clarify: you would never receive a "partially parsed" document. Every JSON document that you receive has either been fully parsed and validated or is flagged as being in error. Anything else would be a bug.

>  I don't want to receive partially parsed document missing truncated string, etc with no error code. 

What this PR does is exclude the trailing garbage at the end of a stream that cannot possibly be a valid JSON document including any document with an unclosed string but also a document with unbalanced brackets and braces ([,],{,}). So if you do...

```
for (auto doc : stream ) {
...
}
```

on something like `{"document1":2} {"document2":2} {"docume` then you will get the first two documents. The last one will be excluded from the stream.

> Apologise if your's implementation is going to return some error code in case of partial document already.


I have the following constraint: I cannot ever ask simdjson to parse a document with an unclosed string. It is simply unsafe because our string processing routine counts on the fact that all strings are closed. In our current branch in our releases, when such a scenario is detected, we throw away the whole block and bail out. In any case, I cannot ever return to you the result of a parsed document when this document may have contained an unclosed string. At a minimum, I need to truncate. What this PR does is to truncate everything at the very end that cannot possibly be a valid document, including anything that contains an unclosed string but also anything that has unmatched braces and unmatched brackets. If the final document (or any other document) has some errors (bad string, bad number, bad object structure, missing comma and so forth), then we would report it.

Of course, I could do extra work to check whether the stream was visibly truncated and report an error in such cases (i.e., it may trigger an exception in your code) but from an API design, you have to figure out when it is best to do so if you want to do so. I am not keen on throwing error in what might be expected behavior. E.g., if you are processing truncated chunks of JSON data, then you may fully expect that the last document is truncated: it is not an error for you, you are doing so on purpose. I know it is common to treat expected conditions as error, but I think that it messes up the APIs by mixing in the expected and the unexpected. One possibility that I considered was to add a method to the document_stream instance that can tell you whether the document was truncated.

**Comment by lemire** [comment]
@rychale Here is what I imagined one might do...

```C++
for(auto doc : stream) {
  // you get full documents here
}
if(auto offset = stream.truncated_offset()) {
  // you truncated at 'offset' bytes
  // when no truncation happened, then offset returns 0
}
```

So if all your documents are 'ok' (valid JSON), then you never get an error, never get an exception.

I submit to you, again, that my philosophy is to avoid treating 'normal' outcomes as 'errors'. So if you input is typically truncated, then I don't want you to be catching exceptions.

**Comment by rychale** [comment]
> on something like `{"document1":2} {"document2":2} {"docume` then you will get the first two documents. The last one will be excluded from the stream.

I’m sorry, my English is not very good. The behavior you’ve describe is just what I was expecting) Just want to understand what you mean by “the last one will be excluded”? Will I’ll be able to call something like iter.current_index() to understand where am I, so I can move the data to the beginning of temporary buffer, append missing bytes and parse again?

**Comment by lemire** [comment]
@rychale The `current_index` gives you the starting point of the current document you are holding. If you call `source()` then you get a string_view over the document that you have parsed (so you know exactly the starting point and the ending point of the document).

**Comment by lemire** [comment]
@rychale I have added a new method `stream.truncated_bytes()` that allows you to know how many bytes (if any) were considered truncated at the end. Truncated bytes have not been parsed as JSON documents. See my documentation:

---

Some users may need to work with truncated streams. The simdjson may truncate documents at the very end of the stream that cannot possibly be valid JSON (e.g., they contain unclosed strings, unmatched brackets, unmatched braces). After iterating through the stream, you may query the `truncated_bytes()` method which tells you how many bytes were truncated. If the stream is made of full (whole) documents, then you should expect `truncated_bytes()` to return zero.


Consider the following example where a truncated document (`{"key":"intentionally unclosed string  `) containing 39 bytes has been left within the stream. In such cases, the first two whole documents are parsed and returned, and the `truncated_bytes()` method returns 39.

```C++
    auto json = R"([1,2,3]  {"1":1,"2":3,"4":4} {"key":"intentionally unclosed string  )"_padded;
    simdjson::dom::parser parser;
    simdjson::dom::document_stream stream;
    auto error = parser.parse_many(json,json.size()).get(stream);
    if(error) { std::cerr << error << std::endl; return; }
    for(auto doc : stream) {
       std::cout << doc << std::endl;
    }
    std::cout << stream.truncated_bytes() << " bytes "<< std::endl; // returns 39 bytes
```


Importantly, you should only call `truncated_bytes()` after iterating through all of the documents since the stream cannot tell whether there are truncated documents at the very end when it may not have accessed that part of the data yet.

**Comment by lemire** [comment]
@rychale 

> Will I’ll be able to call something like iter.current_index() to understand where am I, so I can move the data to the beginning of temporary buffer, append missing bytes and parse again?

The idea of the new `truncated_bytes()` method is just that. You should take these bytes and paste them somehow at the start of the beginning of a new stream.

**Comment by lemire** [comment]
@rychale If you could at least review my documentation, that would be helpful. I am trying to make the code easier for people like yourself.

**Comment by rychale** [comment]
> @rychale If you could at least review my documentation, that would be helpful. I am trying to make the code easier for people like yourself.

Yes, this is exactly I need. Thanks

**Comment by lemire** [comment]
People have had time to review. I am merging this.

**Pull request merged**
