### PR TITLE
Enable /sdl warnings on Windows

### PR DESCRIPTION
**Pull request by jkeiser**
Fixes another warning from #736.

Also enables /sdl so that it won't regress :)

### CODE REVIEW

**Comment by lemire** [comment]
At this point, circleci might as well be disregarded. Here is the new error...


```
+ set
+ grep CHECKPERF
CHECKPERF_BRANCH=master
CHECKPERF_CMAKECACHE=/home/conan/project/.simdjson-user-CMakeCache.txt
CHECKPERF_DIR=/home/conan/project/benchmark/simdjson-master
CHECKPERF_REPOSITORY=https://github.com/simdjson/simdjson
+ '[' -z https://github.com/simdjson/simdjson ']'
+ '[' -z master ']'
+ '[' -z /home/conan/project/benchmark/simdjson-master ']'
+ '[' -z '' ']'
+ '[' -z /home/conan/project/jsonexamples/twitter.json ']'
+ CHECKPERF_ARGS=/home/conan/project/jsonexamples/twitter.json
+ '[' -d /home/conan/project/benchmark/simdjson-master/.git ']'
+ echo 'Checking out the reference branch (master) into /home/conan/project/benchmark/simdjson-master ...'
Checking out the reference branch (master) into /home/conan/project/benchmark/simdjson-master ...
+ pushd /home/conan/project/benchmark/simdjson-master
~/project/benchmark/simdjson-master ~/project/benchmark
+ git remote update
Fetching origin
fatal: unable to access 'https://github.com/simdjson/simdjson/': gnutls_handshake() failed: Error in the pull function.
error: Could not fetch origin


```

**Comment by lemire** [comment]
This still blows up on visual studio.

**Comment by lemire** [comment]
Converted to draft given that it does not fix the issue...

```

219  amalgamate_demo.cpp
220C:\projects\simdjson\build\singleheader\simdjson.cpp(505,97): error C2131: expression did not evaluate to a constant [C:\projects\simdjson\build\singleheader\amalgamate_demo.vcxproj]
221C:\projects\simdjson\build\singleheader\simdjson.cpp(507,3): message : failure was caused by a read of an uninitialized symbol [C:\projects\simdjson\build\singleheader\amalgamate_demo.vcxproj]
```

**Comment by jkeiser** [comment]
@lemire it failed Visual Studio because I didn't update the amalgamated headers, which still had the issue :)

**Comment by lemire** [comment]
RRrrrr

**Comment by lemire** [comment]
Our tests are too good.

**Comment by jkeiser** [comment]
I'll obviously wait for appveyor to finish. It Works On My Machine only carries one so far :)

> Our tests are too good.

I'm happy with this result :) Happier if we got amalgamation to run on Windows, but still quite happy!

**Comment by lemire** [comment]
> I'll obviously wait for appveyor to finish. 

I am not concerned that you will throw bad code into master. I am concerned that I don't understand the error.

**Comment by jkeiser** [comment]
> This will not affect performance. And while it is nice to be able to rely on something being constexpr, we don't really use constexpr very much in simdjson. I bet we could delete all these qualifiers without impacting anything.

Agreed. I think I was going through a brief phase there.

> I'd like to understand the issue though.
> 
> Is it the case that
> 
> ```
> constexpr const implementation * ihatecovid = &haswell_singleton;
> ```
> 
> would blow up?
> 
> Why?
> 
> The `haswell_singleton` thingy has static storage duration, so a pointer to it ought to be subject to constexpr.

The error message says it thinks haswell_singleton is uninitialized, which it obviously *is*, during compilation. Based on that, I have two theories:

1. Visual Studio lacks the ability to tell that the *address* of a thing might be valid, even if the thing itself is not.
2. Visual Studio denies the ability to take the address of an uninitialized variable as `constexpr` because it can't prevent it from getting *dereferenced* during compilation.

**Comment by jkeiser** [comment]
I don't really even know if my second theory is coherent :) Like, I presume you can have and dereference pointers at compile time using constexpr, but I don't *know* that right now.

**Comment by lemire** [comment]
Right.

**Pull request merged**
