### PR TITLE
New escape algorithm with significantly less data dependency

### PR DESCRIPTION
**Pull request by jkeiser**
This algorithm significantly reduces the `escaped` calculation from 9 to 7 bytes (it does not reduce overall instruction count, just dependency chain).

The algorithm is explained in detail [in the comments](https://github.com/simdjson/simdjson/blob/ca29d3fea3675f1a6f9fbc7ab660dfe7d0afb65d/src/generic/stage1/json_escape_scanner.h#L97-L124). Basically, it:

1. Shifts backslashes to get potentially-escaped bytes.
2. ORs in all odd bits to get the starting byte of odd sequences.
3. Uses subtraction to produce 1's for even backslashes and 0's for odd backslashes
4. XORs odd bits back out, flipping the odd and even backslash runs to 1010....

| Operation      | Even-sized   | Even-sized   | Odd-sized    | Odd-sized    |
|                | Even-aligned | Odd-aligned  | Even-aligned | Odd-aligned  |
|----------------|--------------|--------------|--------------|--------------|
| string         | `\\\\XXXX`   | `X\\\\XXX`   | `\\\nXXXX`   | `X\\\nXXX`   |
| backslash      | `11110000`   | `01111000`   | `11100000`   | `01110000`   |
| << 1 | `01111000`   | `00111100`   | `01110000`   | `00111000`   |
| \| odd         | `01111101`   | `01111101`   | `01110101`   | `01111101`   |
| backslash      | `11110000`   | `01111000`   | `11100000`   | `01110000`   |
| -              | `11110101`   | `00000101`   | `11100101`   | `00001101`   |
| ^ odd          | `10100000`   | `01010000`   | `10110000`   | `01011000`   |
|                | `\ \     `   | ` \ \    `   | `\ \n    `   | ` \ \n   `   |
|----------------|--------------|--------------|--------------|--------------|

I haven't tested the performance impact yet. As long as it doesn't go *down*, I'd still prefer this algorithm because it also produces a useful mask of the escape characters themselves alongside the escaped characters.

## Improvements

1. `escaped` and `next_is_escaped` can now be calculated independently, reducing data dependency.
  * `escaped` is down to 7 instructions from 9 (1 of which is parallel), so the CPU can skip ahead to the string prefix_xor sooner.
  * `next_is_escaped` is down to 7 instrucitons as well, so it'll be faster in a tight loop, too.
  * The total instruction count is the same (9 before, 9 now), just dependency chains have been reduced.
2. `escape` (a mask containing the escape characters--the backslashes themselves) is also produced, as part of the calculation for `next_is_escaped`. This isn't useful yet, but it will be when we want to do things like string unescaping in SIMD.

### CODE REVIEW

**Comment by lemire** [comment]
Pinging @geofflangdale (since I think Geoff had a similar strategy in mind though I might misremember)

**Comment by lemire** [comment]
For DOM processing (`parse` benchmark), we appear to have a slight regression of stage 1 (GCC 11, Ice Lake processor).

Before...

```
|- Stage 1
|    Speed        :  10.8301 ns per block ( 34.10%) -   0.1692 ns per byte -   1.9339 ns per structural -   5.9091 GB/s
|    Cycles       :  21.6774 per block    ( 34.75%) -   0.3387 per byte    -   3.8709 per structural    -    2.002 GHz est. frequency
|    Instructions :  70.6102 per block    ( 33.64%) -   1.1033 per byte    -  12.6087 per structural    -    3.257 per cycle
|    Misses       :     127 branch misses ( 23.07%) - 2 cache misses ( 10.67%) - 11179.00 cache references
```

After...
```
|- Stage 1
|    Speed        :  11.0633 ns per block ( 34.55%) -   0.1729 ns per byte -   1.9756 ns per structural -   5.7845 GB/s
|    Cycles       :  22.1234 per block    ( 35.09%) -   0.3457 per byte    -   3.9505 per structural    -    2.000 GHz est. frequency
|    Instructions :  71.4889 per block    ( 33.91%) -   1.1171 per byte    -  12.7656 per structural    -    3.231 per cycle
|    Misses       :     136 branch misses ( 22.82%) - 0 cache misses (  0.00%) - 11449.00 cache references
```

It is very small, something like 1 extra instruction per 64 bytes. So we can merge despite the regression, though it might be nice to play with the code a bit to make sure we can't convince the compiler to do a better job with the new algorithm.

**Comment by lemire** [comment]
We don't need to install clang-13: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md

**Comment by lemire** [comment]
@jkeiser What do you think of this diff?

```diff
index 08f7b22d..9ceb4c91 100644
--- a/src/generic/stage1/json_escape_scanner.h
+++ b/src/generic/stage1/json_escape_scanner.h
@@ -73,7 +73,7 @@ struct json_escape_scanner {
 private:
   static constexpr const uint64_t ODD_BITS = 0xAAAAAAAAAAAAAAAAULL;

-  uint64_t next_escaped_without_backslashes() noexcept {
+  simdjson_really_inline uint64_t next_escaped_without_backslashes() noexcept {
     uint64_t escaped = this->next_is_escaped;
     this->next_is_escaped = 0;
     return escaped;
@@ -148,4 +148,4 @@ private:
 } // namespace SIMDJSON_IMPLEMENTATION
 } // namespace simdjson
```

In my tests, it seems to make your PR just very slightly faster.

Note that the `next_escaped_without_backslashes()` call tends to dominate which is why optimizing it matters.

**Review by lemire — APPROVED** [review]
I think we can get the instruction count to be no higher than before, and I recommend we do so before merging. However, it would be fine to merge directly.

**Comment by jkeiser** [comment]
Ooh, yes! I intended all calls to be inline. Does that fix the instruction count difference?

**Comment by jkeiser** [comment]
I'm seeing an overall improvement on Haswell for stage1 (small but consistent).

**Comment by jkeiser** [comment]
I'll wait on merging until we've validated icelake isn't going down. There's absolutely no reason perf should go *down* with this PR; if CPUs are already saturated it's conceivable it might not go *up.*

**Comment by jkeiser** [comment]
I am the tiniest bit surprised that instruction count is actually down ... when I counted operations in the C++ code, they both came out to 9 (I treat a&~b as a single operation). But I'm guessing the compiler found something I didn't!

**Comment by jkeiser** [comment]
Instruction count is identical after simdjson_inline -> simdjson_really_inline. I don't actually recall whether we had simdjson_inline before; should we prefer one over the other?

**Comment by lemire** [comment]
@jkeiser At least in your test, the instruction count is down by 0.8% and the raw speed is up by 1% (that's because the number of instructions per cycle is very slightly up).

So this PR, at least in this case, makes things very slightly faster.

**Comment by lemire** [comment]
@jkeiser I recommend merging. :-)

**Comment by jkeiser** [comment]
Yep! This is in line with my expectations. It's kinda hard to remember to add inline on every method, but I always get reminded how important it is.

**Comment by jkeiser** [comment]
@lemire after looking through gcc's assembly for this, I suspect the 1-instruction difference is due to the fact that the add_overflow() produces 2 instructions (actually 3, but one is probably a signal to the processor that doesn't get run):

```
        // prev_escaped = 0?
        xor     r13d, r13d
        // uint64_t odd_sequence_starts = backslash & ~even_bits & ~follows_escape;
        andn    rcx, rdx, rax
        and     rcx, rbp
        // prev_escaped = add_overflow(odd_sequence_starts, backslash, &sequences_starting_on_even_bits);
        add     rax, rcx
        setc    r13b
```

**Comment by Validark** [comment]
Sorry if this is the wrong forum in which to ask this, but I was wondering if it is possible to efficiently implement the escape-sequence check for when the bitstrings are in reversed order?

I've been working on the [Accelerated-Zig-Parser](https://github.com/Validark/Accelerated-Zig-Parser), and it would be really nice to be able to support big-endian machines without having to byte-reverse and then do count-**trailing**-zero queries. Specifically mips64 and powerpc64, which always (?) have a count-**leading**-zeroes instruction, it would be more efficient to just stay in big-endian land, which means that bitstrings of backslashes will be in the reverse order from what they would be on a little-endian machine.

`clz` is also one cycle faster than `ctz` on aarch64 and AMD x86_64 machines before Zen 4. Currently, there is an optimization I do on aarch64 where I speculatively bit-reverse my bitstrings in the producer code so the consumer code can use `clz` rather than `rbit`+`clz`. For me, this makes sense because I produce 4 bitstrings that need to be reversed, and I do, on average, ~10.5 "ctz" queries per 64-byte chunk, so I save about 6.5 rbit's per 64-byte chunk by doing the `rbit`s in the producer instead of the consumer. This optimization adds up to several milliseconds on my test bench with just over a million lines of code.

I was thinking a similar optimization should be applicable to x86_64 machines with 32 byte vectors, since I can reverse each of the 32-byte vectors with `vpshufb`+`vpermq`, and then use `clz` rather than `ctz` (`clz` is 1 cycle faster on AMD machines too). However, `vpermq` seems to be latency 6 on Zen 2 and 3, so we'd break the budget by using it twice. However, `vpermq` is 1 or 2 cycles on Zen 1/Zen+, so it could be worth it for those machines. 

Anyway, is there an efficient way to implement this algorithm when the bits are in the reverse order, or is it too big of a problem that the hardware-adder's carry goes in the wrong direction?

Thank you.

**Comment by geofflangdale** [comment]
That reverse-optimization on x86_64 is quite clever. Dealing with reversed bit strings is something that pops up in a few places (e.g. after using the affine transformations from GFNI as a bit matrix transpose). 

Unfortunately, I am not aware of any equivalent reversed-bits version of the tricks we use in simdjson with add. Fundamentally, most arithmetic operations (add, sub, mul) have a towards-MSB data flow.

**Pull request merged**
