### PR TITLE
it the windows numeric_limits problem caused by the max macro?

### PR DESCRIPTION
**Pull request by pauldreik**
see if it's the good old define max that tricks us

### CODE REVIEW

**Comment by pauldreik** [comment]
@friendlyanon I got this weird message from the "main" CI job which may be related to the recent dependencies caching. I bumped the revision, I guess this is the first time it happens.

```
cmake -E sha512sum dependencies/CMakeLists.txt
/tmp/scriptsd1e2c64981855ad8681d0d86d1e91e00.sh: cmake: not found

Exit status: 127
Failed to execute fingerprint script for dep cache!
```

Could you please give me some advice?

**Comment by friendlyanon** [comment]
This is fixed in #1291  
#1282 was merged prematurely, which introduced this issue. I should've better communicated that it wasn't exactly ready for merge.

**Comment by lemire** [comment]
@pauldreik We can merge this.

I am not preoccupied by the failing test.

**Comment by pauldreik** [comment]
I cleaned up the comment and replaced the if with a direct return. The CI failures are unrelated (cmake version and usage limit exceeded).

**Pull request merged**
