### PR TITLE
Copy README.md/amalgamate_demo.cpp only if output dir isn't the same as ${SCRIPTPATH}

### PR DESCRIPTION
**Pull request by pps83**

### CODE REVIEW

**Comment by lemire** [comment]
If we are concerned with the case where they are the same file... and that's the only scenario we care about, then we can check add a check.

What do you think of the following...

https://github.com/simdjson/simdjson/pull/1115

Is there any other instances where you'd like for us to ignore the error?

**Comment by lemire** [comment]
Note that FreeBSD remains broken with this PR.

**Comment by andyzimmerer** [comment]
`````

`````_

**Comment by pps83** [comment]
> Note that FreeBSD remains broken with this PR.

PR updated

**Comment by lemire** [comment]
You do a string comparison when comparing the paths, but that is not safe. It can still be the same directory.

**Comment by pps83** [comment]
> You do a string comparison when comparing the paths, but that is not safe. It can still be the same directory.

If #1115 doesn't have the issue, then it's a better fix.

**Comment by jkeiser** [comment]
If neither of them ends up being acceptable, we have code in jsonexamples/CMakeLists.txt that uses cmake for this purpose :)

**Comment by pps83** [comment]
PR updated to expand `${SCRIPTPATH}` and `${AMALGAMATE_OUTPUT_PATH}` to ensure that equality works even with relative paths

**Comment by pps83** [comment]
I improved the PR, if you take it, please use squash+merge to avoid all the intermediate commits/history in the master

**Comment by lemire** [comment]
Let us try this.

Yes. CMake can definitive copy files and that would be the right move... but let us go with this PR for now.

**Pull request merged**
