### PR TITLE
Fixes issue 1170 and makes the usage of minify easier.

### PR DESCRIPTION
**Pull request by lemire**
Fixes https://github.com/simdjson/simdjson/issues/1170

### CODE REVIEW

**Comment by lemire** [comment]
The failures are apparently coming from the fallback implementation?

**Comment by lemire** [comment]
Ah. I see. (The fallback has an independent implementation.)

**Comment by pauldreik** [comment]
This works, ship it :-)

**Comment by lemire** [comment]
Merging. Thanks.

**Pull request merged**
