### PR TITLE
Prefixing macros (issue 1035)

### PR DESCRIPTION
**Pull request by lemire**
Fixes https://github.com/simdjson/simdjson/issues/1035

### CODE REVIEW

**Comment by jkeiser** [comment]
Ugh, I was hoping we could find a shorter way to do simdjson_really_inline when we prefixed since it's everywhere, but `sj_really_inline` would just add an acronym for people to learn, and I haven't thought of a shorter name that would work besides *maybe* `simdjson_inline`.

Either way, I prefer having prefixes to having short names here, so I am on board with the change.

**Comment by lemire** [comment]
@jkeiser It is not hard to change it from simdjson_really_inline to simdjson_inline but the principle here is to prefix our macros.

Honestly, I don't think that simdjson_really_inline is ugly. I think that SIMDJSON_REALLY_INLINE would be ugly. :-)

**Comment by jkeiser** [comment]
@lemire I don't think it's ugly per se; it just makes a bunch of lines that are already really long, longer :) We use it so frequently that it might be worth it.

**Comment by jkeiser** [comment]
Doesn't get in the way of this PR, though :)

**Comment by jkeiser** [comment]
To your capitalization point, I agree. I think we'll want to change SIMDJSON_UNUSED and SIMDJSON_WARN_UNUSED to all lowercase. It shouts too much and it's sitting in a function definition, where it's one of the least important things to look at.

**Comment by lemire** [comment]
> To your capitalization point, I agree. I think we'll want to change SIMDJSON_UNUSED and SIMDJSON_WARN_UNUSED to all lowercase.

Issue created.

**Pull request merged**
