### PR TITLE
Verification and fix for issue 1063 (JSON Pointers)

### PR DESCRIPTION
**Pull request by lemire**
Fixes our support for JSON pointer,  Issue https://github.com/simdjson/simdjson/issues/1063

Credit to @bbulkow

### CODE REVIEW

**Comment by lemire** [comment]
@jkeiser Please have a look. I think we want to restore JSON pointer support sooner rather than later. 

If we adopt what I coded here, then we should document it a bit better (though maybe not for version 0.5).

**Comment by lemire** [comment]
@jkeiser Ignore the cirrus ci failures.

**Comment by lemire** [comment]
Hmmm... I think we need to be more careful. If we allow omitting the leading slash, then we miss the empty string selector.

**Comment by lemire** [comment]
Ok. I have updated it. No more skipping the leading /.

**Comment by lemire** [comment]
@jkeiser If you are uneasy with how I documented that you could apply JSON Pointer on non-root nodes, we could remove it from the documentation and maybe even put a warning that it is not officially supported.

Honestly though, I'd like for you to think about it. I think it is quite nice once you break away from the "/ is root".

**Comment by jkeiser** [comment]
@lemire I'm good with doing this. However, as we're giving users a breaking change anyway, what about renaming `.at()` to `.at_pointer()` while doing this? My personal reason is I'm not sure this is what we ultimately want for relative JSON pointing and I'd like to reserve the shorter name for then ... but it has several other concrete benefits right now:

* It is more explicit that you're doing JSON Pointer, especially since `.at(int)` is how you address an array.
* It makes the breaking change a compile-time error, giving users an opportunity to fix their code rather than breaking confusingly at runtime.

**Comment by lemire** [comment]
> However, as we're giving users a breaking change anyway, what about renaming .at() to .at_pointer() while doing this?

We need to discuss deprecation.

There are users out there: https://github.com/TkTech/pysimdjson/blob/d2d181ef683706ae86ad29185e246339305e6926/tests/test_element.py


Here is what I propose. We make `at_pointer` the standard-compliant JSON Pointers, and we keep for the time being the `at` function with a deprecation warning but we hack it so that the `at` function calls `at_pointer` after prefixing the query with `/`, except if the query is the empty string.

In this manner, we emulate closely the past behaviour, but we warn the current users, and we open the door for the removal of `at` in the future.

Thoughts?

(I'll implement it but feel free to share your thoughts. I can undo it.)

**Comment by jkeiser** [comment]
That sounds like it'll work! And give users time to fix their code, whether we change it or remove it ultimately.

**Comment by lemire** [comment]
@jkeiser Please have a look. I have updated it. We now check for the 0.4 behaviour and introduce the standard compliant approach with at_pointer.

**Pull request merged**
