### PR TITLE
Possible workaround for libc++ (issue 578)

### PR DESCRIPTION
**Pull request by lemire**
I think that this makes the code *worse* than what we have in master. It certainly makes it more verbose.

I like the syntax:

```
doc["fsdfd"].tie(x.b)
```

It is short and sweet. But I have the feeling that @jkeiser might be highly motivated to write

```
std::tie(x,b) = doc["fsdfd"]
```

Well. That cannot be portable right now since libc++ won't allow it. So we can do...

```
std::tie(x,b) = doc["fsdfd"].ref()
```

(I also introduced "mov" for the case where we need to do a move.)

This is for discussion.

I don't think dropping support for libc++ is good. It means dropping macos and maybe other systems. I think libc++ is in wide use at many important places besides Apple.

### CODE REVIEW

**Comment by lemire** [comment]
Related to https://github.com/simdjson/simdjson/issues/578

**Comment by lemire** [comment]
Other options could be considered, like actually returning std::tuple and avoiding the use of derived classes, but it is more invasive, so I did not try to implement it.

**Comment by jkeiser** [comment]
So, the big reason I like `std::tie()` is that it's an existing thing: there will be people (many many of them?) who have already learned/used it and can transfer that knowledge immediately to our API.

I think I prefer `.tie()` to `.ref()`, personally. I'd rather find out if there are workarounds to make tie work with libc++ rather than the other way around, but we should file an issue and note it. If `tie() = ` doesn't work everywhere, we should probably not encourage people to use it anywhere. Pity, that.

The only thing I prefer about `tie(x, y) = ...` is left to right reading order. I generally expect my assignment targets to be on the left, and thus it's very possible I will stumble when reading `<long expression>.tie(x,y)`. But there's also no better way to do it.

Note there's a Third Way:

```c++
auto result = padded_string::load(...);
if (result.error()) { exit(1); }
auto str = result.value();
```

If only C++ didn't give warnings when shadowing variables, I don't think we'd have any issues at all: my all time preference is definitely `auto [value, error] = ...`

**Comment by lemire** [comment]
@jkeiser It is an old bug... https://bugs.llvm.org/show_bug.cgi?id=17550 and I see no sign that it is being worked on. I think only @ldionne did some work on it but his patch did not appear to land. 

I would also much prefer if we could write to the standard...

**Comment by jkeiser** [comment]
Basically I think we should keep the .tie syntax as our recommended standard, at least until we can make the std::tie work.

**Comment by lemire** [comment]
Closing.

**Comment by ldionne** [comment]
Just FYI, I've resumed work on https://reviews.llvm.org/D50106 and hope to ship it in LLVM 13 (and the corresponding AppleClang, which will be like 6 months down the road).

**Comment by lemire** [comment]
@ldionne  That's fantastic. We ended up downplaying structured bindings but I think it is a great C++ feature generally.

**Pull request closed without merging**
