### PR TITLE
Add .vscode workspace settings

### PR DESCRIPTION
**Pull request by jkeiser**
This adds some workspace level settings for .vscode. As best I can tell, workspace-level settings.json is considered something you check in to the project, while user-level settings are for, well, the user :)

The main reason I did this is I want it to auto-trim whitespaces at the end of the line when saving. It's driving me crazy having to patch up my PRs :)

This also adds a few recommended extensions for the project (which VS Code can show the user if they bring it up).

### CODE REVIEW

**Comment by jkeiser** [comment]
@lemire why did we have *.json set as "binary" diff? (This makes it so `git diff` doesn't show the line-by-line diff). I modified it a little so the diff shows as text now, but I don't really understand how "binary" diff prevents people from modifying the json in the project (as the comment says).

**Comment by lemire** [comment]
> why did we have *.json set as "binary" diff? 

I think that's what we wanted. Or, at least, that's what you want for test and benchmark files. Otherwise, git modifies the file during checkout to match the current system's preferences with respect to line endings.

This means that if you are parsing a JSON file, you are not parsing the *same* file under Windows as you do under Linux due to different file ending preferences. This usually does not matter, but for us, it does. We want byte-by-byte identical files so that we test exactly the same thing under Windows as we do under Linux.

Think about the minefield JSON test. Some of those include weird byte sequences. You don't want git to transform those using heuristics.

This may not longer be a concern since almost all of our test files are in a separate repository and they are recovered as a zip file. Hopefully, unarchiving does not mess with the file ending.

I think it is now fine to do the change, but before we moved the data files, I would have objected.

**Comment by lemire** [comment]
@jkeiser Required reading...
https://en.wikipedia.org/wiki/G._K._Chesterton#Chesterton's_fence

**Comment by lemire** [comment]
:-)

**Comment by jkeiser** [comment]
I think the way I made the change probably handles both concerns :) It makes sense to have them stored binary, and this lets us see diffs too :)

**Comment by lemire** [comment]
@jkeiser 

I see...

```
*.json binary diff=astextplain
```

That looks good.

As I stated... our data files are no longer part of the main repository (except for a few example files), so we are good in any case.

**Pull request merged**
