### PR TITLE
update string_view lite to version 1.6.0, attempt 2

### PR DESCRIPTION
**Pull request by striezel**
@lemire:
This is a rebased version of #1675. Changes are the same, just the parent commit is different.
I submitted this in the hope that it will not encounter the same GitHub Actions issues (_"This request was automatically failed because there were no enabled runners online to process the request for more than 1 days."_) as the other pull request.

__Original message:__
This is the string_view lite header as seen in the current master branch, commit [d27d7b5081406a35b41cb16b321be8833b4cd811](https://github.com/martinmoene/string-view-lite/commit/d27d7b5081406a35b41cb16b321be8833b4cd811), on <https://github.com/martinmoene/string-view-lite>.

### CODE REVIEW

**Comment by lemire** [comment]
Thanks!

**Comment by lemire** [comment]
Odd. It seems to work!

**Comment by striezel** [comment]
Excellent! :)

That's how it should have been from the start. So I presume the failures in #1675 (closed it already) were due to the GitHub Actions incident a few days ago (https://www.githubstatus.com/incidents/8qy34dmg4kdm).

**Comment by lemire** [comment]
Let us merge.

**Pull request merged**
