### PR TITLE
When disabling exceptions, we also disable threading.

### PR DESCRIPTION
**Pull request by lemire**
Our threaded code throws exceptions and there is no clear way to avoid that... so let us disable threads when exceptions are disabled.

### CODE REVIEW

**Comment by jkeiser** [comment]
This seems fine, but do we need to do this in the .h itself for people who aren't using cmake?

**Comment by lemire** [comment]
@jkeiser Good point.

Note that we never had a user report this problem. Mind you, I do not know how many people disable threads. And, of course, our code should not normally throw exceptions... and if it did, it is unclear how many of our users would properly handle the error conditions (we don't).

**Comment by jkeiser** [comment]
What makes it so we can't present an error-code interface in the presence of threads? Does C++ throw by default with threads?

**Comment by lemire** [comment]
@jkeiser Something like join can throw an exception, see
https://en.cppreference.com/w/cpp/thread/thread/join
If exceptions are disabled, then we cannot catch them (duh) but they may still happen. See https://github.com/simdjson/simdjson/pull/1467 and comments by @rrohak who points us at https://stackoverflow.com/questions/6049563/with-fno-exceptions-what-happens-with-new-t

My guess is that if you want to use threads in C++ without exceptions, you should be using the C interface.

Of course, as things are, we are not catching these exceptions so it is unclear whether I am making things noticeable safer. It is more a logical issue. Threads in C++ throw. If you are compiling simdjson without support for exceptions... well... what are you doing with threads ?

**Comment by lemire** [comment]
@jkeiser Let me put it differently. The people who disable exceptions in C++ almost surely do not use C++ threading. So it is logically inconsistent (in a sense) to combine both.

It is the same issue as the custom allocators. They throw. It it is illogical to use them if you are also disabling exceptions.

**Comment by lemire** [comment]
@jkeiser I am actually not sure that "C++ without exceptions" is still standard C++. Let me ask on twitter.

**Comment by jkeiser** [comment]
It sounds like the consensus is "exceptions are baked into standard C++, but roughly50% of C++ users run with -fno-exceptions and accept whatever jankiness results." Not sure where we go with that!

**Comment by lemire** [comment]
For people who want to read through...
https://twitter.com/lemire/status/1366875463428288516

We may simply downplay the version without exceptions without necessarily going out of our way to support it.

**Comment by jkeiser** [comment]
Yeah. I think having first-class support for a no-exception coding style doesn't have to mean ensuring that every last feature is available in a -fno-exceptions environment.

**Comment by rrohak** [comment]
> It is the same issue as the custom allocators. They throw. It it is illogical to use them if you are also disabling exceptions.

I don't entirely agree with this statement because video game developers tend to disable exceptions and use custom allocators due to their space limitations, especially on consoles.

Another idea could be to have two separate implementations with where one uses the c interface, one uses the c++ implementation with an option for exception enabled/disabled. In which exceptions disabled just means the end user deals with whatever issues come with that, or they use their own library.

**Comment by jkeiser** [comment]
I think we don't have to go so far as separate interfaces (though a C simdjson would probably be great for some people). At the moment, we *don't* throw on allocation error (and custom allocators are being added in #1467), and we do compile and work when exceptions are turned off, and AFAIK everything except the thread interface is truly exception-free (we've gone so far as to mark almost everything noexcept, so that the compiler will *tell* us this--it's how we found out about the thread thing).

The question posted here is, I think: "should we use a C thread library so that thread errors are handled without exceptions, allow threads to be enabled and warn users of janky behavior with exceptions off, or turn off threading when exceptions are off?"

**Comment by lemire** [comment]
> I don't entirely agree with this statement because video game developers tend to disable exceptions and use custom allocators due to their space limitations, especially on consoles.

I actually agree with you which is why I am not longer certain that the extra work I asked of you in another issue is warranted.

**Comment by lemire** [comment]
Someone on twitter reminded me of this https://en.cppreference.com/w/cpp/error/terminate

**Comment by jkeiser** [comment]
Can we actually catch the thread exceptions and return an error code to the user?

**Comment by lemire** [comment]
@jkeiser


> Can we actually catch the thread exceptions and return an error code to the user?


If the exceptions are disabled, we can't catch them, but my understanding is that since they are uncaught, they will go to the std::terminate_handler. I think you can only have one `terminate_handler` at a time and you should not expect to find a call stack.

In normal C++, we could catch the exceptions, of course. But it is not quite clear what we could do if they occur. So `stop_thread` might throw, at least according to the specification.  This means that `~stage1_worker()` might throw. In turn, that means that the destructor of document_stream might throw. So we could catch the exception there, but what the hell do we do?

And how do we ensure that we get it right? Compilers can't seem to help us very much...

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61372

Note the fun thing that the noexcept attribute does not, per se, prevent a function from throwing, it just makes it that the exception goes to std::terminate. So you could put noexcept everywhere, being a liar, and it would look fine.

This is a fine mess and it is not our doing.

**Comment by jkeiser** [comment]
terminate doesn't sound like a terrible idea. And I imagine it's what noexcept users have come to expect ...

**Comment by lemire** [comment]
@jkeiser 

I guess that the idea is that you have you app and if you don't want it to rudely abort, you can write some terminate handler. Maybe it goes through and clean things up. And then you die.

**Comment by jkeiser** [comment]
Does the current state of things cause issues?

**Comment by lemire** [comment]
@jkeiser We can safely drop the current PR and bring it back if the issue arises.

**Comment by lemire** [comment]
I am going to close this PR. It was considered. If someone has trouble, well, I prototyped a fix.

**Pull request closed without merging**
