### PR TITLE
Do not enable -fPIC when compiling on Windows

### PR DESCRIPTION
**Pull request by jeremyong**
Regardless of the compiler, Windows targets do not support -fPIC,
as position independent code is already implicitly enabled. Compiling
simdjson with Clang on Windows will error because -fPIC is an
unsupported option for target 'x86_64-pc-windows-msvc'.

### CODE REVIEW

**Comment by jeremyong** [comment]
Incidentally, it may be worth doing a pass to see if other aspects of the build assume `NOT MSVC` is equivalent to `NOT WIN32`. Clang compilation on Windows is a fairly common workflow as well.

**Comment by jeremyong** [comment]
The travis check that failed is due to a spurious github.com outage

image

**Comment by lemire** [comment]
Merging.

We had disabled travis because it was always falling on its head. We re-enabled it for its support of POWER processors... but it is still poor as far as reliability goes.

**Comment by xkszltl** [comment]
Should it be `POSITION_INDEPENDENT_CODE` instead of the hardcoded `-fPIC`?
- https://cmake.org/cmake/help/latest/prop_tgt/POSITION_INDEPENDENT_CODE.html#prop_tgt:POSITION_INDEPENDENT_CODE

**Comment by xkszltl** [comment]
Could you help verifying this?
- https://github.com/simdjson/simdjson/pull/2383

**Pull request merged**
