### PR TITLE
add fuzz element

### PR DESCRIPTION
**Pull request by pauldreik**
This is a new fuzzer to exercise more of the element api. The element-inl.h [is one of the most unfuzzed file in the project](https://github.com/simdjson/simdjson/issues/368#issue-522192008).

This fuzzer replaces both the at_pointer and one of the dump fuzzers but these are not removed at this time.

It also refactors how fuzz data is split into input, in a way that is more efficient for the fuzzer engine to mutate.

Also, creating a padded string from an empty string_view invoked undefined behaviour so I fixed that and added a unit test.

### CODE REVIEW

**Comment by lemire** [comment]
We need to merge something like PR https://github.com/simdjson/simdjson/pull/1238 first thing.

**Comment by lemire** [comment]
Otherwise, there is a lot of good work in this PR and I am marking it 0.6. We should resolve this prior to the next release.

**Comment by pauldreik** [comment]
I merged #1238 into this and added fuzzers for the missing functions tie and is_number as well. If the CI tests pass, it should be good to merge.

**Comment by lemire** [comment]
It looks like it will pass the tests.

**Comment by pauldreik** [comment]
> It looks like it will pass the tests.

Only those appveyor tests left to pass....I don't dare to merge unless it's all green.

**Comment by lemire** [comment]
@pauldreik I recommend merging this.

**Pull request merged**
