### PR TITLE
cmake/add_cpp_test.cmake: fix . to CMAKE_CURRENT_BINARY_DIR

### LINKED ISSUE #1722: When simdjson is part of project as a submodule, the tests are not running because of cmake error
**Describe the bug**
When simdjson is part of project as a submodule, the tests are not running because of cmake error

Here is a proposed solution:
https://github.com/CodeLinaro/simdjson/commit/0216906505a24547e5bba8cbd53d2eeb5945d6dd

Instead of using `--build .` use `--build ${CMAKE_CURRENT_BINARY_DIR}`

If this looks OK. I can open a PR.

This was used on Linux, Ubuntu 18.04 flavor and also tested on Fedora and Cygwin.

### PR DESCRIPTION
**Pull request by kobi-ca**
--build . will not work when this repo is integrated
as a submodule within another repo.
To make sure this is working well, you need
to use CMAKE_CURRENT_BINARY_DIR

Fixes #1722

### CODE REVIEW

**Comment by lemire** [comment]
@kobi-ca Please review the build errors.

**Comment by kobi-ca** [comment]
looking at it.

**Comment by lemire** [comment]
@kobi-ca When you build the library using Ninja as a generator, does it work for you?

**Comment by lemire** [comment]
@kobi-ca Thanks.

Reasonable people use Ninja so we need to support it.

**Comment by lemire** [comment]
I am closing this issue. Please create a new pull request if you'd like to advance this issue.

**Pull request closed without merging**
