### PR TITLE
Introduce logging levels for conditional logging and log key for NO_SUCH_FIELD error

### LINKED ISSUE #2003: Enable error logging
Related issue #506 

### Feature Request

To enable logging of errors only. Currently, setting `SIMDJSON_VERBOSE_LOGGING` will log errors and other info. It would be nice to differentiate the logs into different levels and configure the log levels to be logged via an environment variable / compile option.

Is this a feature that would be desired? Should we implement this with an environment variable or compile option?

### Other notes

The motivation behind this is because I'd like to know the key passed in when we receive `NO_SUCH_FIELD` error code is returned. Enabling verbose logging would be too expensive, because I only need the logs when an error occurs.

### Possible Implementation

I am willing to help and make the changes.

My proposal is to use a environment variable `SIMDJSON_LOG_LEVEL`, which defaults to `INFO`. To log error messages only, we compile with `SIMDJSON_VERBOSE_LOGGING` and set the env variable `SIMDJSON_LOG_LEVEL` to `ERROR`.

1. Add enum class `log_level` in the logger with 2 levels, `INFO`, `ERROR`
2. Add method `should_log(log_level)` in the logger class. It will fetch the env variable on first invocation.
3. Modify `log_line` to take in `log_level` as an additional param (should I default this to `INFO`?)
4. inside `log_line` do something like
```c++
if (LOG_ENABLED && simdjson_unlikely(should_log(log_level)))
{
  // logging impl ...
}
```

### PR DESCRIPTION
**Pull request by yongxiangng**
This resolves #2003

### `SIMDJSON_LOG_LEVEL` Environment variable

Introduces an environment variable `SIMDJSON_LOG_LEVEL` which is available when compiled with the compile option `SIMDJSON_VERBOSE_LOGGING`

`SIMDJSON_LOG_LEVEL` can either be `INFO` or `ERROR`

### Key not found logging

Added logging for key when `NO_SUCH_FIELD` error occurs.

### CODE REVIEW

**Comment by lemire** [comment]
Running tests.

**Comment by lemire** [comment]
Merging.

**Comment by lemire** [comment]
@yongxiangng  

This has a significant negative performance impact for various reasons:

1. Logging went from being a compile-time constant to a runtime constant. This means that we can get the full cost of logging (and not "for free").
2. Temporary small strings are created when accessing keys in objects.

I have to remove it. I do invite you to produce a new PR with the same functionality but it should be free.

cc @jkeiser

**Comment by lemire** [comment]
@yongxiangng

Let me give an example... Compilers will compile `match` to the empty function:

```C++
void log(const char* x) {}


void match(std::string_view v) {
    log("t:");
}
```

What you PR does is ask too much of the compiler... You do the equivalent to ...

```C++
void log(const char* x) {}

void match(std::string_view v) {
    std::string s = "t:";
    s += v;
    log(s.c_str());
}
```

What this does is not at all trivial. The compiler creates an `std::string`, calls the constructor then call the destructor. Yes, I suppose that in theory the compiler could just wipe this out, but it won't.

IMPORTANTLY: You pay the price even do the log function is empty!

So this won't do. 

We need a better solution.

**Comment by yongxiangng** [comment]
@lemire I'm very sorry about that. Yes, I did assume the compiler would have optimized it away, because the log function might get inlined, and the log body is empty when logging is off (also increases chance of inlining), hence the compiler might be able to deduce msg isn't being used and also optimize that away. But I do agree that's not trivial for the compiler and the evidence proves that there is a performance penalty. I am sorry.

I did think of trying to do lazy evaluation, e.g.

```c++
template <typename... Args>
void log(std::string_view format_str, Args&&... args)
{
    if (logging_enabled)
    {
        // do the string formatting inside here
    }
}
```

but the current signature doesn't allow for that because of the defaulted arguments at the back

```c++
static inline void log_error(const json_iterator &iter, const char *error, const char *detail="", int delta=-1, int depth_delta=0) noexcept;
```

I can't think of a good way to solve this problem for now

Thanks for reverting the PR given the severe performance impact and I apologize for the trouble caused.

**Comment by lemire** [comment]
Also, we found out that LOG_ERROR and LOG_INFO were not good choices because people use them as macros (I did not know that).

**Pull request merged**
