### PR TITLE
Make parse_many safer.

### PR DESCRIPTION
**Pull request by lemire**
This disallows passing the input by a move, since it is typically unsafe.

### CODE REVIEW

**Comment by lemire** [comment]
@jkeiser This is meant to keep our users out of trouble.

This was triggered by the reasonable code that @TkTech wrote. He would have expected a compiler error, and I think rightly so. This PR would give him that.

**Comment by jkeiser** [comment]
I'm OK with this level of protection. Can we not do the same with const char *&&?

**Comment by jkeiser** [comment]
parse_many in particular, I expect people to be heavily managing their buffers. I can't see people wanting to do this (which they might with parse):

`for (document_stream doc : parser.parse_many("1 2 3 4 5"_padded)) {}`

**Comment by lemire** [comment]
> Can we not do the same with const char *&&?

Please elaborate.

**Comment by jkeiser** [comment]
I was wondering if the temporary problem could be prevented with char arrays, but I think it only really applies to things that explicitly own their values.

**Pull request merged**
