### PR TITLE
Fix incorrect check for case insensitive key lookup

### PR DESCRIPTION
**Pull request by nongli**

### CODE REVIEW

**Comment by lemire** [comment]
Not only is this code incorrect, but it should also be calling 

```
const bool right_key = (simdjson_strcasecmp(get_string(), key) == 0);
```

**Comment by lemire** [comment]
@jkeiser As far as I can see, each and every tolower becomes a non-inlined function call. We could benchmark it, but I would bet good money that simdjson_strcasecmp is faster.

**Comment by jkeiser** [comment]
I think the reason I did this was strcasecmp assumes a zero-terminated buffer and string_view is not guaranteed to be null-terminated.

This is a good PR, thanks @nongli :)

**Comment by lemire** [comment]
> I think the reason I did this was strcasecmp assumes a zero-terminated buffer and string_view is not guaranteed to be null-terminated. 

I will come back to this.

**Comment by lemire** [comment]
Merging.

**Pull request merged**
