### PR TITLE
Trying to use 0.4 as a reference.

### PR DESCRIPTION
**Pull request by lemire**
Using master as a reference is probably unwise. We want a fixed target, not a moving one.

### CODE REVIEW

**Comment by lemire** [comment]
@jkeiser The checkperf tests are all going to fail because this PR effectively compares our current main branch with the last release.

**Comment by lemire** [comment]
@jkeiser To avoid failures, we could introduce a margin. E.g., we could say that a performance regression of 5% is ok.

**Comment by jkeiser** [comment]
We definitely want to check against the latest stable when considering our cumulative effect, but CI is there to help evaluate the effect of a given PR. Using master has a couple of effects:

1. Flag a PR if it regresses performance improvements we've made since the last stable release.
2. Allow us to take deliberate regressions and not fail every checkin past that point.

The reason we've gotten regressions relative to 0.4.7 is probably that we're ignoring performance failures because the CI tests are still too flaky. Changing the target won't make that any better, though. I also think something may be wrong with my methodology when I personally measure: my first merge after 0.4.6 seems to have regressed the crap out of performance, but the numbers I posted in the PR were pretty peachy.

**Comment by lemire** [comment]
Closing.

**Pull request closed without merging**
