### PR TITLE
Add simdjson_static lib

### LINKED ISSUE #2066: Build shared and static libraries
**Is your feature request related to a problem? Please describe.**
I am packaging `simdjson` on [Conda-Forge](https://conda-forge.org/) where we only ship binaries.
I need to package a static library as well, but, due to how the system is currently organized, we would need two separate CMake targets.
Their names also need to be different, as Windows already generates a `simdjson.lib` static import library for `simdjson.dll`.

**Describe the solution you'd like**
A new target `add_library(simdjson_static STATIC ...)  is controlled by `option(SIMDJSON_BUILD_STATIC ... OFF)`
The target `simdjson` remains unchanged and controlled by `BUILD_SHARED_LIBS`, so this is not breaking.

**Describe alternatives you've considered**
Alternatively, there could be two explicit targets, `simdjson_dyn` and `simdjson`, while `simdjson` is a smart alias that depend on `BUILD_SHARED_LIBS`. This would change the file name of the default static library.

A workaround to any change is building twice with `BUILD_SHARED_LIBS=ON` and `BUILD_SHARED_LIBS=OFF`, but this  would require a lot of patching/sed/renaming.

**Additional context**
https://github.com/conda-forge/simdjson-feedstock

**Are you willing to contribute code or documentation toward this new feature?**
I am willing to contribute a PR.

### PR DESCRIPTION
**Pull request by AntoinePrv**
- Fix #2066
- Chose variable name `SIMDJSON_BUILD_STATIC_LIB` as `SIMDJSON_BUILD_STATIC` is mkared as deprecated
- Please confirm that `simdjson_xxx_props` are used properly
- ~~Still WIP, as~~ I am at the same time trying this branch on Conda-Forge https://github.com/conda-forge/simdjson-feedstock/pull/56

Note: if any maintainer of this project would like to become a co-maintainer of the Conda-Forge package, you are most welcome.

### CODE REVIEW

**Comment by AntoinePrv** [comment]
@lemire this is good for me.

**Comment by lemire** [comment]
I don't think it can cause harm to existing users.

Merging.

**Comment by gf-eaton** [comment]
Is it possible to publish the changes to vcpkg ?  It would be nice to be able to use static libs (.lib and .a)

**Comment by gf-eaton** [comment]
Forgot to mention is it possible to make it available (static-lib) for the `apt install libsimdjson-dev` ?

**Comment by lemire** [comment]
@gf-eaton Regarding vcpkg, can you reach to @myd7349 and possible create an issue at https://github.com/microsoft/vcpkg The simdjson team has no direct control over vcpkg. You need to (politely) reach out to them.


Regarding `apt install libsimdjson-dev`. The debian package is handled by  [Mo Zhou](mailto:lumin@debian.org). You may also reach out the Linux distribution you use. We have no control over what Linux distribution do and how they package simdjson.

**Comment by gf-eaton** [comment]
> @gf-eaton Regarding vcpkg, can you reach to @myd7349 and possible create an issue at https://github.com/microsoft/vcpkg The simdjson team has no direct control over vcpkg. You need to (politely) reach out to them.
> 
> Regarding `apt install libsimdjson-dev`. The debian package is handled by [Mo Zhou](mailto:lumin@debian.org). You may also reach out the Linux distribution you use. We have no control over what Linux distribution do and how they package simdjson.

What is the procedure usually to get the latest changes/release be push to the repositories like vcpkg and apt ?  Is there a event that trigger the update ?

Merci Daniel, keep the good work.

**Comment by lemire** [comment]
@gf-eaton You need to ask vcpkg and your linux distribution. Please consider reaching out to the people I have suggested or to the maintainers of your linux distribution.

**Comment by gf-eaton** [comment]
Bonjour Daniel, @lemire 

I got a return from Mo Zhou, He says that we should file a bug for the libsimdjson in Debian.  First because the lib/package is not ready for multiarch support. AMD64 or arm64 are not supported at the same time.  For cross-platform/architecture compiling. more details below.

```
 # apt install -y libsimdjson-dev:arm64
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following package was automatically installed and is no longer required:
  libsimdjson14
Use 'apt autoremove' to remove it.
The following packages will be REMOVED:
  libsimdjson-dev
The following NEW packages will be installed:
  libsimdjson-dev:arm64
0 upgraded, 1 newly installed, 1 to remove and 0 not upgraded.
Need to get 127 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 [http://deb.debian.org/debian](https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdeb.debian.org%2Fdebian&data=05%7C01%7CGuyFrancoeur%40eaton.com%7C6ccffdedadc44bbd70d808dbd7f61c4e%7Cd6525c95b906431ab926e9b51ba43cc4%7C1%7C0%7C638341224316386614%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fmUTHDP8Eca%2FfLQ2owmcXz%2FAQ%2BWoyyGKGnZIqyqO7EI%3D&reserved=0) bookworm/main arm64 libsimdjson-dev arm64 3.0.1-1 [127 kB]
Fetched 127 kB in 1s (145 kB/s)
Selecting previously unselected package libsimdjson-dev:arm64.
(Reading database ... 52702 files and directories currently installed.)
Preparing to unpack .../libsimdjson-dev_3.0.1-1_arm64.deb ...
Unpacking libsimdjson-dev:arm64 (3.0.1-1) over (3.0.1-1) ...
Setting up libsimdjson-dev:arm64 (3.0.1-1) ...
```

Fix is to come.

---

It may be a good idea to have more formal way to communicate package deployment/update.  When out of sync, the damage it creates (reputation) to the libsimdjson is NON-DETERMINISTIC and unexpected.  It does not give credit to the __work__ when things are failing.

Many people are deploying on many device or multiple architecture when researching for the best JSON lib.  If it only compile on Windows or with source code, we very far from it.  In production/enterprise environment it is unlikely we git pull the source to build.

In my opinion, vcpkg and debian or any other repository should be up-to date.  It ease the usage of the lib.. Also, proposing only .so / .dll and not the static version of .a / .lib makes usage complex.  I give you a use-case : I wish to use the program (EXE) in a Linux where I cannot compile on.  See this like a raw YOCTO made lite OS.  apt is not available nor git pull. We will compile on a different machine (many architecture) and try to limit/embed the libs. Ideally only the executable will be copied on target.  The executable deployed will require the `.a files` at compile time to avoid issues later.

I am waiting for Mo, I will let you know when this is resolved.  If I can do anything to help let me know.

Keep the good work ..

G

**Comment by gf-eaton** [comment]
> @gf-eaton You need to ask vcpkg and your linux distribution. Please consider reaching out to the people I have suggested or to the maintainers of your linux distribution.

Requested. vcpkg.

**Comment by lemire** [comment]
@gf-eaton 

> It may be a good idea to have more formal way to communicate package deployment/update.

If you are volunteering to help, the core team will support your efforts.

**Pull request merged**
