### PR TITLE
Add value.raw_json_token()

### PR DESCRIPTION
**Pull request by jkeiser**
Someone was asking for the ability to parse numbers themselves, their own way, and I think it's a really good thing to have around (it makes it easy to bring strings and numbers into your own format).

### CODE REVIEW

**Comment by lemire** [comment]
This is such a brilliant little idea!!! ❤️

**Review by lemire — APPROVED** [review]
There is really nothing to dislike about this PR. We will need to document it, but it is kind of an "advanced" features, so we can document in due time.

**Comment by lemire** [comment]
@jkeiser I think you are having conflicts with yourself. ;-)

**Comment by jkeiser** [comment]
A far too frequent occurrence, I'm afraid :)

**Comment by longqimin** [comment]
> Someone was asking for the ability to parse numbers themselves, their own way, and I think it's a really good thing to have around (it makes it easy to bring strings and numbers into your own format).

since all the data i need is `value.raw_json_token()`, is it possible to tell `simdjson` not to parse numbers for saving some cycles ? @lemire

**Comment by lemire** [comment]
@longqimin With On Demand (our default front-end), number parsing only occurs if you specifically request it.

**Pull request merged**
