### PR TITLE
Add C++11 tests to cmake

### PR DESCRIPTION
**Pull request by jkeiser**
This:
- Separates simdjson flags into a simdjson-flags target so callers aren't forced to use the flags we compile the library and tools with
- Adds C++11 quickstart test
- Adds C++11 readme_examples and readme_examples_noexceptions tests

The quickstart tests aren't *quite* what I want yet: we need amalgamation in cmake before the command line is just `c++ quickstart.cpp simdjson.cpp`. But it's pretty close!

### CODE REVIEW

**Comment by jkeiser** [comment]
Every time I do this, it reveals more bugs we didn't realize we had :) Turns out cmake flags a few c++11 constructs that g++ doesn't notice. Fixed those, let's see if it compiles clean now.

**Comment by jkeiser** [comment]
Oy, took a while to untangle Windows there. Still a bunch of stuff that won't compile (only new stuff), but at least everything that can be compiled and run on Windows right now, is.

**Comment by jkeiser** [comment]
@lemire I *think* this is done now. It's been a busy day for simdjson and CI is still catching up, but I've had at least one success on every CI variant now. Awaiting tests to confirm, but I think it's baked sans last second typos.

**Comment by jkeiser** [comment]
Yep, all tests passed. Just rebased to master to resolve conflicts, but this is baked.

**Comment by lemire** [comment]
Fixed conflict with master.

**Pull request merged**
