### PR TITLE
Define namespaces inside generic files

### PR DESCRIPTION
**Pull request by jkeiser**
The generic/ files are pretty tricky to use right, right now, because you have to have the namespaces and regions just right, and you can't #include anything inside a generic file (otherwise the namespace goes wonky).

This PR:
* Increases the amount of potential inlining: defines the TARGET_REGION exactly once, at the beginning, before compiling each implementation, and untargets after.
* Opens the appropriate namespaces
* Moves many #include statements where they are needed
* Compiles the jsoncharutils functions per architecture (tables are still once per executable) to facilitate cross-architecture inlining of these critical functions
* Added really_inline to several functions in jsoncharutils.h

## Things I Didn't Do

* Prevent Multiple Inclusion: I also thought of a way to make it so you could prevent architecture-specific files from being included more than once, which would pretty much make these files exactly the same as any other file; but it would break amalgamation, so I didn't include it. I'll think that one more for the future.
* Ensure All Inline Stuff Everywhere Is Compiled With Target Architecture: I'm not sure how many functions we use from simdjson.h, but I bet there's a few out there. We could compile each target architecture in a separate .o pretty easily, allowing us to compile even common stuff with architecture enabled ...
* hex_to_u32_nocheck: fascinatingly, this is faster when NOT inlined.

## Performance

skylake (haswell) is running faster in general. This is presumably due to the compiler being able to inline more (I imagine it's shy about optimizing across architecture boundaries ...).

| File                             | Blocks | master Cycles | PR Cycles | +Throughput | master Instr. | PR Instr. | -Instr. | master Branch Misses | PR Branch Misses | -Branch Misses | master Cache Misses | PR Cache Misses | -Cache Misses | master Cache Refs | PR Cache Refs | -Cache Refs |
| ---                              |    --: |   --: |   --: |   --: |   --: |   --: |   --: |    --: |    --: |   --: |    --: |    --: |   --: |    --: |    --: |   --: |
| update-center                    |   8330 |  45.2 |  42.9 |    5% | 142.1 | 142.1 |    0% |   2888 |   2318 |   19% |      0 |      0 |    0% |  25207 |  25222 |    0% |
| twitterescaped                   |   8787 |  42.8 |  41.3 |    3% | 138.1 | 138.1 |    0% |   2230 |   1911 |   14% |      0 |      0 |    0% |  25095 |  25107 |    0% |
| instruments                      |   3442 |  39.0 |  37.8 |    3% | 143.1 | 143.1 |    0% |    263 |     92 |   65% |      0 |      0 |    0% |  10550 |  10222 |    3% |
| gsoc-2018                        |  51997 |  36.5 |  35.8 |    1% | 101.1 | 101.1 |    0% |  15161 |  14857 |    2% |  29778 |  20698 |   30% | 117065 | 116016 |    0% |
| mesh                             |  11306 |  46.5 |  45.7 |    1% | 174.2 | 174.2 |    0% |    886 |    669 |   24% |      0 |      0 |    0% |  43180 |  42959 |    0% |
| twitter                          |   9867 |  43.6 |  43.2 |    1% | 148.8 | 148.8 |    0% |   1808 |   1734 |    4% |      0 |      0 |    0% |  27194 |  27201 |    0% |
| numbers                          |   2345 |  38.8 |  38.4 |    0% | 144.3 | 144.3 |    0% |    110 |    105 |    4% |      0 |      0 |    0% |   7176 |   7138 |    0% |
| marine_ik                        |  46616 |  54.1 |  53.6 |    0% | 180.9 | 180.9 |    0% |   8827 |   8722 |    1% |  59434 |  78497 |  -32% | 185237 | 186333 |    0% |
| apache_builds                    |   1988 |  37.0 |  36.8 |    0% | 139.3 | 139.3 |    0% |     34 |     24 |   29% |      0 |      0 |    0% |   4893 |   4804 |    1% |
| canada                           |  35172 |  45.3 |  45.1 |    0% | 157.6 | 157.6 |    0% |   5376 |   5313 |    1% |  11213 |  12734 |  -13% | 115376 | 115861 |    0% |
| github_events                    |   1017 |  34.6 |  34.5 |    0% | 129.8 | 129.8 |    0% |      8 |      7 |   12% |      0 |      0 |    0% |   1004 |    959 |    4% |
| mesh.pretty                      |  24646 |  35.9 |  35.8 |    0% | 137.7 | 137.7 |    0% |     43 |     33 |   23% |    281 |      0 |    0% |  69239 |  69306 |    0% |
| citm_catalog                     |  26987 |  34.1 |  34.1 |    0% | 130.7 | 130.7 |    0% |    166 |    160 |    3% |      6 |    141 | -2250% |  71737 |  71547 |    0% |
| random                           |   7976 |  57.7 |  57.7 |    0% | 209.3 | 209.3 |    0% |    975 |   1061 |   -8% |      0 |      0 |    0% |  27743 |  27713 |    0% |

### CODE REVIEW

**Comment by jkeiser** [comment]
Presumably because of the increase in inlining, this actually appears to improve performance (and decrease branch misses) somewhat:

| File                             | Blocks | master Cycles | PR Cycles | +Throughput | master Instr. | PR Instr. | -Instr. | master Branch Misses | PR Branch Misses | -Branch Misses | master Cache Misses | PR Cache Misses | -Cache Misses | master Cache Refs | PR Cache Refs | -Cache Refs |
| ---                              |    --: |   --: |   --: |   --: |   --: |   --: |   --: |    --: |    --: |   --: |    --: |    --: |   --: |    --: |    --: |   --: |
| update-center                    |   8330 |  45.2 |  43.2 |    4% | 142.1 | 142.1 |    0% |   2888 |   2530 |   12% |      0 |      0 |    0% |  25207 |  26943 |   -6% |
| twitterescaped                   |   8787 |  42.8 |  41.0 |    4% | 138.1 | 138.1 |    0% |   2230 |   1895 |   15% |      0 |      0 |    0% |  25095 |  26878 |   -7% |
| instruments                      |   3442 |  39.0 |  37.7 |    3% | 143.1 | 143.1 |    0% |    263 |    100 |   61% |      0 |      0 |    0% |  10550 |  11180 |   -5% |
| mesh                             |  11306 |  46.5 |  45.7 |    1% | 174.2 | 174.2 |    0% |    886 |    764 |   13% |      0 |      0 |    0% |  43180 |  46095 |   -6% |
| twitter                          |   9867 |  43.6 |  42.9 |    1% | 148.8 | 148.8 |    0% |   1808 |   1744 |    3% |      0 |      0 |    0% |  27194 |  29122 |   -7% |
| marine_ik                        |  46616 |  54.1 |  53.3 |    1% | 180.9 | 180.9 |    0% |   8827 |   8665 |    1% |  59434 |  71580 |  -20% | 185237 | 193548 |   -4% |
| gsoc-2018                        |  51997 |  36.5 |  36.0 |    1% | 101.1 | 101.1 |    0% |  15161 |  15368 |   -1% |  29778 |  22360 |   24% | 117065 | 122988 |   -5% |
| github_events                    |   1017 |  34.6 |  34.2 |    1% | 129.8 | 129.8 |    0% |      8 |      6 |   25% |      0 |      0 |    0% |   1004 |   1265 |  -25% |
| apache_builds                    |   1988 |  37.0 |  36.6 |    1% | 139.3 | 139.3 |    0% |     34 |     18 |   47% |      0 |      0 |    0% |   4893 |   5024 |   -2% |
| random                           |   7976 |  57.7 |  57.2 |    0% | 209.3 | 209.3 |    0% |    975 |   1042 |   -6% |      0 |      0 |    0% |  27743 |  29770 |   -7% |
| numbers                          |   2345 |  38.8 |  38.4 |    0% | 144.3 | 144.3 |    0% |    110 |    127 |  -15% |      0 |      0 |    0% |   7176 |   7431 |   -3% |
| mesh.pretty                      |  24646 |  35.9 |  35.6 |    0% | 137.7 | 137.7 |    0% |     43 |     34 |   20% |    281 |      0 |    0% |  69239 |  74171 |   -7% |
| canada                           |  35172 |  45.3 |  44.9 |    0% | 157.6 | 157.6 |    0% |   5376 |   5422 |    0% |  11213 |  11758 |   -4% | 115376 | 122861 |   -6% |
| citm_catalog                     |  26987 |  34.1 |  34.0 |    0% | 130.7 | 130.7 |    0% |    166 |    165 |    0% |      6 |    186 | -3000% |  71737 |  76944 |   -7% |

**Comment by lemire** [comment]
Visual Studio seems grumpy.

**Comment by jkeiser** [comment]
@lemire I found a few functions in jsoncharutils.h that had `inline` but not `really_inline` on them. It turns out we're *faster* when hex_to_u32_nocheck is not inlined. (Changing inline to really_inline makes things a tiny bit slower, but removing inline altogether doesn't change it *at all*.) I haven't followed up to find out why, just yet.

**Comment by lemire** [comment]
> I found a few functions in jsoncharutils.h that had inline but not really_inline on them, and flipped the ones I could. Fascinatingly, it turns out we're faster when hex_to_u32_nocheck is not inlined.

Given that it is on a rarely taken path, it is not too surprising, right?

**Comment by jkeiser** [comment]
> > I found a few functions in jsoncharutils.h that had inline but not really_inline on them, and flipped the ones I could. Fascinatingly, it turns out we're faster when hex_to_u32_nocheck is not inlined.
> 
> Given that it is on a rarely taken path, it is not too surprising, right?

Certainly not the most surprising thing in the world, but it's pretty small, so I didn't anticipate it having any real effect. Makes me wonder what else we can make faster with judicious use of functions.

**Comment by jkeiser** [comment]
Amalgamated headers were broken because of a recursive include (ouch). Fixed that, we'll see if VS is still grumpy.

**Comment by jkeiser** [comment]
NOTE: the performance gain could well be the normal stage 2 jitters, as well. The primary purpose of this checkin is to make generic/ files work more like normal ones.

**Comment by jkeiser** [comment]
Looks like it's in good shape now.

The motivation for me here is, I wanted to move the on demand parser into the generic directory so it could use implementation-specific methods ... but those things tend to override simdjson::simdjson_result<simdjson::haswell::stream::document>, which (a) must be defined outside of simdjson::haswell, and (b) must be aware of simdjson::haswell so that it can reference the class as a template parameter. Making the generic files define namespaces instead of assuming them gives us the freedom to do things like that.

**Comment by lemire** [comment]
@jkeiser There is a mild conflict with what I just merged into master. I think it is easy to fix, but I would rather you do it, so I don't mess things up.

**Comment by jkeiser** [comment]
@lemire for reference, here is the header guard I came up with for the `generic` files (not part of this PR!):

```c++
#if SIMDJSON_IMPLEMENTATION_MASK & ~SIMDJSON_GENERIC_STAGE1_UTF8_LOOKUP4_ALGORITHM_H // Header guard
#define SIMDJSON_GENERIC_STAGE1_UTF8_LOOKUP4_ALGORITHM_H SIMDJSON_GENERIC_STAGE1_UTF8_LOOKUP4_ALGORITHM_H | SIMDJSON_IMPLEMENTATION_MASK

...

#endif // Header guard
```

This would let us definitively treat them like any other header.

**Comment by jkeiser** [comment]
@lemire the gcc10 failures don't make sense to me. I'm investigating, but do they ring a bell?

**Comment by jkeiser** [comment]
```
#!/bin/bash -eo pipefail
echo -e '#include <simdjson.h>\nint main(int argc,char**argv) {simdjson::dom::parser parser;simdjson::dom::element tweets = parser.load(argv[1]); }' > tmp.cpp && c++ -Ibuild/destination/include -Lbuild/destination/lib -std=c++20 -Wl,-rpath,build/destination/lib -o linkandrun tmp.cpp -lsimdjson && ./linkandrun jsonexamples/twitter.json
In file included from tmp.cpp:1:
build/destination/include/simdjson.h:3230:28: error: static assertion failed
 3230 | static_assert(std::ranges::view<simdjson::dom::array>);
      |               ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
build/destination/include/simdjson.h:3230:28: note: constraints not satisfied
In file included from /usr/include/c++/10/string:54,
                 from build/destination/include/simdjson.h:2063,
                 from tmp.cpp:1:
/usr/include/c++/10/bits/range_access.h:861:13:   required for the satisfaction of 'range<_Tp>' [with _Tp = simdjson::dom::array]
/usr/include/c++/10/bits/range_access.h:861:21:   in requirements with 'simdjson::dom::array& __t'
/usr/include/c++/10/bits/range_access.h:863:15: note: the required expression 'std::ranges::__cust::begin(__t)' is invalid
  863 |  ranges::begin(__t);
      |  ~~~~~~~~~~~~~^~~~~
/usr/include/c++/10/bits/range_access.h:864:13: note: the required expression 'std::ranges::__cust::end(__t)' is invalid
  864 |  ranges::end(__t);
      |  ~~~~~~~~~~~^~~~~
cc1plus: note: set '-fconcepts-diagnostics-depth=' to at least 2 for more detail
In file included from tmp.cpp:1:
build/destination/include/simdjson.h:3231:28: error: static assertion failed
 3231 | static_assert(std::ranges::sized_range<simdjson::dom::array>);
      |               ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
build/destination/include/simdjson.h:3231:28: note: constraints not satisfied
In file included from /usr/include/c++/10/string:54,
                 from build/destination/include/simdjson.h:2063,
                 from tmp.cpp:1:
/usr/include/c++/10/bits/range_access.h:861:13:   required for the satisfaction of 'range<_Tp>' [with _Tp = simdjson::dom::array]
/usr/include/c++/10/bits/range_access.h:861:21:   in requirements with 'simdjson::dom::array& __t'
/usr/include/c++/10/bits/range_access.h:863:15: note: the required expression 'std::ranges::__cust::begin(__t)' is invalid
  863 |  ranges::begin(__t);
      |  ~~~~~~~~~~~~~^~~~~
/usr/include/c++/10/bits/range_access.h:864:13: note: the required expression 'std::ranges::__cust::end(__t)' is invalid
  864 |  ranges::end(__t);
      |  ~~~~~~~~~~~^~~~~
```

**Comment by jkeiser** [comment]
Oh! I bet we're broken on gcc-10 after re-amalgamating.

**Comment by jkeiser** [comment]
Pushed without the amalgamated header to test theory; I'll open a bug if so, but will probably merge this.

**Comment by lemire** [comment]
>  I'm investigating, but do they ring a bell?

I think that there is something fishy with C++20 support but I have not yet been able to put my finger on it.

**Comment by jkeiser** [comment]
Yep, that looks like it.

**Pull request merged**
