### PR TITLE
Put back the amalgamation files and add tests

### PR DESCRIPTION
**Pull request by lemire**
- [X] This stops CMake from magically regenerating the amalgamation files. If they are missing, we should get an error.
- [X] This adds back the amalgamated files.
- [X] It adds tests to prevent programmers from ever again deleting these files without triggering a failure.

Fixes https://github.com/simdjson/simdjson/issues/928

### CODE REVIEW

**Comment by lemire** [comment]
> Note: the amalgamated files in this checkin fail to compile.

Do they?  I am puzzled.

**Comment by jkeiser** [comment]
@lemire judging by the test failure, it was probably generated on Windows and committed with \r\n line endings:

```c++
c++ -O3 -std=c++17 -pthread -o amalgamate_demo amalgamate_demo.cpp  && ./amalgamate_demo ../jsonexamples/twitter.json ../jsonexamples/amazon_cellphones.ndjson
Scanning dependencies of target amalgamate_demo_direct_from_repository
[ 85%] Building CXX object singleheader/CMakeFiles/amalgamate_demo_direct_from_repository.dir/amalgamate_demo.cpp.o
In file included from /home/conan/project/singleheader/amalgamate_demo.cpp:4:
/home/conan/project/singleheader/simdjson.h:536:17: error: missing terminating " character [-Werror]
  536 | #pragma message("The simdjson library is designed\
      |                 ^
/home/conan/project/singleheader/simdjson.h:541:47: error: missing terminating " character [-Werror]
  541 | use a 64-bit target such as x64 or 64-bit ARM.")
      |                                               ^
/home/conan/project/singleheader/simdjson.h:544:8: error: missing terminating " character [-Werror]
  544 | #error "The simdjson library is designed\
      |        ^
/home/conan/project/singleheader/simdjson.h:548:39: error: missing terminating " character [-Werror]
  548 | compiling for a known 64-bit platform."
      |                                       ^
```

**Comment by lemire** [comment]
>  judging by the test failure, it was probably generated on Windows and committed with \r\n line endings:

It was not. And the line numbers do not match the actual file.

I think that the problem is that we run cmake in the root directory. That's my theory right now. It, somehow, messes things up.

**Comment by jkeiser** [comment]
@lemire if you run cmake in the root directory, it *will* overwrite the amalgamated files, because the build and source directories will be the same. Still not sure why that would mess up the generated headers, though.

**Comment by jkeiser** [comment]
(I usually use the cmake recommended practice of `mkdir build; cd build; cmake ..; make`.)

**Comment by lemire** [comment]
> I usually use the cmake recommended practice of

So do I, of course.

**Comment by jkeiser** [comment]
Oh, I see what you are getting at. That change was in fact a fix. I know I had to do something like that as well, for when we run from the root directory ...

We should change circle so it uses the best practice, but I'm glad you fixed this.

**Comment by lemire** [comment]
> We should change circle so it uses the best practice, but I'm glad you fixed this.


On it. I will try to get this in this PR.

**Comment by jkeiser** [comment]
I just checked in those last 2 changes, so if you end up messing with stuff you may as well rebase and reamalgamate. Not critical at all though.

**Comment by jkeiser** [comment]
@lemire oh! You didn't checkin singleheader/README.md either.

**Comment by lemire** [comment]
> oh! You didn't checkin singleheader/README.md either.

Fixed.

**Comment by lemire** [comment]
> I just checked in those last 2 changes, so if you end up messing with stuff you may as well rebase and reamalgamate. Not critical at all though.

Done.

**Comment by lemire** [comment]
> We should change circle so it uses the best practice

Done. It is surprisingly difficult.

**Comment by lemire** [comment]
I will let the tests turn green and then merge. Hopefully, they will turn green.

**Comment by lemire** [comment]
Merged.

**Pull request merged**
